/**
 * JUMO FINTECH — Authoritative Financial Family Module Registry
 * Defines independent, installable, upgradeable financial families inside JUMO FINTECH.
 * Single source of truth for family manifests, dependencies, capabilities, and security boundaries.
 */

export interface FintechFamilyManifest {
  id: string;
  code: string;
  name: string;
  shortName: string;
  description: string;
  category: 'Overview' | 'Payments' | 'Banking & Wallets' | 'Lending & Credit' | 'Treasury & Wealth' | 'Infrastructure' | 'Compliance & Security' | 'Accounting & Ledger';
  status: 'SCAFFOLDED' | 'PARTIALLY_IMPLEMENTED' | 'FUNCTIONALLY_IMPLEMENTED' | 'INTEGRATED' | 'BENCHMARK_VERIFIED' | 'PRODUCTION_VERIFIED';
  version: string;
  iconName: string;
  dependencies: string[];
  permissions: string[];
  route: string;
  capabilitiesCount: number;
  verifiedCapabilitiesCount: number;
  isDefaultInstalled: boolean;
  benchmarkSource: string;
  documentationUrl?: string;
  aiAgents: string[];
}

export type FintechFamilyDefinition = FintechFamilyManifest;

export const FintechFamilyRegistry: FintechFamilyManifest[] = [
  // --- ACCOUNTING & FAAP BACKBONE ---
  {
    id: 'FAM_LEDGER',
    code: 'FT-ACC-01',
    name: 'General Ledger & Financial Accounting (FAAP)',
    shortName: 'General Ledger',
    description: 'Cryptographically sealed double-entry postings, chart of accounts, trial balance, triple-column cash books, and real-time ledger parity audit.',
    category: 'Accounting & Ledger',
    status: 'PRODUCTION_VERIFIED',
    version: 'v16.2.0',
    iconName: 'Scale',
    dependencies: [],
    permissions: ['faap.ledger.read', 'faap.ledger.write', 'faap.parity.audit', 'faap.reports.export'],
    route: '/fintech/ledger',
    capabilitiesCount: 18,
    verifiedCapabilitiesCount: 18,
    isDefaultInstalled: true,
    benchmarkSource: 'Modern Treasury, QuickBooks, SAP S/4HANA Finance, FAAP Backbone',
    aiAgents: ['AGENT_FIN_AUDITOR', 'AGENT_LEDGER_RECON']
  },
  {
    id: 'FAM_TAX_REVENUE',
    code: 'FT-ACC-02',
    name: 'Tax, Revenue & Fee Management',
    shortName: 'Tax & Revenue',
    description: 'Automated 1.5% JUMO clearing fee deduction, VAT/WHT statutory calculations, split revenue settlement, and tax compliance registers.',
    category: 'Accounting & Ledger',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.1.0',
    iconName: 'Receipt',
    dependencies: ['FAM_LEDGER'],
    permissions: ['tax.rules.manage', 'tax.reports.generate'],
    route: '/fintech/tax-revenue',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: true,
    benchmarkSource: 'Stripe Tax, Avalara, Kenya Revenue Authority / URA integrations',
    aiAgents: ['AGENT_TAX_COMPLIANCE']
  },

  // --- PAYMENTS & ORCHESTRATION ---
  {
    id: 'FAM_PAY_SWITCH',
    code: 'FT-PAY-01',
    name: 'Universal Payment Switching & Routing',
    shortName: 'Payment Switch',
    description: 'Intelligent multi-rail payment switching, ISO 8583/20022 message routing, failover fallbacks, and real-time fee split orchestration.',
    category: 'Payments',
    status: 'PRODUCTION_VERIFIED',
    version: 'v14.1.0',
    iconName: 'Network',
    dependencies: ['FAM_LEDGER'],
    permissions: ['switch.routes.configure', 'switch.transactions.view', 'switch.settlements.execute'],
    route: '/fintech/payment-switching',
    capabilitiesCount: 16,
    verifiedCapabilitiesCount: 15,
    isDefaultInstalled: true,
    benchmarkSource: 'Cellulant Tingg, Interswitch, Flutterwave Switch, SchoolPay Core',
    aiAgents: ['AGENT_PAYMENT_ROUTER']
  },
  {
    id: 'FAM_MOBILE_MONEY',
    code: 'FT-PAY-02',
    name: 'Mobile Money Core & USSD Rails',
    shortName: 'Mobile Money',
    description: 'M-Pesa, MTN MoMo, Airtel Money integration, C2B collections, B2C disbursements, B2B settlements, and agent float balancing.',
    category: 'Payments',
    status: 'PRODUCTION_VERIFIED',
    version: 'v12.4.0',
    iconName: 'Smartphone',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['momo.transact', 'momo.float.manage', 'momo.reconcile'],
    route: '/fintech/mobile-money',
    capabilitiesCount: 14,
    verifiedCapabilitiesCount: 14,
    isDefaultInstalled: true,
    benchmarkSource: 'Safaricom M-Pesa Daraja, MTN MoMo OpenAPI, Airtel Money API',
    aiAgents: ['AGENT_FLOAT_FORECASTER']
  },
  {
    id: 'FAM_PAYMENT_GATEWAY',
    code: 'FT-PAY-08',
    name: 'Payment Gateway & Checkout',
    shortName: 'Payment Gateway',
    description: 'Hosted checkout modals, dynamic Payment Reference Numbers (PRN), payment links, webhooks, and multi-rail payment acceptance.',
    category: 'Payments',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v4.0.0',
    iconName: 'ShoppingCart',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['gateway.keys.manage', 'gateway.checkout.host'],
    route: '/fintech/payment-gateway',
    capabilitiesCount: 12,
    verifiedCapabilitiesCount: 11,
    isDefaultInstalled: true,
    benchmarkSource: 'Stripe Checkout, Adyen, DPO Pay, Flutterwave',
    aiAgents: ['AGENT_CHECKOUT_CONV']
  },
  {
    id: 'FAM_COLLECTIONS',
    code: 'FT-PAY-06',
    name: 'Institutional & Business Collections',
    shortName: 'Collections',
    description: 'Automated invoice collections, direct debit mandates, PRN generation for school tuition and church offerings, and real-time reconciliation.',
    category: 'Payments',
    status: 'BENCHMARK_VERIFIED',
    version: 'v3.5.0',
    iconName: 'ArrowDownOnSquare',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['collections.mandate.create', 'collections.reconcile'],
    route: '/fintech/collections',
    capabilitiesCount: 12,
    verifiedCapabilitiesCount: 12,
    isDefaultInstalled: true,
    benchmarkSource: 'SchoolPay, Tingg Collect, PayGov Systems',
    aiAgents: ['AGENT_ARREARS_COLLECT']
  },
  {
    id: 'FAM_PAYOUTS',
    code: 'FT-PAY-07',
    name: 'Bulk Payouts & Disbursements',
    shortName: 'Bulk Payouts',
    description: 'Mass salary disbursements, supplier payment batches, humanitarian aid distributions, and scheduled multi-account payouts.',
    category: 'Payments',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v3.2.0',
    iconName: 'ArrowUpOnSquare',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['payouts.batch.upload', 'payouts.batch.approve', 'payouts.disburse'],
    route: '/fintech/payouts',
    capabilitiesCount: 11,
    verifiedCapabilitiesCount: 10,
    isDefaultInstalled: true,
    benchmarkSource: 'Wise Batch, Tipalti, Payoneer Mass Pay',
    aiAgents: ['AGENT_PAYOUT_VERIFIER']
  },
  {
    id: 'FAM_BANK_PAYMENTS',
    code: 'FT-PAY-03',
    name: 'Bank Payments & Account Transfers (EFT / RTGS / ACH)',
    shortName: 'Bank Transfers',
    description: 'Real-time gross settlement (RTGS), automated clearing house (ACH), instant bank-to-bank account transfers, and open banking protocols.',
    category: 'Payments',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.0.0',
    iconName: 'BuildingLibrary',
    dependencies: ['FAM_LEDGER'],
    permissions: ['banking.eft.initiate', 'banking.rtgs.approve'],
    route: '/fintech/bank-payments',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 8,
    isDefaultInstalled: false,
    benchmarkSource: 'FedNow, SEPA Instant, NIP Nigeria, EFT Uganda',
    aiAgents: ['AGENT_SETTLEMENT_OPT']
  },
  {
    id: 'FAM_CROSS_BORDER',
    code: 'FT-PAY-04',
    name: 'Cross-Border Payments & FX Clearing',
    shortName: 'Cross-Border',
    description: 'SWIFT messaging, multi-currency corridors, correspondent banking routes, and regulatory balance of payments reporting.',
    category: 'Payments',
    status: 'PARTIALLY_IMPLEMENTED',
    version: 'v1.8.0',
    iconName: 'PaperAirplane',
    dependencies: ['FAM_FX', 'FAM_LEDGER'],
    permissions: ['crossborder.route', 'crossborder.compliance'],
    route: '/fintech/cross-border',
    capabilitiesCount: 12,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: false,
    benchmarkSource: 'SWIFT gpi, PAPSS (Pan-African Payment and Settlement System), RippleNet',
    aiAgents: ['AGENT_CORRIDOR_ROUTER']
  },
  {
    id: 'FAM_REMITTANCE',
    code: 'FT-PAY-05',
    name: 'Diaspora Remittance Platform',
    shortName: 'Remittance',
    description: 'Cross-border remittances, cash pickup agent integration, direct-to-mobile wallet payouts, and tiered KYC AML screening.',
    category: 'Payments',
    status: 'PARTIALLY_IMPLEMENTED',
    version: 'v1.5.0',
    iconName: 'ArrowPath',
    dependencies: ['FAM_MOBILE_MONEY', 'FAM_COMPLIANCE', 'FAM_LEDGER'],
    permissions: ['remittance.quote', 'remittance.send', 'remittance.payout'],
    route: '/fintech/remittance',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 8,
    isDefaultInstalled: false,
    benchmarkSource: 'Sendwave, WorldRemit, Western Union Digital, LemFi',
    aiAgents: ['AGENT_FX_OPTIMIZER']
  },
  {
    id: 'FAM_MERCHANT_SERVICES',
    code: 'FT-PAY-09',
    name: 'Merchant Services & Dynamic QR',
    shortName: 'Merchant Services',
    description: 'Merchant onboarding, dynamic EMVCo QR code generation, POS terminal terminal management, and gross-net settlement calculation.',
    category: 'Payments',
    status: 'PRODUCTION_VERIFIED',
    version: 'v3.0.0',
    iconName: 'Storefront',
    dependencies: ['FAM_LEDGER', 'FAM_PAY_SWITCH'],
    permissions: ['merchants.create', 'merchants.pos.manage', 'merchants.settle'],
    route: '/fintech/merchant-services',
    capabilitiesCount: 12,
    verifiedCapabilitiesCount: 12,
    isDefaultInstalled: true,
    benchmarkSource: 'Square, Clover, Toast POS, OPay Merchant',
    aiAgents: ['AGENT_MERCHANT_INSIGHT']
  },
  {
    id: 'FAM_MERCHANT_ACQUIRING',
    code: 'FT-PAY-13',
    name: 'Card Acquiring Switch & ISO 8583 Processing',
    shortName: 'Merchant Acquiring',
    description: 'Direct Visa/Mastercard/UnionPay host connections, terminal transaction encryption, and interchange fee calculation.',
    category: 'Payments',
    status: 'SCAFFOLDED',
    version: 'v1.0.0',
    iconName: 'CreditCard',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['acquiring.switch.view', 'acquiring.interchange.audit'],
    route: '/fintech/merchant-acquiring',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 6,
    isDefaultInstalled: false,
    benchmarkSource: 'First Data/Fiserv, Global Payments, Worldpay',
    aiAgents: ['AGENT_CHARGEBACK_DEFENDER']
  },
  {
    id: 'FAM_CARDS',
    code: 'FT-PAY-10',
    name: 'Cards & Virtual Cards Issuing',
    shortName: 'Card Issuing',
    description: 'Virtual and physical card issuance, BIN sponsorship orchestration, spend limits, tokenization, and real-time authorization webhook webhooks.',
    category: 'Payments',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.4.0',
    iconName: 'CreditCard',
    dependencies: ['FAM_DIGITAL_WALLETS', 'FAM_LEDGER'],
    permissions: ['cards.issue', 'cards.freeze', 'cards.limits.update'],
    route: '/fintech/cards',
    capabilitiesCount: 11,
    verifiedCapabilitiesCount: 10,
    isDefaultInstalled: false,
    benchmarkSource: 'Marqeta, Lithic, Stripe Issuing, Galileo',
    aiAgents: ['AGENT_FRAUD_SHIELD']
  },
  {
    id: 'FAM_PAYROLL',
    code: 'FT-PAY-11',
    name: 'Payroll & Mass Salary Payments',
    shortName: 'Payroll Processing',
    description: 'Automated salary disbursements, statutory tax/pension deductions, payslip generation, and direct bank/wallet credit.',
    category: 'Payments',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.2.0',
    iconName: 'Calculator',
    dependencies: ['FAM_PAYOUTS', 'FAM_LEDGER'],
    permissions: ['payroll.run', 'payroll.approve', 'payroll.export'],
    route: '/fintech/payroll',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: true,
    benchmarkSource: 'Gusto, ADP, Deel, JUMO HR/FAAP Integrated',
    aiAgents: ['AGENT_PAYROLL_AUDITOR']
  },
  {
    id: 'FAM_BILLS',
    code: 'FT-PAY-12',
    name: 'Bills, Utilities & Government Payments',
    shortName: 'Bill Payments',
    description: 'Electricity (Umeme/KPLC), water, TV subscriptions, municipal taxes, and government e-citizen payments with instant token generation.',
    category: 'Payments',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.0.0',
    iconName: 'DocumentText',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['bills.fetch', 'bills.pay', 'bills.receipts'],
    route: '/fintech/bills',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: true,
    benchmarkSource: 'PegPay, Tingg Bills, PayBill Kenya, eCitizen',
    aiAgents: ['AGENT_BILL_RECONCILER']
  },

  // --- BANKING & WALLETS ---
  {
    id: 'FAM_DIGITAL_WALLETS',
    code: 'FT-BNK-01',
    name: 'Digital Wallets & Stored Value Facilities',
    shortName: 'Digital Wallets',
    description: 'Customer & business stored-value wallets, tiered KYC wallet limits, peer-to-peer instant transfers, and sub-wallet budgeting.',
    category: 'Banking & Wallets',
    status: 'PRODUCTION_VERIFIED',
    version: 'v11.0.0',
    iconName: 'Wallet',
    dependencies: ['FAM_LEDGER', 'FAM_COMPLIANCE'],
    permissions: ['wallet.create', 'wallet.credit', 'wallet.debit', 'wallet.transfer'],
    route: '/fintech/digital-wallets',
    capabilitiesCount: 14,
    verifiedCapabilitiesCount: 14,
    isDefaultInstalled: true,
    benchmarkSource: 'Apple Cash, PayPal, Chipper Cash, JUMO Digital Pay Stored Value',
    aiAgents: ['AGENT_WALLET_INSIGHT']
  },
  {
    id: 'FAM_MULTI_CURRENCY',
    code: 'FT-BNK-02',
    name: 'Multi-Currency Accounts & Global Balances',
    shortName: 'Multi-Currency',
    description: 'Hold and transact in USD, EUR, GBP, UGX, KES, NGN, and ZAR with auto-currency conversion and currency-specific routing coordinates.',
    category: 'Banking & Wallets',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.5.0',
    iconName: 'Globe',
    dependencies: ['FAM_FX', 'FAM_LEDGER'],
    permissions: ['multicurrency.account.open', 'multicurrency.convert'],
    route: '/fintech/multi-currency',
    capabilitiesCount: 12,
    verifiedCapabilitiesCount: 11,
    isDefaultInstalled: true,
    benchmarkSource: 'Wise Multi-Currency Account, Revolut Business, Payoneer',
    aiAgents: ['AGENT_CURRENCY_HEDGE']
  },
  {
    id: 'FAM_GLOBAL_ACCOUNTS',
    code: 'FT-BNK-03',
    name: 'Global Accounts & Virtual IBANs',
    shortName: 'Global Accounts',
    description: 'Virtual IBAN issuance in US (ACH Routing), UK (Sort Code), EU (IBAN), and local rails for cross-border collection.',
    category: 'Banking & Wallets',
    status: 'PARTIALLY_IMPLEMENTED',
    version: 'v1.6.0',
    iconName: 'GlobeAlt',
    dependencies: ['FAM_MULTI_CURRENCY', 'FAM_COMPLIANCE', 'FAM_LEDGER'],
    permissions: ['iban.provision', 'iban.view'],
    route: '/fintech/global-accounts',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 7,
    isDefaultInstalled: false,
    benchmarkSource: 'Airwallex, Payoneer, Railsr, Currencycloud',
    aiAgents: ['AGENT_ROUTING_COORDINATOR']
  },
  {
    id: 'FAM_AGENT_BANKING',
    code: 'FT-BNK-04',
    name: 'Agent Banking Network & Float Management',
    shortName: 'Agent Banking',
    description: 'Agency network hierarchy, cash-in/cash-out terminal limits, agent float rebalancing, tiered commission rules, and geofenced operations.',
    category: 'Banking & Wallets',
    status: 'PRODUCTION_VERIFIED',
    version: 'v5.2.0',
    iconName: 'Users',
    dependencies: ['FAM_MOBILE_MONEY', 'FAM_LEDGER'],
    permissions: ['agent.register', 'agent.float.topup', 'agent.commission.pay', 'agent.terminal.lock'],
    route: '/fintech/agent-banking',
    capabilitiesCount: 14,
    verifiedCapabilitiesCount: 14,
    isDefaultInstalled: true,
    benchmarkSource: 'OPay Agents, Moniepoint, Equity Bank Agency, CenteAgent',
    aiAgents: ['AGENT_NETWORK_OPTIMIZER']
  },
  {
    id: 'FAM_DIGITAL_BANKING',
    code: 'FT-BNK-05',
    name: 'Core Digital Banking & Account Servicing',
    shortName: 'Digital Banking',
    description: 'Retail and corporate current account origination, overdraft protection, statement generation, interest accrual, and banking workflows.',
    category: 'Banking & Wallets',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v3.0.0',
    iconName: 'BuildingStorefront',
    dependencies: ['FAM_LEDGER'],
    permissions: ['corebanking.account.open', 'corebanking.overdraft.set'],
    route: '/fintech/digital-banking',
    capabilitiesCount: 14,
    verifiedCapabilitiesCount: 12,
    isDefaultInstalled: true,
    benchmarkSource: 'Thought Machine Vault, Mambu, Temenos Transact, Finacle',
    aiAgents: ['AGENT_BANK_AUDITOR']
  },
  {
    id: 'FAM_SAVINGS',
    code: 'FT-BNK-06',
    name: 'Savings, Fixed Deposits & Interest Accrual',
    shortName: 'Savings & Deposits',
    description: 'Goal-based locked savings, fixed deposit contracts, daily compound interest calculators, penalty rules, and automatic maturity rollover.',
    category: 'Banking & Wallets',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.2.0',
    iconName: 'Banknotes',
    dependencies: ['FAM_LEDGER'],
    permissions: ['savings.plan.create', 'savings.interest.accrue'],
    route: '/fintech/savings',
    capabilitiesCount: 11,
    verifiedCapabilitiesCount: 10,
    isDefaultInstalled: true,
    benchmarkSource: 'PiggyVest, Marcus by Goldman Sachs, Standard Bank Fixed Deposits',
    aiAgents: ['AGENT_SAVINGS_GROWTH']
  },

  // --- LENDING & CREDIT ---
  {
    id: 'FAM_MICROFINANCE',
    code: 'FT-LND-01',
    name: 'Microfinance & Joint Liability Group (JLG) Lending',
    shortName: 'Microfinance',
    description: 'Joint liability solidarity groups, weekly/monthly center collections, field officer mobile app sync, micro-loan underwriting, and recovery tracking.',
    category: 'Lending & Credit',
    status: 'PRODUCTION_VERIFIED',
    version: 'v6.0.0',
    iconName: 'Briefcase',
    dependencies: ['FAM_LEDGER', 'FAM_COMPLIANCE'],
    permissions: ['mfi.group.create', 'mfi.loan.disburse', 'mfi.collection.log'],
    route: '/fintech/microfinance',
    capabilitiesCount: 15,
    verifiedCapabilitiesCount: 15,
    isDefaultInstalled: true,
    benchmarkSource: 'Grameen Bank, BRAC Microfinance, FINCA International, Musoni',
    aiAgents: ['AGENT_JLG_RISK']
  },
  {
    id: 'FAM_LENDING',
    code: 'FT-LND-02',
    name: 'Credit Underwriting, Loans & Debt Recovery',
    shortName: 'Lending & Credit',
    description: 'Loan origination system (LOS), loan management system (LMS), reducing balance amortization schedules, automated late fees, and debt recovery workflows.',
    category: 'Lending & Credit',
    status: 'PRODUCTION_VERIFIED',
    version: 'v4.5.0',
    iconName: 'ChartBar',
    dependencies: ['FAM_LEDGER', 'FAM_COMPLIANCE'],
    permissions: ['loans.underwrite', 'loans.disburse', 'loans.restructure'],
    route: '/fintech/lending',
    capabilitiesCount: 15,
    verifiedCapabilitiesCount: 14,
    isDefaultInstalled: true,
    benchmarkSource: 'Tala, Branch International, JUMO World Lending Platform, Enova',
    aiAgents: ['AGENT_CREDIT_RISK']
  },
  {
    id: 'FAM_SACCO',
    code: 'FT-LND-03',
    name: 'SACCO & Cooperative Financial Management',
    shortName: 'SACCO Platform',
    description: 'BOSA (Back Office) and FOSA (Front Office) operations, share capital management, member loan multipliers (3x shares), dividend declarations, and AGM voting.',
    category: 'Lending & Credit',
    status: 'PRODUCTION_VERIFIED',
    version: 'v5.0.0',
    iconName: 'UserGroup',
    dependencies: ['FAM_LEDGER', 'FAM_SAVINGS'],
    permissions: ['sacco.member.admit', 'sacco.shares.credit', 'sacco.dividends.declare'],
    route: '/fintech/sacco',
    capabilitiesCount: 16,
    verifiedCapabilitiesCount: 16,
    isDefaultInstalled: true,
    benchmarkSource: 'Kweli SACCO, Co-op Bank SACCO Suite, Mwalimu National, SASRA Compliance',
    aiAgents: ['AGENT_SACCO_DIVIDEND']
  },
  {
    id: 'FAM_EMBEDDED_FINANCE',
    code: 'FT-INF-02',
    name: 'Embedded Finance & B2B BNPL',
    shortName: 'Embedded Finance',
    description: 'Point-of-sale Buy-Now-Pay-Later (BNPL), invoice factoring, distributor supply-chain financing, and merchant working capital advances.',
    category: 'Lending & Credit',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.0.0',
    iconName: 'PuzzlePiece',
    dependencies: ['FAM_LENDING', 'FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['bnpl.evaluate', 'bnpl.advance'],
    route: '/fintech/embedded-finance',
    capabilitiesCount: 11,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: false,
    benchmarkSource: 'Klarna, Affirm, Billie B2B, Treyd',
    aiAgents: ['AGENT_BNPL_SCORER']
  },
  {
    id: 'FAM_AGRICULTURAL_FINANCE',
    code: 'FT-LND-04',
    name: 'Agricultural Finance & Value Chain Credit',
    shortName: 'Agri-Finance',
    description: 'Farmer cooperative credit, seasonal crop cycle loans, input financing vouchers, satellite weather indexing, and warehouse receipt financing.',
    category: 'Lending & Credit',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v1.5.0',
    iconName: 'Sprout',
    dependencies: ['FAM_SACCO', 'FAM_LEDGER'],
    permissions: ['agri.farmer.onboard', 'agri.voucher.issue'],
    route: '/fintech/agricultural-finance',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 8,
    isDefaultInstalled: false,
    benchmarkSource: 'Apollo Agriculture, One Acre Fund, DigiFarm, Acre Africa',
    aiAgents: ['AGENT_AGRI_YIELD_RISK']
  },

  // --- TREASURY & MARKETS ---
  {
    id: 'FAM_TREASURY',
    code: 'FT-TRZ-02',
    name: 'Corporate Treasury & Liquidity Forecasting',
    shortName: 'Treasury & Liquidity',
    description: 'Real-time multi-bank cash concentration, automated liquidity sweeping, cash flow predictive modeling, and debt covenant monitoring.',
    category: 'Treasury & Wealth',
    status: 'PRODUCTION_VERIFIED',
    version: 'v3.8.0',
    iconName: 'ChartPie',
    dependencies: ['FAM_LEDGER'],
    permissions: ['treasury.view', 'treasury.sweep.execute', 'treasury.forecast'],
    route: '/fintech/treasury',
    capabilitiesCount: 13,
    verifiedCapabilitiesCount: 13,
    isDefaultInstalled: true,
    benchmarkSource: 'Kyriba, FIS Treasury (Quantum), Modern Treasury, GTreasury',
    aiAgents: ['AGENT_LIQUIDITY_FORECASTER']
  },
  {
    id: 'FAM_FX',
    code: 'FT-TRZ-01',
    name: 'Foreign Exchange & FX Dealing Desk',
    shortName: 'FX Treasury',
    description: 'Live rate board feeds, tiered spread configuration, dealing desk trade execution, spot and forward contract booking, and FX exposure management.',
    category: 'Treasury & Wealth',
    status: 'PRODUCTION_VERIFIED',
    version: 'v4.0.0',
    iconName: 'CurrencyExchange',
    dependencies: ['FAM_LEDGER'],
    permissions: ['fx.rates.publish', 'fx.trade.execute', 'fx.spreads.set'],
    route: '/fintech/fx',
    capabilitiesCount: 14,
    verifiedCapabilitiesCount: 14,
    isDefaultInstalled: true,
    benchmarkSource: 'Bloomberg FXGO, Reuters Dealing, Wise Rate Engine, 360T',
    aiAgents: ['AGENT_FX_SPREAD_OPTIMIZER']
  },
  {
    id: 'FAM_INVESTMENT',
    code: 'FT-TRZ-04',
    name: 'Investment, Wealth & Asset Management',
    shortName: 'Investments',
    description: 'Unit trusts, treasury bills & sovereign bond bidding, money market fund (MMF) auto-invest, dividend distributions, and portfolio valuation.',
    category: 'Treasury & Wealth',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.1.0',
    iconName: 'TrendingUp',
    dependencies: ['FAM_LEDGER'],
    permissions: ['invest.portfolio.view', 'invest.fund.subscribe'],
    route: '/fintech/investment',
    capabilitiesCount: 11,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: false,
    benchmarkSource: 'BlackRock Aladdin, Nutmeg, Sanlam Unit Trusts, Stanbic MMF',
    aiAgents: ['AGENT_PORTFOLIO_ADVISOR']
  },
  {
    id: 'FAM_SECURITIES_CUSTODY',
    code: 'FT-TRZ-05',
    name: 'Securities, Custody & Asset Administration',
    shortName: 'Institutional Custody',
    description: 'Institutional asset safekeeping, depository settlement, corporate action processing, and beneficial ownership registers.',
    category: 'Treasury & Wealth',
    status: 'PARTIALLY_IMPLEMENTED',
    version: 'v1.4.0',
    iconName: 'Lock',
    dependencies: ['FAM_LEDGER', 'FAM_COMPLIANCE'],
    permissions: ['custody.assets.lock', 'custody.reports.view'],
    route: '/fintech/securities-custody',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 7,
    isDefaultInstalled: false,
    benchmarkSource: 'BNY Mellon, State Street, Standard Chartered Custody Services',
    aiAgents: ['AGENT_CUSTODY_VERIFIER']
  },
  {
    id: 'FAM_INSURANCE',
    code: 'FT-TRZ-03',
    name: 'Insurance & Insurtech Policy Administration',
    shortName: 'Insurtech',
    description: 'Micro-insurance underwriting, health/agriculture policy enrollment, premium deductions, automated claim verification, and reinsurance treaties.',
    category: 'Treasury & Wealth',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.0.0',
    iconName: 'ShieldCheck',
    dependencies: ['FAM_LEDGER', 'FAM_PAY_SWITCH'],
    permissions: ['insurance.policy.issue', 'insurance.claim.assess', 'insurance.claim.payout'],
    route: '/fintech/insurance',
    capabilitiesCount: 11,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: false,
    benchmarkSource: 'Lemonade, BIMA, MicroEnsure, Britam Insurtech',
    aiAgents: ['AGENT_CLAIMS_ASSESSOR']
  },
  {
    id: 'FAM_TRADE_FINANCE',
    code: 'FT-TRZ-06',
    name: 'Trade Finance & Letter of Credit (LC)',
    shortName: 'Trade Finance',
    description: 'Documentary letters of credit (LC), bank guarantees, bill discounting, warehouse receipts, and cross-border trade document validation.',
    category: 'Treasury & Wealth',
    status: 'PARTIALLY_IMPLEMENTED',
    version: 'v1.2.0',
    iconName: 'ClipboardCheck',
    dependencies: ['FAM_LEDGER', 'FAM_CROSS_BORDER'],
    permissions: ['trade.lc.issue', 'trade.guarantee.verify'],
    route: '/fintech/trade-finance',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 7,
    isDefaultInstalled: false,
    benchmarkSource: 'Bolero, TradeAssets, Standard Bank Trade',
    aiAgents: ['AGENT_TRADE_DOC_OCR']
  },

  // --- INFRASTRUCTURE & RAILS ---
  {
    id: 'FAM_STABLECOIN',
    code: 'FT-INF-01',
    name: 'Stablecoin & Digital Asset Settlement Rails',
    shortName: 'Stablecoin Rails',
    description: 'USDC/USDT on/off-ramp settlement, custodial wallet generation, gas fee abstraction, and crypto-to-fiat treasury rebalancing.',
    category: 'Infrastructure',
    status: 'FUNCTIONALLY_IMPLEMENTED',
    version: 'v2.0.0',
    iconName: 'CubeTransparent',
    dependencies: ['FAM_LEDGER', 'FAM_COMPLIANCE'],
    permissions: ['crypto.mint', 'crypto.burn', 'crypto.transfer', 'crypto.audit'],
    route: '/fintech/stablecoin',
    capabilitiesCount: 10,
    verifiedCapabilitiesCount: 9,
    isDefaultInstalled: false,
    benchmarkSource: 'Circle Mint, Stripe Crypto Payouts, Paxos, BVNK',
    aiAgents: ['AGENT_ONRAMP_OPTIMIZER']
  },
  {
    id: 'FAM_ATM_SELF_SERVICE',
    code: 'FT-INF-04',
    name: 'ATM & Self-Service Kiosk Gateway',
    shortName: 'ATM Gateway',
    description: 'NDC/DDC ATM protocol handler, cardless mobile cash withdrawals via OTP, kiosk bill payments, and ATM cash cassette tracking.',
    category: 'Infrastructure',
    status: 'SCAFFOLDED',
    version: 'v1.0.0',
    iconName: 'Monitor',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['atm.terminal.status', 'atm.cash.reconcile'],
    route: '/fintech/atm-self-service',
    capabilitiesCount: 9,
    verifiedCapabilitiesCount: 6,
    isDefaultInstalled: false,
    benchmarkSource: 'Diebold Nixdorf, NCR Aptra, GRGBanking',
    aiAgents: ['AGENT_ATM_CASH_PREDICTOR']
  },
  {
    id: 'FAM_DEVELOPER_API',
    code: 'FT-INF-03',
    name: 'Financial API & Developer Platform',
    shortName: 'Developer Platform',
    description: 'Open banking API gateway, OAuth2 client credential management, webhook delivery retry queue, interactive sandbox, and SDK generation.',
    category: 'Infrastructure',
    status: 'PRODUCTION_VERIFIED',
    version: 'v4.0.0',
    iconName: 'CommandLine',
    dependencies: ['FAM_PAY_SWITCH', 'FAM_LEDGER'],
    permissions: ['api.keys.create', 'api.webhooks.configure', 'api.sandbox.reset'],
    route: '/fintech/developer-api',
    capabilitiesCount: 14,
    verifiedCapabilitiesCount: 14,
    isDefaultInstalled: true,
    benchmarkSource: 'Stripe Developers, Plaid, Yapily, Open Banking UK',
    aiAgents: ['AGENT_API_DOC_GEN']
  },

  // --- COMPLIANCE & SECURITY ---
  {
    id: 'FAM_COMPLIANCE',
    code: 'FT-SEC-01',
    name: 'Financial Compliance, AML & Sanctions Guard',
    shortName: 'AML & Compliance',
    description: 'Automated screening against UN/OFAC/EU sanctions lists, Politically Exposed Persons (PEP) detection, SAR filing, and transaction monitoring rules.',
    category: 'Compliance & Security',
    status: 'PRODUCTION_VERIFIED',
    version: 'v5.0.0',
    iconName: 'MagnifyingGlass',
    dependencies: [],
    permissions: ['compliance.sanction.screen', 'compliance.sar.file', 'compliance.whitelist.manage'],
    route: '/fintech/compliance',
    capabilitiesCount: 15,
    verifiedCapabilitiesCount: 15,
    isDefaultInstalled: true,
    benchmarkSource: 'ComplyAdvantage, Fenergo, Chainalysis, LexisNexis WorldCompliance',
    aiAgents: ['AGENT_SANCTION_SENTRY', 'AGENT_SAR_REPORTER']
  },
  {
    id: 'FAM_DATA_INTELLIGENCE',
    code: 'FT-SEC-02',
    name: 'Financial Data Intelligence & Predictive AI',
    shortName: 'Predictive AI',
    description: 'Alternative credit scoring using telco/utility data, cash flow forecasting, transaction anomaly detection, and synthetic ledger stress tests.',
    category: 'Compliance & Security',
    status: 'PRODUCTION_VERIFIED',
    version: 'v3.6.0',
    iconName: 'Sparkles',
    dependencies: ['FAM_LEDGER'],
    permissions: ['ai.models.execute', 'ai.insights.view'],
    route: '/fintech/data-intelligence',
    capabilitiesCount: 12,
    verifiedCapabilitiesCount: 12,
    isDefaultInstalled: true,
    benchmarkSource: 'JUMO AI Engine, Feedzai, DataRobot Financial AI',
    aiAgents: ['AGENT_FIN_AUDITOR', 'AGENT_CREDIT_RISK']
  }
];

export function getFintechFamily(idOrCode?: string): FintechFamilyManifest {
  if (!idOrCode) return FintechFamilyRegistry[0];
  const upper = idOrCode.toUpperCase();
  const found = FintechFamilyRegistry.find(f => 
    f.id.toUpperCase() === upper || 
    f.code.toUpperCase() === upper ||
    f.name.toUpperCase().includes(upper) ||
    f.shortName.toUpperCase().includes(upper)
  );
  return found || FintechFamilyRegistry[0];
}

export function getInstalledFintechFamilies(): FintechFamilyManifest[] {
  return FintechFamilyRegistry.filter(f => f.isDefaultInstalled);
}

export function calculateFamilyCapabilityCoverage(family: FintechFamilyManifest): number {
  if (!family.capabilitiesCount || family.capabilitiesCount === 0) return 100;
  return Math.round((family.verifiedCapabilitiesCount / family.capabilitiesCount) * 100);
}
