import { CanonicalProductHierarchy } from './types';

export const ALUMNI_COMMUNITY_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-alumni-community',
    code: 'ALERP',
    name: 'Alumni Association & Community Network Enterprise ERP',
    category: 'INSTITUTIONAL_ERP',
    description: 'National and institutional alumni network: Cohort year chapters, alumni subscription dues billing, legacy endowment trusts, mentorship matching, annual dinner ticketing, job board, and distinguished alumni awards.',
    version: '2026.4.0',
    iconName: 'Users',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Alumni Association President / Executive Director',
    governingLegislation: 'National NGO Act & Alumni Association Charter 2026',
    directorateIds: ['AL-DIR-001', 'AL-DIR-002', 'AL-DIR-003', 'AL-DIR-004']
  },
  directorates: [
    { id: 'AL-DIR-001', productId: 'prod-alumni-community', code: 'AL-DIR-MEMBERSHIP-CHAPTERS', name: 'Directorate of Cohorts, Diaspora & Regional Chapters', description: 'Year cohort class lists, diaspora chapters (UK, USA, UAE, South Africa), and verified alumni directory.', leadRole: 'DIRECTOR_MEMBERSHIP_CHAPTERS', departmentIds: ['AL-DEPT-001', 'AL-DEPT-002'] },
    { id: 'AL-DIR-002', productId: 'prod-alumni-community', code: 'AL-DIR-TREASURY-ENDOWMENT', name: 'Directorate of Association Treasury, Dues & Endowment Fund', description: 'Annual subscription dues, institutional legacy endowment fund, bursary awards, and audited accounts.', leadRole: 'ASSOCIATION_TREASURER', departmentIds: ['AL-DEPT-003', 'AL-DEPT-004'] },
    { id: 'AL-DIR-003', productId: 'prod-alumni-community', code: 'AL-DIR-CAREERS-MENTORSHIP', name: 'Directorate of Career Placement, Job Board & Mentorship', description: 'Undergraduate student mentorship, alumni executive job postings, startup angel investments, and internships.', leadRole: 'DIRECTOR_CAREER_DEVELOPMENT', departmentIds: ['AL-DEPT-005', 'AL-DEPT-006'] },
    { id: 'AL-DIR-004', productId: 'prod-alumni-community', code: 'AL-DIR-EVENTS-REUNIONS', name: 'Directorate of Annual Dinners, Reunions & Awards', description: 'Grand annual alumni homecoming dinner, cohort jubilees, golf tournaments, and Hall of Fame honors.', leadRole: 'DIRECTOR_EVENTS_COMMUNICATIONS', departmentIds: ['AL-DEPT-007', 'AL-DEPT-008'] }
  ],
  departments: [
    { id: 'AL-DEPT-001', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', code: 'AL-DEPT-COHORT-YEARS', name: 'Department of Cohort Class Years & Validation', description: 'Maps entry and completion years, student numbers, and verifies genuine alumni credentials.', headRole: 'HEAD_COHORT_RECORDS', officeIds: ['AL-OFF-001'] },
    { id: 'AL-DEPT-002', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', code: 'AL-DEPT-DIASPORA-CHAPTERS', name: 'Department of International & Diaspora Chapters', description: 'Coordinates London, Washington DC, Dubai, and Nairobi alumni chapter charters.', headRole: 'HEAD_DIASPORA_CHAPTERS', officeIds: ['AL-OFF-002'] },
    { id: 'AL-DEPT-003', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', code: 'AL-DEPT-DUES-COLLECTION', name: 'Department of Annual Subscriptions & Life Membership', description: 'Automates annual subscription renewal invoices, Pegasus mobile money, and life member cards.', headRole: 'HEAD_SUBSCRIPTIONS_BURSARY', officeIds: ['AL-OFF-003'] },
    { id: 'AL-DEPT-004', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', code: 'AL-DEPT-ENDOWMENT-TRUST', name: 'Department of Legacy Endowment Fund & Scholarships', description: 'Manages multi-billion alumni endowment trust for alma mater infrastructure and student scholarships.', headRole: 'HEAD_ENDOWMENT_INVESTMENTS', officeIds: ['AL-OFF-004'] },
    { id: 'AL-DEPT-005', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', code: 'AL-DEPT-MENTORSHIP-MATCH', name: 'Department of Student Mentorship & Coaching Network', description: 'Pairs senior corporate alumni executives with graduating university students for 6-month mentorship.', headRole: 'HEAD_MENTORSHIP_PROGRAMS', officeIds: ['AL-OFF-005'] },
    { id: 'AL-DEPT-006', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', code: 'AL-DEPT-JOB-OPPORTUNITIES', name: 'Department of Executive Job Board & Internships', description: 'Exclusive alumni career portal for senior management openings and student internship attachments.', headRole: 'HEAD_CAREER_PLACEMENT', officeIds: ['AL-OFF-006'] },
    { id: 'AL-DEPT-007', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', code: 'AL-DEPT-HOMECOMING-DINNER', name: 'Department of Annual Homecoming & Event Ticketing', description: 'Annual dinner table sales, QR e-tickets, golf open tournament, and cohort reunion logistics.', headRole: 'HEAD_EVENT_OPERATIONS', officeIds: ['AL-OFF-007'] },
    { id: 'AL-DEPT-008', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', code: 'AL-DEPT-ALUMNI-AWARDS', name: 'Department of Distinguished Alumni Awards & Hall of Fame', description: 'Nominations, public voting, and jury awards for outstanding public service, business, and science.', headRole: 'HEAD_HONORS_AWARDS', officeIds: ['AL-OFF-008'] }
  ],
  offices: [
    { id: 'AL-OFF-001', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-001', code: 'AL-OFF-VERIFICATION-DESK', name: 'Alumni Verification & Cohort Records Desk', description: 'Verifies graduation year transcripts and issues official digital alumni membership IDs.', officerRole: 'ALUMNI_REGISTRAR', portalIds: ['AL-PORTAL-001', 'AL-PORTAL-002'], moduleIds: ['AL-MOD-001'] },
    { id: 'AL-OFF-002', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-002', code: 'AL-OFF-DIASPORA-LIAISON', name: 'Global Diaspora Chapters Liaison Office', description: 'Manages chapter elections, overseas bank remittances, and global networking webinars.', officerRole: 'DIASPORA_LIAISON_OFFICER', portalIds: ['AL-PORTAL-001', 'AL-PORTAL-002'], moduleIds: ['AL-MOD-002'] },
    { id: 'AL-OFF-003', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-003', code: 'AL-OFF-DUES-CASHIER', name: 'Subscription Dues & Membership Counter', description: 'Issues annual subscription receipts, Gold/Platinum life member cards, and financial statements.', officerRole: 'TREASURY_ACCOUNTANT', portalIds: ['AL-PORTAL-001', 'AL-PORTAL-002'], moduleIds: ['AL-MOD-003'] },
    { id: 'AL-OFF-004', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-004', code: 'AL-OFF-ENDOWMENT-DESK', name: 'Endowment Fund & Student Scholarship Desk', description: 'Tracks endowment principal capital, Treasury bond interest yield, and bursary awards.', officerRole: 'ENDOWMENT_FUND_MANAGER', portalIds: ['AL-PORTAL-001'], moduleIds: ['AL-MOD-004'] },
    { id: 'AL-OFF-005', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-005', code: 'AL-OFF-MENTORSHIP-HUB', name: 'Corporate Mentorship & Coaching Hub Desk', description: 'Matches student mentees with industry veterans and tracks monthly coaching sessions.', officerRole: 'MENTORSHIP_COORDINATOR', portalIds: ['AL-PORTAL-002'], moduleIds: ['AL-MOD-005'] },
    { id: 'AL-OFF-006', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-006', code: 'AL-OFF-CAREERS-DESK', name: 'Executive Job Board & Internship Placement Desk', description: 'Vets corporate employer vacancies and reviews student internship applications.', officerRole: 'CAREER_PLACEMENT_OFFICER', portalIds: ['AL-PORTAL-002', 'AL-PORTAL-003'], moduleIds: ['AL-MOD-006'] },
    { id: 'AL-OFF-007', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-007', code: 'AL-OFF-TICKETING-DESK', name: 'Annual Dinner Ticketing & Reunions Desk', description: 'Corporate table bookings, QR gate pass generation, and reunion seating plans.', officerRole: 'EVENTS_MANAGER', portalIds: ['AL-PORTAL-001', 'AL-PORTAL-002'], moduleIds: ['AL-MOD-007'] },
    { id: 'AL-OFF-008', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-008', code: 'AL-OFF-AWARDS-DESK', name: 'Distinguished Alumni Honors & Awards Office', description: 'Gathers nomination dossiers, tallies committee scores, and orders crystal trophies.', officerRole: 'AWARDS_COMMITTEE_SECRETARY', portalIds: ['AL-PORTAL-001', 'AL-PORTAL-002'], moduleIds: ['AL-MOD-008'] }
  ],
  portals: [
    { id: 'AL-PORTAL-001', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-001', officeId: 'AL-OFF-001', code: 'AL-PORTAL-EXECUTIVE-BOARD', name: 'Alumni National Executive & Trustees Portal', description: 'Total active alumni members, annual dues collections, endowment portfolio balance, and chapter performance.', targetRole: 'ALUMNI_PRESIDENT', authLevel: 'PKI_SOVEREIGN', route: '/alumni/board', moduleIds: ['AL-MOD-001', 'AL-MOD-003', 'AL-MOD-004', 'AL-MOD-007', 'AL-MOD-008'] },
    { id: 'AL-PORTAL-002', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-001', officeId: 'AL-OFF-001', code: 'AL-PORTAL-SECRETARIAT-STAFF', name: 'Alumni Association Secretariat Workspace', description: 'Verify graduate credentials, post job openings, manage dinner ticketing, and coordinate mentorship pairings.', targetRole: 'SECRETARIAT_STAFF', authLevel: 'STAFF', route: '/alumni/staff', moduleIds: ['AL-MOD-001', 'AL-MOD-002', 'AL-MOD-003', 'AL-MOD-005', 'AL-MOD-006', 'AL-MOD-007', 'AL-MOD-008'] },
    { id: 'AL-PORTAL-003', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-006', officeId: 'AL-OFF-006', code: 'AL-PORTAL-MEMBER-APP', name: 'Alumni Network Mobile App & Directory', description: 'Search old classmates, pay annual subscription dues, browse exclusive jobs, and buy reunion dinner tickets.', targetRole: 'ALUMNI_MEMBER', authLevel: 'PUBLIC', route: '/alumni/member', moduleIds: ['AL-MOD-001', 'AL-MOD-003', 'AL-MOD-005', 'AL-MOD-006', 'AL-MOD-007'] }
  ],
  modules: [
    { id: 'AL-MOD-001', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-001', officeId: 'AL-OFF-001', portalId: 'AL-PORTAL-002', code: 'AL-MOD-COHORT-DIRECTORY', name: 'Cohort Class Directory & Verified Membership ID', description: 'Searchable alumni directory by class year, professional industry, and digital NFC membership card.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-001', 'AL-CAP-002'], screenIds: ['AL-SCR-001'], formIds: ['AL-FORM-001'], dashboardIds: ['AL-DASH-001'], reportIds: ['AL-REP-001'], workflowIds: ['AL-WF-001'], databaseEntityIds: ['AL-DB-001'], apiIds: ['AL-API-001'], runtimeComponentId: 'AL-RTC-001', permissionIds: ['AL-PERM-001'] },
    { id: 'AL-MOD-002', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-002', officeId: 'AL-OFF-002', portalId: 'AL-PORTAL-002', code: 'AL-MOD-DIASPORA-CHAPTERS', name: 'Global Diaspora Chapters & Regional Branches', description: 'Manages international alumni chapters, executive committees, and regional chapter bank accounts.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-003', 'AL-CAP-004'], screenIds: ['AL-SCR-002'], formIds: ['AL-FORM-002'], dashboardIds: ['AL-DASH-001'], reportIds: ['AL-REP-002'], workflowIds: ['AL-WF-002'], databaseEntityIds: ['AL-DB-002'], apiIds: ['AL-API-002'], runtimeComponentId: 'AL-RTC-002', permissionIds: ['AL-PERM-002'] },
    { id: 'AL-MOD-003', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-003', officeId: 'AL-OFF-003', portalId: 'AL-PORTAL-001', code: 'AL-MOD-DUES-COLLECTION', name: 'Annual Subscription Dues & Life Membership Ledger', description: 'Automates subscription invoicing, Mobile Money/Card payment ingestion, and life membership certificates.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-005', 'AL-CAP-006'], screenIds: ['AL-SCR-003'], formIds: ['AL-FORM-003'], dashboardIds: ['AL-DASH-002'], reportIds: ['AL-REP-003'], workflowIds: ['AL-WF-003'], databaseEntityIds: ['AL-DB-003'], apiIds: ['AL-API-003'], runtimeComponentId: 'AL-RTC-003', permissionIds: ['AL-PERM-003'] },
    { id: 'AL-MOD-004', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-004', officeId: 'AL-OFF-004', portalId: 'AL-PORTAL-001', code: 'AL-MOD-ENDOWMENT-TRUST', name: 'Legacy Endowment Trust & Alma Mater Grants', description: 'Invests capital in Treasury bills/bonds, tracks donor endowments, and funds student scholarships.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-007', 'AL-CAP-008'], screenIds: ['AL-SCR-004'], formIds: ['AL-FORM-004'], dashboardIds: ['AL-DASH-002'], reportIds: ['AL-REP-004'], workflowIds: ['AL-WF-004'], databaseEntityIds: ['AL-DB-004'], apiIds: ['AL-API-004'], runtimeComponentId: 'AL-RTC-004', permissionIds: ['AL-PERM-004'] },
    { id: 'AL-MOD-005', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-005', officeId: 'AL-OFF-005', portalId: 'AL-PORTAL-002', code: 'AL-MOD-MENTORSHIP-HUB', name: 'Student Mentorship & Executive Coaching Hub', description: 'Algorithmically matches final-year students with alumni executives for 6-month career preparation.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-009', 'AL-CAP-010'], screenIds: ['AL-SCR-005'], formIds: ['AL-FORM-005'], dashboardIds: ['AL-DASH-003'], reportIds: ['AL-REP-005'], workflowIds: ['AL-WF-005'], databaseEntityIds: ['AL-DB-005'], apiIds: ['AL-API-005'], runtimeComponentId: 'AL-RTC-005', permissionIds: ['AL-PERM-005'] },
    { id: 'AL-MOD-006', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-006', officeId: 'AL-OFF-006', portalId: 'AL-PORTAL-003', code: 'AL-MOD-JOB-PORTAL', name: 'Executive Job Board & Internship Attachment Board', description: 'Alumni-only job vacancies, headhunting talent directory, and undergraduate internship postings.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-011', 'AL-CAP-012'], screenIds: ['AL-SCR-006'], formIds: ['AL-FORM-006'], dashboardIds: ['AL-DASH-003'], reportIds: ['AL-REP-006'], workflowIds: ['AL-WF-006'], databaseEntityIds: ['AL-DB-006'], apiIds: ['AL-API-006'], runtimeComponentId: 'AL-RTC-006', permissionIds: ['AL-PERM-006'] },
    { id: 'AL-MOD-007', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-007', officeId: 'AL-OFF-007', portalId: 'AL-PORTAL-002', code: 'AL-MOD-REUNION-TICKETING', name: 'Annual Dinner, Golf Open & Reunion Ticketing', description: 'E-ticketing engine with QR code generation, corporate table reservations, and seating arrangements.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-013', 'AL-CAP-014'], screenIds: ['AL-SCR-007'], formIds: ['AL-FORM-007'], dashboardIds: ['AL-DASH-004'], reportIds: ['AL-REP-007'], workflowIds: ['AL-WF-007'], databaseEntityIds: ['AL-DB-007'], apiIds: ['AL-API-007'], runtimeComponentId: 'AL-RTC-007', permissionIds: ['AL-PERM-007'] },
    { id: 'AL-MOD-008', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-008', officeId: 'AL-OFF-008', portalId: 'AL-PORTAL-001', code: 'AL-MOD-AWARDS-HONORS', name: 'Distinguished Alumni Awards & Hall of Fame', description: 'Nominations intake, peer voting audit, jury scorecards, and historical Hall of Fame gallery.', status: 'ACTIVE_CORE', capabilityIds: ['AL-CAP-015', 'AL-CAP-016'], screenIds: ['AL-SCR-008'], formIds: ['AL-FORM-008'], dashboardIds: ['AL-DASH-004'], reportIds: ['AL-REP-008'], workflowIds: ['AL-WF-008'], databaseEntityIds: ['AL-DB-008'], apiIds: ['AL-API-008'], runtimeComponentId: 'AL-RTC-008', permissionIds: ['AL-PERM-008'] }
  ],
  capabilities: [
    { id: 'AL-CAP-001', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-001', officeId: 'AL-OFF-001', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-001', code: 'AL_CAP_VERIFY_ALUMNUS', name: 'Verify & Approve Alumni Registration', description: 'Cross-checks university graduation register and issues permanent digital membership ID.', serviceAction: 'alumni.membership.verifyAlumnus', requiredPermission: 'AL-PERM-001', runtimeComponentId: 'AL-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-002', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-001', officeId: 'AL-OFF-001', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-001', code: 'AL_CAP_ISSUE_DIGITAL_CARD', name: 'Issue NFC Digital Alumni ID Card', description: 'Generates Apple Wallet / Google Wallet pass with member tier, QR code, and photo.', serviceAction: 'alumni.membership.issueDigitalCard', requiredPermission: 'AL-PERM-001', runtimeComponentId: 'AL-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-003', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-002', officeId: 'AL-OFF-002', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-002', code: 'AL_CAP_CHARTER_DIASPORA_CHAPTER', name: 'Charter International Diaspora Chapter', description: 'Approves chapter constitution, recognizes elected chairperson, and creates official hub.', serviceAction: 'alumni.chapters.charterChapter', requiredPermission: 'AL-PERM-002', runtimeComponentId: 'AL-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-004', productId: 'prod-alumni-community', directorateId: 'AL-DIR-001', departmentId: 'AL-DEPT-002', officeId: 'AL-OFF-002', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-002', code: 'AL_CAP_REMIT_CHAPTER_FUNDS', name: 'Reconcile Chapter Dues Remittance', description: 'Receives international wire transfer for chapter share of annual subscription dues.', serviceAction: 'alumni.chapters.remitFunds', requiredPermission: 'AL-PERM-002', runtimeComponentId: 'AL-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-005', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-003', officeId: 'AL-OFF-003', portalId: 'AL-PORTAL-001', moduleId: 'AL-MOD-003', code: 'AL_CAP_COLLECT_SUBSCRIPTION_DUES', name: 'Process Annual Subscription Dues Payment', description: 'Reconciles mobile money or card payment against member dues account and sends receipt.', serviceAction: 'alumni.treasury.collectDues', requiredPermission: 'AL-PERM-003', runtimeComponentId: 'AL-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-006', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-003', officeId: 'AL-OFF-003', portalId: 'AL-PORTAL-001', moduleId: 'AL-MOD-003', code: 'AL_CAP_UPGRADE_LIFE_MEMBERSHIP', name: 'Grant Distinguished Life Membership', description: 'Enrolls donor as Life Patron upon one-off qualifying endowment or milestone donation.', serviceAction: 'alumni.treasury.upgradeLifeMembership', requiredPermission: 'AL-PERM-003', runtimeComponentId: 'AL-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-007', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-004', officeId: 'AL-OFF-004', portalId: 'AL-PORTAL-001', moduleId: 'AL-MOD-004', code: 'AL_CAP_RECORD_ENDOWMENT_DONATION', name: 'Record Named Capital Endowment Donation', description: 'Establishes named scholarship or capital project fund with legal deed of gift.', serviceAction: 'alumni.endowment.recordDonation', requiredPermission: 'AL-PERM-004', runtimeComponentId: 'AL-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-008', productId: 'prod-alumni-community', directorateId: 'AL-DIR-002', departmentId: 'AL-DEPT-004', officeId: 'AL-OFF-004', portalId: 'AL-PORTAL-001', moduleId: 'AL-MOD-004', code: 'AL_CAP_DISBURSE_ALUMNI_SCHOLARSHIP', name: 'Award Alumni Needy Student Scholarship', description: 'Transfers tuition funds directly to university bursary for qualifying undergraduate scholar.', serviceAction: 'alumni.endowment.disburseScholarship', requiredPermission: 'AL-PERM-004', runtimeComponentId: 'AL-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-009', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-005', officeId: 'AL-OFF-005', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-005', code: 'AL_CAP_MATCH_MENTOR_MENTEE', name: 'Pair Executive Mentor with Student Mentee', description: 'Runs AI match based on career aspiration, degree program, and mentor industry domain.', serviceAction: 'alumni.mentorship.matchPair', requiredPermission: 'AL-PERM-005', runtimeComponentId: 'AL-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-010', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-005', officeId: 'AL-OFF-005', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-005', code: 'AL_CAP_LOG_MENTORSHIP_SESSION', name: 'Log Mentorship Coaching Milestone', description: 'Records session date, discussion topics (CV review, mock interview), and feedback score.', serviceAction: 'alumni.mentorship.logSession', requiredPermission: 'AL-PERM-005', runtimeComponentId: 'AL-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-011', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-006', officeId: 'AL-OFF-006', portalId: 'AL-PORTAL-003', moduleId: 'AL-MOD-006', code: 'AL_CAP_POST_JOB_OPENING', name: 'Post Executive Job Opening / Internship', description: 'Publishes verified employment opportunity to network members with direct resume drop.', serviceAction: 'alumni.jobs.postJob', requiredPermission: 'AL-PERM-006', runtimeComponentId: 'AL-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-012', productId: 'prod-alumni-community', directorateId: 'AL-DIR-003', departmentId: 'AL-DEPT-006', officeId: 'AL-OFF-006', portalId: 'AL-PORTAL-003', moduleId: 'AL-MOD-006', code: 'AL_CAP_SUBMIT_JOB_APPLICATION', name: 'Submit One-Click Alumni Job Application', description: 'Submits verified alumni profile, LinkedIn URL, and CV directly to corporate hiring manager.', serviceAction: 'alumni.jobs.submitApplication', requiredPermission: 'AL-PERM-006', runtimeComponentId: 'AL-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-013', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-007', officeId: 'AL-OFF-007', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-007', code: 'AL_CAP_SELL_DINNER_TICKET', name: 'Sell Annual Homecoming Dinner Ticket / Table', description: 'Generates cryptographic QR ticket for individual seat or 10-person corporate table.', serviceAction: 'alumni.events.sellDinnerTicket', requiredPermission: 'AL-PERM-007', runtimeComponentId: 'AL-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-014', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-007', officeId: 'AL-OFF-007', portalId: 'AL-PORTAL-002', moduleId: 'AL-MOD-007', code: 'AL_CAP_SCAN_EVENT_TICKET', name: 'Scan & Validate Event QR Gate Pass', description: 'Validates ticket authenticity at banquet hall gate to prevent double entry.', serviceAction: 'alumni.events.scanTicket', requiredPermission: 'AL-PERM-007', runtimeComponentId: 'AL-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-015', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-008', officeId: 'AL-OFF-008', portalId: 'AL-PORTAL-001', moduleId: 'AL-MOD-008', code: 'AL_CAP_SUBMIT_AWARD_NOMINATION', name: 'Submit Distinguished Alumnus Nomination', description: 'Submits candidate biography, career accomplishments, and supporting citation letters.', serviceAction: 'alumni.awards.submitNomination', requiredPermission: 'AL-PERM-008', runtimeComponentId: 'AL-RTC-008', status: 'ACTIVE_CORE' },
    { id: 'AL-CAP-016', productId: 'prod-alumni-community', directorateId: 'AL-DIR-004', departmentId: 'AL-DEPT-008', officeId: 'AL-OFF-008', portalId: 'AL-PORTAL-001', moduleId: 'AL-MOD-008', code: 'AL_CAP_TALLY_AWARDS_VOTES', name: 'Tally Jury & Public Awards Scorecard', description: 'Calculates weighted score (70% Jury / 30% Member Voting) and declares award winners.', serviceAction: 'alumni.awards.tallyVotes', requiredPermission: 'AL-PERM-008', runtimeComponentId: 'AL-RTC-008', status: 'ACTIVE_CORE' }
  ],
  screens: [
    { id: 'AL-SCR-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', code: 'AL-SCR-DIRECTORY', title: 'Alumni Cohort Directory & Verified Rolls', description: 'Searchable alumni database and class rosters.', viewType: 'TABLE', route: '/alumni/directory' },
    { id: 'AL-SCR-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', code: 'AL-SCR-CHAPTERS', title: 'Global Diaspora & Regional Chapter Hubs', description: 'International chapters, leaders, and events.', viewType: 'DASHBOARD', route: '/alumni/chapters' },
    { id: 'AL-SCR-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', code: 'AL-SCR-DUES', title: 'Subscription Dues & Life Member Cashbook', description: 'Annual subscriptions and financial statements.', viewType: 'TABLE', route: '/alumni/dues' },
    { id: 'AL-SCR-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', code: 'AL-SCR-ENDOWMENT', title: 'Legacy Endowment Trust & Scholarships', description: 'Capital portfolio yield and student bursaries.', viewType: 'TABLE', route: '/alumni/endowment' },
    { id: 'AL-SCR-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', code: 'AL-SCR-MENTORSHIP', title: 'Student Mentorship & Coaching Network', description: 'Active mentor pairs and session logs.', viewType: 'TABLE', route: '/alumni/mentorship' },
    { id: 'AL-SCR-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', code: 'AL-SCR-JOBS', title: 'Executive Job Board & Internship Portal', description: 'Exclusive job listings and applicant resumes.', viewType: 'TABLE', route: '/alumni/jobs' },
    { id: 'AL-SCR-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', code: 'AL-SCR-REUNIONS', title: 'Annual Dinner & Reunion Ticketing Console', description: 'Table reservations and QR gate passes.', viewType: 'TABLE', route: '/alumni/events' },
    { id: 'AL-SCR-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', code: 'AL-SCR-AWARDS', title: 'Distinguished Alumni Awards & Hall of Fame', description: 'Nomination dockets and Hall of Fame gallery.', viewType: 'DASHBOARD', route: '/alumni/awards' }
  ],
  forms: [
    { id: 'AL-FORM-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', code: 'AL-FORM-MEMBER-ENROLL', title: 'Alumni Membership Verification & Profile Enrollment', submitAction: 'alumni.membership.verifyAlumnus', fieldCount: 5, fields: [{ name: 'fullName', label: 'Full Legal Name', type: 'text', required: true }, { name: 'graduationYear', label: 'Year of Graduation (e.g. 2018)', type: 'number', required: true }, { name: 'degreeFaculty', label: 'Degree / Program & Faculty', type: 'text', required: true }, { name: 'currentJobTitle', label: 'Current Employer & Job Title', type: 'text', required: true }, { name: 'phoneMobileMoney', label: 'Phone Number (Mobile Money)', type: 'text', required: true }], validationRules: ['YEAR_VALID'] },
    { id: 'AL-FORM-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', code: 'AL-FORM-CHAPTER-CREATE', title: 'Diaspora Chapter Charter Application', submitAction: 'alumni.chapters.charterChapter', fieldCount: 5, fields: [{ name: 'chapterCountryCity', label: 'Chapter Country / City (e.g. UK - London)', type: 'text', required: true }, { name: 'chapterChairperson', label: 'Elected Chapter Chairperson Name', type: 'text', required: true }, { name: 'chairpersonEmail', label: 'Chairperson Official Email', type: 'email', required: true }, { name: 'estimatedMembers', label: 'Estimated Active Members in Region', type: 'number', required: true }, { name: 'bankAccountDetails', label: 'Chapter Regional Bank Details', type: 'textarea', required: true }], validationRules: ['EMAIL_VALID'] },
    { id: 'AL-FORM-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', code: 'AL-FORM-DUES-PAY', title: 'Annual Alumni Subscription Dues Payment', submitAction: 'alumni.treasury.collectDues', fieldCount: 4, fields: [{ name: 'alumnusMemberId', label: 'Alumni Member ID Number', type: 'text', required: true }, { name: 'membershipTier', label: 'Subscription Tier (Annual UGX 100k / Life Patron UGX 2M)', type: 'select', required: true }, { name: 'paymentChannel', label: 'Channel (MTN MoMo / Airtel / Card / Bank)', type: 'select', required: true }, { name: 'transactionRef', label: 'Transaction Reference / Receipt PIN', type: 'text', required: true }], validationRules: ['REF_NOT_EMPTY'] },
    { id: 'AL-FORM-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', code: 'AL-FORM-ENDOWMENT-GIFT', title: 'Deed of Gift Capital Endowment Contribution', submitAction: 'alumni.endowment.recordDonation', fieldCount: 5, fields: [{ name: 'donorLegalName', label: 'Donor / Corporate Entity Legal Name', type: 'text', required: true }, { name: 'endowmentCategory', label: 'Designation (Needy Bursary / Engineering Lab / General)', type: 'select', required: true }, { name: 'donationAmount', label: 'Gift Amount (UGX / USD)', type: 'number', required: true }, { name: 'currency', label: 'Currency Code (UGX/USD/GBP)', type: 'select', required: true }, { name: 'recognitionPreference', label: 'Public Recognition / Anonymous', type: 'select', required: true }], validationRules: ['AMOUNT_POSITIVE'] },
    { id: 'AL-FORM-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', code: 'AL-FORM-MENTOR-ENROLL', title: 'Executive Mentor Volunteer Registration', submitAction: 'alumni.mentorship.matchPair', fieldCount: 5, fields: [{ name: 'mentorFullName', label: 'Mentor Full Name', type: 'text', required: true }, { name: 'corporateDesignation', label: 'Executive Role & Company', type: 'text', required: true }, { name: 'yearsOfExperience', label: 'Years of Professional Experience', type: 'number', required: true }, { name: 'maxMentees', label: 'Max Students to Coach (1-3)', type: 'number', required: true }, { name: 'specialtyAreas', label: 'Coaching Focus (Finance / Tech / Law / Medicine)', type: 'select', required: true }], validationRules: ['EXPERIENCE_GTE_5'] },
    { id: 'AL-FORM-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', code: 'AL-FORM-JOB-POST', title: 'Post Alumni Executive Vacancy / Internship', submitAction: 'alumni.jobs.postJob', fieldCount: 5, fields: [{ name: 'jobTitle', label: 'Job / Internship Position Title', type: 'text', required: true }, { name: 'hiringCompany', label: 'Hiring Company / Organization', type: 'text', required: true }, { name: 'employmentType', label: 'Type (Full-Time / Executive / Internship)', type: 'select', required: true }, { name: 'salaryRangeUgx', label: 'Salary Range / Allowance', type: 'text', required: false }, { name: 'jobDescription', label: 'Key Requirements & How to Apply', type: 'textarea', required: true }], validationRules: ['TITLE_NOT_EMPTY'] },
    { id: 'AL-FORM-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', code: 'AL-FORM-DINNER-TICKET', title: 'Homecoming Dinner Ticket & Table Reservation', submitAction: 'alumni.events.sellDinnerTicket', fieldCount: 5, fields: [{ name: 'attendeeFullName', label: 'Lead Attendee / Company Name', type: 'text', required: true }, { name: 'ticketType', label: 'Ticket Option (Single Seat / Couple / Corporate Table 10)', type: 'select', required: true }, { name: 'cohortYearTable', label: 'Preferred Cohort Year Seating Table', type: 'number', required: false }, { name: 'dietaryRequirements', label: 'Special Dietary Preference (Vegetarian / Halal)', type: 'text', required: false }, { name: 'mobileMoneyPhone', label: 'Payment Mobile Money Number', type: 'text', required: true }], validationRules: ['PHONE_VALID'] },
    { id: 'AL-FORM-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', code: 'AL-FORM-AWARD-NOM', title: 'Distinguished Alumnus Award Nomination Dossier', submitAction: 'alumni.awards.submitNomination', fieldCount: 5, fields: [{ name: 'nomineeFullName', label: 'Nominee Full Name & Class Year', type: 'text', required: true }, { name: 'awardCategory', label: 'Award Category (Lifetime Service / STEM / Entrepreneurship)', type: 'select', required: true }, { name: 'accomplishmentNarrative', label: 'Citation of Major Career Achievements', type: 'textarea', required: true }, { name: 'supportingEvidenceUrl', label: 'Portfolio / Press Articles URL', type: 'text', required: false }, { name: 'nominatorStaffId', label: 'Nominator Member ID', type: 'text', required: true }], validationRules: ['CITATION_MIN_100_WORDS'] }
  ],
  dashboards: [
    {
      id: 'AL-DASH-001',
      productId: 'prod-alumni-community',
      moduleId: 'AL-MOD-001',
      code: 'AL-DASH-MEMBERSHIP',
      title: 'Global Alumni Network & Cohort Demographics',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Verified Alumni Members', value: '48,200 Alumni', trend: 'up', change: 'Across 62 Cohort Years' },
        { label: 'Active International Chapters', value: '18 Chapters', trend: 'up', change: 'UK, USA, UAE, Kenya' },
        { label: 'Digital NFC Cards Issued', value: '31,400 Passes', trend: 'up', change: 'Apple/Google Wallet' },
        { label: 'Directory Engagement Rate', value: '82.4%', trend: 'up', change: 'Monthly Peer Searches' }
      ]
    },
    {
      id: 'AL-DASH-002',
      productId: 'prod-alumni-community',
      moduleId: 'AL-MOD-003',
      code: 'AL-DASH-FINANCIALS',
      title: 'Association Subscriptions & Legacy Endowment Trust',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Annual Dues Collections', value: 'UGX 1.84 Billion', trend: 'up', change: '84% Compliance' },
        { label: 'Legacy Endowment Capital', value: 'UGX 12.5 Billion', trend: 'up', change: 'Invested in T-Bonds' },
        { label: 'Endowment Annual Yield', value: 'UGX 1.6 Billion', trend: 'up', change: '13.2% Weighted ROI' },
        { label: 'Needy Scholarships Funded', value: '148 Students', trend: 'up', change: '100% Tuition Covered' }
      ]
    },
    {
      id: 'AL-DASH-003',
      productId: 'prod-alumni-community',
      moduleId: 'AL-MOD-005',
      code: 'AL-DASH-CAREERS',
      title: 'Executive Mentorship & Alumni Job Placement',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Active Mentorship Pairs', value: '420 Pairs', trend: 'up', change: '6-Month Cohorts' },
        { label: 'Senior Executive Mentors', value: '280 Mentors', trend: 'up', change: 'CEOs & Directors' },
        { label: 'Exclusive Jobs Posted', value: '184 Positions', trend: 'up', change: 'Alumni Recruited' },
        { label: 'Internship Placement Rate', value: '94.2%', trend: 'up', change: 'Final-Year Students' }
      ]
    },
    {
      id: 'AL-DASH-004',
      productId: 'prod-alumni-community',
      moduleId: 'AL-MOD-007',
      code: 'AL-DASH-EVENTS-HONORS',
      title: 'Annual Dinner Reunions & Hall of Fame Awards',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Homecoming Dinner Tickets Sold', value: '1,800 Guests', trend: 'up', change: '180 Tables Sold Out' },
        { label: 'Reunion Ticket Revenue', value: 'UGX 450 Million', trend: 'up', change: 'Sponsorships Included' },
        { label: 'Distinguished Award Nominees', value: '42 Leaders', trend: 'neutral', change: 'Jury Reviewing' },
        { label: 'Hall of Fame Inductees', value: '6 Laureates', trend: 'up', change: 'Lifetime Honors' }
      ]
    }
  ],
  reports: [
    { id: 'AL-REP-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', code: 'AL-REP-COHORT-CENSUS', title: 'Global Alumni Demographics & Cohort Census Register', format: 'TABULAR', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'AL-REP-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', code: 'AL-REP-CHAPTERS-ROSTER', title: 'International Diaspora Chapters & Remittance Audit', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'AL-REP-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', code: 'AL-REP-DUES-STATEMENT', title: 'Audited Statement of Annual Subscriptions & Life Dues', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'AL-REP-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', code: 'AL-REP-ENDOWMENT-AUDIT', title: 'Endowment Trust Portfolio & Scholarship Disbursement Audit', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'AL-REP-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', code: 'AL-REP-MENTORSHIP-LOG', title: 'Mentorship Coaching Outcomes & Student Impact Report', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'AL-REP-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', code: 'AL-REP-JOBS-METRICS', title: 'Alumni Executive Job Placement & Corporate Recruitment Log', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'AL-REP-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', code: 'AL-REP-DINNER-RECEIPTS', title: 'Annual Homecoming Dinner Ticketing & Seating Register', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'AL-REP-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', code: 'AL-REP-AWARDS-CITATIONS', title: 'Distinguished Alumni Awards Jury Scorecard & Citations', format: 'SUMMARY', exportTypes: ['PDF'] }
  ],
  workflows: [
    { id: 'AL-WF-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', code: 'AL-WF-VERIFICATION', title: 'Graduate Credential Verification & ID Flow', stages: ['Registration Submit', 'Degree Verification', 'Secretariat Approval', 'Digital NFC Card Issuance'], slaHours: 24, requiredApprovers: ['ALUMNI_REGISTRAR'], initialState: 'Registration Submit' },
    { id: 'AL-WF-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', code: 'AL-WF-CHAPTER-CHARTER', title: 'Diaspora Chapter Charter Approval Flow', stages: ['Petition Review', 'Constitution Audit', 'Board Vote', 'Charter Ceremony'], slaHours: 72, requiredApprovers: ['DIASPORA_LIAISON_OFFICER', 'ALUMNI_PRESIDENT'], initialState: 'Petition Review' },
    { id: 'AL-WF-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', code: 'AL-WF-DUES-INVOICE', title: 'Annual Subscription Renewal & Receipt Flow', stages: ['Invoice Auto-Generate', 'Payment Ingest', 'General Ledger Credit', 'Receipt & Badge Issue'], slaHours: 1, requiredApprovers: ['TREASURY_ACCOUNTANT'], initialState: 'Invoice Auto-Generate' },
    { id: 'AL-WF-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', code: 'AL-WF-SCHOLARSHIP', title: 'Endowment Needy Scholarship Award Flow', stages: ['Student Hardship Application', 'Academic Vetting', 'Trustee Approval', 'Tuition Wire to Alma Mater'], slaHours: 48, requiredApprovers: ['ENDOWMENT_FUND_MANAGER', 'ASSOCIATION_TREASURER'], initialState: 'Student Hardship Application' },
    { id: 'AL-WF-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', code: 'AL-WF-MENTOR-MATCH', title: 'Corporate Mentorship Pairing Flow', stages: ['Student Goal Profile', 'AI Compatibility Match', 'Mentor Acceptance', 'Orientation Launch'], slaHours: 48, requiredApprovers: ['MENTORSHIP_COORDINATOR'], initialState: 'Student Goal Profile' },
    { id: 'AL-WF-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', code: 'AL-WF-JOB-VETTING', title: 'Executive Job Posting Vetting Flow', stages: ['Employer Submission', 'Salary & Terms Audit', 'Post to Network', 'Applicant Longlist Handover'], slaHours: 12, requiredApprovers: ['CAREER_PLACEMENT_OFFICER'], initialState: 'Employer Submission' },
    { id: 'AL-WF-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', code: 'AL-WF-EVENT-TICKET', title: 'Homecoming Dinner Ticketing & Seating Flow', stages: ['Table Order', 'Payment Reconciliation', 'QR Pass Delivery', 'Gate Scan Tally'], slaHours: 1, requiredApprovers: ['EVENTS_MANAGER'], initialState: 'Table Order' },
    { id: 'AL-WF-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', code: 'AL-WF-AWARD-JUDGING', title: 'Distinguished Alumni Award Judging Flow', stages: ['Public Nominations', 'Shortlist Audit', 'Jury Evaluation', 'Award Ceremony Induction'], slaHours: 168, requiredApprovers: ['AWARDS_COMMITTEE_SECRETARY', 'ALUMNI_PRESIDENT'], initialState: 'Public Nominations' }
  ],
  databaseEntities: [
    { id: 'AL-DB-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', tableName: 'al_alumni_directory', primaryKey: 'member_id', fields: [{ name: 'member_id', type: 'VARCHAR(32)', required: true, indexed: true }, { name: 'full_name', type: 'VARCHAR(128)', required: true }, { name: 'grad_year', type: 'INT', required: true }], auditLogged: true },
    { id: 'AL-DB-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', tableName: 'al_diaspora_chapters', primaryKey: 'chapter_id', fields: [{ name: 'chapter_id', type: 'VARCHAR(32)', required: true, indexed: true }, { name: 'city_country', type: 'VARCHAR(128)', required: true }, { name: 'chairperson', type: 'VARCHAR(128)', required: true }], auditLogged: true },
    { id: 'AL-DB-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', tableName: 'al_dues_payments', primaryKey: 'payment_id', fields: [{ name: 'payment_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'member_id', type: 'VARCHAR(32)', required: true }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'AL-DB-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', tableName: 'al_endowment_trust', primaryKey: 'fund_id', fields: [{ name: 'fund_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'donor_name', type: 'VARCHAR(128)', required: true }, { name: 'balance_ugx', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'AL-DB-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', tableName: 'al_mentorship_pairs', primaryKey: 'pair_id', fields: [{ name: 'pair_id', type: 'VARCHAR(64)', required: true }, { name: 'mentor_id', type: 'VARCHAR(32)', required: true }, { name: 'mentee_id', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'AL-DB-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', tableName: 'al_job_postings', primaryKey: 'job_id', fields: [{ name: 'job_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'title', type: 'VARCHAR(128)', required: true }, { name: 'company', type: 'VARCHAR(128)', required: true }], auditLogged: true },
    { id: 'AL-DB-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', tableName: 'al_dinner_tickets', primaryKey: 'ticket_id', fields: [{ name: 'ticket_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'buyer_name', type: 'VARCHAR(128)', required: true }, { name: 'table_no', type: 'INT', required: true }], auditLogged: true },
    { id: 'AL-DB-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', tableName: 'al_awards_nominations', primaryKey: 'nomination_id', fields: [{ name: 'nomination_id', type: 'VARCHAR(64)', required: true }, { name: 'nominee_name', type: 'VARCHAR(128)', required: true }, { name: 'category', type: 'VARCHAR(64)', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'AL-API-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', code: 'AL_API_MEMBERSHIP', method: 'POST', endpoint: '/api/v1/alumni/members/verify', requiredPermission: 'AL-PERM-001', handlerName: 'verifyAlumnusHandler', summary: 'Verify alumnus registration' },
    { id: 'AL-API-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', code: 'AL_API_CHAPTERS', method: 'POST', endpoint: '/api/v1/alumni/chapters/charter', requiredPermission: 'AL-PERM-002', handlerName: 'charterChapterHandler', summary: 'Charter diaspora chapter' },
    { id: 'AL-API-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', code: 'AL_API_DUES', method: 'POST', endpoint: '/api/v1/alumni/treasury/dues', requiredPermission: 'AL-PERM-003', handlerName: 'collectDuesHandler', summary: 'Collect annual subscription dues' },
    { id: 'AL-API-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', code: 'AL_API_ENDOWMENT', method: 'POST', endpoint: '/api/v1/alumni/endowment/donate', requiredPermission: 'AL-PERM-004', handlerName: 'recordEndowmentGiftHandler', summary: 'Record endowment donation' },
    { id: 'AL-API-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', code: 'AL_API_MENTORSHIP', method: 'POST', endpoint: '/api/v1/alumni/mentorship/match', requiredPermission: 'AL-PERM-005', handlerName: 'matchMentorMenteeHandler', summary: 'Match mentor with mentee' },
    { id: 'AL-API-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', code: 'AL_API_JOBS', method: 'POST', endpoint: '/api/v1/alumni/jobs/post', requiredPermission: 'AL-PERM-006', handlerName: 'postJobOpeningHandler', summary: 'Post executive job opening' },
    { id: 'AL-API-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', code: 'AL_API_EVENTS', method: 'POST', endpoint: '/api/v1/alumni/events/ticket', requiredPermission: 'AL-PERM-007', handlerName: 'sellDinnerTicketHandler', summary: 'Purchase dinner ticket' },
    { id: 'AL-API-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', code: 'AL_API_AWARDS', method: 'POST', endpoint: '/api/v1/alumni/awards/nominate', requiredPermission: 'AL-PERM-008', handlerName: 'submitAwardNominationHandler', summary: 'Submit award nomination' }
  ],
  runtimeComponents: [
    { id: 'AL-RTC-001', productId: 'prod-alumni-community', moduleId: 'AL-MOD-001', componentKey: 'AlumniCohortDirectoryEngine', name: 'Cohort Class Directory & Verified Membership ID', description: 'Searchable alumni registry and digital NFC wallet pass generator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MEMBERSHIP' },
    { id: 'AL-RTC-002', productId: 'prod-alumni-community', moduleId: 'AL-MOD-002', componentKey: 'AlumniDiasporaChaptersEngine', name: 'Global Diaspora Chapters & Regional Branches', description: 'International chapter management and remittance tracking.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CHAPTERS' },
    { id: 'AL-RTC-003', productId: 'prod-alumni-community', moduleId: 'AL-MOD-003', componentKey: 'AlumniDuesCollectionEngine', name: 'Annual Subscription Dues & Life Membership Ledger', description: 'Subscription billing engine and mobile money cashbook.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FINANCE' },
    { id: 'AL-RTC-004', productId: 'prod-alumni-community', moduleId: 'AL-MOD-004', componentKey: 'AlumniEndowmentTrustEngine', name: 'Legacy Endowment Trust & Alma Mater Grants', description: 'Treasury investments yield tracker and student scholarship disbursements.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ENDOWMENT' },
    { id: 'AL-RTC-005', productId: 'prod-alumni-community', moduleId: 'AL-MOD-005', componentKey: 'AlumniMentorshipHubEngine', name: 'Student Mentorship & Executive Coaching Hub', description: 'Executive-student coaching matching and milestone tracker.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MENTORSHIP' },
    { id: 'AL-RTC-006', productId: 'prod-alumni-community', moduleId: 'AL-MOD-006', componentKey: 'AlumniJobPortalEngine', name: 'Executive Job Board & Internship Attachment Board', description: 'Alumni job board and 1-click verified resume application pipeline.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CAREERS' },
    { id: 'AL-RTC-007', productId: 'prod-alumni-community', moduleId: 'AL-MOD-007', componentKey: 'AlumniReunionTicketingEngine', name: 'Annual Dinner, Golf Open & Reunion Ticketing', description: 'Banquet table reservation engine and QR gate ticket scanner.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EVENTS' },
    { id: 'AL-RTC-008', productId: 'prod-alumni-community', moduleId: 'AL-MOD-008', componentKey: 'AlumniAwardsHonorsEngine', name: 'Distinguished Alumni Awards & Hall of Fame', description: 'Awards nomination intake, jury scoring matrix, and Hall of Fame gallery.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'HONORS' }
  ],
  permissions: [
    { id: 'AL-PERM-001', productId: 'prod-alumni-community', code: 'alumni:membership:verify', name: 'Alumni Verification & Records', description: 'Authority to verify graduation credentials and issue ID cards' },
    { id: 'AL-PERM-002', productId: 'prod-alumni-community', code: 'alumni:chapters:diaspora', name: 'Diaspora Chapters Management', description: 'Authority to charter chapters and manage remittances' },
    { id: 'AL-PERM-003', productId: 'prod-alumni-community', code: 'alumni:treasury:dues', name: 'Subscription Dues Cashbook', description: 'Authority to bill dues and manage membership ledger' },
    { id: 'AL-PERM-004', productId: 'prod-alumni-community', code: 'alumni:endowment:trust', name: 'Endowment Trust Governance', description: 'Authority to record capital gifts and disburse scholarships' },
    { id: 'AL-PERM-005', productId: 'prod-alumni-community', code: 'alumni:mentorship:hub', name: 'Mentorship Network Governance', description: 'Authority to pair students with corporate alumni' },
    { id: 'AL-PERM-006', productId: 'prod-alumni-community', code: 'alumni:jobs:placement', name: 'Executive Job Board Management', description: 'Authority to vet and post employment vacancies' },
    { id: 'AL-PERM-007', productId: 'prod-alumni-community', code: 'alumni:events:reunions', name: 'Homecoming Dinner Ticketing', description: 'Authority to manage dinner table sales and QR access' },
    { id: 'AL-PERM-008', productId: 'prod-alumni-community', code: 'alumni:awards:honors', name: 'Distinguished Awards Governance', description: 'Authority to gather nominations and tally jury scorecards' }
  ],
  roles: [
    { id: 'AL-ROLE-001', productId: 'prod-alumni-community', code: 'ALUMNI_PRESIDENT', name: 'Alumni Association President', tier: 'GOVERNANCE', permissionIds: ['AL-PERM-001', 'AL-PERM-002', 'AL-PERM-003', 'AL-PERM-004', 'AL-PERM-007', 'AL-PERM-008'] },
    { id: 'AL-ROLE-002', productId: 'prod-alumni-community', code: 'EXECUTIVE_DIRECTOR', name: 'Alumni Executive Director', tier: 'EXECUTIVE', permissionIds: ['AL-PERM-001', 'AL-PERM-002', 'AL-PERM-005', 'AL-PERM-006', 'AL-PERM-007'] },
    { id: 'AL-ROLE-003', productId: 'prod-alumni-community', code: 'ASSOCIATION_TREASURER', name: 'Association Treasurer', tier: 'EXECUTIVE', permissionIds: ['AL-PERM-003', 'AL-PERM-004'] },
    { id: 'AL-ROLE-004', productId: 'prod-alumni-community', code: 'CHAPTER_SECRETARY', name: 'Chapter Secretary / Officer', tier: 'OPERATIONAL', permissionIds: ['AL-PERM-001', 'AL-PERM-002', 'AL-PERM-005'] },
    { id: 'AL-ROLE-005', productId: 'prod-alumni-community', code: 'VERIFIED_ALUMNUS', name: 'Verified Alumnus / Alumna', tier: 'CLIENT', permissionIds: [] }
  ]
};
