import { CanonicalProductHierarchy } from './types';

export const CHURCH_FAITH_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-church-faith',
    code: 'CHERP',
    name: 'Church & Diocesan Enterprise ERP',
    category: 'INSTITUTIONAL_ERP',
    description: 'Sovereign diocese, cathedral, parish, and faith ministry operating system: Canonical parishioner rolls, sacramental registers (Baptism, Confirmation, Holy Matrimony banns), home cell fellowships, dual-custody Sunday tithe & e-giving collection, cathedral capital building pledges, benevolence welfare fund, rural evangelism missions, Sunday RTMP livestream broadcasts, and sermon audio transcript vault.',
    version: '2026.4.0',
    iconName: 'Church',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Diocesan Bishop / Senior Pastor & Synod Executive',
    governingLegislation: 'Ecclesiastical Canon Law & Diocesan Synod Constitution 2026',
    directorateIds: [
      'CH-DIR-PASTORAL-SACRAMENTS',
      'CH-DIR-TREASURY-STEWARDSHIP',
      'CH-DIR-OUTREACH-BENEVOLENCE',
      'CH-DIR-MEDIA-LITURGY'
    ]
  },
  directorates: [
    {
      id: 'CH-DIR-PASTORAL-SACRAMENTS',
      productId: 'prod-church-faith',
      code: 'CH-DIR-PASTORAL',
      name: 'Directorate of Pastoral Care, Sacraments & Parishioner Registry',
      description: 'Parish family directory, holy sacramental registers (Baptism, Confirmation, Matrimony), home cell fellowships, discipleship foundation classes, and pastoral visitation.',
      leadRole: 'DEAN_OF_CATHEDRAL_VICAR',
      departmentIds: ['CH-DEPT-SACRAMENTAL-ROLL', 'CH-DEPT-CELL-FELLOWSHIPS', 'CH-DEPT-PASTORAL-COUNSELING']
    },
    {
      id: 'CH-DIR-TREASURY-STEWARDSHIP',
      productId: 'prod-church-faith',
      code: 'CH-DIR-TREASURY',
      name: 'Directorate of Diocesan Treasury, Tithes & Stewardship',
      description: 'Dual-custody Sunday offertory counting, Mobile Money tithes & e-giving via Digital Pay, capital building campaign pledges, and FAAP tithe ledger reconciliation.',
      leadRole: 'DIOCESAN_TREASURER',
      departmentIds: ['CH-DEPT-TITHE-OFFERTORY', 'CH-DEPT-BUILDING-PLEDGES']
    },
    {
      id: 'CH-DIR-OUTREACH-BENEVOLENCE',
      productId: 'prod-church-faith',
      code: 'CH-DIR-OUTREACH',
      name: 'Directorate of Community Outreach, Benevolence & Missions',
      description: 'Benevolence compassion fund for widows and orphans, emergency community relief, rural evangelism crusades, and church planting grants.',
      leadRole: 'DIRECTOR_MISSIONS_OUTREACH',
      departmentIds: ['CH-DEPT-BENEVOLENCE-WELFARE', 'CH-DEPT-RURAL-MISSIONS']
    },
    {
      id: 'CH-DIR-MEDIA-LITURGY',
      productId: 'prod-church-faith',
      code: 'CH-DIR-MEDIA',
      name: 'Directorate of Media Broadcasting, Liturgy & Sanctuary Logistics',
      description: 'Sunday RTMP multi-camera live streaming, sermon podcast audio mastering, theological transcript index, and sanctuary liturgical duty rosters.',
      leadRole: 'HEAD_MEDIA_LITURGY',
      departmentIds: ['CH-DEPT-LIVESTREAM-MEDIA', 'CH-DEPT-SANCTUARY-EVENTS']
    }
  ],
  departments: [
    {
      id: 'CH-DEPT-SACRAMENTAL-ROLL',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      code: 'CH-DEPT-SACRAMENTS',
      name: 'Department of Sacramental Registers & Parish Records',
      description: 'Family biographical cards, Holy Baptism certificates, Confirmation registries, Holy Matrimony banns of marriage, and memorial burial rolls.',
      headRole: 'CHANCELLOR_REGISTRAR',
      officeIds: ['CH-OFF-PARISH-SECRETARY']
    },
    {
      id: 'CH-DEPT-CELL-FELLOWSHIPS',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      code: 'CH-DEPT-CELLS',
      name: 'Department of Home Cell Fellowships & Discipleship Classes',
      description: 'Zonal cell groups, neighborhood fellowship hosts, weekly study outlines, and new convert discipleship foundation trackers.',
      headRole: 'CELL_PASTOR',
      officeIds: ['CH-OFF-CELL-COORDINATOR']
    },
    {
      id: 'CH-DEPT-PASTORAL-COUNSELING',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      code: 'CH-DEPT-COUNSELING',
      name: 'Department of Pastoral Counseling & Visitation Care',
      description: 'Hospital patient visits, pre-marital counseling logs, bereavement comfort ministry, and confidential clergy counseling sessions.',
      headRole: 'PASTORAL_CARE_MINISTER',
      officeIds: ['CH-OFF-PASTORAL-CARE']
    },
    {
      id: 'CH-DEPT-TITHE-OFFERTORY',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      code: 'CH-DEPT-TITHE',
      name: 'Department of Sunday Collections & Mobile Money Giving',
      description: 'Dual-custody offertory counting sheets, Mobile Money tithe collections via Digital Pay, member envelope reconciliation, and annual giving statements.',
      headRole: 'CHIEF_CHURCH_ACCOUNTANT',
      officeIds: ['CH-OFF-TREASURY-CASHIER']
    },
    {
      id: 'CH-DEPT-BUILDING-PLEDGES',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      code: 'CH-DEPT-PLEDGES',
      name: 'Department of Cathedral Development & Capital Pledges',
      description: 'Cathedral renovation pledges, donor commitment tracking, installment SMS payment reminders, and contractor milestone payouts.',
      headRole: 'PROJECTS_FINANCIAL_OFFICER',
      officeIds: ['CH-OFF-PLEDGES-DESK']
    },
    {
      id: 'CH-DEPT-BENEVOLENCE-WELFARE',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      code: 'CH-DEPT-BENEVOLENCE',
      name: 'Department of Benevolence & Compassion Fund',
      description: 'Hardship vetting committee, vulnerable family food distribution, medical emergency assistance, and orphan education bursaries.',
      headRole: 'WELFARE_COMMITTEE_CHAIR',
      officeIds: ['CH-OFF-BENEVOLENCE-DESK']
    },
    {
      id: 'CH-DEPT-RURAL-MISSIONS',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      code: 'CH-DEPT-MISSIONS',
      name: 'Department of Rural Evangelism, Crusades & Church Planting',
      description: 'Evangelistic mission budgets, village church plant seed funding, field missionary monthly stipends, and open-air gospel crusade logistics.',
      headRole: 'MISSIONS_DIRECTOR',
      officeIds: ['CH-OFF-MISSIONS-DESK']
    },
    {
      id: 'CH-DEPT-LIVESTREAM-MEDIA',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      code: 'CH-DEPT-MEDIA',
      name: 'Department of Digital Livestream & Sermon Archive',
      description: 'Multi-platform RTMP video broadcasting, sermon audio mastering for podcasting, and searchable theological sermon transcripts.',
      headRole: 'CHIEF_BROADCAST_ENGINEER',
      officeIds: ['CH-OFF-MEDIA-CONTROL']
    },
    {
      id: 'CH-DEPT-SANCTUARY-EVENTS',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      code: 'CH-DEPT-SANCTUARY',
      name: 'Department of Sanctuary Booking, Weddings & Liturgical Rosters',
      description: 'Sanctuary event reservations, wedding ceremony protocols, memorial services, and Sunday service liturgical volunteer rosters.',
      headRole: 'SANCTUARY_PROTOCOL_OFFICER',
      officeIds: ['CH-OFF-SANCTUARY-DESK']
    }
  ],
  offices: [
    {
      id: 'CH-OFF-PARISH-SECRETARY',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-SACRAMENTAL-ROLL',
      code: 'CH-OFF-SECRETARY',
      name: 'Parish Secretary & Sacraments Desk',
      description: 'Issuing baptism certificates, registering wedding banns, and maintaining family records.',
      officerRole: 'PARISH_SECRETARY',
      portalIds: ['CH-PORTAL-BISHOP', 'CH-PORTAL-VICAR-CLERGY'],
      moduleIds: ['CH-MOD-MEMBERSHIP-SACRAMENTS']
    },
    {
      id: 'CH-OFF-CELL-COORDINATOR',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-CELL-FELLOWSHIPS',
      code: 'CH-OFF-CELLS',
      name: 'Cell Fellowship & Discipleship Desk',
      description: 'Cell group leadership rosters, weekly discussion outlines, and attendance registers.',
      officerRole: 'CELL_COORDINATOR',
      portalIds: ['CH-PORTAL-VICAR-CLERGY'],
      moduleIds: ['CH-MOD-CELL-FELLOWSHIPS']
    },
    {
      id: 'CH-OFF-PASTORAL-CARE',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-PASTORAL-COUNSELING',
      code: 'CH-OFF-COUNSELING',
      name: 'Pastoral Counseling & Visitation Desk',
      description: 'Confidential pastoral counseling appointments, hospital visit logs, and bereavement support.',
      officerRole: 'PASTORAL_CARE_OFFICER',
      portalIds: ['CH-PORTAL-VICAR-CLERGY'],
      moduleIds: ['CH-MOD-PASTORAL-CARE']
    },
    {
      id: 'CH-OFF-TREASURY-CASHIER',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-TITHE-OFFERTORY',
      code: 'CH-OFF-TREASURY',
      name: 'Treasury Cashier & Counting Room Desk',
      description: 'Counting room dual-signoff sheets, mobile money tithe ingestion, and banking slips.',
      officerRole: 'TREASURY_CASHIER',
      portalIds: ['CH-PORTAL-BISHOP', 'CH-PORTAL-TREASURY'],
      moduleIds: ['CH-MOD-TITHE-OFFERTORY']
    },
    {
      id: 'CH-OFF-PLEDGES-DESK',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-BUILDING-PLEDGES',
      code: 'CH-OFF-PLEDGES',
      name: 'Capital Projects & Pledges Desk',
      description: 'Capital development pledge cards, installment reconciliation, and contractor vouchers.',
      officerRole: 'PROJECTS_FINANCIAL_OFFICER',
      portalIds: ['CH-PORTAL-BISHOP', 'CH-PORTAL-TREASURY'],
      moduleIds: ['CH-MOD-BUILDING-PLEDGES']
    },
    {
      id: 'CH-OFF-BENEVOLENCE-DESK',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-BENEVOLENCE-WELFARE',
      code: 'CH-OFF-BENEVOLENCE',
      name: 'Compassion & Welfare Desk',
      description: 'Vetting hardship cases, food relief parcels, and compassion cash grants.',
      officerRole: 'WELFARE_OFFICER',
      portalIds: ['CH-PORTAL-VICAR-CLERGY'],
      moduleIds: ['CH-MOD-BENEVOLENCE-WELFARE']
    },
    {
      id: 'CH-OFF-MISSIONS-DESK',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-RURAL-MISSIONS',
      code: 'CH-OFF-MISSIONS',
      name: 'Missions & Church Planting Desk',
      description: 'Field crusade logistics, church plant land acquisition, and missionary stipends.',
      officerRole: 'MISSIONS_COORDINATOR',
      portalIds: ['CH-PORTAL-VICAR-CLERGY'],
      moduleIds: ['CH-MOD-MISSIONS-CRUSADES']
    },
    {
      id: 'CH-OFF-MEDIA-CONTROL',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-LIVESTREAM-MEDIA',
      code: 'CH-OFF-MEDIA',
      name: 'Master Media Control Suite',
      description: 'Broadcasting Sunday video stream, sermon podcast uploads, and AV technician schedules.',
      officerRole: 'MEDIA_DIRECTOR',
      portalIds: ['CH-PORTAL-VICAR-CLERGY'],
      moduleIds: ['CH-MOD-LIVESTREAM-MEDIA']
    },
    {
      id: 'CH-OFF-SANCTUARY-DESK',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-SANCTUARY-EVENTS',
      code: 'CH-OFF-SANCTUARY',
      name: 'Sanctuary Protocol & Liturgy Desk',
      description: 'Sanctuary calendar, wedding rehearsals, usher rosters, and communion prep.',
      officerRole: 'SANCTUARY_WARDEN',
      portalIds: ['CH-PORTAL-VICAR-CLERGY', 'CH-PORTAL-CONGREGATION'],
      moduleIds: ['CH-MOD-SANCTUARY-EVENTS']
    }
  ],
  portals: [
    {
      id: 'CH-PORTAL-BISHOP',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-TITHE-OFFERTORY',
      officeId: 'CH-OFF-TREASURY-CASHIER',
      code: 'CH-PORTAL-BISHOP',
      name: 'Bishop, Synod & Board of Trustees Cockpit',
      description: 'Diocesan financial stewardship summaries, membership growth census, capital project milestones, and synod governance.',
      targetRole: 'BISHOP_SYNOD',
      authLevel: 'PKI_SOVEREIGN',
      route: '/church/bishop',
      moduleIds: ['CH-MOD-MEMBERSHIP-SACRAMENTS', 'CH-MOD-TITHE-OFFERTORY', 'CH-MOD-BUILDING-PLEDGES', 'CH-MOD-MISSIONS-CRUSADES']
    },
    {
      id: 'CH-PORTAL-VICAR-CLERGY',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-SACRAMENTAL-ROLL',
      officeId: 'CH-OFF-PARISH-SECRETARY',
      code: 'CH-PORTAL-CLERGY',
      name: 'Parish Clergy, Pastors & Ministry Leaders Workspace',
      description: 'Administer sacraments, review cell group attendance, conduct pre-marital counseling, approve benevolence relief, and curate sermons.',
      targetRole: 'PARISH_CLERGY',
      authLevel: 'STAFF',
      route: '/church/clergy',
      moduleIds: ['CH-MOD-MEMBERSHIP-SACRAMENTS', 'CH-MOD-CELL-FELLOWSHIPS', 'CH-MOD-PASTORAL-CARE', 'CH-MOD-BENEVOLENCE-WELFARE', 'CH-MOD-LIVESTREAM-MEDIA', 'CH-MOD-SANCTUARY-EVENTS']
    },
    {
      id: 'CH-PORTAL-TREASURY',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-TITHE-OFFERTORY',
      officeId: 'CH-OFF-TREASURY-CASHIER',
      code: 'CH-PORTAL-TREASURY',
      name: 'Diocesan Treasury & Stewardship Terminal',
      description: 'Sunday collection dual-custody verification, Mobile Money tithe reconciliation, building pledge receipts, and FAAP ledger posting.',
      targetRole: 'CHURCH_TREASURER',
      authLevel: 'STAFF',
      route: '/church/treasury',
      moduleIds: ['CH-MOD-TITHE-OFFERTORY', 'CH-MOD-BUILDING-PLEDGES']
    },
    {
      id: 'CH-PORTAL-CONGREGATION',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-SANCTUARY-EVENTS',
      officeId: 'CH-OFF-SANCTUARY-DESK',
      code: 'CH-PORTAL-MEMBER',
      name: 'Parishioner Mobile App & E-Giving Portal',
      description: 'Give tithes via Mobile Money, watch Sunday live stream, download sermon study notes, and submit prayer requests.',
      targetRole: 'PARISHIONER',
      authLevel: 'PUBLIC',
      route: '/church/app',
      moduleIds: ['CH-MOD-TITHE-OFFERTORY', 'CH-MOD-LIVESTREAM-MEDIA', 'CH-MOD-SANCTUARY-EVENTS', 'CH-MOD-PASTORAL-CARE']
    }
  ],
  modules: [
    {
      id: 'CH-MOD-MEMBERSHIP-SACRAMENTS',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-SACRAMENTAL-ROLL',
      officeId: 'CH-OFF-PARISH-SECRETARY',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-MEMBERSHIP-SACRAMENTS',
      name: 'Canonical Parishioner Rolls & Sacramental Register',
      description: 'Family records, Holy Baptism registry, Confirmation records, Holy Matrimony banns, and clergy sacramental signatures.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-SAC-001', 'CH-CAP-SAC-002'],
      screenIds: ['CH-SCR-SACRAMENTS'],
      formIds: ['CH-FORM-BAPTISM-REG'],
      dashboardIds: ['CH-DASH-MINISTRY'],
      reportIds: ['CH-REP-SACRAMENTS'],
      workflowIds: ['CH-WF-SACRAMENTS'],
      databaseEntityIds: ['CH-DB-SACRAMENTS'],
      apiIds: ['CH-API-SACRAMENTS'],
      runtimeComponentId: 'CH-RTC-SACRAMENTS',
      permissionIds: ['CH-PERM-CLERGY']
    },
    {
      id: 'CH-MOD-CELL-FELLOWSHIPS',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-CELL-FELLOWSHIPS',
      officeId: 'CH-OFF-CELL-COORDINATOR',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-CELL-FELLOWSHIPS',
      name: 'Home Cell Groups & Discipleship Foundation Tracker',
      description: 'Zonal cell directories, weekly attendance registers, host homes, discipleship course milestone completion.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-CELL-001', 'CH-CAP-CELL-002'],
      screenIds: ['CH-SCR-CELLS'],
      formIds: ['CH-FORM-CELL-LOG'],
      dashboardIds: ['CH-DASH-MINISTRY'],
      reportIds: ['CH-REP-CELLS'],
      workflowIds: ['CH-WF-CELLS'],
      databaseEntityIds: ['CH-DB-CELLS'],
      apiIds: ['CH-API-CELLS'],
      runtimeComponentId: 'CH-RTC-CELLS',
      permissionIds: ['CH-PERM-CLERGY']
    },
    {
      id: 'CH-MOD-PASTORAL-CARE',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-PASTORAL-COUNSELING',
      officeId: 'CH-OFF-PASTORAL-CARE',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-PASTORAL-CARE',
      name: 'Pastoral Counseling, Visitation & Bereavement Care',
      description: 'Hospital patient visits, confidential marriage counseling notes, prayer requests, and bereavement ministry support.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-CARE-001', 'CH-CAP-CARE-002'],
      screenIds: ['CH-SCR-CARE'],
      formIds: ['CH-FORM-COUNSELING-SESSION'],
      dashboardIds: ['CH-DASH-MINISTRY'],
      reportIds: ['CH-REP-CARE'],
      workflowIds: ['CH-WF-CARE'],
      databaseEntityIds: ['CH-DB-COUNSELING'],
      apiIds: ['CH-API-CARE'],
      runtimeComponentId: 'CH-RTC-CARE',
      permissionIds: ['CH-PERM-CLERGY']
    },
    {
      id: 'CH-MOD-TITHE-OFFERTORY',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-TITHE-OFFERTORY',
      officeId: 'CH-OFF-TREASURY-CASHIER',
      portalId: 'CH-PORTAL-TREASURY',
      code: 'CH-MOD-TITHE-OFFERTORY',
      name: 'Sunday Collections, E-Giving & Confidential Statements',
      description: 'Dual-custody count sheets, mobile money tithes via JUMO DIGITAL PAY, envelope tithe ledger, and tax-exempt giving statements.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-TITHE-001', 'CH-CAP-TITHE-002'],
      screenIds: ['CH-SCR-TITHE'],
      formIds: ['CH-FORM-OFFERTORY-COUNT'],
      dashboardIds: ['CH-DASH-TREASURY'],
      reportIds: ['CH-REP-TITHE'],
      workflowIds: ['CH-WF-TITHE'],
      databaseEntityIds: ['CH-DB-TITHE-LEDGER'],
      apiIds: ['CH-API-TITHE'],
      runtimeComponentId: 'CH-RTC-TITHE',
      permissionIds: ['CH-PERM-TREASURY']
    },
    {
      id: 'CH-MOD-BUILDING-PLEDGES',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-BUILDING-PLEDGES',
      officeId: 'CH-OFF-PLEDGES-DESK',
      portalId: 'CH-PORTAL-TREASURY',
      code: 'CH-MOD-BUILDING-PLEDGES',
      name: 'Cathedral Building Fund & Capital Pledges Ledger',
      description: 'Capital development pledges, installment tracking, donor recognition tiers, and contractor progress payouts.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-PLEDGE-001', 'CH-CAP-PLEDGE-002'],
      screenIds: ['CH-SCR-PLEDGES'],
      formIds: ['CH-FORM-PLEDGE-ENTRY'],
      dashboardIds: ['CH-DASH-TREASURY'],
      reportIds: ['CH-REP-PLEDGES'],
      workflowIds: ['CH-WF-PLEDGES'],
      databaseEntityIds: ['CH-DB-PLEDGES'],
      apiIds: ['CH-API-PLEDGES'],
      runtimeComponentId: 'CH-RTC-PLEDGES',
      permissionIds: ['CH-PERM-TREASURY']
    },
    {
      id: 'CH-MOD-BENEVOLENCE-WELFARE',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-BENEVOLENCE-WELFARE',
      officeId: 'CH-OFF-BENEVOLENCE-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-BENEVOLENCE-WELFARE',
      name: 'Benevolence Fund, Widows & Orphans Compassion Relief',
      description: 'Hardship relief vetting, food relief packages, emergency medical vouchers, and compassion grants.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-WEL-001', 'CH-CAP-WEL-002'],
      screenIds: ['CH-SCR-BENEVOLENCE'],
      formIds: ['CH-FORM-BENEVOLENCE-GRANT'],
      dashboardIds: ['CH-DASH-OUTREACH'],
      reportIds: ['CH-REP-BENEVOLENCE'],
      workflowIds: ['CH-WF-BENEVOLENCE'],
      databaseEntityIds: ['CH-DB-BENEVOLENCE'],
      apiIds: ['CH-API-BENEVOLENCE'],
      runtimeComponentId: 'CH-RTC-BENEVOLENCE',
      permissionIds: ['CH-PERM-CLERGY']
    },
    {
      id: 'CH-MOD-MISSIONS-CRUSADES',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-RURAL-MISSIONS',
      officeId: 'CH-OFF-MISSIONS-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-MISSIONS-CRUSADES',
      name: 'Rural Evangelism Crusades & Church Planting Engine',
      description: 'Outreach mission logistics, village church plant seed grants, field missionary allowances, and convert tracking.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-MISS-001', 'CH-CAP-MISS-002'],
      screenIds: ['CH-SCR-MISSIONS'],
      formIds: ['CH-FORM-MISSION-BUDGET'],
      dashboardIds: ['CH-DASH-OUTREACH'],
      reportIds: ['CH-REP-MISSIONS'],
      workflowIds: ['CH-WF-MISSIONS'],
      databaseEntityIds: ['CH-DB-MISSIONS'],
      apiIds: ['CH-API-MISSIONS'],
      runtimeComponentId: 'CH-RTC-MISSIONS',
      permissionIds: ['CH-PERM-CLERGY']
    },
    {
      id: 'CH-MOD-LIVESTREAM-MEDIA',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-LIVESTREAM-MEDIA',
      officeId: 'CH-OFF-MEDIA-CONTROL',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-LIVESTREAM-MEDIA',
      name: 'Sunday RTMP Livestream Broadcast & Sermon Audio Vault',
      description: 'RTMP live video feeds, sermon audio podcast publishing, and AI-indexed doctrinal transcript archive.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-MEDIA-001', 'CH-CAP-MEDIA-002'],
      screenIds: ['CH-SCR-MEDIA'],
      formIds: ['CH-FORM-SERMON-UPLOAD'],
      dashboardIds: ['CH-DASH-MINISTRY'],
      reportIds: ['CH-REP-MEDIA'],
      workflowIds: ['CH-WF-MEDIA'],
      databaseEntityIds: ['CH-DB-SERMONS'],
      apiIds: ['CH-API-MEDIA'],
      runtimeComponentId: 'CH-RTC-MEDIA',
      permissionIds: ['CH-PERM-CLERGY']
    },
    {
      id: 'CH-MOD-SANCTUARY-EVENTS',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-SANCTUARY-EVENTS',
      officeId: 'CH-OFF-SANCTUARY-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      code: 'CH-MOD-SANCTUARY-EVENTS',
      name: 'Sanctuary Calendar, Holy Matrimony & Liturgical Rosters',
      description: 'Sanctuary reservations, wedding date bookings, Sunday reading/usher rosters, and communion steward duty schedules.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['CH-CAP-SANC-001', 'CH-CAP-SANC-002'],
      screenIds: ['CH-SCR-SANCTUARY'],
      formIds: ['CH-FORM-WEDDING-BOOKING'],
      dashboardIds: ['CH-DASH-MINISTRY'],
      reportIds: ['CH-REP-SANCTUARY'],
      workflowIds: ['CH-WF-SANCTUARY'],
      databaseEntityIds: ['CH-DB-SANCTUARY-EVENTS'],
      apiIds: ['CH-API-SANCTUARY'],
      runtimeComponentId: 'CH-RTC-SANCTUARY',
      permissionIds: ['CH-PERM-CLERGY']
    }
  ],
  capabilities: [
    {
      id: 'CH-CAP-SAC-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-SACRAMENTAL-ROLL',
      officeId: 'CH-OFF-PARISH-SECRETARY',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS',
      code: 'CH_CAP_SAC_REGISTER_BAPTISM',
      name: 'Register Holy Baptism & Issue Official Certificate',
      description: 'Records candidate baptism details, godparents, officiating clergy, and generates official ecclesiastical certificate.',
      serviceAction: 'church.sacraments.registerBaptism',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-SACRAMENTS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-SAC-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-SACRAMENTAL-ROLL',
      officeId: 'CH-OFF-PARISH-SECRETARY',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS',
      code: 'CH_CAP_SAC_PUBLISH_MARRIAGE_BANNS',
      name: 'Publish Holy Matrimony Banns of Marriage',
      description: 'Validates canonical matrimonial requirements, single status affidavits, and schedules 3-Sunday congregational banns.',
      serviceAction: 'church.sacraments.publishBanns',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-SACRAMENTS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-CELL-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-CELL-FELLOWSHIPS',
      officeId: 'CH-OFF-CELL-COORDINATOR',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-CELL-FELLOWSHIPS',
      code: 'CH_CAP_CELL_SUBMIT_MEETING_ROLL',
      name: 'Submit Weekly Cell Fellowship Attendance Roll',
      description: 'Records midweek prayer attendance, visitor headcount, and cell offering collections.',
      serviceAction: 'church.cells.submitMeetingRoll',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-CELLS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-CELL-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-CELL-FELLOWSHIPS',
      officeId: 'CH-OFF-CELL-COORDINATOR',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-CELL-FELLOWSHIPS',
      code: 'CH_CAP_CELL_GRADUATE_DISCIPLESHIP',
      name: 'Graduate Believer from Foundation Discipleship Class',
      description: 'Certifies completion of 12-week biblical foundation lessons and authorizes ministry service placement.',
      serviceAction: 'church.cells.graduateDiscipleship',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-CELLS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-CARE-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-PASTORAL-COUNSELING',
      officeId: 'CH-OFF-PASTORAL-CARE',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-PASTORAL-CARE',
      code: 'CH_CAP_CARE_LOG_HOSPITAL_VISIT',
      name: 'Log Hospital Pastoral Visitation & Anointing',
      description: 'Records clinical hospital ward visits, pastoral prayers of healing, and communion for homebound parishioners.',
      serviceAction: 'church.care.logHospitalVisit',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-CARE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-CARE-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-PASTORAL-SACRAMENTS',
      departmentId: 'CH-DEPT-PASTORAL-COUNSELING',
      officeId: 'CH-OFF-PASTORAL-CARE',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-PASTORAL-CARE',
      code: 'CH_CAP_CARE_SCHEDULE_PREMARITAL',
      name: 'Schedule Pre-Marital Pastoral Counseling Course',
      description: 'Books 6-session structured marriage preparation course for engaged couples with pastoral signoff.',
      serviceAction: 'church.care.schedulePreMarital',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-CARE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-TITHE-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-TITHE-OFFERTORY',
      officeId: 'CH-OFF-TREASURY-CASHIER',
      portalId: 'CH-PORTAL-TREASURY',
      moduleId: 'CH-MOD-TITHE-OFFERTORY',
      code: 'CH_CAP_TITHE_SUBMIT_OFFERTORY_COUNT',
      name: 'Submit Dual-Custody Sunday Offertory Count',
      description: 'Enters Sunday collection denominations with simultaneous verification by two authorized counting wardens.',
      serviceAction: 'church.treasury.submitCountSheet',
      requiredPermission: 'CH-PERM-TREASURY',
      runtimeComponentId: 'CH-RTC-TITHE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-TITHE-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-TITHE-OFFERTORY',
      officeId: 'CH-OFF-TREASURY-CASHIER',
      portalId: 'CH-PORTAL-TREASURY',
      moduleId: 'CH-MOD-TITHE-OFFERTORY',
      code: 'CH_CAP_TITHE_POST_MOMO_GIVING',
      name: 'Reconcile Mobile Money E-Giving via Digital Pay',
      description: 'Matches Mobile Money donation references to parishioner envelope records and issues instant receipt.',
      serviceAction: 'church.treasury.reconcileMoMo',
      requiredPermission: 'CH-PERM-TREASURY',
      runtimeComponentId: 'CH-RTC-TITHE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-PLEDGE-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-BUILDING-PLEDGES',
      officeId: 'CH-OFF-PLEDGES-DESK',
      portalId: 'CH-PORTAL-TREASURY',
      moduleId: 'CH-MOD-BUILDING-PLEDGES',
      code: 'CH_CAP_PLEDGE_RECORD_COMMITMENT',
      name: 'Record Cathedral Capital Building Pledge',
      description: 'Logs member pledge amount, fulfillment target date, and preferred installment schedule.',
      serviceAction: 'church.pledges.recordCommitment',
      requiredPermission: 'CH-PERM-TREASURY',
      runtimeComponentId: 'CH-RTC-PLEDGES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-PLEDGE-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-TREASURY-STEWARDSHIP',
      departmentId: 'CH-DEPT-BUILDING-PLEDGES',
      officeId: 'CH-OFF-PLEDGES-DESK',
      portalId: 'CH-PORTAL-TREASURY',
      moduleId: 'CH-MOD-BUILDING-PLEDGES',
      code: 'CH_CAP_PLEDGE_DISBURSE_CONTRACTOR',
      name: 'Disburse Capital Project Contractor Milestone',
      description: 'Verifies engineer building certificate and disburses milestone payment via FAAP vote book.',
      serviceAction: 'church.pledges.disburseContractor',
      requiredPermission: 'CH-PERM-TREASURY',
      runtimeComponentId: 'CH-RTC-PLEDGES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-WEL-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-BENEVOLENCE-WELFARE',
      officeId: 'CH-OFF-BENEVOLENCE-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-BENEVOLENCE-WELFARE',
      code: 'CH_CAP_WEL_APPROVE_EMERGENCY_RELIEF',
      name: 'Approve Emergency Hardship Compassion Grant',
      description: 'Authorizes urgent benevolent grant for destitute family, medical prescription, or funeral assistance.',
      serviceAction: 'church.welfare.approveEmergencyRelief',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-BENEVOLENCE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-WEL-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-BENEVOLENCE-WELFARE',
      officeId: 'CH-OFF-BENEVOLENCE-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-BENEVOLENCE-WELFARE',
      code: 'CH_CAP_WEL_DISTRIBUTE_FOOD_PARCELS',
      name: 'Dispatch Food Basket Parcels to Vulnerable Homes',
      description: 'Tracks monthly distribution of maize meal, rice, and soap hampers to elderly and vulnerable parishioners.',
      serviceAction: 'church.welfare.distributeFoodParcels',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-BENEVOLENCE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-MISS-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-RURAL-MISSIONS',
      officeId: 'CH-OFF-MISSIONS-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-MISSIONS-CRUSADES',
      code: 'CH_CAP_MISS_COMMISSION_CHURCH_PLANT',
      name: 'Commission Rural Church Plant & Seed Funding',
      description: 'Allocates launch budget, pastoral tent/building materials, and sound gear for new mission plant.',
      serviceAction: 'church.missions.commissionPlant',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-MISSIONS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-MISS-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-OUTREACH-BENEVOLENCE',
      departmentId: 'CH-DEPT-RURAL-MISSIONS',
      officeId: 'CH-OFF-MISSIONS-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-MISSIONS-CRUSADES',
      code: 'CH_CAP_MISS_DISBURSE_MISSIONARY_STIPEND',
      name: 'Disburse Rural Field Missionary Monthly Stipend',
      description: 'Transfers monthly pastoral living allowance to remote frontline evangelists via Mobile Money.',
      serviceAction: 'church.missions.disburseStipend',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-MISSIONS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-MEDIA-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-LIVESTREAM-MEDIA',
      officeId: 'CH-OFF-MEDIA-CONTROL',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-LIVESTREAM-MEDIA',
      code: 'CH_CAP_MEDIA_START_SUNDAY_LIVESTREAM',
      name: 'Initiate Sunday Multi-Platform RTMP Livestream',
      description: 'Controls YouTube, Facebook, and Web live video stream broadcast and monitors audio levels.',
      serviceAction: 'church.media.startLivestream',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-MEDIA',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-MEDIA-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-LIVESTREAM-MEDIA',
      officeId: 'CH-OFF-MEDIA-CONTROL',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-LIVESTREAM-MEDIA',
      code: 'CH_CAP_MEDIA_INDEX_SERMON_TRANSCRIPT',
      name: 'Index Sermon Podcast Audio & Doctrinal Transcript',
      description: 'Uploads mastered sermon MP3 and generates searchable semantic sermon study notes for congregation app.',
      serviceAction: 'church.media.indexSermonTranscript',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-MEDIA',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-SANC-001',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-SANCTUARY-EVENTS',
      officeId: 'CH-OFF-SANCTUARY-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-SANCTUARY-EVENTS',
      code: 'CH_CAP_SANC_BOOK_WEDDING_SANCTUARY',
      name: 'Book Sanctuary for Holy Matrimony Ceremony',
      description: 'Confirms sanctuary availability, sound technician roster, and floral protocol reservation.',
      serviceAction: 'church.sanctuary.bookWedding',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-SANCTUARY',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'CH-CAP-SANC-002',
      productId: 'prod-church-faith',
      directorateId: 'CH-DIR-MEDIA-LITURGY',
      departmentId: 'CH-DEPT-SANCTUARY-EVENTS',
      officeId: 'CH-OFF-SANCTUARY-DESK',
      portalId: 'CH-PORTAL-VICAR-CLERGY',
      moduleId: 'CH-MOD-SANCTUARY-EVENTS',
      code: 'CH_CAP_SANC_PUBLISH_DUTY_ROSTER',
      name: 'Publish Sunday Liturgical Duty Roster',
      description: 'Assigns lay readers, intercessory leaders, ushers, and communion stewards with automated SMS reminders.',
      serviceAction: 'church.sanctuary.publishDutyRoster',
      requiredPermission: 'CH-PERM-CLERGY',
      runtimeComponentId: 'CH-RTC-SANCTUARY',
      status: 'ACTIVE_CORE'
    }
  ],
  screens: [
    { id: 'CH-SCR-SACRAMENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS', code: 'CH-SCR-SACRAMENTS', title: 'Canonical Sacramental Registers & Parish Roll', description: 'Baptism, Confirmation, Matrimony registers, and family cards.', viewType: 'TABLE', route: '/church/sacraments' },
    { id: 'CH-SCR-CELLS', productId: 'prod-church-faith', moduleId: 'CH-MOD-CELL-FELLOWSHIPS', code: 'CH-SCR-CELLS', title: 'Home Cell Groups & Discipleship Classes', description: 'Weekly cell attendance, zonal maps, and foundation class completion.', viewType: 'TABLE', route: '/church/cells' },
    { id: 'CH-SCR-CARE', productId: 'prod-church-faith', moduleId: 'CH-MOD-PASTORAL-CARE', code: 'CH-SCR-CARE', title: 'Pastoral Counseling, Visitation & Hospital Care', description: 'Confidential care encounters, hospital logs, and prayer requests.', viewType: 'TABLE', route: '/church/care' },
    { id: 'CH-SCR-TITHE', productId: 'prod-church-faith', moduleId: 'CH-MOD-TITHE-OFFERTORY', code: 'CH-SCR-TITHE', title: 'Sunday Offertory & Mobile Money Tithe Ledger', description: 'Dual-custody count sheets, e-giving records, and statements.', viewType: 'TABLE', route: '/church/tithe' },
    { id: 'CH-SCR-PLEDGES', productId: 'prod-church-faith', moduleId: 'CH-MOD-BUILDING-PLEDGES', code: 'CH-SCR-PLEDGES', title: 'Cathedral Capital Building Pledges & Projects', description: 'Donor pledge installments, building progress, and contractor vouchers.', viewType: 'TABLE', route: '/church/pledges' },
    { id: 'CH-SCR-BENEVOLENCE', productId: 'prod-church-faith', moduleId: 'CH-MOD-BENEVOLENCE-WELFARE', code: 'CH-SCR-BENEVOLENCE', title: 'Benevolence Compassion Fund & Relief Distribution', description: 'Hardship grant approvals, food hamper logs, and bursaries.', viewType: 'TABLE', route: '/church/benevolence' },
    { id: 'CH-SCR-MISSIONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MISSIONS-CRUSADES', code: 'CH-SCR-MISSIONS', title: 'Rural Missions, Crusades & Church Plants', description: 'Mission station budgets, missionary stipends, and crusade logs.', viewType: 'TABLE', route: '/church/missions' },
    { id: 'CH-SCR-MEDIA', productId: 'prod-church-faith', moduleId: 'CH-MOD-LIVESTREAM-MEDIA', code: 'CH-SCR-MEDIA', title: 'Sunday RTMP Livestream & Sermon Audio Archive', description: 'Live broadcast status, sermon podcast library, and transcripts.', viewType: 'TABLE', route: '/church/media' },
    { id: 'CH-SCR-SANCTUARY', productId: 'prod-church-faith', moduleId: 'CH-MOD-SANCTUARY-EVENTS', code: 'CH-SCR-SANCTUARY', title: 'Sanctuary Bookings, Matrimony & Liturgy Rosters', description: 'Sanctuary reservations, wedding dates, and Sunday rosters.', viewType: 'TABLE', route: '/church/sanctuary' }
  ],
  forms: [
    {
      id: 'CH-FORM-BAPTISM-REG',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS',
      code: 'CH-FORM-BAPTISM-REG',
      title: 'Canonical Holy Baptism Entry Form',
      submitAction: 'church.sacraments.registerBaptism',
      fieldCount: 5,
      fields: [
        { name: 'candidateFullName', label: 'Candidate Full Name', type: 'text', required: true },
        { name: 'dateOfBirth', label: 'Date of Birth', type: 'date', required: true },
        { name: 'parentsNames', label: 'Parents Full Legal Names', type: 'text', required: true },
        { name: 'godparentsNames', label: 'Godparents Names', type: 'text', required: true },
        { name: 'officiatingClergy', label: 'Officiating Priest / Pastor', type: 'text', required: true }
      ],
      validationRules: ['NAMES_VALID']
    },
    {
      id: 'CH-FORM-CELL-LOG',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-CELL-FELLOWSHIPS',
      code: 'CH-FORM-CELL-LOG',
      title: 'Weekly Cell Fellowship Meeting Report',
      submitAction: 'church.cells.submitMeetingRoll',
      fieldCount: 5,
      fields: [
        { name: 'cellGroupName', label: 'Cell Group / Zone Name', type: 'select', required: true },
        { name: 'meetingDate', label: 'Meeting Date', type: 'date', required: true },
        { name: 'memberAttendanceCount', label: 'Attending Members Headcount', type: 'number', required: true },
        { name: 'newVisitorsCount', label: 'First-Time Visitors Count', type: 'number', required: true },
        { name: 'offeringCollectedUgx', label: 'Cell Offering Collected (UGX)', type: 'number', required: true }
      ],
      validationRules: ['HEADCOUNT_POSITIVE']
    },
    {
      id: 'CH-FORM-COUNSELING-SESSION',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-PASTORAL-CARE',
      code: 'CH-FORM-COUNSELING-SESSION',
      title: 'Confidential Pastoral Counseling Encounter Log',
      submitAction: 'church.care.schedulePreMarital',
      fieldCount: 4,
      fields: [
        { name: 'parishionerMemberNo', label: 'Parishioner Membership Card ID', type: 'text', required: true },
        { name: 'counselingCategory', label: 'Category (Pre-Marital / Bereavement / Spiritual)', type: 'select', required: true },
        { name: 'sessionDate', label: 'Encounter Date', type: 'date', required: true },
        { name: 'pastoralActionPlan', label: 'Pastoral Follow-Up Action Plan', type: 'textarea', required: true }
      ],
      validationRules: ['CARE_VALID']
    },
    {
      id: 'CH-FORM-OFFERTORY-COUNT',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-TITHE-OFFERTORY',
      code: 'CH-FORM-OFFERTORY-COUNT',
      title: 'Sunday Offertory Dual-Custody Count Sheet',
      submitAction: 'church.treasury.submitCountSheet',
      fieldCount: 5,
      fields: [
        { name: 'serviceSession', label: 'Service (1st English / 2nd Luganda / Youth)', type: 'select', required: true },
        { name: 'cashTotalUgx', label: 'Physical Cash Count Total (UGX)', type: 'number', required: true },
        { name: 'envelopesCount', label: 'Enclosed Tithe Envelopes Count', type: 'number', required: true },
        { name: 'counterWarden1', label: '1st Verifying Church Warden Staff ID', type: 'text', required: true },
        { name: 'counterWarden2', label: '2nd Verifying Church Warden Staff ID', type: 'text', required: true }
      ],
      validationRules: ['DUAL_SIGNATURE_REQUIRED']
    },
    {
      id: 'CH-FORM-PLEDGE-ENTRY',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-BUILDING-PLEDGES',
      code: 'CH-FORM-PLEDGE-ENTRY',
      title: 'Cathedral Capital Building Fund Pledge Card',
      submitAction: 'church.pledges.recordCommitment',
      fieldCount: 4,
      fields: [
        { name: 'donorFullName', label: 'Donor / Member Name', type: 'text', required: true },
        { name: 'pledgedAmountUgx', label: 'Total Pledged Amount (UGX)', type: 'number', required: true },
        { name: 'installmentsPlan', label: 'Plan (One-Off / Monthly / Quarterly)', type: 'select', required: true },
        { name: 'mobilePhoneForSms', label: 'Mobile Phone for Payment Reminders', type: 'text', required: true }
      ],
      validationRules: ['PLEDGE_POSITIVE']
    },
    {
      id: 'CH-FORM-BENEVOLENCE-GRANT',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-BENEVOLENCE-WELFARE',
      code: 'CH-FORM-BENEVOLENCE-GRANT',
      title: 'Benevolence Compassion Hardship Grant Request',
      submitAction: 'church.welfare.approveEmergencyRelief',
      fieldCount: 4,
      fields: [
        { name: 'beneficiaryName', label: 'Beneficiary / Family Name', type: 'text', required: true },
        { name: 'hardshipReason', label: 'Hardship Reason (Medical / Bereavement / Destitution)', type: 'select', required: true },
        { name: 'recommendedAmountUgx', label: 'Approved Grant Amount (UGX)', type: 'number', required: true },
        { name: 'committeeChairApproval', label: 'Vetting Committee Chair PIN', type: 'password', required: true }
      ],
      validationRules: ['AMOUNT_VALID']
    },
    {
      id: 'CH-FORM-MISSION-BUDGET',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-MISSIONS-CRUSADES',
      code: 'CH-FORM-MISSION-BUDGET',
      title: 'Rural Evangelism Crusade & Plant Budget Requisition',
      submitAction: 'church.missions.commissionPlant',
      fieldCount: 4,
      fields: [
        { name: 'missionLocation', label: 'Target Village / Mission Station', type: 'text', required: true },
        { name: 'crusadeDates', label: 'Outreach Duration (Start to End Date)', type: 'text', required: true },
        { name: 'estimatedBudgetUgx', label: 'Total Mission Budget (UGX)', type: 'number', required: true },
        { name: 'teamLeaderClergy', label: 'Mission Team Leader Clergy ID', type: 'text', required: true }
      ],
      validationRules: ['BUDGET_VALID']
    },
    {
      id: 'CH-FORM-SERMON-UPLOAD',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-LIVESTREAM-MEDIA',
      code: 'CH-FORM-SERMON-UPLOAD',
      title: 'Sunday Sermon Audio & Study Transcript Upload',
      submitAction: 'church.media.indexSermonTranscript',
      fieldCount: 4,
      fields: [
        { name: 'sermonTitle', label: 'Sermon Message Title', type: 'text', required: true },
        { name: 'preacherName', label: 'Preacher / Guest Speaker Name', type: 'text', required: true },
        { name: 'biblePassage', label: 'Scripture Reference (e.g. Romans 8:28-39)', type: 'text', required: true },
        { name: 'sermonSeriesName', label: 'Sermon Series Category', type: 'text', required: true }
      ],
      validationRules: ['TITLE_REQUIRED']
    },
    {
      id: 'CH-FORM-WEDDING-BOOKING',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-SANCTUARY-EVENTS',
      code: 'CH-FORM-WEDDING-BOOKING',
      title: 'Holy Matrimony Sanctuary Date Booking',
      submitAction: 'church.sanctuary.bookWedding',
      fieldCount: 4,
      fields: [
        { name: 'groomFullName', label: 'Groom Full Name', type: 'text', required: true },
        { name: 'brideFullName', label: 'Bride Full Name', type: 'text', required: true },
        { name: 'weddingDate', label: 'Desired Wedding Date', type: 'date', required: true },
        { name: 'receptionSanctuaryUse', label: 'Grounds / Hall Required for Reception?', type: 'checkbox', required: false }
      ],
      validationRules: ['DATE_FUTURE']
    }
  ],
  dashboards: [
    {
      id: 'CH-DASH-MINISTRY',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS',
      code: 'CH-DASH-MINISTRY',
      title: 'Diocesan Parish Rolls & Sacramental Growth',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Registered Parish Families', value: '4,280 Families', trend: 'up', change: '14,500 Souls' },
        { label: 'Annual Baptisms & Confirmations', value: '340 Candidates', trend: 'up', change: 'Canonical Rolls' },
        { label: 'Active Home Cell Fellowships', value: '112 Groups', trend: 'up', change: 'Weekly Discipleship' },
        { label: 'Livestream Viewers', value: '8,450 Online', trend: 'up', change: 'Sunday Live RTMP' }
      ]
    },
    {
      id: 'CH-DASH-TREASURY',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-TITHE-OFFERTORY',
      code: 'CH-DASH-TREASURY',
      title: 'Tithe Stewardship, E-Giving & Building Pledges',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Monthly Tithes & Offerings', value: 'UGX 380 Million', trend: 'up', change: 'Dual Custody Count' },
        { label: 'Mobile Money E-Giving Share', value: '64.2%', trend: 'up', change: 'Via JUMO DIGITAL PAY' },
        { label: 'Cathedral Building Pledges', value: 'UGX 1.25 Billion', trend: 'up', change: '84% Fulfilled' },
        { label: 'Diocesan Remittances', value: '100% On-Schedule', trend: 'up', change: 'FAAP Synced' }
      ]
    },
    {
      id: 'CH-DASH-OUTREACH',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-BENEVOLENCE-WELFARE',
      code: 'CH-DASH-OUTREACH',
      title: 'Benevolence Relief & Mission Church Plants',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Benevolence Hardship Grants', value: 'UGX 42M / Qtr', trend: 'up', change: '185 Families Aided' },
        { label: 'Food Basket Hampers', value: '350 Hampers', trend: 'up', change: 'Widows & Orphans' },
        { label: 'Active Rural Church Plants', value: '18 Mission Plants', trend: 'up', change: 'Seed Funded' },
        { label: 'Field Missionaries Supported', value: '24 Evangelists', trend: 'neutral', change: 'Monthly Stipends' }
      ]
    },
    {
      id: 'CH-DASH-SANCTUARY',
      productId: 'prod-church-faith',
      moduleId: 'CH-MOD-SANCTUARY-EVENTS',
      code: 'CH-DASH-SANCTUARY',
      title: 'Sanctuary Calendar, Weddings & Volunteers',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Upcoming Holy Matrimonies', value: '14 Weddings Booked', trend: 'up', change: 'Banns Published' },
        { label: 'Active Liturgical Volunteers', value: '160 Ushers/Stewards', trend: 'up', change: 'Rostered on SMS' },
        { label: 'Sermon Audio Downloads', value: '28,400 Streams', trend: 'up', change: 'Podcast Archive' },
        { label: 'Pre-Marital Course Couples', value: '18 Couples', trend: 'up', change: 'In Pastoral Care' }
      ]
    }
  ],
  reports: [
    { id: 'CH-REP-SACRAMENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS', code: 'CH-REP-SACRAMENTS', title: 'Official Diocesan Sacramental Register Ledger', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'CSV'] },
    { id: 'CH-REP-CELLS', productId: 'prod-church-faith', moduleId: 'CH-MOD-CELL-FELLOWSHIPS', code: 'CH-REP-CELLS', title: 'Midweek Home Cell Fellowship Attendance & Offerings', format: 'TABULAR', exportTypes: ['PDF', 'XLSX'] },
    { id: 'CH-REP-CARE', productId: 'prod-church-faith', moduleId: 'CH-MOD-PASTORAL-CARE', code: 'CH-REP-CARE', title: 'Pastoral Care Encounters, Hospital Visits & Bereavement', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'CH-REP-TITHE', productId: 'prod-church-faith', moduleId: 'CH-MOD-TITHE-OFFERTORY', code: 'CH-REP-TITHE', title: 'Sunday Offertory Cashbook & Mobile Money Tithe Reconciliation', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX', 'CSV'] },
    { id: 'CH-REP-PLEDGES', productId: 'prod-church-faith', moduleId: 'CH-MOD-BUILDING-PLEDGES', code: 'CH-REP-PLEDGES', title: 'Cathedral Development Capital Pledges & Contractor Ledger', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'CH-REP-BENEVOLENCE', productId: 'prod-church-faith', moduleId: 'CH-MOD-BENEVOLENCE-WELFARE', code: 'CH-REP-BENEVOLENCE', title: 'Compassion & Benevolence Fund Disbursement Audit', format: 'FORENSIC_TRAIL', exportTypes: ['PDF', 'CSV'] },
    { id: 'CH-REP-MISSIONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MISSIONS-CRUSADES', code: 'CH-REP-MISSIONS', title: 'Rural Missions, Crusades & Church Plant Progress', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'CH-REP-MEDIA', productId: 'prod-church-faith', moduleId: 'CH-MOD-LIVESTREAM-MEDIA', code: 'CH-REP-MEDIA', title: 'Digital Broadcast Telemetry & Sermon Engagement Log', format: 'TABULAR', exportTypes: ['PDF', 'XLSX'] },
    { id: 'CH-REP-SANCTUARY', productId: 'prod-church-faith', moduleId: 'CH-MOD-SANCTUARY-EVENTS', code: 'CH-REP-SANCTUARY', title: 'Sanctuary Reservations, Weddings & Duty Rosters', format: 'SUMMARY', exportTypes: ['PDF'] }
  ],
  workflows: [
    { id: 'CH-WF-SACRAMENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS', code: 'CH-WF-SACRAMENTS', title: 'Canonical Holy Sacrament Registration Workflow', stages: ['CANDIDATE_VETTED', 'SACRAMENT_ADMINISTERED', 'CERTIFICATE_SEALED'], slaHours: 48, requiredApprovers: ['ROLE_CH_CLERGY', 'ROLE_CH_BISHOP'], initialState: 'CANDIDATE_VETTED' },
    { id: 'CH-WF-CELLS', productId: 'prod-church-faith', moduleId: 'CH-MOD-CELL-FELLOWSHIPS', code: 'CH-WF-CELLS', title: 'Cell Group Meeting Report & Offering Workflow', stages: ['SUBMITTED', 'VERIFIED', 'POSTED_TO_TITHE'], slaHours: 24, requiredApprovers: ['ROLE_CH_CLERGY'], initialState: 'SUBMITTED' },
    { id: 'CH-WF-CARE', productId: 'prod-church-faith', moduleId: 'CH-MOD-PASTORAL-CARE', code: 'CH-WF-CARE', title: 'Pastoral Counseling & Visitation Workflow', stages: ['APPOINTED', 'VISITED', 'CARE_CONCLUDED'], slaHours: 72, requiredApprovers: ['ROLE_CH_CLERGY'], initialState: 'APPOINTED' },
    { id: 'CH-WF-TITHE', productId: 'prod-church-faith', moduleId: 'CH-MOD-TITHE-OFFERTORY', code: 'CH-WF-TITHE', title: 'Sunday Offertory Dual-Custody Verification Workflow', stages: ['COUNTED', 'DUAL_SIGNED', 'BANKED_POSTED'], slaHours: 12, requiredApprovers: ['ROLE_CH_WARDEN', 'ROLE_CH_TREASURER'], initialState: 'COUNTED' },
    { id: 'CH-WF-PLEDGES', productId: 'prod-church-faith', moduleId: 'CH-MOD-BUILDING-PLEDGES', code: 'CH-WF-PLEDGES', title: 'Capital Building Pledge Installment Workflow', stages: ['PLEDGED', 'INSTALLMENT_PAID', 'FULFILLED'], slaHours: 168, requiredApprovers: ['ROLE_CH_TREASURER'], initialState: 'PLEDGED' },
    { id: 'CH-WF-BENEVOLENCE', productId: 'prod-church-faith', moduleId: 'CH-MOD-BENEVOLENCE-WELFARE', code: 'CH-WF-BENEVOLENCE', title: 'Benevolence Hardship Vetting & Grant Workflow', stages: ['VETTED', 'CHAIR_APPROVED', 'RELIEF_DISBURSED'], slaHours: 24, requiredApprovers: ['ROLE_CH_CLERGY', 'ROLE_CH_WARDEN'], initialState: 'VETTED' },
    { id: 'CH-WF-MISSIONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MISSIONS-CRUSADES', code: 'CH-WF-MISSIONS', title: 'Rural Church Plant Commissioning Workflow', stages: ['PROPOSED', 'SYNOD_APPROVED', 'COMMISSIONED'], slaHours: 720, requiredApprovers: ['ROLE_CH_BISHOP'], initialState: 'PROPOSED' },
    { id: 'CH-WF-MEDIA', productId: 'prod-church-faith', moduleId: 'CH-MOD-LIVESTREAM-MEDIA', code: 'CH-WF-MEDIA', title: 'Sunday Sermon Audio Mastering & Indexing Workflow', stages: ['RECORDED', 'MASTERED', 'PUBLISHED_INDEXED'], slaHours: 6, requiredApprovers: ['ROLE_CH_CLERGY'], initialState: 'RECORDED' },
    { id: 'CH-WF-SANCTUARY', productId: 'prod-church-faith', moduleId: 'CH-MOD-SANCTUARY-EVENTS', code: 'CH-WF-SANCTUARY', title: 'Holy Matrimony Sanctuary Booking Workflow', stages: ['REQUESTED', 'BANNS_CLEARED', 'CONFIRMED'], slaHours: 336, requiredApprovers: ['ROLE_CH_CLERGY', 'ROLE_CH_BISHOP'], initialState: 'REQUESTED' }
  ],
  databaseEntities: [
    { id: 'CH-DB-SACRAMENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS', tableName: 'ch_sacramental_registers', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'candidate_name', type: 'VARCHAR(255)', required: true }, { name: 'sacrament_type', type: 'VARCHAR(50)', required: true }, { name: 'minister_name', type: 'VARCHAR(255)', required: true }, { name: 'administered_at', type: 'DATE', required: true }], auditLogged: true },
    { id: 'CH-DB-CELLS', productId: 'prod-church-faith', moduleId: 'CH-MOD-CELL-FELLOWSHIPS', tableName: 'ch_cell_fellowships', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'cell_name', type: 'VARCHAR(255)', required: true }, { name: 'leader_name', type: 'VARCHAR(255)', required: true }, { name: 'meeting_day', type: 'VARCHAR(20)', required: true }, { name: 'attendance_count', type: 'INTEGER', required: true }], auditLogged: true },
    { id: 'CH-DB-COUNSELING', productId: 'prod-church-faith', moduleId: 'CH-MOD-PASTORAL-CARE', tableName: 'ch_pastoral_care_encounters', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'member_id', type: 'UUID', required: true, indexed: true }, { name: 'encounter_type', type: 'VARCHAR(50)', required: true }, { name: 'counselor_name', type: 'VARCHAR(255)', required: true }, { name: 'notes_sealed', type: 'BOOLEAN', required: true }], auditLogged: true },
    { id: 'CH-DB-TITHE-LEDGER', productId: 'prod-church-faith', moduleId: 'CH-MOD-TITHE-OFFERTORY', tableName: 'ch_tithes_offertory', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'service_date', type: 'DATE', required: true, indexed: true }, { name: 'envelope_no', type: 'VARCHAR(50)', required: false }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }, { name: 'currency', type: 'VARCHAR(3)', required: true }], auditLogged: true },
    { id: 'CH-DB-PLEDGES', productId: 'prod-church-faith', moduleId: 'CH-MOD-BUILDING-PLEDGES', tableName: 'ch_building_pledges', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'member_id', type: 'UUID', required: true, indexed: true }, { name: 'total_pledged', type: 'DECIMAL(18,2)', required: true }, { name: 'total_paid', type: 'DECIMAL(18,2)', required: true }, { name: 'due_date', type: 'DATE', required: true }], auditLogged: true },
    { id: 'CH-DB-BENEVOLENCE', productId: 'prod-church-faith', moduleId: 'CH-MOD-BENEVOLENCE-WELFARE', tableName: 'ch_benevolence_relief', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'beneficiary_name', type: 'VARCHAR(255)', required: true }, { name: 'case_category', type: 'VARCHAR(50)', required: true }, { name: 'amount_approved', type: 'DECIMAL(18,2)', required: true }, { name: 'disbursed_at', type: 'TIMESTAMP', required: false }], auditLogged: true },
    { id: 'CH-DB-MISSIONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MISSIONS-CRUSADES', tableName: 'ch_missions_church_plants', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'location_name', type: 'VARCHAR(255)', required: true }, { name: 'pastor_in_charge', type: 'VARCHAR(255)', required: true }, { name: 'launch_date', type: 'DATE', required: true }, { name: 'budget_allocated', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'CH-DB-SERMONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-LIVESTREAM-MEDIA', tableName: 'ch_sermon_audio_vault', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'title', type: 'VARCHAR(255)', required: true }, { name: 'preacher', type: 'VARCHAR(255)', required: true }, { name: 'scripture_reference', type: 'VARCHAR(100)', required: true }, { name: 'audio_url', type: 'TEXT', required: true }], auditLogged: true },
    { id: 'CH-DB-SANCTUARY-EVENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-SANCTUARY-EVENTS', tableName: 'ch_sanctuary_events', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'event_name', type: 'VARCHAR(255)', required: true }, { name: 'event_type', type: 'VARCHAR(50)', required: true }, { name: 'start_time', type: 'TIMESTAMP', required: true }, { name: 'end_time', type: 'TIMESTAMP', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'CH-API-SACRAMENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS', code: 'API_CH_SACRAMENTS', method: 'POST', endpoint: '/api/v1/church/sacraments/register', requiredPermission: 'CH-PERM-CLERGY', handlerName: 'registerSacramentHandler', summary: 'Register sacrament and generate certificate.' },
    { id: 'CH-API-CELLS', productId: 'prod-church-faith', moduleId: 'CH-MOD-CELL-FELLOWSHIPS', code: 'API_CH_CELLS', method: 'POST', endpoint: '/api/v1/church/cells/roll', requiredPermission: 'CH-PERM-CLERGY', handlerName: 'submitCellRollHandler', summary: 'Submit weekly cell fellowship meeting roll.' },
    { id: 'CH-API-CARE', productId: 'prod-church-faith', moduleId: 'CH-MOD-PASTORAL-CARE', code: 'API_CH_CARE', method: 'POST', endpoint: '/api/v1/church/care/log', requiredPermission: 'CH-PERM-CLERGY', handlerName: 'logPastoralCareHandler', summary: 'Log pastoral counseling or hospital visit.' },
    { id: 'CH-API-TITHE', productId: 'prod-church-faith', moduleId: 'CH-MOD-TITHE-OFFERTORY', code: 'API_CH_TITHE', method: 'POST', endpoint: '/api/v1/church/tithes/post', requiredPermission: 'CH-PERM-TREASURY', handlerName: 'postTitheCountHandler', summary: 'Post Sunday collection dual-custody count.' },
    { id: 'CH-API-PLEDGES', productId: 'prod-church-faith', moduleId: 'CH-MOD-BUILDING-PLEDGES', code: 'API_CH_PLEDGES', method: 'POST', endpoint: '/api/v1/church/pledges/record', requiredPermission: 'CH-PERM-TREASURY', handlerName: 'recordBuildingPledgeHandler', summary: 'Record cathedral capital pledge.' },
    { id: 'CH-API-BENEVOLENCE', productId: 'prod-church-faith', moduleId: 'CH-MOD-BENEVOLENCE-WELFARE', code: 'API_CH_BENEVOLENCE', method: 'POST', endpoint: '/api/v1/church/welfare/grant', requiredPermission: 'CH-PERM-CLERGY', handlerName: 'approveBenevolenceGrantHandler', summary: 'Approve emergency benevolence hardship grant.' },
    { id: 'CH-API-MISSIONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MISSIONS-CRUSADES', code: 'API_CH_MISSIONS', method: 'POST', endpoint: '/api/v1/church/missions/plant', requiredPermission: 'CH-PERM-BISHOP', handlerName: 'commissionChurchPlantHandler', summary: 'Commission rural mission church plant.' },
    { id: 'CH-API-MEDIA', productId: 'prod-church-faith', moduleId: 'CH-MOD-LIVESTREAM-MEDIA', code: 'API_CH_MEDIA', method: 'POST', endpoint: '/api/v1/church/media/sermon', requiredPermission: 'CH-PERM-CLERGY', handlerName: 'uploadSermonMediaHandler', summary: 'Upload sermon audio and index notes.' },
    { id: 'CH-API-SANCTUARY', productId: 'prod-church-faith', moduleId: 'CH-MOD-SANCTUARY-EVENTS', code: 'API_CH_SANCTUARY', method: 'POST', endpoint: '/api/v1/church/sanctuary/booking', requiredPermission: 'CH-PERM-CLERGY', handlerName: 'bookSanctuaryEventHandler', summary: 'Book sanctuary for wedding or service.' }
  ],
  runtimeComponents: [
    { id: 'CH-RTC-SACRAMENTS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MEMBERSHIP-SACRAMENTS', componentKey: 'ChurchSacramentsEngine', name: 'Canonical Sacraments & Parish Roll Engine', description: 'Interactive sacramental registrar and canonical baptismal cert generator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LITURGICAL_OPERATIONS' },
    { id: 'CH-RTC-CELLS', productId: 'prod-church-faith', moduleId: 'CH-MOD-CELL-FELLOWSHIPS', componentKey: 'ChurchCellsEngine', name: 'Home Cell Fellowship & Discipleship Engine', description: 'Parish cell fellowship locator, meeting attendance logs, and prayer requests.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'PARISH_CARE' },
    { id: 'CH-RTC-CARE', productId: 'prod-church-faith', moduleId: 'CH-MOD-PASTORAL-CARE', componentKey: 'ChurchCareEngine', name: 'Pastoral Care & Counseling Encounter Engine', description: 'Confidential clergy counseling tracker and hospital visitation journal.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'PARISH_CARE' },
    { id: 'CH-RTC-TITHE', productId: 'prod-church-faith', moduleId: 'CH-MOD-TITHE-OFFERTORY', componentKey: 'ChurchTitheEngine', name: 'Sunday Offertory & Mobile Money Tithe Engine', description: 'Dual-custody cash counting sheet and mobile money tithe aggregator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'STEWARDSHIP_TREASURY' },
    { id: 'CH-RTC-PLEDGES', productId: 'prod-church-faith', moduleId: 'CH-MOD-BUILDING-PLEDGES', componentKey: 'ChurchPledgesEngine', name: 'Cathedral Building Pledges & Projects Engine', description: 'Capital project installment ledger and donor recognition registry.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'STEWARDSHIP_TREASURY' },
    { id: 'CH-RTC-BENEVOLENCE', productId: 'prod-church-faith', moduleId: 'CH-MOD-BENEVOLENCE-WELFARE', componentKey: 'ChurchBenevolenceEngine', name: 'Benevolence Compassion Relief Engine', description: 'Vetted emergency welfare claims and charitable disbursements.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'COMPASSION_WELFARE' },
    { id: 'CH-RTC-MISSIONS', productId: 'prod-church-faith', moduleId: 'CH-MOD-MISSIONS-CRUSADES', componentKey: 'ChurchMissionsEngine', name: 'Rural Missions & Church Planting Engine', description: 'Crusade logistics planner, missionary sponsorships, and outpost tracking.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EVANGELISM_MISSIONS' },
    { id: 'CH-RTC-MEDIA', productId: 'prod-church-faith', moduleId: 'CH-MOD-LIVESTREAM-MEDIA', componentKey: 'ChurchMediaEngine', name: 'Sunday RTMP Livestream & Sermon Vault Engine', description: 'High-definition video/audio sermon indexing and scripture tagger.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'DIGITAL_MEDIA' },
    { id: 'CH-RTC-SANCTUARY', productId: 'prod-church-faith', moduleId: 'CH-MOD-SANCTUARY-EVENTS', componentKey: 'ChurchSanctuaryEngine', name: 'Sanctuary Calendar & Liturgical Roster Engine', description: 'Altar guild scheduling, holy matrimony calendar, and usher assignments.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SANCTUARY_LOGISTICS' }
  ],
  permissions: [
    { id: 'CH-PERM-BISHOP', productId: 'prod-church-faith', code: 'PERM_CH_BISHOP_SYNOD', name: 'Bishop & Synod Sovereign Permission', description: 'Full diocesan oversight, clergy appointments, and doctrinal approvals.' },
    { id: 'CH-PERM-CLERGY', productId: 'prod-church-faith', code: 'PERM_CH_CLERGY_MINISTRY', name: 'Parish Clergy & Sacraments Permission', description: 'Administer sacraments, conduct pastoral care, and register members.' },
    { id: 'CH-PERM-TREASURY', productId: 'prod-church-faith', code: 'PERM_CH_TREASURY_STEWARDSHIP', name: 'Diocesan Treasury & Tithe Cashbook Permission', description: 'Access financial journals, count sheets, and bank reconciliations.' }
  ],
  roles: [
    { id: 'CH-ROLE-BISHOP', productId: 'prod-church-faith', code: 'ROLE_CH_BISHOP', name: 'Diocesan Bishop / Senior Pastor', tier: 'GOVERNANCE', permissionIds: ['CH-PERM-BISHOP', 'CH-PERM-CLERGY', 'CH-PERM-TREASURY'] },
    { id: 'CH-ROLE-CLERGY', productId: 'prod-church-faith', code: 'ROLE_CH_CLERGY', name: 'Parish Priest / Resident Pastor', tier: 'EXECUTIVE', permissionIds: ['CH-PERM-CLERGY'] },
    { id: 'CH-ROLE-TREASURER', productId: 'prod-church-faith', code: 'ROLE_CH_TREASURER', name: 'Diocesan Treasurer / Church Accountant', tier: 'OPERATIONAL', permissionIds: ['CH-PERM-TREASURY'] },
    { id: 'CH-ROLE-WARDEN', productId: 'prod-church-faith', code: 'ROLE_CH_WARDEN', name: 'Parish Church Warden', tier: 'OPERATIONAL', permissionIds: ['CH-PERM-TREASURY', 'CH-PERM-CLERGY'] }
  ]
};
