import { CanonicalProductHierarchy } from './types';

export const DIGITAL_PAY_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-digital-pay',
    code: 'DPAY',
    name: 'JUMO DIGITAL PAY National Payment Switch',
    category: 'PAYMENT_SWITCH',
    description: 'National multi-rail payment switch, QR merchant acquiring, ISO 20022 messaging, real-time gross settlement (RTGS) bridge, automated merchant settlement, fraud prevention, and POS terminal management.',
    version: '2026.4.0',
    iconName: 'CreditCard',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Chief Operating Officer / National Switch Governor',
    governingLegislation: 'National Payment Systems Act 2020 & Bank of Uganda Payment Guidelines 2026',
    directorateIds: ['DPAY-DIR-001', 'DPAY-DIR-002', 'DPAY-DIR-003', 'DPAY-DIR-004']
  },
  directorates: [
    { id: 'DPAY-DIR-001', productId: 'prod-digital-pay', code: 'DPAY-DIR-SWITCH', name: 'Directorate of Multi-Rail Transaction Switching', description: 'Real-time ISO 20022 message routing across banks, telcos (MTN/Airtel), card schemes (Visa/Mastercard), and national QR.', leadRole: 'DIRECTOR_SWITCH_ARCHITECTURE', departmentIds: ['DPAY-DEPT-001', 'DPAY-DEPT-002'] },
    { id: 'DPAY-DIR-002', productId: 'prod-digital-pay', code: 'DPAY-DIR-MERCHANT', name: 'Directorate of Merchant Acquiring & Terminal Fleet', description: 'Dynamic EMV QR codes, Smart Android POS terminal provisioning, and merchant tiering.', leadRole: 'HEAD_MERCHANT_ACQUIRING', departmentIds: ['DPAY-DEPT-003', 'DPAY-DEPT-004'] },
    { id: 'DPAY-DIR-003', productId: 'prod-digital-pay', code: 'DPAY-DIR-CLEARING', name: 'Directorate of Clearing, Settlement & Escrow', description: 'T+0 instant net settlement, interchange fee distribution, and Bank of Uganda RTGS clearing window.', leadRole: 'CHIEF_CLEARING_OFFICER', departmentIds: ['DPAY-DEPT-005', 'DPAY-DEPT-006'] },
    { id: 'DPAY-DIR-004', productId: 'prod-digital-pay', code: 'DPAY-DIR-FRAUD', name: 'Directorate of Real-Time Fraud & Anti-Money Laundering', description: 'Sub-50ms machine learning fraud scoring, velocity checks, and suspicious transaction reporting (STR).', leadRole: 'CHIEF_RISK_OFFICER', departmentIds: ['DPAY-DEPT-007', 'DPAY-DEPT-008'] }
  ],
  departments: [
    { id: 'DPAY-DEPT-001', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', code: 'DPAY-DEPT-ISO20022', name: 'Department of ISO 20022 High-Throughput Routing', description: 'Processes PACS.008, PACS.002, and PAIN messages at 50,000 transactions per second.', headRole: 'HEAD_SWITCH_OPERATIONS', officeIds: ['DPAY-OFF-001'] },
    { id: 'DPAY-DEPT-002', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', code: 'DPAY-DEPT-MOMO-BRIDGE', name: 'Department of Telco Interoperability & USSD Gateways', description: 'Cross-network mobile money interoperability connecting all telecom subscribers.', headRole: 'HEAD_TELCO_INTEGRATION', officeIds: ['DPAY-OFF-002'] },
    { id: 'DPAY-DEPT-003', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', code: 'DPAY-DEPT-QR-NETWORK', name: 'Department of National EMV QR Standards', description: 'Interoperable merchant QR codes accepting all wallets with instant soundbox audio alerts.', headRole: 'HEAD_QR_NETWORK', officeIds: ['DPAY-OFF-003'] },
    { id: 'DPAY-DEPT-004', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', code: 'DPAY-DEPT-POS-TERMINALS', name: 'Department of Smart POS Fleet Remote Management', description: 'TMS over-the-air firmware updates, key injection, and hardware tamper logs.', headRole: 'HEAD_POS_OPERATIONS', officeIds: ['DPAY-OFF-004'] },
    { id: 'DPAY-DEPT-005', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', code: 'DPAY-DEPT-INSTANT-SETTLE', name: 'Department of T+0 Instant Merchant Settlement', description: 'Automated revenue split, withholding tax deduction (WHT 6%), and bank transfers.', headRole: 'HEAD_MERCHANT_SETTLEMENT', officeIds: ['DPAY-OFF-005'] },
    { id: 'DPAY-DEPT-006', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', code: 'DPAY-DEPT-INTERCHANGE', name: 'Department of Multilateral Interchange & RTGS', description: 'Computes multilateral netting matrix and submits clearing files to Central Bank RTGS.', headRole: 'HEAD_INTERCHANGE_CLEARING', officeIds: ['DPAY-OFF-006'] },
    { id: 'DPAY-DEPT-007', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', code: 'DPAY-DEPT-FRAUD-RADAR', name: 'Department of Sub-Second AI Fraud Scoring', description: 'Evaluates 80+ risk features per transaction before authorization.', headRole: 'HEAD_FRAUD_PREVENTION', officeIds: ['DPAY-OFF-007'] },
    { id: 'DPAY-DEPT-008', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', code: 'DPAY-DEPT-DISPUTES', name: 'Department of Chargebacks, Disputes & Pre-Arbitration', description: 'Automated chargeback lifecycle, evidence submission, and arbitration rulings.', headRole: 'HEAD_DISPUTE_RESOLUTION', officeIds: ['DPAY-OFF-008'] }
  ],
  offices: [
    { id: 'DPAY-OFF-001', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-001', code: 'DPAY-OFF-NOC-SWITCH', name: '24/7 National Switch Network Operations Center', description: 'Real-time TPS, latency, and route failover monitoring.', officerRole: 'NOC_SWITCH_CONTROLLER', portalIds: ['DPAY-PORTAL-001', 'DPAY-PORTAL-002'], moduleIds: ['DPAY-MOD-001'] },
    { id: 'DPAY-OFF-002', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-002', code: 'DPAY-OFF-TELCO-GATEWAY', name: 'Mobile Interoperability Gateway Desk', description: 'Direct interconnect with MTN, Airtel, and regional payment switches.', officerRole: 'TELCO_GATEWAY_ENGINEER', portalIds: ['DPAY-PORTAL-002'], moduleIds: ['DPAY-MOD-002'] },
    { id: 'DPAY-OFF-003', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-003', code: 'DPAY-OFF-MERCHANT-ONBOARD', name: 'Merchant QR Acquiring & Soundbox Desk', description: 'Merchant KYC, tax TIN validation, and static/dynamic QR code generation.', officerRole: 'MERCHANT_ONBOARDING_LEAD', portalIds: ['DPAY-PORTAL-002', 'DPAY-PORTAL-003'], moduleIds: ['DPAY-MOD-003'] },
    { id: 'DPAY-OFF-004', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-004', code: 'DPAY-OFF-TMS-FLEET', name: 'Terminal Management System (TMS) Fleet Desk', description: 'POS firmware push, remote key loading (RKL), and geofence tracking.', officerRole: 'TMS_FLEET_CONTROLLER', portalIds: ['DPAY-PORTAL-002'], moduleIds: ['DPAY-MOD-004'] },
    { id: 'DPAY-OFF-005', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-005', code: 'DPAY-OFF-SETTLEMENT-DESK', name: 'Merchant Payout & Treasury Settlement Desk', description: 'Initiating hourly instant bank disbursements to merchants.', officerRole: 'SETTLEMENT_OFFICER', portalIds: ['DPAY-PORTAL-001', 'DPAY-PORTAL-002'], moduleIds: ['DPAY-MOD-005'] },
    { id: 'DPAY-OFF-006', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-006', code: 'DPAY-OFF-RTGS-CLEARING', name: 'Central Bank RTGS Clearing Desk', description: 'Generating multilateral net settlement files for Bank of Uganda windows.', officerRole: 'RTGS_CLEARING_OFFICER', portalIds: ['DPAY-PORTAL-001'], moduleIds: ['DPAY-MOD-006'] },
    { id: 'DPAY-OFF-007', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-007', code: 'DPAY-OFF-FRAUD-DESK', name: 'Real-Time Fraud Prevention & Rule Engine Desk', description: 'Setting velocity limits, blacklisting fraudulent MSISDNs, and reviewing blocked transactions.', officerRole: 'FRAUD_ANALYST', portalIds: ['DPAY-PORTAL-001', 'DPAY-PORTAL-002'], moduleIds: ['DPAY-MOD-007'] },
    { id: 'DPAY-OFF-008', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-008', code: 'DPAY-OFF-DISPUTES-DESK', name: 'Chargeback & Dispute Arbitration Desk', description: 'Processing customer claim affidavits and issuing refund reversals.', officerRole: 'DISPUTE_ARBITRATOR', portalIds: ['DPAY-PORTAL-002'], moduleIds: ['DPAY-MOD-008'] }
  ],
  portals: [
    { id: 'DPAY-PORTAL-001', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-001', officeId: 'DPAY-OFF-001', code: 'DPAY-PORTAL-EXECUTIVE', name: 'National Switch Governor & Executive Cockpit', description: 'National switch volume, network uptime, BoU RTGS clearing balances, and fraud telemetry.', targetRole: 'SWITCH_GOVERNOR', authLevel: 'PKI_SOVEREIGN', route: '/digital-pay/executive', moduleIds: ['DPAY-MOD-001', 'DPAY-MOD-005', 'DPAY-MOD-006', 'DPAY-MOD-007'] },
    { id: 'DPAY-PORTAL-002', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-001', officeId: 'DPAY-OFF-001', code: 'DPAY-PORTAL-OPERATIONS', name: 'Switch Operations, Merchant & TMS Console', description: 'Live transaction monitor, terminal provisioning, dispute cases, and settlement logs.', targetRole: 'SWITCH_OPERATOR', authLevel: 'STAFF', route: '/digital-pay/operations', moduleIds: ['DPAY-MOD-001', 'DPAY-MOD-002', 'DPAY-MOD-003', 'DPAY-MOD-004', 'DPAY-MOD-007', 'DPAY-MOD-008'] },
    { id: 'DPAY-PORTAL-003', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-003', officeId: 'DPAY-OFF-003', code: 'DPAY-PORTAL-MERCHANT', name: 'Merchant Business & Cashier Portal', description: 'Generate instant dynamic QR codes, track incoming payments, and configure automated bank payouts.', targetRole: 'MERCHANT_OWNER', authLevel: 'PUBLIC', route: '/digital-pay/merchant', moduleIds: ['DPAY-MOD-003', 'DPAY-MOD-005'] }
  ],
  modules: [
    { id: 'DPAY-MOD-001', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-001', officeId: 'DPAY-OFF-001', portalId: 'DPAY-PORTAL-002', code: 'DPAY-MOD-SWITCH-ROUTER', name: 'ISO 20022 High-Throughput Switching Engine', description: 'Universal transaction router with sub-100ms multi-rail protocol translation.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-001', 'DPAY-CAP-002'], screenIds: ['DPAY-SCR-001'], formIds: ['DPAY-FORM-001'], dashboardIds: ['DPAY-DASH-001'], reportIds: ['DPAY-REP-001'], workflowIds: ['DPAY-WF-001'], databaseEntityIds: ['DPAY-DB-001'], apiIds: ['DPAY-API-001'], runtimeComponentId: 'DPAY-RTC-001', permissionIds: ['DPAY-PERM-001'] },
    { id: 'DPAY-MOD-002', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-002', officeId: 'DPAY-OFF-002', portalId: 'DPAY-PORTAL-002', code: 'DPAY-MOD-TELCO-BRIDGE', name: 'Cross-Network Telco Interoperability Bridge', description: 'Connects MTN MoMo, Airtel Money, and card networks for seamless P2P and P2B transfers.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-003', 'DPAY-CAP-004'], screenIds: ['DPAY-SCR-002'], formIds: [], dashboardIds: ['DPAY-DASH-001'], reportIds: ['DPAY-REP-002'], workflowIds: ['DPAY-WF-002'], databaseEntityIds: ['DPAY-DB-002'], apiIds: ['DPAY-API-002'], runtimeComponentId: 'DPAY-RTC-002', permissionIds: ['DPAY-PERM-002'] },
    { id: 'DPAY-MOD-003', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-003', officeId: 'DPAY-OFF-003', portalId: 'DPAY-PORTAL-003', code: 'DPAY-MOD-MERCHANT-QR', name: 'National EMV QR Acquiring & Soundbox Engine', description: 'Generates ISO/IEC 18004 dynamic QR codes and triggers instant IoT soundbox voice alerts.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-005', 'DPAY-CAP-006'], screenIds: ['DPAY-SCR-003'], formIds: ['DPAY-FORM-002'], dashboardIds: ['DPAY-DASH-002'], reportIds: ['DPAY-REP-003'], workflowIds: ['DPAY-WF-003'], databaseEntityIds: ['DPAY-DB-003'], apiIds: ['DPAY-API-003'], runtimeComponentId: 'DPAY-RTC-003', permissionIds: ['DPAY-PERM-003'] },
    { id: 'DPAY-MOD-004', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-004', officeId: 'DPAY-OFF-004', portalId: 'DPAY-PORTAL-002', code: 'DPAY-MOD-TMS-FLEET', name: 'Smart Android POS Terminal Management (TMS)', description: 'Remote fleet monitoring, tamper detection, and OTA kernel updates.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-007', 'DPAY-CAP-008'], screenIds: ['DPAY-SCR-004'], formIds: ['DPAY-FORM-003'], dashboardIds: ['DPAY-DASH-002'], reportIds: ['DPAY-REP-004'], workflowIds: ['DPAY-WF-004'], databaseEntityIds: ['DPAY-DB-004'], apiIds: ['DPAY-API-004'], runtimeComponentId: 'DPAY-RTC-004', permissionIds: ['DPAY-PERM-004'] },
    { id: 'DPAY-MOD-005', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-005', officeId: 'DPAY-OFF-005', portalId: 'DPAY-PORTAL-001', code: 'DPAY-MOD-MERCHANT-SETTLE', name: 'T+0 Instant Merchant Settlement & Revenue Split', description: 'Automated settlement to commercial bank accounts with WHT deduction and invoice matching.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-009', 'DPAY-CAP-010'], screenIds: ['DPAY-SCR-005'], formIds: ['DPAY-FORM-004'], dashboardIds: ['DPAY-DASH-003'], reportIds: ['DPAY-REP-005'], workflowIds: ['DPAY-WF-005'], databaseEntityIds: ['DPAY-DB-005'], apiIds: ['DPAY-API-005'], runtimeComponentId: 'DPAY-RTC-005', permissionIds: ['DPAY-PERM-005'] },
    { id: 'DPAY-MOD-006', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-006', officeId: 'DPAY-OFF-006', portalId: 'DPAY-PORTAL-001', code: 'DPAY-MOD-RTGS-CLEARING', name: 'Multilateral Interchange & BoU RTGS Clearing', description: 'Calculates multilateral net balances across all participating banks and settles via Central Bank RTGS.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-011', 'DPAY-CAP-012'], screenIds: ['DPAY-SCR-006'], formIds: [], dashboardIds: ['DPAY-DASH-003'], reportIds: ['DPAY-REP-006'], workflowIds: ['DPAY-WF-006'], databaseEntityIds: ['DPAY-DB-006'], apiIds: ['DPAY-API-006'], runtimeComponentId: 'DPAY-RTC-006', permissionIds: ['DPAY-PERM-006'] },
    { id: 'DPAY-MOD-007', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-007', officeId: 'DPAY-OFF-007', portalId: 'DPAY-PORTAL-001', code: 'DPAY-MOD-FRAUD-RADAR', name: 'Real-Time Fraud Radar & AML Scoring Engine', description: '50ms AI evaluation with device fingerprinting, geolocation anomaly, and mule account detection.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-013', 'DPAY-CAP-014'], screenIds: ['DPAY-SCR-007'], formIds: ['DPAY-FORM-005'], dashboardIds: ['DPAY-DASH-004'], reportIds: ['DPAY-REP-007'], workflowIds: ['DPAY-WF-007'], databaseEntityIds: ['DPAY-DB-007'], apiIds: ['DPAY-API-007'], runtimeComponentId: 'DPAY-RTC-007', permissionIds: ['DPAY-PERM-007'] },
    { id: 'DPAY-MOD-008', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-008', officeId: 'DPAY-OFF-008', portalId: 'DPAY-PORTAL-002', code: 'DPAY-MOD-DISPUTE-ENGINE', name: 'Chargeback Lifecycle & Dispute Arbitration', description: 'Automated claim submission, document evidence management, and arbitration settlement.', status: 'ACTIVE_CORE', capabilityIds: ['DPAY-CAP-015', 'DPAY-CAP-016'], screenIds: ['DPAY-SCR-008'], formIds: ['DPAY-FORM-006'], dashboardIds: ['DPAY-DASH-004'], reportIds: ['DPAY-REP-008'], workflowIds: ['DPAY-WF-008'], databaseEntityIds: ['DPAY-DB-008'], apiIds: ['DPAY-API-008'], runtimeComponentId: 'DPAY-RTC-008', permissionIds: ['DPAY-PERM-008'] }
  ],
  capabilities: [
    { id: 'DPAY-CAP-001', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-001', officeId: 'DPAY-OFF-001', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-001', code: 'DPAY_CAP_ROUTE_ISO20022', name: 'Route ISO 20022 Financial Message', description: 'Validates XML schema and routes payment message to destination participant bank in < 80ms.', serviceAction: 'digitalpay.switch.routeMessage', requiredPermission: 'DPAY-PERM-001', runtimeComponentId: 'DPAY-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-002', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-001', officeId: 'DPAY-OFF-001', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-001', code: 'DPAY_CAP_EXECUTE_REVERSAL', name: 'Execute Automated Transaction Reversal', description: 'Triggers atomic rollback on transaction timeout to ensure zero fund loss.', serviceAction: 'digitalpay.switch.executeReversal', requiredPermission: 'DPAY-PERM-001', runtimeComponentId: 'DPAY-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-003', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-002', officeId: 'DPAY-OFF-002', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-002', code: 'DPAY_CAP_EXECUTE_MOMO_BRIDGE', name: 'Execute Cross-Telco P2P Transfer', description: 'Switches payment between MTN MoMo and Airtel Money wallets with instant confirmation.', serviceAction: 'digitalpay.telco.transferCrossNetwork', requiredPermission: 'DPAY-PERM-002', runtimeComponentId: 'DPAY-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-004', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-001', departmentId: 'DPAY-DEPT-002', officeId: 'DPAY-OFF-002', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-002', code: 'DPAY_CAP_QUERY_NAME_LOOKUP', name: 'Query Beneficiary Name Lookup API', description: 'Retrieves verified account/phone holder name prior to fund transfer to prevent misdirection.', serviceAction: 'digitalpay.telco.queryAccountName', requiredPermission: 'DPAY-PERM-002', runtimeComponentId: 'DPAY-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-005', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-003', officeId: 'DPAY-OFF-003', portalId: 'DPAY-PORTAL-003', moduleId: 'DPAY-MOD-003', code: 'DPAY_CAP_GENERATE_DYNAMIC_QR', name: 'Generate Dynamic Merchant EMV QR Code', description: 'Generates single-use QR payload containing merchant ID, amount, and invoice reference.', serviceAction: 'digitalpay.qr.generateDynamicQr', requiredPermission: 'DPAY-PERM-003', runtimeComponentId: 'DPAY-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-006', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-003', officeId: 'DPAY-OFF-003', portalId: 'DPAY-PORTAL-003', moduleId: 'DPAY-MOD-003', code: 'DPAY_CAP_TRIGGER_SOUNDBOX_AUDIO', name: 'Trigger IoT Soundbox Audio Payment Announcement', description: 'Broadcasts voice payment confirmation in English, Luganda, or Swahili to merchant soundbox.', serviceAction: 'digitalpay.qr.triggerSoundbox', requiredPermission: 'DPAY-PERM-003', runtimeComponentId: 'DPAY-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-007', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-004', officeId: 'DPAY-OFF-004', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-004', code: 'DPAY_CAP_PROVISION_POS_TERMINAL', name: 'Provision Smart POS Terminal', description: 'Injects Master Session Keys (DUKPT) and binds terminal to merchant outlet.', serviceAction: 'digitalpay.tms.provisionTerminal', requiredPermission: 'DPAY-PERM-004', runtimeComponentId: 'DPAY-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-008', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-002', departmentId: 'DPAY-DEPT-004', officeId: 'DPAY-OFF-004', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-004', code: 'DPAY_CAP_REMOTE_WIPE_TERMINAL', name: 'Remote Wipe / Freeze Tampered POS Terminal', description: 'Erases cryptographic keys immediately if hardware accelerometer detects physical tamper.', serviceAction: 'digitalpay.tms.remoteWipeTerminal', requiredPermission: 'DPAY-PERM-004', runtimeComponentId: 'DPAY-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-009', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-005', officeId: 'DPAY-OFF-005', portalId: 'DPAY-PORTAL-001', moduleId: 'DPAY-MOD-005', code: 'DPAY_CAP_CALCULATE_MERCHANT_PAYOUT', name: 'Calculate Net Merchant Settlement (T+0)', description: 'Deducts MDR fee and 6% WHT, generating net bank transfer instruction.', serviceAction: 'digitalpay.settlement.calculatePayout', requiredPermission: 'DPAY-PERM-005', runtimeComponentId: 'DPAY-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-010', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-005', officeId: 'DPAY-OFF-005', portalId: 'DPAY-PORTAL-001', moduleId: 'DPAY-MOD-005', code: 'DPAY_CAP_EXECUTE_BATCH_PAYOUT', name: 'Execute Batch Instant Merchant Payout', description: 'Pushes bulk settlement instructions directly to commercial bank EFT switch.', serviceAction: 'digitalpay.settlement.executeBatchPayout', requiredPermission: 'DPAY-PERM-005', runtimeComponentId: 'DPAY-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-011', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-006', officeId: 'DPAY-OFF-006', portalId: 'DPAY-PORTAL-001', moduleId: 'DPAY-MOD-006', code: 'DPAY_CAP_GENERATE_NETTING_MATRIX', name: 'Compute Multilateral Net Clearing Matrix', description: 'Nets off gross debits and credits between all commercial banks for RTGS posting.', serviceAction: 'digitalpay.clearing.generateNettingMatrix', requiredPermission: 'DPAY-PERM-006', runtimeComponentId: 'DPAY-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-012', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-003', departmentId: 'DPAY-DEPT-006', officeId: 'DPAY-OFF-006', portalId: 'DPAY-PORTAL-001', moduleId: 'DPAY-MOD-006', code: 'DPAY_CAP_POST_RTGS_CLEARING_FILE', name: 'Transmit Net Settlement to Bank of Uganda RTGS', description: 'Transmits cryptographically signed PACS.009 settlement file to BoU RTGS gateway.', serviceAction: 'digitalpay.clearing.postRtgsFile', requiredPermission: 'DPAY-PERM-006', runtimeComponentId: 'DPAY-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-013', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-007', officeId: 'DPAY-OFF-007', portalId: 'DPAY-PORTAL-001', moduleId: 'DPAY-MOD-007', code: 'DPAY_CAP_EVALUATE_FRAUD_SCORE', name: 'Real-Time AI Fraud Risk Evaluation', description: 'Returns risk score (0-1000) and recommendation (APPROVE / CHALLENGE / DECLINE).', serviceAction: 'digitalpay.fraud.evaluateRiskScore', requiredPermission: 'DPAY-PERM-007', runtimeComponentId: 'DPAY-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-014', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-007', officeId: 'DPAY-OFF-007', portalId: 'DPAY-PORTAL-001', moduleId: 'DPAY-MOD-007', code: 'DPAY_CAP_ADD_FRAUD_BLACKLIST', name: 'Add Compromised Identifier to Global Blacklist', description: 'Propagates national blacklist update across all POS, QR, and web acquiring channels.', serviceAction: 'digitalpay.fraud.addBlacklist', requiredPermission: 'DPAY-PERM-007', runtimeComponentId: 'DPAY-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-015', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-008', officeId: 'DPAY-OFF-008', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-008', code: 'DPAY_CAP_INITIATE_CHARGEBACK', name: 'Initiate Interbank Chargeback Claim', description: 'Generates chargeback case with evidence submission window under scheme rules.', serviceAction: 'digitalpay.disputes.initiateChargeback', requiredPermission: 'DPAY-PERM-008', runtimeComponentId: 'DPAY-RTC-008', status: 'ACTIVE_CORE' },
    { id: 'DPAY-CAP-016', productId: 'prod-digital-pay', directorateId: 'DPAY-DIR-004', departmentId: 'DPAY-DEPT-008', officeId: 'DPAY-OFF-008', portalId: 'DPAY-PORTAL-002', moduleId: 'DPAY-MOD-008', code: 'DPAY_CAP_RULE_ARBITRATION', name: 'Issue Binding Chargeback Arbitration Ruling', description: 'Determines fault and executes final debit/credit adjustment between acquiring and issuing bank.', serviceAction: 'digitalpay.disputes.ruleArbitration', requiredPermission: 'DPAY-PERM-008', runtimeComponentId: 'DPAY-RTC-008', status: 'ACTIVE_CORE' }
  ],
  screens: [
    { id: 'DPAY-SCR-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', code: 'DPAY-SCR-SWITCH', title: 'National Payment Switch Real-Time Monitor', description: 'Live TPS, response times, and routing status.', viewType: 'DASHBOARD', route: '/digital-pay/switch' },
    { id: 'DPAY-SCR-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-002', code: 'DPAY-SCR-TELCO', title: 'Cross-Network Telco Interoperability Gateway', description: 'MTN & Airtel MoMo bridge logs.', viewType: 'TABLE', route: '/digital-pay/telco' },
    { id: 'DPAY-SCR-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', code: 'DPAY-SCR-MERCHANT-QR', title: 'Merchant QR Network & Soundbox Management', description: 'Active merchant terminals and live QR sales.', viewType: 'TABLE', route: '/digital-pay/merchants' },
    { id: 'DPAY-SCR-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', code: 'DPAY-SCR-TMS', title: 'Smart Android POS Terminal Fleet Console', description: 'Provisioned POS terminals, battery, and tamper status.', viewType: 'TABLE', route: '/digital-pay/terminals' },
    { id: 'DPAY-SCR-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', code: 'DPAY-SCR-SETTLEMENT', title: 'T+0 Instant Merchant Settlement Ledger', description: 'Net payouts, WHT tax splits, and bank transfers.', viewType: 'TABLE', route: '/digital-pay/settlement' },
    { id: 'DPAY-SCR-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-006', code: 'DPAY-SCR-RTGS', title: 'Bank of Uganda RTGS Clearing & Multilateral Netting', description: 'Interbank netting matrix and clearing batches.', viewType: 'DASHBOARD', route: '/digital-pay/rtgs' },
    { id: 'DPAY-SCR-007', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', code: 'DPAY-SCR-FRAUD', title: 'Real-Time Fraud Radar & AML Screening', description: 'Live suspicious activity feeds and blacklist rules.', viewType: 'DASHBOARD', route: '/digital-pay/fraud' },
    { id: 'DPAY-SCR-008', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', code: 'DPAY-SCR-DISPUTES', title: 'Chargeback & Dispute Arbitration Console', description: 'Open customer disputes and arbitration claims.', viewType: 'TABLE', route: '/digital-pay/disputes' }
  ],
  forms: [
    { id: 'DPAY-FORM-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', code: 'DPAY-FORM-MANUAL-PAY', title: 'Manual Switch Payment Simulation', submitAction: 'digitalpay.switch.routeMessage', fieldCount: 5, fields: [{ name: 'senderRail', label: 'Originating Payment Rail', type: 'select', required: true }, { name: 'receiverRail', label: 'Destination Rail / Bank', type: 'select', required: true }, { name: 'senderIdentifier', label: 'Sender Phone / Account', type: 'text', required: true }, { name: 'receiverIdentifier', label: 'Receiver Phone / Account', type: 'text', required: true }, { name: 'amountUgx', label: 'Transfer Amount (UGX)', type: 'number', required: true }], validationRules: ['AMOUNT_POSITIVE', 'RAILS_DIFFERENT'] },
    { id: 'DPAY-FORM-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', code: 'DPAY-FORM-MERCHANT-REG', title: 'Merchant QR Acquiring Onboarding', submitAction: 'digitalpay.qr.generateDynamicQr', fieldCount: 5, fields: [{ name: 'businessLegalName', label: 'Registered Business Name', type: 'text', required: true }, { name: 'tinNumber', label: 'URA Tax Identification (TIN)', type: 'text', required: true }, { name: 'settlementBankAccount', label: 'Settlement Bank Account Number', type: 'text', required: true }, { name: 'settlementBankCode', label: 'Settlement Bank Code', type: 'select', required: true }, { name: 'soundboxDeviceId', label: 'IoT Soundbox Serial Number', type: 'text', required: false }], validationRules: ['TIN_VALIDATED'] },
    { id: 'DPAY-FORM-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', code: 'DPAY-FORM-POS-ENROLL', title: 'Smart POS Terminal Enrollment', submitAction: 'digitalpay.tms.provisionTerminal', fieldCount: 4, fields: [{ name: 'serialNumber', label: 'POS Hardware Serial Number', type: 'text', required: true }, { name: 'merchantId', label: 'Assigned Merchant ID', type: 'text', required: true }, { name: 'outletLocation', label: 'Store / Branch Outlet Name', type: 'text', required: true }, { name: 'modelType', label: 'Terminal Hardware Model', type: 'select', required: true }], validationRules: ['SERIAL_UNIQUE'] },
    { id: 'DPAY-FORM-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', code: 'DPAY-FORM-SETTLE-EXEC', title: 'Instant Merchant Payout Authorization', submitAction: 'digitalpay.settlement.executeBatchPayout', fieldCount: 4, fields: [{ name: 'settlementBatchRef', label: 'Settlement Batch Reference', type: 'text', required: true }, { name: 'totalMerchants', label: 'Merchant Count in Batch', type: 'number', required: true }, { name: 'totalGrossAmountUgx', label: 'Gross Settlement (UGX)', type: 'number', required: true }, { name: 'dualSignerAuthPin', label: 'Treasury Dual Authorization PIN', type: 'password', required: true }], validationRules: ['DUAL_AUTH_VALID'] },
    { id: 'DPAY-FORM-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', code: 'DPAY-FORM-BLACKLIST-ENTRY', title: 'Add Compromised Entity to Fraud Blacklist', submitAction: 'digitalpay.fraud.addBlacklist', fieldCount: 4, fields: [{ name: 'identifierType', label: 'Identifier Type (MSISDN/NIN/ACCOUNT/IMEI)', type: 'select', required: true }, { name: 'identifierValue', label: 'Compromised Value', type: 'text', required: true }, { name: 'fraudCategory', label: 'Fraud Incident Category', type: 'select', required: true }, { name: 'caseNarrative', label: 'Investigative Evidence Summary', type: 'textarea', required: true }], validationRules: ['VALUE_FORMAT_VALID'] },
    { id: 'DPAY-FORM-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', code: 'DPAY-FORM-CHARGEBACK-FILE', title: 'Customer Chargeback Claim Filing', submitAction: 'digitalpay.disputes.initiateChargeback', fieldCount: 5, fields: [{ name: 'switchTransactionRef', label: 'Original Switch Reference (RRN)', type: 'text', required: true }, { name: 'claimAmountUgx', label: 'Disputed Amount (UGX)', type: 'number', required: true }, { name: 'disputeReasonCode', label: 'Reason Code (10.4 Fraud / 13.1 Non-Receipt)', type: 'select', required: true }, { name: 'cardholderAffidavit', label: 'Customer Written Affidavit Ref', type: 'text', required: true }, { name: 'issuerBankCode', label: 'Filing Bank Code', type: 'text', required: true }], validationRules: ['RRN_FOUND', 'CLAIM_WITHIN_90_DAYS'] }
  ],
  dashboards: [
    {
      id: 'DPAY-DASH-001',
      productId: 'prod-digital-pay',
      moduleId: 'DPAY-MOD-001',
      code: 'DPAY-DASH-SWITCH-HEALTH',
      title: 'National Payment Switch Real-Time Telemetry',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Current Switch Throughput', value: '4,280 TPS', trend: 'up', change: 'Peak: 12,500 TPS' },
        { label: 'Switch Success Rate', value: '99.98%', trend: 'up', change: 'Carrier Grade' },
        { label: 'Average Processing Latency', value: '68 Milliseconds', trend: 'down', change: 'Sub-100ms SLA' },
        { label: 'Daily Processed Volume', value: 'UGX 182 Billion', trend: 'up', change: '+14% YoY' }
      ]
    },
    {
      id: 'DPAY-DASH-002',
      productId: 'prod-digital-pay',
      moduleId: 'DPAY-MOD-003',
      code: 'DPAY-DASH-MERCHANTS',
      title: 'Merchant Acquiring Network & POS Fleet Status',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Active Merchant QR Points', value: '84,200 Outlets', trend: 'up', change: '+3,400 This Month' },
        { label: 'Connected Smart Soundboxes', value: '38,500 Devices', trend: 'up', change: '99.2% Online' },
        { label: 'Deployed Android POS Terminals', value: '14,800 POS', trend: 'up', change: 'Zero Hardware Tamper' },
        { label: 'Merchant Acquiring Volume', value: 'UGX 64.5 Billion', trend: 'up', change: 'Retail & Fuel' }
      ]
    },
    {
      id: 'DPAY-DASH-003',
      productId: 'prod-digital-pay',
      moduleId: 'DPAY-MOD-005',
      code: 'DPAY-DASH-CLEARING',
      title: 'T+0 Merchant Settlements & BoU RTGS Clearing',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'T+0 Instant Settled Volume', value: 'UGX 62.1 Billion', trend: 'up', change: 'Hourly Batches' },
        { label: 'Total Interbank Net Position', value: 'UGX 118.4 Billion', trend: 'neutral', change: 'Balanced Netting' },
        { label: 'BoU RTGS Clearing Cycles', value: '4 of 4 Completed', trend: 'up', change: '100% On-Time' },
        { label: 'Total MDR Fee Yield', value: 'UGX 840 Million', trend: 'up', change: 'Interchange Margin' }
      ]
    },
    {
      id: 'DPAY-DASH-004',
      productId: 'prod-digital-pay',
      moduleId: 'DPAY-MOD-007',
      code: 'DPAY-DASH-SECURITY',
      title: 'Real-Time Fraud Radar & Dispute Status',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'AI Fraud Detection Rate', value: '99.4%', trend: 'up', change: 'Sub-50ms Decision' },
        { label: 'Blocked Fraudulent Volume', value: 'UGX 410 Million', trend: 'down', change: 'Prevented Losses' },
        { label: 'Global Blacklisted Identifiers', value: '6,420 Items', trend: 'up', change: 'Shared with Banks' },
        { label: 'Open Dispute Cases', value: '28 Cases', trend: 'down', change: 'Resolved in < 24h' }
      ]
    }
  ],
  reports: [
    { id: 'DPAY-REP-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', code: 'DPAY-REP-SWITCH-DAILY', title: 'National Payment Switch Daily Transaction Summary', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'DPAY-REP-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-002', code: 'DPAY-REP-TELCO-INTEROP', title: 'Cross-Network Telco Interoperability Clearing Report', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'DPAY-REP-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', code: 'DPAY-REP-MERCHANT-SALES', title: 'Merchant QR Acquiring & Soundbox Settlement Statement', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'DPAY-REP-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', code: 'DPAY-REP-TMS-FLEET', title: 'POS Terminal Fleet Audit & Firmware Compliance Register', format: 'TABULAR', exportTypes: ['PDF', 'XLSX'] },
    { id: 'DPAY-REP-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', code: 'DPAY-REP-TAX-WHT', title: 'Merchant Withholding Tax (WHT 6%) Statutory URA Schedule', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'CSV'] },
    { id: 'DPAY-REP-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-006', code: 'DPAY-REP-BOU-RTGS', title: 'Bank of Uganda RTGS Multilateral Clearing Settlement Sheet', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] },
    { id: 'DPAY-REP-007', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', code: 'DPAY-REP-FRAUD-STR', title: 'Financial Intelligence Authority (FIA) Suspicious Activity (STR) Log', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] },
    { id: 'DPAY-REP-008', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', code: 'DPAY-REP-DISPUTES-LOG', title: 'Interbank Dispute Arbitration & Chargeback Log', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] }
  ],
  workflows: [
    { id: 'DPAY-WF-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', code: 'DPAY-WF-SWITCH', title: 'ISO 20022 Switching & Routing Workflow', stages: ['Message Parse', 'Fraud Scoring', 'Rail Authorization', 'Ack Delivery'], slaHours: 1, requiredApprovers: ['NOC_SWITCH_CONTROLLER'], initialState: 'Message Parse' },
    { id: 'DPAY-WF-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-002', code: 'DPAY-WF-TELCO', title: 'Cross-Telco Wallet Interoperability Flow', stages: ['Source Wallet Debit', 'Switch Escrow Hold', 'Dest Wallet Credit', 'Confirmation SMS'], slaHours: 1, requiredApprovers: ['TELCO_GATEWAY_ENGINEER'], initialState: 'Source Wallet Debit' },
    { id: 'DPAY-WF-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', code: 'DPAY-WF-QR-ACQUIRE', title: 'Merchant QR Acquiring & Voice Alert Flow', stages: ['Customer QR Scan', 'Instant Authorization', 'Soundbox Voice Broadcast', 'Merchant Ledger Update'], slaHours: 1, requiredApprovers: ['MERCHANT_ONBOARDING_LEAD'], initialState: 'Customer QR Scan' },
    { id: 'DPAY-WF-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', code: 'DPAY-WF-TMS-OTA', title: 'POS Terminal Over-the-Air Firmware Update Flow', stages: ['Package Staging', 'Hash Verification', 'Canary Rollout', 'Full Fleet Activation'], slaHours: 24, requiredApprovers: ['TMS_FLEET_CONTROLLER'], initialState: 'Package Staging' },
    { id: 'DPAY-WF-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', code: 'DPAY-WF-SETTLEMENT', title: 'T+0 Instant Merchant Settlement Payout Flow', stages: ['Batch Netting', 'Tax Deduction', 'Dual Authorization', 'Bank EFT Transfer'], slaHours: 2, requiredApprovers: ['SETTLEMENT_OFFICER', 'CHIEF_CLEARING_OFFICER'], initialState: 'Batch Netting' },
    { id: 'DPAY-WF-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-006', code: 'DPAY-WF-RTGS', title: 'Bank of Uganda RTGS Clearing Window Flow', stages: ['Cutoff Trigger', 'Multilateral Netting', 'BoU RTGS Posting', 'Participant Confirmation'], slaHours: 1, requiredApprovers: ['RTGS_CLEARING_OFFICER'], initialState: 'Cutoff Trigger' },
    { id: 'DPAY-WF-007', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', code: 'DPAY-WF-FRAUD-ALERT', title: 'Real-Time Fraud Investigation Flow', stages: ['Anomaly Flagging', 'Automated Hold', 'Analyst Review', 'Blacklist Enrollment'], slaHours: 1, requiredApprovers: ['FRAUD_ANALYST'], initialState: 'Anomaly Flagging' },
    { id: 'DPAY-WF-008', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', code: 'DPAY-WF-DISPUTE', title: 'Chargeback Arbitration & Resolution Flow', stages: ['Dispute Ingest', 'Merchant Evidence Window', 'Arbitration Ruling', 'Fund Adjustment'], slaHours: 72, requiredApprovers: ['DISPUTE_ARBITRATOR'], initialState: 'Dispute Ingest' }
  ],
  databaseEntities: [
    { id: 'DPAY-DB-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', tableName: 'dpay_switch_transactions', primaryKey: 'rrn', fields: [{ name: 'rrn', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'DPAY-DB-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-002', tableName: 'dpay_telco_interop_logs', primaryKey: 'log_id', fields: [{ name: 'log_id', type: 'VARCHAR(64)', required: true }, { name: 'source_telco', type: 'VARCHAR(32)', required: true }, { name: 'dest_telco', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'DPAY-DB-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', tableName: 'dpay_merchants', primaryKey: 'merchant_id', fields: [{ name: 'merchant_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'business_name', type: 'VARCHAR(128)', required: true }, { name: 'tin', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'DPAY-DB-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', tableName: 'dpay_pos_terminals', primaryKey: 'terminal_id', fields: [{ name: 'terminal_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'merchant_id', type: 'VARCHAR(64)', required: true }, { name: 'tamper_state', type: 'VARCHAR(16)', required: true }], auditLogged: true },
    { id: 'DPAY-DB-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', tableName: 'dpay_settlement_batches', primaryKey: 'batch_id', fields: [{ name: 'batch_id', type: 'VARCHAR(64)', required: true }, { name: 'total_amount', type: 'DECIMAL(18,2)', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'DPAY-DB-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-006', tableName: 'dpay_rtgs_clearing_records', primaryKey: 'record_id', fields: [{ name: 'record_id', type: 'VARCHAR(64)', required: true }, { name: 'bou_batch_ref', type: 'VARCHAR(64)', required: true }, { name: 'net_settled', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'DPAY-DB-007', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', tableName: 'dpay_fraud_incidents', primaryKey: 'incident_id', fields: [{ name: 'incident_id', type: 'VARCHAR(64)', required: true }, { name: 'rrn', type: 'VARCHAR(64)', required: true }, { name: 'risk_score', type: 'INT', required: true }], auditLogged: true },
    { id: 'DPAY-DB-008', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', tableName: 'dpay_dispute_cases', primaryKey: 'case_id', fields: [{ name: 'case_id', type: 'VARCHAR(64)', required: true }, { name: 'rrn', type: 'VARCHAR(64)', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'DPAY-API-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', code: 'DPAY_API_SWITCH', method: 'POST', endpoint: '/api/v1/switch/iso20022/route', requiredPermission: 'DPAY-PERM-001', handlerName: 'routeSwitchMessageHandler', summary: 'Route ISO 20022 payment' },
    { id: 'DPAY-API-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-002', code: 'DPAY_API_TELCO', method: 'POST', endpoint: '/api/v1/switch/telco/interop', requiredPermission: 'DPAY-PERM-002', handlerName: 'crossTelcoTransferHandler', summary: 'Execute cross-telco transfer' },
    { id: 'DPAY-API-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', code: 'DPAY_API_QR', method: 'POST', endpoint: '/api/v1/switch/merchant/qr/generate', requiredPermission: 'DPAY-PERM-003', handlerName: 'generateMerchantQrHandler', summary: 'Generate dynamic EMV QR' },
    { id: 'DPAY-API-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', code: 'DPAY_API_TMS', method: 'POST', endpoint: '/api/v1/switch/tms/provision', requiredPermission: 'DPAY-PERM-004', handlerName: 'provisionPosHandler', summary: 'Provision POS terminal' },
    { id: 'DPAY-API-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', code: 'DPAY_API_SETTLEMENT', method: 'POST', endpoint: '/api/v1/switch/settlement/payout', requiredPermission: 'DPAY-PERM-005', handlerName: 'executePayoutHandler', summary: 'Execute instant merchant payout' },
    { id: 'DPAY-API-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-006', code: 'DPAY_API_RTGS', method: 'POST', endpoint: '/api/v1/switch/clearing/rtgs', requiredPermission: 'DPAY-PERM-006', handlerName: 'postRtgsClearingHandler', summary: 'Post netting file to BoU RTGS' },
    { id: 'DPAY-API-007', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', code: 'DPAY_API_FRAUD', method: 'POST', endpoint: '/api/v1/switch/fraud/score', requiredPermission: 'DPAY-PERM-007', handlerName: 'scoreFraudRiskHandler', summary: 'Real-time fraud evaluation' },
    { id: 'DPAY-API-008', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', code: 'DPAY_API_DISPUTES', method: 'POST', endpoint: '/api/v1/switch/disputes/chargeback', requiredPermission: 'DPAY-PERM-008', handlerName: 'fileChargebackHandler', summary: 'Submit dispute chargeback claim' }
  ],
  runtimeComponents: [
    { id: 'DPAY-RTC-001', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-001', componentKey: 'DigitalPaySwitchRouterEngine', name: 'ISO 20022 High-Throughput Switching Engine', description: 'Universal transaction router and live TPS telemetry monitor.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SWITCH_ENGINE' },
    { id: 'DPAY-RTC-002', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-002', componentKey: 'DigitalPayTelcoBridgeEngine', name: 'Cross-Network Telco Interoperability Bridge', description: 'MTN & Airtel MoMo bridge and unified name lookup tool.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'TELCO_BRIDGE' },
    { id: 'DPAY-RTC-003', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-003', componentKey: 'DigitalPayMerchantQrEngine', name: 'National EMV QR Acquiring & Soundbox Engine', description: 'Dynamic QR generator and IoT soundbox voice broadcast simulator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MERCHANT_ACQUIRING' },
    { id: 'DPAY-RTC-004', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-004', componentKey: 'DigitalPayTmsFleetEngine', name: 'Smart Android POS Terminal Fleet Console', description: 'Remote terminal provisioning, key injection, and tamper detection.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'TERMINAL_MANAGEMENT' },
    { id: 'DPAY-RTC-005', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-005', componentKey: 'DigitalPayMerchantSettleEngine', name: 'T+0 Instant Merchant Settlement Engine', description: 'Net payout calculator, WHT tax deduction, and bank transfer pusher.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SETTLEMENT' },
    { id: 'DPAY-RTC-006', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-006', componentKey: 'DigitalPayRtgsClearingEngine', name: 'Multilateral Interchange & BoU RTGS Engine', description: 'Interbank netting matrix and BoU clearing window generator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CLEARING' },
    { id: 'DPAY-RTC-007', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-007', componentKey: 'DigitalPayFraudRadarEngine', name: 'Real-Time Fraud Radar & AML Scoring Engine', description: 'Sub-50ms AI fraud scoring and global blacklist management.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FRAUD_PREVENTION' },
    { id: 'DPAY-RTC-008', productId: 'prod-digital-pay', moduleId: 'DPAY-MOD-008', componentKey: 'DigitalPayDisputeEngine', name: 'Chargeback Lifecycle & Dispute Arbitration Engine', description: 'Interbank chargeback tracker and arbitration ruling console.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'DISPUTE_RESOLUTION' }
  ],
  permissions: [
    { id: 'DPAY-PERM-001', productId: 'prod-digital-pay', code: 'digitalpay:switch:route', name: 'Switch Message Routing Access', description: 'Authority to route and monitor ISO 20022 payments' },
    { id: 'DPAY-PERM-002', productId: 'prod-digital-pay', code: 'digitalpay:telco:bridge', name: 'Cross-Telco Gateway Access', description: 'Authority to bridge mobile money networks' },
    { id: 'DPAY-PERM-003', productId: 'prod-digital-pay', code: 'digitalpay:qr:acquire', name: 'Merchant QR Network Access', description: 'Authority to onboard merchants and generate dynamic QRs' },
    { id: 'DPAY-PERM-004', productId: 'prod-digital-pay', code: 'digitalpay:tms:fleet', name: 'TMS POS Fleet Management', description: 'Authority to provision and wipe POS terminals' },
    { id: 'DPAY-PERM-005', productId: 'prod-digital-pay', code: 'digitalpay:settle:merchants', name: 'Merchant Settlement Authority', description: 'Authority to disburse T+0 merchant payouts' },
    { id: 'DPAY-PERM-006', productId: 'prod-digital-pay', code: 'digitalpay:clearing:rtgs', name: 'BoU RTGS Clearing Authority', description: 'Authority to submit multilateral netting files to Central Bank' },
    { id: 'DPAY-PERM-007', productId: 'prod-digital-pay', code: 'digitalpay:fraud:radar', name: 'Real-Time Fraud Radar Access', description: 'Authority to configure risk models and blacklist bad actors' },
    { id: 'DPAY-PERM-008', productId: 'prod-digital-pay', code: 'digitalpay:disputes:arbitrate', name: 'Dispute Arbitration Authority', description: 'Authority to rule on interbank chargebacks' }
  ],
  roles: [
    { id: 'DPAY-ROLE-001', productId: 'prod-digital-pay', code: 'NATIONAL_SWITCH_GOVERNOR', name: 'National Payment Switch Governor', tier: 'GOVERNANCE', permissionIds: ['DPAY-PERM-001', 'DPAY-PERM-003', 'DPAY-PERM-005', 'DPAY-PERM-006', 'DPAY-PERM-007'] },
    { id: 'DPAY-ROLE-002', productId: 'prod-digital-pay', code: 'CHIEF_RISK_OFFICER', name: 'Chief Risk & Compliance Officer', tier: 'EXECUTIVE', permissionIds: ['DPAY-PERM-007', 'DPAY-PERM-008'] },
    { id: 'DPAY-ROLE-003', productId: 'prod-digital-pay', code: 'NOC_SWITCH_ENGINEER', name: 'Switch NOC Operations Engineer', tier: 'OPERATIONAL', permissionIds: ['DPAY-PERM-001', 'DPAY-PERM-002', 'DPAY-PERM-004'] },
    { id: 'DPAY-ROLE-004', productId: 'prod-digital-pay', code: 'SETTLEMENT_OFFICER', name: 'Merchant Settlement & RTGS Officer', tier: 'OPERATIONAL', permissionIds: ['DPAY-PERM-005', 'DPAY-PERM-006'] },
    { id: 'DPAY-ROLE-005', productId: 'prod-digital-pay', code: 'MERCHANT_OWNER_USER', name: 'Retail Merchant Owner', tier: 'CLIENT', permissionIds: [] }
  ]
};
