import { CanonicalProductHierarchy } from './types';

export const FAAP_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-faap',
    code: 'FAAP',
    name: 'JUMO FAAP Financial Asset Automation Platform',
    category: 'FINANCIAL_ENGINE',
    description: 'Enterprise asset-backed tokenization, sovereign yield curves, structured automated liquidity pools, fractionalized treasury bills, automated secondary market settlement, and regulatory escrow.',
    version: '2026.4.0',
    iconName: 'Coins',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Chief Investment Officer / Sovereign Asset Manager',
    governingLegislation: 'Capital Markets Authority (CMA) Regulatory Sandbox & Securities Act 2026',
    directorateIds: ['FAAP-DIR-001', 'FAAP-DIR-002', 'FAAP-DIR-003', 'FAAP-DIR-004']
  },
  directorates: [
    { id: 'FAAP-DIR-001', productId: 'prod-faap', code: 'FAAP-DIR-ISSUANCE', name: 'Directorate of Sovereign Debt & Asset Tokenization', description: 'Fractionalization of Treasury Bills, infrastructure bonds, and institutional commercial paper.', leadRole: 'DIRECTOR_DEBT_ISSUANCE', departmentIds: ['FAAP-DEPT-001', 'FAAP-DEPT-002'] },
    { id: 'FAAP-DIR-002', productId: 'prod-faap', code: 'FAAP-DIR-MARKETS', name: 'Directorate of Secondary Trading & Liquidity Pools', description: 'Automated Market Maker (AMM) yield pools, continuous order matching, and zero-slippage rebalancing.', leadRole: 'HEAD_MARKET_OPERATIONS', departmentIds: ['FAAP-DEPT-003', 'FAAP-DEPT-004'] },
    { id: 'FAAP-DIR-003', productId: 'prod-faap', code: 'FAAP-DIR-CUSTODY', name: 'Directorate of Cryptographic Custody & Escrow Registry', description: 'Multi-party computation (MPC) cold storage, Bank of Uganda central depository linkage, and smart contract escrow.', leadRole: 'CHIEF_CUSTODIAN', departmentIds: ['FAAP-DEPT-005', 'FAAP-DEPT-006'] },
    { id: 'FAAP-DIR-004', productId: 'prod-faap', code: 'FAAP-DIR-COMPLIANCE', name: 'Directorate of Capital Markets Surveillance & CMA Sandbox', description: 'Real-time wash trading detection, investor accreditation vetting, and statutory CMA filings.', leadRole: 'CHIEF_COMPLIANCE_OFFICER', departmentIds: ['FAAP-DEPT-007', 'FAAP-DEPT-008'] }
  ],
  departments: [
    { id: 'FAAP-DEPT-001', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', code: 'FAAP-DEPT-TBILLS', name: 'Department of Fractional Treasury Bill Origination', description: 'Packages 91-day, 182-day, and 364-day sovereign bills into UGX 10,000 fractional micro-units.', headRole: 'HEAD_TBILL_ORIGINATION', officeIds: ['FAAP-OFF-001'] },
    { id: 'FAAP-DEPT-002', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', code: 'FAAP-DEPT-INFRA-BONDS', name: 'Department of Green & Infrastructure Bond Securitization', description: 'Structured debt financing for public roads, solar grids, and municipal water utilities.', headRole: 'HEAD_SECURITIZATION', officeIds: ['FAAP-OFF-002'] },
    { id: 'FAAP-DEPT-003', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', code: 'FAAP-DEPT-AMM-POOLS', name: 'Department of Liquidity Pool Smart Contracts', description: 'Constant product automated market maker pools maintaining daily liquidity for retail investors.', headRole: 'HEAD_AMM_ALGORITHMS', officeIds: ['FAAP-OFF-003'] },
    { id: 'FAAP-DEPT-004', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', code: 'FAAP-DEPT-ORDER-BOOK', name: 'Department of Institutional High-Frequency Matcher', description: 'Sub-millisecond matching engine for commercial banks and primary dealers.', headRole: 'HEAD_EXCHANGE_ENGINE', officeIds: ['FAAP-OFF-004'] },
    { id: 'FAAP-DEPT-005', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', code: 'FAAP-DEPT-MPC-VAULT', name: 'Department of Multi-Sig Custody & Central Depository', description: 'Hardware security module (HSM) key shards and Bank of Uganda CSD reconciliation.', headRole: 'HEAD_SECURE_CUSTODY', officeIds: ['FAAP-OFF-005'] },
    { id: 'FAAP-DEPT-006', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', code: 'FAAP-DEPT-ESCROW', name: 'Department of Automated Coupon & Maturity Settlement', description: 'Smart contract automated dividend and coupon distribution directly to investor wallets.', headRole: 'HEAD_SETTLEMENT_ESCROW', officeIds: ['FAAP-OFF-006'] },
    { id: 'FAAP-DEPT-007', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', code: 'FAAP-DEPT-SURVEILLANCE', name: 'Department of Algorithmic Market Surveillance', description: 'AI-driven anomalous order book behavior and insider trading pattern detection.', headRole: 'HEAD_MARKET_SURVEILLANCE', officeIds: ['FAAP-OFF-007'] },
    { id: 'FAAP-DEPT-008', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', code: 'FAAP-DEPT-ACCREDITATION', name: 'Department of Investor Classification & Risk Disclosures', description: 'Enforces retail investor caps and qualifies high-net-worth institutional participants.', headRole: 'HEAD_INVESTOR_GOVERNANCE', officeIds: ['FAAP-OFF-008'] }
  ],
  offices: [
    { id: 'FAAP-OFF-001', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-001', code: 'FAAP-OFF-TBILL-DESK', name: 'Treasury Bill Tokenization Desk', description: 'Primary auction bidding and micro-unit fractional minting.', officerRole: 'TBILL_PORTFOLIO_MANAGER', portalIds: ['FAAP-PORTAL-001', 'FAAP-PORTAL-002'], moduleIds: ['FAAP-MOD-001'] },
    { id: 'FAAP-OFF-002', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-002', code: 'FAAP-OFF-BOND-DESK', name: 'Green Bond & Structured Notes Desk', description: 'Structuring prospectus, ESG metrics, and coupon rate setting.', officerRole: 'BOND_STRUCTURING_LEAD', portalIds: ['FAAP-PORTAL-001'], moduleIds: ['FAAP-MOD-002'] },
    { id: 'FAAP-OFF-003', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-003', code: 'FAAP-OFF-AMM-DESK', name: 'Liquidity Pool Rebalancing Desk', description: 'Managing yield spreads, liquidity provider (LP) rewards, and impermanent loss buffers.', officerRole: 'AMM_OPERATIONS_LEAD', portalIds: ['FAAP-PORTAL-001', 'FAAP-PORTAL-002'], moduleIds: ['FAAP-MOD-003'] },
    { id: 'FAAP-OFF-004', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-004', code: 'FAAP-OFF-MATCHING-DESK', name: 'Secondary Market Exchange Desk', description: 'Real-time order book execution and primary dealer quotes.', officerRole: 'CHIEF_EXCHANGE_TRADER', portalIds: ['FAAP-PORTAL-001', 'FAAP-PORTAL-002'], moduleIds: ['FAAP-MOD-004'] },
    { id: 'FAAP-OFF-005', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-005', code: 'FAAP-OFF-MPC-DESK', name: 'HSM Multi-Signature Security Desk', description: 'Key rotation ceremonies and cold wallet reserve audits.', officerRole: 'MPC_SECURITY_ENGINEER', portalIds: ['FAAP-PORTAL-001'], moduleIds: ['FAAP-MOD-005'] },
    { id: 'FAAP-OFF-006', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-006', code: 'FAAP-OFF-COUPON-DESK', name: 'Automated Coupon Payout Desk', description: 'Daily interest and maturity principal distributions via instant payment rails.', officerRole: 'COUPON_SETTLEMENT_OFFICER', portalIds: ['FAAP-PORTAL-001', 'FAAP-PORTAL-003'], moduleIds: ['FAAP-MOD-006'] },
    { id: 'FAAP-OFF-007', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-007', code: 'FAAP-OFF-SURVEILLANCE-DESK', name: 'Market Surveillance & Anti-Manipulation Desk', description: 'Monitoring order spikes, quote stuffing, and volume abnormalities.', officerRole: 'SURVEILLANCE_ANALYST', portalIds: ['FAAP-PORTAL-001'], moduleIds: ['FAAP-MOD-007'] },
    { id: 'FAAP-OFF-008', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-008', code: 'FAAP-OFF-CMA-DESK', name: 'CMA Sandbox & Investor Compliance Desk', description: 'Regulatory quarterly filings and investor suitability testing.', officerRole: 'REGULATORY_LIAISON', portalIds: ['FAAP-PORTAL-001'], moduleIds: ['FAAP-MOD-008'] }
  ],
  portals: [
    { id: 'FAAP-PORTAL-001', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-001', officeId: 'FAAP-OFF-001', code: 'FAAP-PORTAL-INSTITUTIONAL', name: 'Institutional Asset Manager & Primary Dealer Portal', description: 'High-volume bond subscription, AMM liquidity provisioning, and CSD clearing.', targetRole: 'CHIEF_INVESTMENT_OFFICER', authLevel: 'PKI_SOVEREIGN', route: '/faap/institutional', moduleIds: ['FAAP-MOD-001', 'FAAP-MOD-002', 'FAAP-MOD-003', 'FAAP-MOD-004', 'FAAP-MOD-005', 'FAAP-MOD-007'] },
    { id: 'FAAP-PORTAL-002', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-003', officeId: 'FAAP-OFF-003', code: 'FAAP-PORTAL-TRADING', name: 'Secondary Market Trading & Order Desk', description: 'Live order book, depth charts, liquidity pools, and position management.', targetRole: 'MARKET_TRADER', authLevel: 'STAFF', route: '/faap/trading', moduleIds: ['FAAP-MOD-003', 'FAAP-MOD-004', 'FAAP-MOD-006'] },
    { id: 'FAAP-PORTAL-003', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-006', officeId: 'FAAP-OFF-006', code: 'FAAP-PORTAL-RETAIL', name: 'Retail Micro-Investor Yield Dashboard', description: 'Earn 12-16% annualized sovereign yield with UGX 10,000 micro-investments.', targetRole: 'RETAIL_INVESTOR', authLevel: 'PUBLIC', route: '/faap/yield', moduleIds: ['FAAP-MOD-001', 'FAAP-MOD-006'] }
  ],
  modules: [
    { id: 'FAAP-MOD-001', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-001', officeId: 'FAAP-OFF-001', portalId: 'FAAP-PORTAL-001', code: 'FAAP-MOD-TBILL-MINT', name: 'Fractional Treasury Bill Securitization Engine', description: 'Primary auction allocation, smart contract minting, and micro-unit denomination.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-001', 'FAAP-CAP-002'], screenIds: ['FAAP-SCR-001'], formIds: ['FAAP-FORM-001'], dashboardIds: ['FAAP-DASH-001'], reportIds: ['FAAP-REP-001'], workflowIds: ['FAAP-WF-001'], databaseEntityIds: ['FAAP-DB-001'], apiIds: ['FAAP-API-001'], runtimeComponentId: 'FAAP-RTC-001', permissionIds: ['FAAP-PERM-001'] },
    { id: 'FAAP-MOD-002', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-002', officeId: 'FAAP-OFF-002', portalId: 'FAAP-PORTAL-001', code: 'FAAP-MOD-INFRA-BONDS', name: 'Infrastructure Bond & Real Estate Tokenizer', description: 'Asset appraisal, prospectus anchoring, and fractional equity/debt issuance.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-003', 'FAAP-CAP-004'], screenIds: ['FAAP-SCR-002'], formIds: ['FAAP-FORM-002'], dashboardIds: ['FAAP-DASH-001'], reportIds: ['FAAP-REP-002'], workflowIds: ['FAAP-WF-002'], databaseEntityIds: ['FAAP-DB-002'], apiIds: ['FAAP-API-002'], runtimeComponentId: 'FAAP-RTC-002', permissionIds: ['FAAP-PERM-002'] },
    { id: 'FAAP-MOD-003', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-003', officeId: 'FAAP-OFF-003', portalId: 'FAAP-PORTAL-002', code: 'FAAP-MOD-AMM-POOLS', name: 'Automated Market Maker Yield & Liquidity Pools', description: 'Algorithmic bonding curves, 24/7 instant cash-out liquidity, and LP fee shares.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-005', 'FAAP-CAP-006'], screenIds: ['FAAP-SCR-003'], formIds: ['FAAP-FORM-003'], dashboardIds: ['FAAP-DASH-002'], reportIds: ['FAAP-REP-003'], workflowIds: ['FAAP-WF-003'], databaseEntityIds: ['FAAP-DB-003'], apiIds: ['FAAP-API-003'], runtimeComponentId: 'FAAP-RTC-003', permissionIds: ['FAAP-PERM-003'] },
    { id: 'FAAP-MOD-004', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-004', officeId: 'FAAP-OFF-004', portalId: 'FAAP-PORTAL-002', code: 'FAAP-MOD-ORDER-BOOK', name: 'Institutional Continuous Order Book & Trading Engine', description: 'Central limit order book (CLOB), depth charts, limit/market orders, and trade tape.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-007', 'FAAP-CAP-008'], screenIds: ['FAAP-SCR-004'], formIds: ['FAAP-FORM-004'], dashboardIds: ['FAAP-DASH-002'], reportIds: ['FAAP-REP-004'], workflowIds: ['FAAP-WF-004'], databaseEntityIds: ['FAAP-DB-004'], apiIds: ['FAAP-API-004'], runtimeComponentId: 'FAAP-RTC-004', permissionIds: ['FAAP-PERM-004'] },
    { id: 'FAAP-MOD-005', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-005', officeId: 'FAAP-OFF-005', portalId: 'FAAP-PORTAL-001', code: 'FAAP-MOD-MPC-CUSTODY', name: 'Multi-Party Computation HSM Custody Vault', description: 'Threshold cryptography, key sharding across sovereign entities, and BoU CSD sync.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-009', 'FAAP-CAP-010'], screenIds: ['FAAP-SCR-005'], formIds: [], dashboardIds: ['FAAP-DASH-003'], reportIds: ['FAAP-REP-005'], workflowIds: ['FAAP-WF-005'], databaseEntityIds: ['FAAP-DB-005'], apiIds: ['FAAP-API-005'], runtimeComponentId: 'FAAP-RTC-005', permissionIds: ['FAAP-PERM-005'] },
    { id: 'FAAP-MOD-006', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-006', officeId: 'FAAP-OFF-006', portalId: 'FAAP-PORTAL-003', code: 'FAAP-MOD-COUPON-SETTLE', name: 'Automated Smart Contract Coupon & Maturity Settler', description: 'Daily interest yield compounding and automated redemption to mobile money.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-011', 'FAAP-CAP-012'], screenIds: ['FAAP-SCR-006'], formIds: ['FAAP-FORM-005'], dashboardIds: ['FAAP-DASH-003'], reportIds: ['FAAP-REP-006'], workflowIds: ['FAAP-WF-006'], databaseEntityIds: ['FAAP-DB-006'], apiIds: ['FAAP-API-006'], runtimeComponentId: 'FAAP-RTC-006', permissionIds: ['FAAP-PERM-006'] },
    { id: 'FAAP-MOD-007', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-007', officeId: 'FAAP-OFF-007', portalId: 'FAAP-PORTAL-001', code: 'FAAP-MOD-SURVEILLANCE', name: 'Market Integrity & Surveillance Radar', description: 'Real-time wash trading detection, spoofing alerts, and volume volatility bounds.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-013', 'FAAP-CAP-014'], screenIds: ['FAAP-SCR-007'], formIds: [], dashboardIds: ['FAAP-DASH-004'], reportIds: ['FAAP-REP-007'], workflowIds: ['FAAP-WF-007'], databaseEntityIds: ['FAAP-DB-007'], apiIds: ['FAAP-API-007'], runtimeComponentId: 'FAAP-RTC-007', permissionIds: ['FAAP-PERM-007'] },
    { id: 'FAAP-MOD-008', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-008', officeId: 'FAAP-OFF-008', portalId: 'FAAP-PORTAL-001', code: 'FAAP-MOD-CMA-COMPLIANCE', name: 'CMA Sandbox Reporting & Investor Accreditation', description: 'Capital Markets Authority compliance filings and investor suitability governance.', status: 'ACTIVE_CORE', capabilityIds: ['FAAP-CAP-015', 'FAAP-CAP-016'], screenIds: ['FAAP-SCR-008'], formIds: ['FAAP-FORM-006'], dashboardIds: ['FAAP-DASH-004'], reportIds: ['FAAP-REP-008'], workflowIds: ['FAAP-WF-008'], databaseEntityIds: ['FAAP-DB-008'], apiIds: ['FAAP-API-008'], runtimeComponentId: 'FAAP-RTC-008', permissionIds: ['FAAP-PERM-008'] }
  ],
  capabilities: [
    { id: 'FAAP-CAP-001', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-001', officeId: 'FAAP-OFF-001', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-001', code: 'FAAP_CAP_MINT_TBILL_TOKENS', name: 'Mint Fractional Treasury Bill Units', description: 'Ingests Primary Auction ISIN and mints cryptographic asset units backed 1:1 by sovereign debt.', serviceAction: 'faap.issuance.mintTbillUnits', requiredPermission: 'FAAP-PERM-001', runtimeComponentId: 'FAAP-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-002', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-001', officeId: 'FAAP-OFF-001', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-001', code: 'FAAP_CAP_CALCULATE_YIELD_CURVE', name: 'Publish Sovereign Benchmark Yield Curve', description: 'Interpolates real-time yields across 91d, 182d, 364d, 2y, 5y, 10y, 15y, 20y tenors.', serviceAction: 'faap.issuance.publishYieldCurve', requiredPermission: 'FAAP-PERM-001', runtimeComponentId: 'FAAP-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-003', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-002', officeId: 'FAAP-OFF-002', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-002', code: 'FAAP_CAP_SECURITIZE_GREEN_BOND', name: 'Structure Green Infrastructure Bond', description: 'Anchors audited solar/water revenue cash flows to smart contract bond covenants.', serviceAction: 'faap.bonds.securitizeAsset', requiredPermission: 'FAAP-PERM-002', runtimeComponentId: 'FAAP-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-004', productId: 'prod-faap', directorateId: 'FAAP-DIR-001', departmentId: 'FAAP-DEPT-002', officeId: 'FAAP-OFF-002', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-002', code: 'FAAP_CAP_AUDIT_ESG_IMPACT', name: 'Verify ESG Impact Telemetry', description: 'Ingests IoT sensor data from funded solar grids to verify carbon credit offsets.', serviceAction: 'faap.bonds.auditEsgTelemetry', requiredPermission: 'FAAP-PERM-002', runtimeComponentId: 'FAAP-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-005', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-003', officeId: 'FAAP-OFF-003', portalId: 'FAAP-PORTAL-002', moduleId: 'FAAP-MOD-003', code: 'FAAP_CAP_PROVIDE_LP_LIQUIDITY', name: 'Deposit Capital in Sovereign Liquidity Pool', description: 'Supplies UGX liquidity to earn pro-rata share of trading fees and sovereign yield.', serviceAction: 'faap.amm.provideLiquidity', requiredPermission: 'FAAP-PERM-003', runtimeComponentId: 'FAAP-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-006', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-003', officeId: 'FAAP-OFF-003', portalId: 'FAAP-PORTAL-002', moduleId: 'FAAP-MOD-003', code: 'FAAP_CAP_EXECUTE_SWAP', name: 'Execute Instant Zero-Slippage Bond Swap', description: 'Swaps cash for fractional bonds instantly against constant-product bonding pool.', serviceAction: 'faap.amm.executeSwap', requiredPermission: 'FAAP-PERM-003', runtimeComponentId: 'FAAP-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-007', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-004', officeId: 'FAAP-OFF-004', portalId: 'FAAP-PORTAL-002', moduleId: 'FAAP-MOD-004', code: 'FAAP_CAP_PLACE_LIMIT_ORDER', name: 'Submit Limit / Market Order to CLOB', description: 'Enters bid/ask order into central high-frequency matching engine.', serviceAction: 'faap.trading.placeOrder', requiredPermission: 'FAAP-PERM-004', runtimeComponentId: 'FAAP-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-008', productId: 'prod-faap', directorateId: 'FAAP-DIR-002', departmentId: 'FAAP-DEPT-004', officeId: 'FAAP-OFF-004', portalId: 'FAAP-PORTAL-002', moduleId: 'FAAP-MOD-004', code: 'FAAP_CAP_CANCEL_ORDER', name: 'Cancel Open Unfilled Exchange Order', description: 'Removes quote from order book and releases locked account balance.', serviceAction: 'faap.trading.cancelOrder', requiredPermission: 'FAAP-PERM-004', runtimeComponentId: 'FAAP-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-009', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-005', officeId: 'FAAP-OFF-005', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-005', code: 'FAAP_CAP_RECONCILE_BOU_CSD', name: 'Reconcile Bank of Uganda Central Securities Depository', description: 'Performs daily cryptographic proof-of-reserve reconciliation with BoU CSD.', serviceAction: 'faap.custody.reconcileCsd', requiredPermission: 'FAAP-PERM-005', runtimeComponentId: 'FAAP-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-010', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-005', officeId: 'FAAP-OFF-005', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-005', code: 'FAAP_CAP_ROTATE_MPC_KEYS', name: 'Execute MPC Key Resharing Protocol', description: 'Rotates cold-storage key shards without changing underlying institutional address.', serviceAction: 'faap.custody.rotateMpcKeys', requiredPermission: 'FAAP-PERM-005', runtimeComponentId: 'FAAP-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-011', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-006', officeId: 'FAAP-OFF-006', portalId: 'FAAP-PORTAL-003', moduleId: 'FAAP-MOD-006', code: 'FAAP_CAP_EXECUTE_COUPON_DISTRIBUTION', name: 'Execute Automated Coupon Payment', description: 'Triggers smart contract payment of interest directly into investor wallets.', serviceAction: 'faap.settlement.distributeCoupons', requiredPermission: 'FAAP-PERM-006', runtimeComponentId: 'FAAP-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-012', productId: 'prod-faap', directorateId: 'FAAP-DIR-003', departmentId: 'FAAP-DEPT-006', officeId: 'FAAP-OFF-006', portalId: 'FAAP-PORTAL-003', moduleId: 'FAAP-MOD-006', code: 'FAAP_CAP_REDEEM_PRINCIPAL_MATURITY', name: 'Redeem Sovereign Debt Principal on Maturity', description: 'Burns matured token units and returns full face value capital to investors.', serviceAction: 'faap.settlement.redeemPrincipal', requiredPermission: 'FAAP-PERM-006', runtimeComponentId: 'FAAP-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-013', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-007', officeId: 'FAAP-OFF-007', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-007', code: 'FAAP_CAP_DETECT_WASH_TRADING', name: 'Algorithmic Wash Trading & Spoofing Radar', description: 'Identifies circular trading between affiliated addresses to artificially inflate volume.', serviceAction: 'faap.surveillance.detectWashTrading', requiredPermission: 'FAAP-PERM-007', runtimeComponentId: 'FAAP-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-014', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-007', officeId: 'FAAP-OFF-007', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-007', code: 'FAAP_CAP_ENFORCE_CIRCUIT_BREAKER', name: 'Trigger Exchange Trading Circuit Breaker', description: 'Halts trading automatically if asset price moves more than +/- 5% within 10 minutes.', serviceAction: 'faap.surveillance.triggerCircuitBreaker', requiredPermission: 'FAAP-PERM-007', runtimeComponentId: 'FAAP-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-015', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-008', officeId: 'FAAP-OFF-008', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-008', code: 'FAAP_CAP_GENERATE_CMA_SANDBOX_RETURN', name: 'Compile Quarterly CMA Regulatory Filing', description: 'Generates automated compliance report covering investor protection and capital reserves.', serviceAction: 'faap.compliance.generateCmaFiling', requiredPermission: 'FAAP-PERM-008', runtimeComponentId: 'FAAP-RTC-008', status: 'ACTIVE_CORE' },
    { id: 'FAAP-CAP-016', productId: 'prod-faap', directorateId: 'FAAP-DIR-004', departmentId: 'FAAP-DEPT-008', officeId: 'FAAP-OFF-008', portalId: 'FAAP-PORTAL-001', moduleId: 'FAAP-MOD-008', code: 'FAAP_CAP_VERIFY_INVESTOR_ACCREDITATION', name: 'Verify Investor Tier & Investment Limits', description: 'Enforces statutory maximum exposure limits on retail vs accredited investors.', serviceAction: 'faap.compliance.verifyAccreditation', requiredPermission: 'FAAP-PERM-008', runtimeComponentId: 'FAAP-RTC-008', status: 'ACTIVE_CORE' }
  ],
  screens: [
    { id: 'FAAP-SCR-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', code: 'FAAP-SCR-TBILLS', title: 'Fractional Treasury Bill Primary Minting', description: 'Sovereign issuance and fractional units.', viewType: 'TABLE', route: '/faap/tbills' },
    { id: 'FAAP-SCR-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', code: 'FAAP-SCR-BONDS', title: 'Green Infrastructure & Corporate Bonds', description: 'Securitized debt offerings and ESG metrics.', viewType: 'TABLE', route: '/faap/bonds' },
    { id: 'FAAP-SCR-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', code: 'FAAP-SCR-AMM', title: 'Automated Market Maker Liquidity Pools', description: 'Bonding curves, TVL, and yield distribution.', viewType: 'DASHBOARD', route: '/faap/pools' },
    { id: 'FAAP-SCR-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', code: 'FAAP-SCR-ORDERBOOK', title: 'Institutional Continuous Exchange & CLOB', description: 'Order book, depth chart, and trade tape.', viewType: 'DASHBOARD', route: '/faap/clob' },
    { id: 'FAAP-SCR-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-005', code: 'FAAP-SCR-CUSTODY', title: 'MPC Multi-Signature Custody Vault & CSD', description: 'HSM key shards and proof of reserves.', viewType: 'DASHBOARD', route: '/faap/custody' },
    { id: 'FAAP-SCR-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', code: 'FAAP-SCR-SETTLEMENT', title: 'Smart Contract Coupon & Maturity Settler', description: 'Daily interest payouts and principal redemption.', viewType: 'TABLE', route: '/faap/settlement' },
    { id: 'FAAP-SCR-007', productId: 'prod-faap', moduleId: 'FAAP-MOD-007', code: 'FAAP-SCR-SURVEILLANCE', title: 'Market Integrity & Surveillance Radar', description: 'Wash trading alerts and circuit breakers.', viewType: 'DASHBOARD', route: '/faap/surveillance' },
    { id: 'FAAP-SCR-008', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', code: 'FAAP-SCR-CMA', title: 'CMA Sandbox & Compliance Governance', description: 'Regulatory returns and accreditation vetting.', viewType: 'TABLE', route: '/faap/compliance' }
  ],
  forms: [
    { id: 'FAAP-FORM-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', code: 'FAAP-FORM-TBILL-MINT', title: 'Treasury Bill Tokenization Minting Order', submitAction: 'faap.issuance.mintTbillUnits', fieldCount: 5, fields: [{ name: 'isinCode', label: 'Primary Market ISIN Code', type: 'text', required: true }, { name: 'auctionDate', label: 'Auction Settlement Date', type: 'date', required: true }, { name: 'faceValueUgx', label: 'Total Face Value (UGX)', type: 'number', required: true }, { name: 'annualYieldRate', label: 'Discount / Yield Rate (%)', type: 'number', required: true }, { name: 'tenorDays', label: 'Tenor (91/182/364 Days)', type: 'number', required: true }], validationRules: ['ISIN_AUTHENTIC', 'YIELD_POSITIVE'] },
    { id: 'FAAP-FORM-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', code: 'FAAP-FORM-BOND-ORIGINATE', title: 'Infrastructure Green Bond Securitization', submitAction: 'faap.bonds.securitizeAsset', fieldCount: 5, fields: [{ name: 'projectTitle', label: 'Project / Asset Title', type: 'text', required: true }, { name: 'totalOfferingUgx', label: 'Total Issuance Size (UGX)', type: 'number', required: true }, { name: 'couponFrequency', label: 'Coupon Frequency (Semi-Annual/Annual)', type: 'select', required: true }, { name: 'fixedCouponRate', label: 'Fixed Coupon Rate (%)', type: 'number', required: true }, { name: 'esgRatingAgency', label: 'ESG Certification Body', type: 'text', required: true }], validationRules: ['PROSPECTUS_APPROVED'] },
    { id: 'FAAP-FORM-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', code: 'FAAP-FORM-LP-DEPOSIT', title: 'Liquidity Pool Capital Provision', submitAction: 'faap.amm.provideLiquidity', fieldCount: 4, fields: [{ name: 'poolId', label: 'Select Target Liquidity Pool', type: 'select', required: true }, { name: 'depositUgx', label: 'UGX Cash Contribution', type: 'number', required: true }, { name: 'assetTokenAmount', label: 'Asset Token Contribution', type: 'number', required: true }, { name: 'slippageTolerance', label: 'Slippage Tolerance (%)', type: 'number', required: true }], validationRules: ['BALANCE_SUFFICIENT'] },
    { id: 'FAAP-FORM-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', code: 'FAAP-FORM-ORDER-ENTRY', title: 'Continuous Exchange Order Entry', submitAction: 'faap.trading.placeOrder', fieldCount: 5, fields: [{ name: 'assetPair', label: 'Trading Pair (e.g. TBILL91D/UGX)', type: 'select', required: true }, { name: 'orderSide', label: 'Order Side (BUY / SELL)', type: 'select', required: true }, { name: 'orderType', label: 'Order Type (LIMIT / MARKET)', type: 'select', required: true }, { name: 'orderQuantity', label: 'Number of Micro-Units', type: 'number', required: true }, { name: 'limitPriceUgx', label: 'Limit Price per Unit (UGX)', type: 'number', required: false }], validationRules: ['INVESTMENT_CAP_CHECK'] },
    { id: 'FAAP-FORM-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', code: 'FAAP-FORM-COUPON-EXEC', title: 'Manual Coupon Distribution Trigger', submitAction: 'faap.settlement.distributeCoupons', fieldCount: 4, fields: [{ name: 'bondSeriesId', label: 'Bond / T-Bill Series ID', type: 'text', required: true }, { name: 'couponPeriod', label: 'Coupon Cycle Period', type: 'text', required: true }, { name: 'totalDisbursementUgx', label: 'Total Payout Amount (UGX)', type: 'number', required: true }, { name: 'escrowSignerPin', label: 'Escrow Keyholder Authorization PIN', type: 'password', required: true }], validationRules: ['ESCROW_FUNDED'] },
    { id: 'FAAP-FORM-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', code: 'FAAP-FORM-ACCREDIT-USER', title: 'Investor Accreditation & Risk Profile', submitAction: 'faap.compliance.verifyAccreditation', fieldCount: 4, fields: [{ name: 'investorNIN', label: 'Investor National ID (NIN)', type: 'text', required: true }, { name: 'netWorthBracket', label: 'Verified Net Worth (UGX)', type: 'select', required: true }, { name: 'investorCategory', label: 'Category (RETAIL / ACCREDITED / INSTITUTIONAL)', type: 'select', required: true }, { name: 'riskAcknowledgement', label: 'Risk Disclosure Acceptance', type: 'checkbox', required: true }], validationRules: ['NIN_VERIFIED'] }
  ],
  dashboards: [
    {
      id: 'FAAP-DASH-001',
      productId: 'prod-faap',
      moduleId: 'FAAP-MOD-001',
      code: 'FAAP-DASH-SECURITIZATION',
      title: 'Sovereign Debt Securitization & Issuance',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Tokenized Assets (AUM)', value: 'UGX 124.5 Billion', trend: 'up', change: '+18.2% MoM' },
        { label: 'Fractional T-Bill Holders', value: '48,200 Citizens', trend: 'up', change: 'Democratized Debt' },
        { label: 'Weighted Average Sovereign Yield', value: '13.85% p.a.', trend: 'up', change: 'Risk-Free' },
        { label: 'Active Green Infrastructure Bonds', value: '6 Projects', trend: 'up', change: '100% ESG Audited' }
      ]
    },
    {
      id: 'FAAP-DASH-002',
      productId: 'prod-faap',
      moduleId: 'FAAP-MOD-003',
      code: 'FAAP-DASH-MARKETS',
      title: 'Secondary Market Trading & AMM Liquidity',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Daily Trading Volume', value: 'UGX 3.4 Billion', trend: 'up', change: 'Liquid Secondary' },
        { label: 'AMM Total Value Locked (TVL)', value: 'UGX 32.8 Billion', trend: 'up', change: 'Zero Slippage' },
        { label: 'CLOB Order Execution Latency', value: '1.2 Milliseconds', trend: 'down', change: 'Ultra-Fast' },
        { label: 'Annualized LP Pool Yield', value: '15.4%', trend: 'up', change: 'Fee + Sovereign Yield' }
      ]
    },
    {
      id: 'FAAP-DASH-003',
      productId: 'prod-faap',
      moduleId: 'FAAP-MOD-005',
      code: 'FAAP-DASH-CUSTODY',
      title: 'MPC HSM Custody & Automated Settlement',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Proof-of-Reserve Ratio', value: '100.00%', trend: 'neutral', change: 'BoU CSD Backed' },
        { label: 'Cumulative Coupons Paid', value: 'UGX 14.8 Billion', trend: 'up', change: 'Zero Default' },
        { label: 'MPC Threshold Nodes', value: '5 of 7 Shards', trend: 'neutral', change: 'Institutional Grade' },
        { label: 'Settlement Finality Time', value: 'Instant (< 3s)', trend: 'down', change: 'Real-Time' }
      ]
    },
    {
      id: 'FAAP-DASH-004',
      productId: 'prod-faap',
      moduleId: 'FAAP-MOD-007',
      code: 'FAAP-DASH-INTEGRITY',
      title: 'Market Integrity Radar & CMA Compliance',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Surveillance Alert Score', value: '0.00 (Clean)', trend: 'neutral', change: 'Zero Manipulation' },
        { label: 'Circuit Breaker Status', value: 'ACTIVE / NORMAL', trend: 'neutral', change: '+/- 5% Guardrails' },
        { label: 'Accredited Institutional Funds', value: '42 Institutions', trend: 'up', change: 'Pension/Insurance' },
        { label: 'CMA Sandbox Filing Status', value: 'COMPLIANT', trend: 'neutral', change: 'Full Transparency' }
      ]
    }
  ],
  reports: [
    { id: 'FAAP-REP-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', code: 'FAAP-REP-TBILL-REGISTRY', title: 'Fractional Treasury Bill Issuance & Holder Register', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'FAAP-REP-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', code: 'FAAP-REP-GREEN-BONDS', title: 'Green Infrastructure Bond Prospectus & ESG Impact Report', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] },
    { id: 'FAAP-REP-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', code: 'FAAP-REP-AMM-LIQUIDITY', title: 'AMM Liquidity Pool TVL & Impermanent Loss Analysis', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'FAAP-REP-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', code: 'FAAP-REP-EXCHANGE-TAPE', title: 'Daily Central Limit Order Book Trade Execution Tape', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'FAAP-REP-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-005', code: 'FAAP-REP-PROOF-OF-RESERVES', title: 'Bank of Uganda CSD Cryptographic Proof-of-Reserve Audit', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] },
    { id: 'FAAP-REP-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', code: 'FAAP-REP-COUPON-DISTRIBUTION', title: 'Automated Coupon Interest & Principal Redemption Ledger', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV'] },
    { id: 'FAAP-REP-007', productId: 'prod-faap', moduleId: 'FAAP-MOD-007', code: 'FAAP-REP-SURVEILLANCE-LOG', title: 'Market Integrity Surveillance & Wash-Trading Audit Log', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] },
    { id: 'FAAP-REP-008', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', code: 'FAAP-REP-CMA-QUARTERLY', title: 'Capital Markets Authority Regulatory Sandbox Quarterly Return', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] }
  ],
  workflows: [
    { id: 'FAAP-WF-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', code: 'FAAP-WF-TBILL-MINT', title: 'Treasury Bill Primary Securitization Flow', stages: ['Primary Auction Win', 'ISIN Verification', 'Smart Contract Minting', 'Public Marketplace Release'], slaHours: 4, requiredApprovers: ['DIRECTOR_DEBT_ISSUANCE', 'CHIEF_INVESTMENT_OFFICER'], initialState: 'Primary Auction Win' },
    { id: 'FAAP-WF-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', code: 'FAAP-WF-BOND-STRUCT', title: 'Green Infrastructure Bond Structuring Flow', stages: ['Project Feasibility', 'ESG Verification', 'CMA Approval', 'Bond Fractionalization'], slaHours: 168, requiredApprovers: ['HEAD_SECURITIZATION', 'CHIEF_COMPLIANCE_OFFICER'], initialState: 'Project Feasibility' },
    { id: 'FAAP-WF-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', code: 'FAAP-WF-AMM-POOL', title: 'AMM Liquidity Pool Rebalancing Flow', stages: ['Spread Calculation', 'LP Yield Distribution', 'Reserve Rebalancing', 'Circuit Check'], slaHours: 1, requiredApprovers: ['HEAD_AMM_ALGORITHMS'], initialState: 'Spread Calculation' },
    { id: 'FAAP-WF-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', code: 'FAAP-WF-ORDER-MATCH', title: 'CLOB Continuous Order Matching Flow', stages: ['Order Ingest', 'Balance Pre-Fund Check', 'Sub-ms Matching', 'Atomic CSD Transfer'], slaHours: 1, requiredApprovers: ['CHIEF_EXCHANGE_TRADER'], initialState: 'Order Ingest' },
    { id: 'FAAP-WF-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-005', code: 'FAAP-WF-CSD-SYNC', title: 'Bank of Uganda CSD Reconciliation Flow', stages: ['CSD Balance Query', 'On-Chain Supply Audit', 'Cryptographic Proof', 'Audit Stamp'], slaHours: 2, requiredApprovers: ['CHIEF_CUSTODIAN'], initialState: 'CSD Balance Query' },
    { id: 'FAAP-WF-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', code: 'FAAP-WF-COUPON-PAY', title: 'Automated Coupon Interest Payout Flow', stages: ['Coupon Day Trigger', 'Snapshot Holder Balances', 'Smart Contract Execution', 'Mobile Money Delivery'], slaHours: 1, requiredApprovers: ['HEAD_SETTLEMENT_ESCROW'], initialState: 'Coupon Day Trigger' },
    { id: 'FAAP-WF-007', productId: 'prod-faap', moduleId: 'FAAP-MOD-007', code: 'FAAP-WF-CIRCUIT-TRIP', title: 'Market Circuit Breaker & Halting Flow', stages: ['Volatility Trigger', 'Immediate Trade Freeze', 'Surveillance Investigation', 'Controlled Restart'], slaHours: 1, requiredApprovers: ['HEAD_MARKET_SURVEILLANCE'], initialState: 'Volatility Trigger' },
    { id: 'FAAP-WF-008', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', code: 'FAAP-WF-CMA-AUDIT', title: 'CMA Sandbox Quarterly Compliance Flow', stages: ['Audit Data Extraction', 'Capital Ratio Audit', 'CMA Portal Submission', 'Regulatory Clearance'], slaHours: 48, requiredApprovers: ['CHIEF_COMPLIANCE_OFFICER'], initialState: 'Audit Data Extraction' }
  ],
  databaseEntities: [
    { id: 'FAAP-DB-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', tableName: 'faap_securitized_assets', primaryKey: 'asset_token_id', fields: [{ name: 'asset_token_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'isin', type: 'VARCHAR(32)', required: true }, { name: 'total_supply', type: 'BIGINT', required: true }], auditLogged: true },
    { id: 'FAAP-DB-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', tableName: 'faap_green_bonds', primaryKey: 'bond_id', fields: [{ name: 'bond_id', type: 'VARCHAR(64)', required: true }, { name: 'project_name', type: 'VARCHAR(128)', required: true }, { name: 'coupon_rate', type: 'FLOAT', required: true }], auditLogged: true },
    { id: 'FAAP-DB-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', tableName: 'faap_amm_pools', primaryKey: 'pool_id', fields: [{ name: 'pool_id', type: 'VARCHAR(64)', required: true }, { name: 'reserve_ugx', type: 'DECIMAL(18,2)', required: true }, { name: 'reserve_tokens', type: 'BIGINT', required: true }], auditLogged: true },
    { id: 'FAAP-DB-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', tableName: 'faap_clob_orders', primaryKey: 'order_id', fields: [{ name: 'order_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'investor_id', type: 'VARCHAR(64)', required: true }, { name: 'price', type: 'DECIMAL(18,2)', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'FAAP-DB-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-005', tableName: 'faap_mpc_custody_records', primaryKey: 'custody_id', fields: [{ name: 'custody_id', type: 'VARCHAR(64)', required: true }, { name: 'bou_csd_account', type: 'VARCHAR(64)', required: true }, { name: 'verified_reserve', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'FAAP-DB-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', tableName: 'faap_coupon_payouts', primaryKey: 'payout_id', fields: [{ name: 'payout_id', type: 'VARCHAR(64)', required: true }, { name: 'investor_id', type: 'VARCHAR(64)', required: true }, { name: 'amount_ugx', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'FAAP-DB-007', productId: 'prod-faap', moduleId: 'FAAP-MOD-007', tableName: 'faap_surveillance_alerts', primaryKey: 'alert_id', fields: [{ name: 'alert_id', type: 'VARCHAR(64)', required: true }, { name: 'anomaly_type', type: 'VARCHAR(64)', required: true }, { name: 'severity', type: 'VARCHAR(16)', required: true }], auditLogged: true },
    { id: 'FAAP-DB-008', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', tableName: 'faap_accredited_investors', primaryKey: 'investor_id', fields: [{ name: 'investor_id', type: 'VARCHAR(64)', required: true }, { name: 'nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'tier', type: 'VARCHAR(32)', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'FAAP-API-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', code: 'FAAP_API_MINT', method: 'POST', endpoint: '/api/v1/faap/issuance/mint', requiredPermission: 'FAAP-PERM-001', handlerName: 'mintSecuritizedAssetHandler', summary: 'Mint fractional T-Bill units' },
    { id: 'FAAP-API-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', code: 'FAAP_API_BONDS', method: 'POST', endpoint: '/api/v1/faap/bonds/originate', requiredPermission: 'FAAP-PERM-002', handlerName: 'originateGreenBondHandler', summary: 'Structure green infrastructure bond' },
    { id: 'FAAP-API-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', code: 'FAAP_API_AMM', method: 'POST', endpoint: '/api/v1/faap/amm/swap', requiredPermission: 'FAAP-PERM-003', handlerName: 'swapAssetTokensHandler', summary: 'Execute instant pool swap' },
    { id: 'FAAP-API-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', code: 'FAAP_API_ORDERS', method: 'POST', endpoint: '/api/v1/faap/trading/orders', requiredPermission: 'FAAP-PERM-004', handlerName: 'placeClobOrderHandler', summary: 'Submit limit/market order to CLOB' },
    { id: 'FAAP-API-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-005', code: 'FAAP_API_CUSTODY', method: 'GET', endpoint: '/api/v1/faap/custody/proof-of-reserves', requiredPermission: 'FAAP-PERM-005', handlerName: 'getProofOfReservesHandler', summary: 'Get CSD proof of reserves' },
    { id: 'FAAP-API-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', code: 'FAAP_API_COUPONS', method: 'POST', endpoint: '/api/v1/faap/settlement/trigger-coupon', requiredPermission: 'FAAP-PERM-006', handlerName: 'triggerCouponPayoutHandler', summary: 'Execute automated coupon payout' },
    { id: 'FAAP-API-007', productId: 'prod-faap', moduleId: 'FAAP-MOD-007', code: 'FAAP_API_SURVEILLANCE', method: 'GET', endpoint: '/api/v1/faap/surveillance/alerts', requiredPermission: 'FAAP-PERM-007', handlerName: 'getSurveillanceAlertsHandler', summary: 'Get live market integrity alerts' },
    { id: 'FAAP-API-008', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', code: 'FAAP_API_ACCREDITATION', method: 'POST', endpoint: '/api/v1/faap/compliance/accredit', requiredPermission: 'FAAP-PERM-008', handlerName: 'accreditInvestorHandler', summary: 'Approve investor accreditation' }
  ],
  runtimeComponents: [
    { id: 'FAAP-RTC-001', productId: 'prod-faap', moduleId: 'FAAP-MOD-001', componentKey: 'FaapTbillSecuritizationEngine', name: 'Fractional Treasury Bill Securitization Engine', description: 'Primary auction intake and micro-unit fractional minting workbench.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SECURITIZATION' },
    { id: 'FAAP-RTC-002', productId: 'prod-faap', moduleId: 'FAAP-MOD-002', componentKey: 'FaapInfrastructureBondEngine', name: 'Green Infrastructure & Corporate Bond Engine', description: 'Bond structuring prospectus and ESG telemetry monitor.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'BOND_ENGINE' },
    { id: 'FAAP-RTC-003', productId: 'prod-faap', moduleId: 'FAAP-MOD-003', componentKey: 'FaapAmmYieldPoolEngine', name: 'Automated Market Maker Yield & Pool Engine', description: 'Algorithmic bonding curves, 24/7 cashouts, and LP fee shares.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'AMM_ENGINE' },
    { id: 'FAAP-RTC-004', productId: 'prod-faap', moduleId: 'FAAP-MOD-004', componentKey: 'FaapClobTradingEngine', name: 'Institutional Continuous Order Book (CLOB)', description: 'Depth chart, real-time order entry, and trade execution tape.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EXCHANGE_ENGINE' },
    { id: 'FAAP-RTC-005', productId: 'prod-faap', moduleId: 'FAAP-MOD-005', componentKey: 'FaapMpcCustodyVaultEngine', name: 'Multi-Party Computation HSM Custody Vault', description: 'Cryptographic key sharding and BoU CSD reserve auditor.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CUSTODY_VAULT' },
    { id: 'FAAP-RTC-006', productId: 'prod-faap', moduleId: 'FAAP-MOD-006', componentKey: 'FaapCouponSettlementEngine', name: 'Smart Contract Coupon & Maturity Settler', description: 'Automated daily yield compounding and mobile money redemption.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SETTLEMENT' },
    { id: 'FAAP-RTC-007', productId: 'prod-faap', moduleId: 'FAAP-MOD-007', componentKey: 'FaapSurveillanceRadarEngine', name: 'Market Integrity & Surveillance Radar', description: 'Wash trading detector, spoofing monitor, and circuit breaker console.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SURVEILLANCE' },
    { id: 'FAAP-RTC-008', productId: 'prod-faap', moduleId: 'FAAP-MOD-008', componentKey: 'FaapCmaComplianceEngine', name: 'CMA Sandbox Reporting & Investor Accreditation', description: 'Capital Markets Authority regulatory returns and investor profiling.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'COMPLIANCE' }
  ],
  permissions: [
    { id: 'FAAP-PERM-001', productId: 'prod-faap', code: 'faap:issuance:mint', name: 'Securitization & Minting Access', description: 'Authority to mint fractional sovereign debt units' },
    { id: 'FAAP-PERM-002', productId: 'prod-faap', code: 'faap:bonds:originate', name: 'Green Bond Structuring Access', description: 'Authority to structure and originate debt offerings' },
    { id: 'FAAP-PERM-003', productId: 'prod-faap', code: 'faap:amm:manage', name: 'AMM Pool Operations Access', description: 'Authority to deploy and rebalance liquidity pools' },
    { id: 'FAAP-PERM-004', productId: 'prod-faap', code: 'faap:trading:clob', name: 'Continuous Exchange Trading Access', description: 'Authority to trade and quote on order book' },
    { id: 'FAAP-PERM-005', productId: 'prod-faap', code: 'faap:custody:mpc', name: 'MPC HSM Custody Keyholder', description: 'Authority to participate in threshold signing ceremonies' },
    { id: 'FAAP-PERM-006', productId: 'prod-faap', code: 'faap:settlement:coupons', name: 'Coupon & Settlement Authority', description: 'Authority to execute automated dividend and coupon payouts' },
    { id: 'FAAP-PERM-007', productId: 'prod-faap', code: 'faap:surveillance:radar', name: 'Market Surveillance Access', description: 'Authority to monitor integrity and trigger circuit breakers' },
    { id: 'FAAP-PERM-008', productId: 'prod-faap', code: 'faap:compliance:cma', name: 'CMA Sandbox Compliance Authority', description: 'Authority to approve accreditations and submit regulatory filings' }
  ],
  roles: [
    { id: 'FAAP-ROLE-001', productId: 'prod-faap', code: 'CHIEF_INVESTMENT_OFFICER', name: 'Chief Investment Officer', tier: 'GOVERNANCE', permissionIds: ['FAAP-PERM-001', 'FAAP-PERM-002', 'FAAP-PERM-003', 'FAAP-PERM-005', 'FAAP-PERM-008'] },
    { id: 'FAAP-ROLE-002', productId: 'prod-faap', code: 'HEAD_MARKET_OPERATIONS', name: 'Head of Market Operations', tier: 'EXECUTIVE', permissionIds: ['FAAP-PERM-003', 'FAAP-PERM-004', 'FAAP-PERM-007'] },
    { id: 'FAAP-ROLE-003', productId: 'prod-faap', code: 'PRIMARY_DEALER_TRADER', name: 'Primary Dealer / Institutional Trader', tier: 'OPERATIONAL', permissionIds: ['FAAP-PERM-004'] },
    { id: 'FAAP-ROLE-004', productId: 'prod-faap', code: 'CMA_REGULATORY_AUDITOR', name: 'CMA Regulatory Sandbox Auditor', tier: 'AUDITOR', permissionIds: ['FAAP-PERM-007', 'FAAP-PERM-008'] },
    { id: 'FAAP-ROLE-005', productId: 'prod-faap', code: 'RETAIL_INVESTOR_USER', name: 'Citizen Micro-Investor', tier: 'PUBLIC', permissionIds: [] }
  ]
};
