import { CanonicalProductHierarchy } from './types';

export const FINTECH_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-fintech',
    code: 'FTERP',
    name: 'Fintech, Microfinance & SACCO Core Banking OS',
    category: 'FINANCIAL_SERVICES',
    description: 'Sovereign tier-4 microfinance institution (MFI) and SACCO core banking engine: BOU & UMRA regulatory compliance, member share capital ledger, compulsory savings accounts, automated loan underwriting with collateral haircuts, Credit Reference Bureau (CRB) API checks, Mobile Money B2C/C2B integrations via JUMO DIGITAL PAY, double-entry financial accounting, AML/CFT transaction monitoring, and physical vault cash drawer custody.',
    version: '2026.4.0',
    iconName: 'Landmark',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Chief Executive Officer / SACCO General Manager',
    governingLegislation: 'Uganda Microfinance Regulatory Authority (UMRA) Act & Tier 4 Microfinance Act 2026',
    directorateIds: [
      'FT-DIR-CORE-BANKING',
      'FT-DIR-CREDIT-RISK',
      'FT-DIR-DIGITAL-CHANNELS',
      'FT-DIR-COMPLIANCE-AUDIT'
    ]
  },
  directorates: [
    {
      id: 'FT-DIR-CORE-BANKING',
      productId: 'prod-fintech',
      code: 'FT-DIR-BANKING',
      name: 'Directorate of Core Banking, Savings & Member Shares',
      description: 'Member customer onboarding (KYC), voluntary/compulsory savings deposit ledgers, fixed deposit certificates, share capital dividend calculation, and cashier counter vault drawers.',
      leadRole: 'HEAD_CORE_BANKING_OPERATIONS',
      departmentIds: ['FT-DEPT-MEMBER-KYC', 'FT-DEPT-SAVINGS-SHARES', 'FT-DEPT-VAULT-TELLERS']
    },
    {
      id: 'FT-DIR-CREDIT-RISK',
      productId: 'prod-fintech',
      code: 'FT-DIR-CREDIT',
      name: 'Directorate of Credit Risk, Underwriting & Loan Recovery',
      description: 'Loan application appraisals, CRB credit checks, guarantor verification, collateral asset valuation haircuts, loan schedule disbursement, and PAR (Portfolio At Risk) collections.',
      leadRole: 'CHIEF_CREDIT_OFFICER',
      departmentIds: ['FT-DEPT-LOAN-APPRAISALS', 'FT-DEPT-COLLATERAL-CRB', 'FT-DEPT-LOAN-RECOVERY']
    },
    {
      id: 'FT-DIR-DIGITAL-CHANNELS',
      productId: 'prod-fintech',
      code: 'FT-DIR-DIGITAL',
      name: 'Directorate of Digital Channels, Mobile Money & USSD Gateway',
      description: 'C2B mobile money savings collections, B2C instant loan disbursements via JUMO DIGITAL PAY rail, USSD banking session routing, and agent banking agency network.',
      leadRole: 'HEAD_DIGITAL_FINANCIAL_SERVICES',
      departmentIds: ['FT-DEPT-MOMO-SWITCH', 'FT-DEPT-AGENT-BANKING']
    },
    {
      id: 'FT-DIR-COMPLIANCE-AUDIT',
      productId: 'prod-fintech',
      code: 'FT-DIR-COMPLIANCE',
      name: 'Directorate of Regulatory Compliance, AML/CFT & Internal Audit',
      description: 'UMRA statutory prudential returns, Anti-Money Laundering (AML) cash threshold alerts, FATF sanctions screening, and daily double-entry general ledger balance sheet reconciliation.',
      leadRole: 'HEAD_RISK_COMPLIANCE_INTERNAL_AUDIT',
      departmentIds: ['FT-DEPT-UMRA-RETURNS', 'FT-DEPT-AML-SCREENING']
    }
  ],
  departments: [
    {
      id: 'FT-DEPT-MEMBER-KYC',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      code: 'FT-DEPT-KYC',
      name: 'Department of Member Registration & Tier-4 KYC Vetting',
      description: 'National ID (NIRA) verification, biometric photo capture, next-of-kin records, member account number generation, and signatory mandate setup.',
      headRole: 'CUSTOMER_SERVICE_MANAGER',
      officeIds: ['FT-OFF-KYC-DESK']
    },
    {
      id: 'FT-DEPT-SAVINGS-SHARES',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      code: 'FT-DEPT-SAVINGS',
      name: 'Department of Savings Deposits & Share Capital Ledger',
      description: 'Voluntary savings ledgers, target savings lock accounts, share capital certificate registry, and annual dividend distributions.',
      headRole: 'HEAD_SAVINGS_PRODUCT',
      officeIds: ['FT-OFF-SAVINGS-OFFICER']
    },
    {
      id: 'FT-DEPT-VAULT-TELLERS',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      code: 'FT-DEPT-VAULT',
      name: 'Department of Cash Vault, Tellers & Branch Drawers',
      description: 'Morning teller cash drawer provisioning, dual-custody strongroom vault balance, end-of-day till reconciliation, and cash-in-transit shipments.',
      headRole: 'CHIEF_TELLER_CASHIER',
      officeIds: ['FT-OFF-HEAD-TELLER']
    },
    {
      id: 'FT-DEPT-LOAN-APPRAISALS',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      code: 'FT-DEPT-APPRAISALS',
      name: 'Department of Loan Applications, Scoring & Credit Committee',
      description: 'Business cashflow analysis, debt-service coverage ratio (DSCR) calculations, loan committee approval dockets, and promissory note generation.',
      headRole: 'SENIOR_LOAN_APPRAISER',
      officeIds: ['FT-OFF-CREDIT-OFFICER']
    },
    {
      id: 'FT-DEPT-COLLATERAL-CRB',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      code: 'FT-DEPT-COLLATERAL',
      name: 'Department of Collateral Perfection & CRB Credit Bureau Checks',
      description: 'Land title search, motor vehicle logbook liens, chattel mortgages with 30-50% haircuts, and real-time CRB financial card credit scoring.',
      headRole: 'COLLATERAL_VALUER',
      officeIds: ['FT-OFF-COLLATERAL-DESK']
    },
    {
      id: 'FT-DEPT-LOAN-RECOVERY',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      code: 'FT-DEPT-RECOVERY',
      name: 'Department of Non-Performing Loans, PAR & Debt Recovery',
      description: 'Portfolio At Risk (PAR 30/60/90) monitoring, automated SMS overdue notices, loan restructuring agreements, and auction bailiff enforcement.',
      headRole: 'RECOVERY_MANAGER',
      officeIds: ['FT-OFF-RECOVERY-DESK']
    },
    {
      id: 'FT-DEPT-MOMO-SWITCH',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      code: 'FT-DEPT-MOMO',
      name: 'Department of Mobile Money Switching & Digital Pay Rail',
      description: 'Instant loan B2C disbursement gateway via JUMO DIGITAL PAY, C2B mobile money savings collection webhooks, and telecom float wallet management.',
      headRole: 'DIGITAL_SWITCH_ENGINEER',
      officeIds: ['FT-OFF-SWITCH-OPERATOR']
    },
    {
      id: 'FT-DEPT-AGENT-BANKING',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      code: 'FT-DEPT-AGENTS',
      name: 'Department of SACCO Agent Banking & POS Terminals',
      description: 'Agent float limit management, POS terminal transaction logs, agency commission settlements, and field cash-in/cash-out supervision.',
      headRole: 'AGENCY_BANKING_COORDINATOR',
      officeIds: ['FT-OFF-AGENT-DESK']
    },
    {
      id: 'FT-DEPT-UMRA-RETURNS',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      code: 'FT-DEPT-UMRA',
      name: 'Department of UMRA Statutory Returns & General Ledger',
      description: 'UMRA quarterly prudential ratios, liquidity reserve compliance (15%), capital adequacy metrics, and double-entry chart of accounts reconciliation.',
      headRole: 'CHIEF_FINANCIAL_OFFICER',
      officeIds: ['FT-OFF-CFO-DESK']
    },
    {
      id: 'FT-DEPT-AML-SCREENING',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      code: 'FT-DEPT-AML',
      name: 'Department of AML/CFT Monitoring & Sanctions Compliance',
      description: 'Uganda Financial Intelligence Authority (FIA) large cash transaction reports (CTR >= UGX 20M), PEP identification, and suspicious activity reports (SAR).',
      headRole: 'MONEY_LAUNDERING_REPORTING_OFFICER',
      officeIds: ['FT-OFF-MLRO-DESK']
    }
  ],
  offices: [
    {
      id: 'FT-OFF-KYC-DESK',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-MEMBER-KYC',
      code: 'FT-OFF-KYC',
      name: 'Member Onboarding & NIRA KYC Desk',
      description: 'Enrolling new SACCO members, validating National Identification Number (NIN), and issuing member passbooks.',
      officerRole: 'KYC_OFFICER',
      portalIds: ['FT-PORTAL-CEO-BOARD', 'FT-PORTAL-STAFF-CORE'],
      moduleIds: ['FT-MOD-MEMBER-KYC', 'FT-MOD-SAVINGS-ACCOUNTS']
    },
    {
      id: 'FT-OFF-SAVINGS-OFFICER',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      code: 'FT-OFF-SAVINGS',
      name: 'Savings Accounts & Share Capital Desk',
      description: 'Opening fixed deposit contracts, calculating annual share dividends, and issuing share certificates.',
      officerRole: 'SAVINGS_OFFICER',
      portalIds: ['FT-PORTAL-STAFF-CORE'],
      moduleIds: ['FT-MOD-SAVINGS-ACCOUNTS', 'FT-MOD-SHARE-CAPITAL']
    },
    {
      id: 'FT-OFF-HEAD-TELLER',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-VAULT-TELLERS',
      code: 'FT-OFF-TELLER',
      name: 'Chief Cashier & Strongroom Vault Counter',
      description: 'Processing over-the-counter cash deposits/withdrawals, till balancing, and dual-key vault locking.',
      officerRole: 'CHIEF_TELLER',
      portalIds: ['FT-PORTAL-STAFF-CORE'],
      moduleIds: ['FT-MOD-VAULT-CASH']
    },
    {
      id: 'FT-OFF-CREDIT-OFFICER',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-LOAN-APPRAISALS',
      code: 'FT-OFF-CREDIT',
      name: 'Credit Appraisal & Loan Committee Desk',
      description: 'Appraising business loan proposals, assessing debt ratios, and submitting files to Credit Committee.',
      officerRole: 'CREDIT_OFFICER',
      portalIds: ['FT-PORTAL-STAFF-CORE', 'FT-PORTAL-CREDIT-COMMITTEE'],
      moduleIds: ['FT-MOD-LOAN-UNDERWRITING']
    },
    {
      id: 'FT-OFF-COLLATERAL-DESK',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-COLLATERAL-CRB',
      code: 'FT-OFF-COLLATERAL',
      name: 'Collateral Registry & CRB Check Desk',
      description: 'Querying CRB credit scores, registering security interest in URSB SIMPO registry, and inspecting collateral.',
      officerRole: 'COLLATERAL_OFFICER',
      portalIds: ['FT-PORTAL-CREDIT-COMMITTEE'],
      moduleIds: ['FT-MOD-LOAN-UNDERWRITING', 'FT-MOD-CRB-COLLATERAL']
    },
    {
      id: 'FT-OFF-RECOVERY-DESK',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-LOAN-RECOVERY',
      code: 'FT-OFF-RECOVERY',
      name: 'PAR Monitoring & Loan Recovery Desk',
      description: 'Tracking 30+ day arrears, issuing demand letters, negotiating loan restructuring, and auction notices.',
      officerRole: 'RECOVERY_OFFICER',
      portalIds: ['FT-PORTAL-STAFF-CORE'],
      moduleIds: ['FT-MOD-LOAN-UNDERWRITING', 'FT-MOD-CRB-COLLATERAL']
    },
    {
      id: 'FT-OFF-SWITCH-OPERATOR',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      departmentId: 'FT-DEPT-MOMO-SWITCH',
      code: 'FT-OFF-SWITCH',
      name: 'Mobile Money Gateway Switch Desk',
      description: 'Monitoring JUMO DIGITAL PAY disbursements, managing MTN/Airtel float balances, and handling webhook retries.',
      officerRole: 'SWITCH_OPERATOR',
      portalIds: ['FT-PORTAL-CEO-BOARD', 'FT-PORTAL-STAFF-CORE'],
      moduleIds: ['FT-MOD-DIGITAL-MOMO']
    },
    {
      id: 'FT-OFF-AGENT-DESK',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      departmentId: 'FT-DEPT-AGENT-BANKING',
      code: 'FT-OFF-AGENTS',
      name: 'SACCO Agent Banking Administration Desk',
      description: 'Onboarding agent locations, reconciling agent float wallets, and auditing POS transaction logs.',
      officerRole: 'AGENCY_OFFICER',
      portalIds: ['FT-PORTAL-STAFF-CORE'],
      moduleIds: ['FT-MOD-DIGITAL-MOMO']
    },
    {
      id: 'FT-OFF-CFO-DESK',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      code: 'FT-OFF-CFO',
      name: 'Chief Financial Officer & General Ledger Desk',
      description: 'Maintaining double-entry general ledger, generating UMRA statutory returns, and managing liquidity ratios.',
      officerRole: 'CFO',
      portalIds: ['FT-PORTAL-CEO-BOARD', 'FT-PORTAL-COMPLIANCE'],
      moduleIds: ['FT-MOD-GENERAL-LEDGER', 'FT-MOD-UMRA-COMPLIANCE']
    },
    {
      id: 'FT-OFF-MLRO-DESK',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-AML-SCREENING',
      code: 'FT-OFF-MLRO',
      name: 'Money Laundering Reporting Officer (MLRO) Desk',
      description: 'Screening high-value transactions, submitting FIA reports, and investigating sanctions hits.',
      officerRole: 'MLRO',
      portalIds: ['FT-PORTAL-CEO-BOARD', 'FT-PORTAL-COMPLIANCE'],
      moduleIds: ['FT-MOD-UMRA-COMPLIANCE']
    }
  ],
  portals: [
    {
      id: 'FT-PORTAL-CEO-BOARD',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      code: 'FT-PORTAL-EXECUTIVE',
      name: 'CEO & Board of Directors Core Banking Cockpit',
      description: 'High-level financial KPIs: Total loan portfolio, PAR%, savings deposit growth, UMRA capital adequacy, and liquidity reserves.',
      targetRole: 'CEO_BOARD',
      authLevel: 'PKI_SOVEREIGN',
      route: '/fintech/executive',
      moduleIds: ['FT-MOD-MEMBER-KYC', 'FT-MOD-SAVINGS-ACCOUNTS', 'FT-MOD-SHARE-CAPITAL', 'FT-MOD-LOAN-UNDERWRITING', 'FT-MOD-GENERAL-LEDGER', 'FT-MOD-UMRA-COMPLIANCE']
    },
    {
      id: 'FT-PORTAL-STAFF-CORE',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-MEMBER-KYC',
      officeId: 'FT-OFF-KYC-DESK',
      code: 'FT-PORTAL-OPERATIONS',
      name: 'Branch Banking Operations & Teller Terminal',
      description: 'Member account lookup, cash deposit/withdrawal processing, till balancing, loan repayments, and passbook updates.',
      targetRole: 'OPERATIONS_STAFF',
      authLevel: 'STAFF',
      route: '/fintech/teller',
      moduleIds: ['FT-MOD-MEMBER-KYC', 'FT-MOD-SAVINGS-ACCOUNTS', 'FT-MOD-VAULT-CASH', 'FT-MOD-DIGITAL-MOMO']
    },
    {
      id: 'FT-PORTAL-CREDIT-COMMITTEE',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-LOAN-APPRAISALS',
      officeId: 'FT-OFF-CREDIT-OFFICER',
      code: 'FT-PORTAL-CREDIT',
      name: 'Credit Committee & Underwriting Terminal',
      description: 'Review loan appraisal files, CRB credit scores, collateral valuation haircuts, and cast voting approval signatures.',
      targetRole: 'CREDIT_COMMITTEE',
      authLevel: 'STAFF',
      route: '/fintech/credit',
      moduleIds: ['FT-MOD-LOAN-UNDERWRITING', 'FT-MOD-CRB-COLLATERAL']
    },
    {
      id: 'FT-PORTAL-COMPLIANCE',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      code: 'FT-PORTAL-AUDIT',
      name: 'Risk, UMRA Compliance & General Ledger Terminal',
      description: 'Audit double-entry financial journals, inspect AML cash threshold alerts, verify FIA reports, and export UMRA returns.',
      targetRole: 'COMPLIANCE_AUDITOR',
      authLevel: 'STAFF',
      route: '/fintech/compliance',
      moduleIds: ['FT-MOD-GENERAL-LEDGER', 'FT-MOD-UMRA-COMPLIANCE']
    },
    {
      id: 'FT-PORTAL-MEMBER-APP',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      departmentId: 'FT-DEPT-MOMO-SWITCH',
      officeId: 'FT-OFF-SWITCH-OPERATOR',
      code: 'FT-PORTAL-MEMBER',
      name: 'SACCO Member Mobile & USSD Banking Portal',
      description: 'Check savings balances, view share dividends, apply for instant digital emergency loans, and repay via Mobile Money.',
      targetRole: 'SACCO_MEMBER',
      authLevel: 'PUBLIC',
      route: '/fintech/app',
      moduleIds: ['FT-MOD-SAVINGS-ACCOUNTS', 'FT-MOD-SHARE-CAPITAL', 'FT-MOD-LOAN-UNDERWRITING', 'FT-MOD-DIGITAL-MOMO']
    }
  ],
  modules: [
    {
      id: 'FT-MOD-MEMBER-KYC',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-MEMBER-KYC',
      officeId: 'FT-OFF-KYC-DESK',
      portalId: 'FT-PORTAL-STAFF-CORE',
      code: 'FT-MOD-MEMBER-KYC',
      name: 'Member Customer Information File (CIF) & Biometric KYC',
      description: 'SACCO member registration, National ID verification, signature mandates, next-of-kin, and membership numbering.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-KYC-001', 'FT-CAP-KYC-002'],
      screenIds: ['FT-SCR-KYC'],
      formIds: ['FT-FORM-MEMBER-REG'],
      dashboardIds: ['FT-DASH-BANKING'],
      reportIds: ['FT-REP-KYC'],
      workflowIds: ['FT-WF-KYC'],
      databaseEntityIds: ['FT-DB-MEMBERS-CIF'],
      apiIds: ['FT-API-KYC'],
      runtimeComponentId: 'FT-RTC-KYC',
      permissionIds: ['FT-PERM-CORE-BANKING']
    },
    {
      id: 'FT-MOD-SAVINGS-ACCOUNTS',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      officeId: 'FT-OFF-SAVINGS-OFFICER',
      portalId: 'FT-PORTAL-STAFF-CORE',
      code: 'FT-MOD-SAVINGS-ACCOUNTS',
      name: 'Voluntary, Compulsory & Fixed Deposit Savings Engine',
      description: 'Multi-tier savings accounts, automated interest calculation, withdrawal limits, and maturity schedules for fixed deposits.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-SAV-001', 'FT-CAP-SAV-002'],
      screenIds: ['FT-SCR-SAVINGS'],
      formIds: ['FT-FORM-FIXED-DEPOSIT'],
      dashboardIds: ['FT-DASH-BANKING'],
      reportIds: ['FT-REP-SAVINGS'],
      workflowIds: ['FT-WF-SAVINGS'],
      databaseEntityIds: ['FT-DB-SAVINGS-ACCOUNTS'],
      apiIds: ['FT-API-SAVINGS'],
      runtimeComponentId: 'FT-RTC-SAVINGS',
      permissionIds: ['FT-PERM-CORE-BANKING']
    },
    {
      id: 'FT-MOD-SHARE-CAPITAL',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      officeId: 'FT-OFF-SAVINGS-OFFICER',
      portalId: 'FT-PORTAL-CEO-BOARD',
      code: 'FT-MOD-SHARE-CAPITAL',
      name: 'SACCO Member Share Capital & Dividend Allocation',
      description: 'Institutional share capital requirements, minimum mandatory shares, share transfers, and AGM dividend allocations.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-SHARE-001', 'FT-CAP-SHARE-002'],
      screenIds: ['FT-SCR-SHARES'],
      formIds: ['FT-FORM-SHARE-PURCHASE'],
      dashboardIds: ['FT-DASH-BANKING'],
      reportIds: ['FT-REP-SHARES'],
      workflowIds: ['FT-WF-SHARES'],
      databaseEntityIds: ['FT-DB-SHARES-LEDGER'],
      apiIds: ['FT-API-SHARES'],
      runtimeComponentId: 'FT-RTC-SHARES',
      permissionIds: ['FT-PERM-CORE-BANKING']
    },
    {
      id: 'FT-MOD-VAULT-CASH',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-VAULT-TELLERS',
      officeId: 'FT-OFF-HEAD-TELLER',
      portalId: 'FT-PORTAL-STAFF-CORE',
      code: 'FT-MOD-VAULT-CASH',
      name: 'Cash Vault, Teller Tills & Dual-Custody Strongroom',
      description: 'Teller drawer cash limits, daily till balancing, cash deposit/withdrawal vouchers, and strongroom vault logbooks.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-VAULT-001', 'FT-CAP-VAULT-002'],
      screenIds: ['FT-SCR-VAULT'],
      formIds: ['FT-FORM-TILL-TRANSFER'],
      dashboardIds: ['FT-DASH-BANKING'],
      reportIds: ['FT-REP-VAULT'],
      workflowIds: ['FT-WF-VAULT'],
      databaseEntityIds: ['FT-DB-VAULT-LEDGER'],
      apiIds: ['FT-API-VAULT'],
      runtimeComponentId: 'FT-RTC-VAULT',
      permissionIds: ['FT-PERM-CORE-BANKING']
    },
    {
      id: 'FT-MOD-LOAN-UNDERWRITING',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-LOAN-APPRAISALS',
      officeId: 'FT-OFF-CREDIT-OFFICER',
      portalId: 'FT-PORTAL-CREDIT-COMMITTEE',
      code: 'FT-MOD-LOAN-UNDERWRITING',
      name: 'Automated Loan Underwriting, Amortization & PAR Engine',
      description: 'Flat vs reducing balance interest calculators, credit scoring, committee approvals, disbursement schedules, and PAR tracking.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-LOAN-001', 'FT-CAP-LOAN-002'],
      screenIds: ['FT-SCR-LOANS'],
      formIds: ['FT-FORM-LOAN-APP'],
      dashboardIds: ['FT-DASH-CREDIT'],
      reportIds: ['FT-REP-LOANS'],
      workflowIds: ['FT-WF-LOANS'],
      databaseEntityIds: ['FT-DB-LOANS-PORTFOLIO'],
      apiIds: ['FT-API-LOANS'],
      runtimeComponentId: 'FT-RTC-LOANS',
      permissionIds: ['FT-PERM-CREDIT-RISK']
    },
    {
      id: 'FT-MOD-CRB-COLLATERAL',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-COLLATERAL-CRB',
      officeId: 'FT-OFF-COLLATERAL-DESK',
      portalId: 'FT-PORTAL-CREDIT-COMMITTEE',
      code: 'FT-MOD-CRB-COLLATERAL',
      name: 'CRB Credit Reference API & Collateral Registry',
      description: 'Direct CRB financial card credit score inquiries, chattel/land title collateral haircuts, and security liens.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-CRB-001', 'FT-CAP-CRB-002'],
      screenIds: ['FT-SCR-COLLATERAL'],
      formIds: ['FT-FORM-COLLATERAL-REG'],
      dashboardIds: ['FT-DASH-CREDIT'],
      reportIds: ['FT-REP-COLLATERAL'],
      workflowIds: ['FT-WF-COLLATERAL'],
      databaseEntityIds: ['FT-DB-COLLATERAL-REGISTRY'],
      apiIds: ['FT-API-CRB'],
      runtimeComponentId: 'FT-RTC-COLLATERAL',
      permissionIds: ['FT-PERM-CREDIT-RISK']
    },
    {
      id: 'FT-MOD-DIGITAL-MOMO',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      departmentId: 'FT-DEPT-MOMO-SWITCH',
      officeId: 'FT-OFF-SWITCH-OPERATOR',
      portalId: 'FT-PORTAL-STAFF-CORE',
      code: 'FT-MOD-DIGITAL-MOMO',
      name: 'Mobile Money Switch, B2C Loans & C2B Collections',
      description: 'MTN MoMo & Airtel Money gateway via JUMO DIGITAL PAY: Instant B2C loan disbursements, C2B savings pushes, and USSD banking.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-MOMO-001', 'FT-CAP-MOMO-002'],
      screenIds: ['FT-SCR-MOMO'],
      formIds: ['FT-FORM-MOMO-DISBURSE'],
      dashboardIds: ['FT-DASH-DIGITAL'],
      reportIds: ['FT-REP-MOMO'],
      workflowIds: ['FT-WF-MOMO'],
      databaseEntityIds: ['FT-DB-MOMO-TRANSACTIONS'],
      apiIds: ['FT-API-MOMO'],
      runtimeComponentId: 'FT-RTC-MOMO',
      permissionIds: ['FT-PERM-DIGITAL-PAY']
    },
    {
      id: 'FT-MOD-GENERAL-LEDGER',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      portalId: 'FT-PORTAL-COMPLIANCE',
      code: 'FT-MOD-GENERAL-LEDGER',
      name: 'Double-Entry Financial Accounting & Chart of Accounts',
      description: 'Automated double-entry debit/credit ledger, trial balance, income statement, balance sheet, and FAAP ledger synchronizer.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-GL-001', 'FT-CAP-GL-002'],
      screenIds: ['FT-SCR-GL'],
      formIds: ['FT-FORM-JOURNAL-ENTRY'],
      dashboardIds: ['FT-DASH-COMPLIANCE'],
      reportIds: ['FT-REP-GL'],
      workflowIds: ['FT-WF-GL'],
      databaseEntityIds: ['FT-DB-GENERAL-LEDGER'],
      apiIds: ['FT-API-GL'],
      runtimeComponentId: 'FT-RTC-GL',
      permissionIds: ['FT-PERM-FINANCE-AUDIT']
    },
    {
      id: 'FT-MOD-UMRA-COMPLIANCE',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      portalId: 'FT-PORTAL-COMPLIANCE',
      code: 'FT-MOD-UMRA-COMPLIANCE',
      name: 'UMRA Statutory Prudential Returns & AML/CFT Monitor',
      description: 'UMRA quarterly returns, capital adequacy ratio, liquidity ratios (>=15%), and AML large cash transaction reporting (CTR).',
      status: 'ACTIVE_CORE',
      capabilityIds: ['FT-CAP-UMRA-001', 'FT-CAP-UMRA-002'],
      screenIds: ['FT-SCR-UMRA'],
      formIds: ['FT-FORM-AML-REPORT'],
      dashboardIds: ['FT-DASH-COMPLIANCE'],
      reportIds: ['FT-REP-UMRA'],
      workflowIds: ['FT-WF-UMRA'],
      databaseEntityIds: ['FT-DB-COMPLIANCE-REPORTS'],
      apiIds: ['FT-API-UMRA'],
      runtimeComponentId: 'FT-RTC-UMRA',
      permissionIds: ['FT-PERM-FINANCE-AUDIT']
    }
  ],
  capabilities: [
    {
      id: 'FT-CAP-KYC-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-MEMBER-KYC',
      officeId: 'FT-OFF-KYC-DESK',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-MEMBER-KYC',
      code: 'FT_CAP_KYC_ONBOARD_MEMBER',
      name: 'Onboard SACCO Member & Generate CIF',
      description: 'Enters member National ID, phone number, physical address, and issues unique SACCO Member Account Number.',
      serviceAction: 'fintech.kyc.onboardMember',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-KYC',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-KYC-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-MEMBER-KYC',
      officeId: 'FT-OFF-KYC-DESK',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-MEMBER-KYC',
      code: 'FT_CAP_KYC_VERIFY_NIRA_NIN',
      name: 'Verify National ID Number (NIN) against NIRA DB',
      description: 'Validates member biographical details against national identity database to eliminate fraudulent accounts.',
      serviceAction: 'fintech.kyc.verifyNIN',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-KYC',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-SAV-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      officeId: 'FT-OFF-SAVINGS-OFFICER',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-SAVINGS-ACCOUNTS',
      code: 'FT_CAP_SAV_POST_SAVINGS_DEPOSIT',
      name: 'Post Voluntary / Compulsory Savings Deposit',
      description: 'Credits member savings account, updates running passbook balance, and posts dual-entry journal to cash account.',
      serviceAction: 'fintech.savings.postDeposit',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-SAVINGS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-SAV-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      officeId: 'FT-OFF-SAVINGS-OFFICER',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-SAVINGS-ACCOUNTS',
      code: 'FT_CAP_SAV_CREATE_FIXED_DEPOSIT',
      name: 'Book Fixed Deposit Contract & Certificate',
      description: 'Locks deposit amount for specified tenure (e.g. 6 months @ 12% p.a.) and generates encrypted maturity certificate.',
      serviceAction: 'fintech.savings.createFixedDeposit',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-SAVINGS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-SHARE-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      officeId: 'FT-OFF-SAVINGS-OFFICER',
      portalId: 'FT-PORTAL-CEO-BOARD',
      moduleId: 'FT-MOD-SHARE-CAPITAL',
      code: 'FT_CAP_SHARE_ISSUE_SHARE_CAPITAL',
      name: 'Issue Institutional Share Capital Shares',
      description: 'Records purchased share units (e.g. UGX 50,000 per share) towards mandatory institutional capital requirements.',
      serviceAction: 'fintech.shares.issueShares',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-SHARES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-SHARE-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-SAVINGS-SHARES',
      officeId: 'FT-OFF-SAVINGS-OFFICER',
      portalId: 'FT-PORTAL-CEO-BOARD',
      moduleId: 'FT-MOD-SHARE-CAPITAL',
      code: 'FT_CAP_SHARE_DISTRIBUTE_DIVIDENDS',
      name: 'Compute & Disburse Annual Share Dividends',
      description: 'Calculates prorated AGM approved dividend percentage on weighted member shareholdings and credits savings.',
      serviceAction: 'fintech.shares.distributeDividends',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-SHARES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-VAULT-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-VAULT-TELLERS',
      officeId: 'FT-OFF-HEAD-TELLER',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-VAULT-CASH',
      code: 'FT_CAP_VAULT_DISBURSE_TELLER_TILL',
      name: 'Transfer Cash from Strongroom to Teller Till',
      description: 'Transfers physical cash from master vault to teller till with dual authorization by Head Teller and Branch Manager.',
      serviceAction: 'fintech.vault.transferToTill',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-VAULT',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-VAULT-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CORE-BANKING',
      departmentId: 'FT-DEPT-VAULT-TELLERS',
      officeId: 'FT-OFF-HEAD-TELLER',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-VAULT-CASH',
      code: 'FT_CAP_VAULT_RECONCILE_END_OF_DAY',
      name: 'Perform End-of-Day Teller Till & Vault Balancing',
      description: 'Matches physical banknote denomination count against system journal entries and locks vault for the night.',
      serviceAction: 'fintech.vault.reconcileEndOfDay',
      requiredPermission: 'FT-PERM-CORE-BANKING',
      runtimeComponentId: 'FT-RTC-VAULT',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-LOAN-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-LOAN-APPRAISALS',
      officeId: 'FT-OFF-CREDIT-OFFICER',
      portalId: 'FT-PORTAL-CREDIT-COMMITTEE',
      moduleId: 'FT-MOD-LOAN-UNDERWRITING',
      code: 'FT_CAP_LOAN_APPRAISE_APPLICATION',
      name: 'Appraise Loan Application & Calculate DSCR',
      description: 'Evaluates applicant cashflows, debt service coverage ratio, savings multiplier (up to 3x), and generates amortization schedule.',
      serviceAction: 'fintech.loans.appraiseApplication',
      requiredPermission: 'FT-PERM-CREDIT-RISK',
      runtimeComponentId: 'FT-RTC-LOANS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-LOAN-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-LOAN-APPRAISALS',
      officeId: 'FT-OFF-CREDIT-OFFICER',
      portalId: 'FT-PORTAL-CREDIT-COMMITTEE',
      moduleId: 'FT-MOD-LOAN-UNDERWRITING',
      code: 'FT_CAP_LOAN_DISBURSE_APPROVED_LOAN',
      name: 'Disburse Approved Loan to Member Account / MoMo',
      description: 'Executes credit committee approval, deducts loan processing fee and insurance, and credits member account.',
      serviceAction: 'fintech.loans.disburseLoan',
      requiredPermission: 'FT-PERM-CREDIT-RISK',
      runtimeComponentId: 'FT-RTC-LOANS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-CRB-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-COLLATERAL-CRB',
      officeId: 'FT-OFF-COLLATERAL-DESK',
      portalId: 'FT-PORTAL-CREDIT-COMMITTEE',
      moduleId: 'FT-MOD-CRB-COLLATERAL',
      code: 'FT_CAP_CRB_QUERY_CREDIT_REPORT',
      name: 'Query Real-Time CRB Financial Card Credit Report',
      description: 'Fetches applicant non-performing loans across all Ugandan financial institutions and retrieves Credit Bureau score.',
      serviceAction: 'fintech.crb.queryCreditReport',
      requiredPermission: 'FT-PERM-CREDIT-RISK',
      runtimeComponentId: 'FT-RTC-COLLATERAL',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-CRB-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-CREDIT-RISK',
      departmentId: 'FT-DEPT-COLLATERAL-CRB',
      officeId: 'FT-OFF-COLLATERAL-DESK',
      portalId: 'FT-PORTAL-CREDIT-COMMITTEE',
      moduleId: 'FT-MOD-CRB-COLLATERAL',
      code: 'FT_CAP_CRB_REGISTER_COLLATERAL_LIEN',
      name: 'Register Collateral Asset & Apply Haircut Valuation',
      description: 'Applies forced sale valuation (FSV) discount (30-50%) on motor vehicle or land title and registers lien in security register.',
      serviceAction: 'fintech.crb.registerCollateralLien',
      requiredPermission: 'FT-PERM-CREDIT-RISK',
      runtimeComponentId: 'FT-RTC-COLLATERAL',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-MOMO-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      departmentId: 'FT-DEPT-MOMO-SWITCH',
      officeId: 'FT-OFF-SWITCH-OPERATOR',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-DIGITAL-MOMO',
      code: 'FT_CAP_MOMO_DISBURSE_B2C_PAYMENT',
      name: 'Disburse B2C Instant Mobile Money Loan via Digital Pay',
      description: 'Initiates direct API transfer to member MTN / Airtel line with automated cryptographic idempotency key.',
      serviceAction: 'fintech.momo.disburseB2C',
      requiredPermission: 'FT-PERM-DIGITAL-PAY',
      runtimeComponentId: 'FT-RTC-MOMO',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-MOMO-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-DIGITAL-CHANNELS',
      departmentId: 'FT-DEPT-MOMO-SWITCH',
      officeId: 'FT-OFF-SWITCH-OPERATOR',
      portalId: 'FT-PORTAL-STAFF-CORE',
      moduleId: 'FT-MOD-DIGITAL-MOMO',
      code: 'FT_CAP_MOMO_INGEST_C2B_SAVINGS_PUSH',
      name: 'Ingest C2B Mobile Money Savings Deposit',
      description: 'Receives instant payment webhook notification, reconciles reference against loan/savings account, and sends SMS receipt.',
      serviceAction: 'fintech.momo.ingestC2B',
      requiredPermission: 'FT-PERM-DIGITAL-PAY',
      runtimeComponentId: 'FT-RTC-MOMO',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-GL-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      portalId: 'FT-PORTAL-COMPLIANCE',
      moduleId: 'FT-MOD-GENERAL-LEDGER',
      code: 'FT_CAP_GL_POST_JOURNAL_VOUCHER',
      name: 'Post Double-Entry General Ledger Journal Voucher',
      description: 'Creates balanced debit and credit entries conforming to IFRS and Tier-4 chart of accounts standard.',
      serviceAction: 'fintech.gl.postJournalVoucher',
      requiredPermission: 'FT-PERM-FINANCE-AUDIT',
      runtimeComponentId: 'FT-RTC-GL',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-GL-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      portalId: 'FT-PORTAL-COMPLIANCE',
      moduleId: 'FT-MOD-GENERAL-LEDGER',
      code: 'FT_CAP_GL_GENERATE_BALANCE_SHEET',
      name: 'Generate Real-Time Trial Balance & Balance Sheet',
      description: 'Produces financial position statement with automatic validation that Total Assets = Liabilities + Member Equity.',
      serviceAction: 'fintech.gl.generateBalanceSheet',
      requiredPermission: 'FT-PERM-FINANCE-AUDIT',
      runtimeComponentId: 'FT-RTC-GL',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-UMRA-001',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-UMRA-RETURNS',
      officeId: 'FT-OFF-CFO-DESK',
      portalId: 'FT-PORTAL-COMPLIANCE',
      moduleId: 'FT-MOD-UMRA-COMPLIANCE',
      code: 'FT_CAP_UMRA_EXPORT_PRUDENTIAL_RETURNS',
      name: 'Export UMRA Quarterly Prudential Compliance Return',
      description: 'Aggregates PAR portfolio aging, liquidity reserve ratio (15%), capital adequacy, and outputs official UMRA XML/PDF.',
      serviceAction: 'fintech.compliance.exportUMRAReturns',
      requiredPermission: 'FT-PERM-FINANCE-AUDIT',
      runtimeComponentId: 'FT-RTC-UMRA',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'FT-CAP-UMRA-002',
      productId: 'prod-fintech',
      directorateId: 'FT-DIR-COMPLIANCE-AUDIT',
      departmentId: 'FT-DEPT-AML-SCREENING',
      officeId: 'FT-OFF-MLRO-DESK',
      portalId: 'FT-PORTAL-COMPLIANCE',
      moduleId: 'FT-MOD-UMRA-COMPLIANCE',
      code: 'FT_CAP_UMRA_FLAG_LARGE_CASH_CTR',
      name: 'Screen AML Large Cash Transactions (CTR >= 20M)',
      description: 'Monitors single or linked cash transactions equal to or exceeding UGX 20,000,000 for mandatory FIA reporting.',
      serviceAction: 'fintech.compliance.flagLargeCashCTR',
      requiredPermission: 'FT-PERM-FINANCE-AUDIT',
      runtimeComponentId: 'FT-RTC-UMRA',
      status: 'ACTIVE_CORE'
    }
  ],
  screens: [
    { id: 'FT-SCR-KYC', productId: 'prod-fintech', moduleId: 'FT-MOD-MEMBER-KYC', code: 'FT-SCR-KYC', title: 'Member Customer Information File (CIF) & KYC Vetting', description: 'Member registration, National ID verification, and signatures.', viewType: 'TABLE', route: '/fintech/kyc' },
    { id: 'FT-SCR-SAVINGS', productId: 'prod-fintech', moduleId: 'FT-MOD-SAVINGS-ACCOUNTS', code: 'FT-SCR-SAVINGS', title: 'Savings Accounts & Fixed Deposits Ledger', description: 'Voluntary savings, fixed deposit certificates, and transactions.', viewType: 'TABLE', route: '/fintech/savings' },
    { id: 'FT-SCR-SHARES', productId: 'prod-fintech', moduleId: 'FT-MOD-SHARE-CAPITAL', code: 'FT-SCR-SHARES', title: 'SACCO Member Share Capital & Dividends', description: 'Institutional shares, capital reserves, and dividend payouts.', viewType: 'TABLE', route: '/fintech/shares' },
    { id: 'FT-SCR-VAULT', productId: 'prod-fintech', moduleId: 'FT-MOD-VAULT-CASH', code: 'FT-SCR-VAULT', title: 'Cash Vault, Teller Drawers & Strongroom Ledger', description: 'Physical cash custody, till limits, and vault balances.', viewType: 'TABLE', route: '/fintech/vault' },
    { id: 'FT-SCR-LOANS', productId: 'prod-fintech', moduleId: 'FT-MOD-LOAN-UNDERWRITING', code: 'FT-SCR-LOANS', title: 'Loan Underwriting, Portfolio & PAR Collections', description: 'Appraisals, committee approvals, disbursements, and aging arrears.', viewType: 'TABLE', route: '/fintech/loans' },
    { id: 'FT-SCR-COLLATERAL', productId: 'prod-fintech', moduleId: 'FT-MOD-CRB-COLLATERAL', code: 'FT-SCR-COLLATERAL', title: 'CRB Credit Reference & Collateral Security Liens', description: 'CRB scores, vehicle logbooks, land titles, and forced valuations.', viewType: 'TABLE', route: '/fintech/collateral' },
    { id: 'FT-SCR-MOMO', productId: 'prod-fintech', moduleId: 'FT-MOD-DIGITAL-MOMO', code: 'FT-SCR-MOMO', title: 'Digital Mobile Money Gateway & B2C/C2B Switch', description: 'Live transactions, webhook logs, and float wallet balance.', viewType: 'TABLE', route: '/fintech/momo' },
    { id: 'FT-SCR-GL', productId: 'prod-fintech', moduleId: 'FT-MOD-GENERAL-LEDGER', code: 'FT-SCR-GL', title: 'Double-Entry General Ledger & Balance Sheet', description: 'Journal entries, trial balance, and financial statements.', viewType: 'TABLE', route: '/fintech/gl' },
    { id: 'FT-SCR-UMRA', productId: 'prod-fintech', moduleId: 'FT-MOD-UMRA-COMPLIANCE', code: 'FT-SCR-UMRA', title: 'UMRA Statutory Returns & AML Transaction Monitor', description: 'Quarterly prudential reports, liquidity, and AML alerts.', viewType: 'TABLE', route: '/fintech/compliance' }
  ],
  forms: [
    {
      id: 'FT-FORM-MEMBER-REG',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-MEMBER-KYC',
      code: 'FT-FORM-MEMBER-REG',
      title: 'SACCO Member Customer Onboarding Form',
      submitAction: 'fintech.kyc.onboardMember',
      fieldCount: 5,
      fields: [
        { name: 'memberFullName', label: 'Member Full Legal Name', type: 'text', required: true },
        { name: 'nationalIdNumber', label: 'National ID Number (NIN)', type: 'text', required: true },
        { name: 'mobilePhoneNumber', label: 'Registered Mobile Phone', type: 'text', required: true },
        { name: 'physicalResidence', label: 'Village / LC1 Residence Details', type: 'text', required: true },
        { name: 'initialSharesSubscribed', label: 'Initial Mandatory Share Units', type: 'number', required: true }
      ],
      validationRules: ['NIN_VALID']
    },
    {
      id: 'FT-FORM-FIXED-DEPOSIT',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-SAVINGS-ACCOUNTS',
      code: 'FT-FORM-FIXED-DEPOSIT',
      title: 'Fixed Term Deposit Account Contract',
      submitAction: 'fintech.savings.createFixedDeposit',
      fieldCount: 4,
      fields: [
        { name: 'memberAccountNo', label: 'Member Account Number', type: 'text', required: true },
        { name: 'principalAmountUgx', label: 'Deposit Principal Amount (UGX)', type: 'number', required: true },
        { name: 'tenureMonths', label: 'Tenure (3 / 6 / 12 Months)', type: 'select', required: true },
        { name: 'agreedInterestRate', label: 'Contract Interest Rate (% p.a.)', type: 'number', required: true }
      ],
      validationRules: ['AMOUNT_POSITIVE']
    },
    {
      id: 'FT-FORM-SHARE-PURCHASE',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-SHARE-CAPITAL',
      code: 'FT-FORM-SHARE-PURCHASE',
      title: 'SACCO Share Capital Subscription Entry',
      submitAction: 'fintech.shares.issueShares',
      fieldCount: 4,
      fields: [
        { name: 'memberAccountNo', label: 'Member Account Number', type: 'text', required: true },
        { name: 'numberOfShares', label: 'Number of Shares to Purchase', type: 'number', required: true },
        { name: 'pricePerShareUgx', label: 'Unit Share Price (UGX)', type: 'number', required: true },
        { name: 'paymentSourceAccount', label: 'Funding Source (Cash Till / Savings)', type: 'select', required: true }
      ],
      validationRules: ['SHARES_POSITIVE']
    },
    {
      id: 'FT-FORM-TILL-TRANSFER',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-VAULT-CASH',
      code: 'FT-FORM-TILL-TRANSFER',
      title: 'Cash Vault to Teller Till Cash Transfer Voucher',
      submitAction: 'fintech.vault.transferToTill',
      fieldCount: 4,
      fields: [
        { name: 'tellerUserId', label: 'Receiving Teller User ID', type: 'text', required: true },
        { name: 'cashAmountUgx', label: 'Transfer Cash Amount (UGX)', type: 'number', required: true },
        { name: 'headTellerAuthPin', label: 'Head Teller Authorization PIN', type: 'password', required: true },
        { name: 'managerDualPin', label: 'Branch Manager Dual Key PIN', type: 'password', required: true }
      ],
      validationRules: ['DUAL_AUTH_REQUIRED']
    },
    {
      id: 'FT-FORM-LOAN-APP',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-LOAN-UNDERWRITING',
      code: 'FT-FORM-LOAN-APP',
      title: 'SACCO Credit Application & Appraisal Docket',
      submitAction: 'fintech.loans.appraiseApplication',
      fieldCount: 5,
      fields: [
        { name: 'memberAccountNo', label: 'Borrower Member Account No', type: 'text', required: true },
        { name: 'loanProductType', label: 'Loan Product (Business / Agriculture / Emergency)', type: 'select', required: true },
        { name: 'requestedAmountUgx', label: 'Requested Loan Principal (UGX)', type: 'number', required: true },
        { name: 'repaymentPeriodMonths', label: 'Repayment Period (Months)', type: 'number', required: true },
        { name: 'monthlyNetIncomeUgx', label: 'Verified Monthly Net Income (UGX)', type: 'number', required: true }
      ],
      validationRules: ['LOAN_ELIGIBLE']
    },
    {
      id: 'FT-FORM-COLLATERAL-REG',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-CRB-COLLATERAL',
      code: 'FT-FORM-COLLATERAL-REG',
      title: 'Collateral Asset Registration & Valuation',
      submitAction: 'fintech.crb.registerCollateralLien',
      fieldCount: 4,
      fields: [
        { name: 'loanApplicationRef', label: 'Loan Application Reference', type: 'text', required: true },
        { name: 'assetType', label: 'Collateral Type (Land Title / Logbook / Chattel)', type: 'select', required: true },
        { name: 'openMarketValueUgx', label: 'Open Market Valuation (UGX)', type: 'number', required: true },
        { name: 'haircutDiscountPercent', label: 'Valuation Haircut Discount (e.g. 40%)', type: 'number', required: true }
      ],
      validationRules: ['COLLATERAL_VALID']
    },
    {
      id: 'FT-FORM-MOMO-DISBURSE',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-DIGITAL-MOMO',
      code: 'FT-FORM-MOMO-DISBURSE',
      title: 'Instant B2C Mobile Money Disbursement Order',
      submitAction: 'fintech.momo.disburseB2C',
      fieldCount: 4,
      fields: [
        { name: 'recipientPhoneNumber', label: 'Recipient Mobile Money Phone Number', type: 'text', required: true },
        { name: 'disbursementAmountUgx', label: 'Disbursement Amount (UGX)', type: 'number', required: true },
        { name: 'telecomNetwork', label: 'Network Operator (MTN / Airtel)', type: 'select', required: true },
        { name: 'idempotencyKey', label: 'Unique Transaction Idempotency Key', type: 'text', required: true }
      ],
      validationRules: ['PHONE_VALID']
    },
    {
      id: 'FT-FORM-JOURNAL-ENTRY',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-GENERAL-LEDGER',
      code: 'FT-FORM-JOURNAL-ENTRY',
      title: 'Double-Entry General Ledger Journal Entry',
      submitAction: 'fintech.gl.postJournalVoucher',
      fieldCount: 4,
      fields: [
        { name: 'debitAccountCode', label: 'Debit Account (Chart of Accounts Code)', type: 'text', required: true },
        { name: 'creditAccountCode', label: 'Credit Account (Chart of Accounts Code)', type: 'text', required: true },
        { name: 'transactionAmountUgx', label: 'Balanced Transaction Amount (UGX)', type: 'number', required: true },
        { name: 'narrativeDescription', label: 'Journal Description Narrative', type: 'textarea', required: true }
      ],
      validationRules: ['BALANCED_DEBIT_CREDIT']
    },
    {
      id: 'FT-FORM-AML-REPORT',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-UMRA-COMPLIANCE',
      code: 'FT-FORM-AML-REPORT',
      title: 'Financial Intelligence Authority (FIA) Large Cash Report',
      submitAction: 'fintech.compliance.flagLargeCashCTR',
      fieldCount: 4,
      fields: [
        { name: 'transactionRef', label: 'Core Banking Transaction Ref', type: 'text', required: true },
        { name: 'memberAccountNo', label: 'Transacting Member Account ID', type: 'text', required: true },
        { name: 'cashAmountUgx', label: 'Reportable Cash Amount (UGX)', type: 'number', required: true },
        { name: 'sourceOfFundsProof', label: 'Declared Source of Funds & Purpose', type: 'textarea', required: true }
      ],
      validationRules: ['CTR_THRESHOLD_MET']
    }
  ],
  dashboards: [
    {
      id: 'FT-DASH-BANKING',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-SAVINGS-ACCOUNTS',
      code: 'FT-DASH-BANKING',
      title: 'Core Banking, Savings Deposits & Shares',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Enrolled SACCO Members', value: '8,920 Members', trend: 'up', change: 'KYC Verified' },
        { label: 'Total Savings Deposit Balance', value: 'UGX 4.85 Billion', trend: 'up', change: 'Compulsory & Fixed' },
        { label: 'Paid-Up Share Capital', value: 'UGX 1.12 Billion', trend: 'up', change: 'Institutional Equity' },
        { label: 'Vault Cash Liquidity', value: 'UGX 185 Million', trend: 'neutral', change: 'In Branch Strongroom' }
      ]
    },
    {
      id: 'FT-DASH-CREDIT',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-LOAN-UNDERWRITING',
      code: 'FT-DASH-CREDIT',
      title: 'Credit Risk, Loan Portfolio & PAR Arrears',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Gross Performing Loan Book', value: 'UGX 3.42 Billion', trend: 'up', change: '1,240 Active Loans' },
        { label: 'Portfolio At Risk (PAR > 30)', value: '3.8%', trend: 'down', change: 'UMRA Benchmark < 5%' },
        { label: 'CRB Query Clearance Ratio', value: '94.2%', trend: 'up', change: 'Real-Time Check' },
        { label: 'Secured Collateral Coverage', value: '185% Ratio', trend: 'up', change: 'After 40% Haircut' }
      ]
    },
    {
      id: 'FT-DASH-DIGITAL',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-DIGITAL-MOMO',
      code: 'FT-DASH-DIGITAL',
      title: 'Mobile Money Gateway & USSD Switching',
      widgetCount: 4,
      kpiMetrics: [
        { label: '24-Hour B2C Loan Disbursements', value: 'UGX 84.5 Million', trend: 'up', change: 'Instant MoMo Pushes' },
        { label: 'C2B Savings Collections', value: 'UGX 142 Million', trend: 'up', change: 'Digital Pay Webhooks' },
        { label: 'Active Telecom Float Wallet', value: 'UGX 92 Million', trend: 'neutral', change: 'MTN & Airtel Float' },
        { label: 'Switch API Success Rate', value: '99.94%', trend: 'up', change: 'JUMO DIGITAL PAY' }
      ]
    },
    {
      id: 'FT-DASH-COMPLIANCE',
      productId: 'prod-fintech',
      moduleId: 'FT-MOD-UMRA-COMPLIANCE',
      code: 'FT-DASH-COMPLIANCE',
      title: 'UMRA Regulatory Ratios & Double-Entry Balance Sheet',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'UMRA Liquidity Ratio', value: '22.4%', trend: 'up', change: 'Min Required: 15%' },
        { label: 'Core Capital Adequacy Ratio', value: '18.6%', trend: 'up', change: 'Min Required: 10%' },
        { label: 'FIA Reportable CTR Alerts', value: '3 Flagged', trend: 'neutral', change: 'Trans >= 20M UGX' },
        { label: 'General Ledger Balancing', value: '100% In Balance', trend: 'up', change: 'Debits = Credits' }
      ]
    }
  ],
  reports: [
    { id: 'FT-REP-KYC', productId: 'prod-fintech', moduleId: 'FT-MOD-MEMBER-KYC', code: 'FT-REP-KYC', title: 'SACCO Member Registry & KYC Verification Audit', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'FT-REP-SAVINGS', productId: 'prod-fintech', moduleId: 'FT-MOD-SAVINGS-ACCOUNTS', code: 'FT-REP-SAVINGS', title: 'Savings Deposits Ledger & Fixed Deposit Maturity Schedule', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'FT-REP-SHARES', productId: 'prod-fintech', moduleId: 'FT-MOD-SHARE-CAPITAL', code: 'FT-REP-SHARES', title: 'Member Share Capital Register & Dividend Distribution Ledger', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'FT-REP-VAULT', productId: 'prod-fintech', moduleId: 'FT-MOD-VAULT-CASH', code: 'FT-REP-VAULT', title: 'Cash Vault & Branch Teller Till Daily Balance Logbook', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] },
    { id: 'FT-REP-LOANS', productId: 'prod-fintech', moduleId: 'FT-MOD-LOAN-UNDERWRITING', code: 'FT-REP-LOANS', title: 'Loan Portfolio Quality & Aging PAR Arrears Report', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'XLSX'] },
    { id: 'FT-REP-COLLATERAL', productId: 'prod-fintech', moduleId: 'FT-MOD-CRB-COLLATERAL', code: 'FT-REP-COLLATERAL', title: 'Collateral Perfection Register & URSB SIMPO Liens', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'FT-REP-MOMO', productId: 'prod-fintech', moduleId: 'FT-MOD-DIGITAL-MOMO', code: 'FT-REP-MOMO', title: 'Mobile Money Gateway B2C/C2B Settlement Statement', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX', 'CSV'] },
    { id: 'FT-REP-GL', productId: 'prod-fintech', moduleId: 'FT-MOD-GENERAL-LEDGER', code: 'FT-REP-GL', title: 'Monthly Trial Balance, Income Statement & Balance Sheet', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'FT-REP-UMRA', productId: 'prod-fintech', moduleId: 'FT-MOD-UMRA-COMPLIANCE', code: 'FT-REP-UMRA', title: 'Official UMRA Tier-4 Quarterly Prudential Regulatory Return', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'XLSX'] }
  ],
  workflows: [
    { id: 'FT-WF-KYC', productId: 'prod-fintech', moduleId: 'FT-MOD-MEMBER-KYC', code: 'FT-WF-KYC', title: 'Member Onboarding & NIRA NIN Vetting Workflow', stages: ['APPLIED', 'NIN_VERIFIED', 'ACCOUNT_ACTIVATED'], slaHours: 24, requiredApprovers: ['ROLE_FT_CREDIT_OFFICER'], initialState: 'APPLIED' },
    { id: 'FT-WF-SAVINGS', productId: 'prod-fintech', moduleId: 'FT-MOD-SAVINGS-ACCOUNTS', code: 'FT-WF-SAVINGS', title: 'Fixed Deposit Booking & Maturity Workflow', stages: ['BOOKED', 'RUNNING', 'MATURED_DISBURSED'], slaHours: 12, requiredApprovers: ['ROLE_FT_TELLER', 'ROLE_FT_CFO'], initialState: 'BOOKED' },
    { id: 'FT-WF-SHARES', productId: 'prod-fintech', moduleId: 'FT-MOD-SHARE-CAPITAL', code: 'FT-WF-SHARES', title: 'Share Capital Purchase & Certificate Workflow', stages: ['SUBSCRIBED', 'PAID', 'CERTIFICATE_SEALED'], slaHours: 48, requiredApprovers: ['ROLE_FT_CFO'], initialState: 'SUBSCRIBED' },
    { id: 'FT-WF-VAULT', productId: 'prod-fintech', moduleId: 'FT-MOD-VAULT-CASH', code: 'FT-WF-VAULT', title: 'Teller Drawer Daily Requisition & Balancing Workflow', stages: ['ISSUED', 'OPERATING', 'BALANCED_CLOSED'], slaHours: 8, requiredApprovers: ['ROLE_FT_TELLER', 'ROLE_FT_CFO'], initialState: 'ISSUED' },
    { id: 'FT-WF-LOANS', productId: 'prod-fintech', moduleId: 'FT-MOD-LOAN-UNDERWRITING', code: 'FT-WF-LOANS', title: 'Loan Appraisal, Committee Approval & Disbursement Workflow', stages: ['APPRAISED', 'CRB_CLEARED', 'COMMITTEE_APPROVED', 'DISBURSED'], slaHours: 48, requiredApprovers: ['ROLE_FT_CREDIT_OFFICER', 'ROLE_FT_CEO'], initialState: 'APPRAISED' },
    { id: 'FT-WF-COLLATERAL', productId: 'prod-fintech', moduleId: 'FT-MOD-CRB-COLLATERAL', code: 'FT-WF-COLLATERAL', title: 'Collateral Inspection & Lien Registration Workflow', stages: ['INSPECTED', 'HAIRCUT_APPLIED', 'LIEN_PERFECTED'], slaHours: 72, requiredApprovers: ['ROLE_FT_CREDIT_OFFICER'], initialState: 'INSPECTED' },
    { id: 'FT-WF-MOMO', productId: 'prod-fintech', moduleId: 'FT-MOD-DIGITAL-MOMO', code: 'FT-WF-MOMO', title: 'Digital Pay B2C Disbursement Gateway Workflow', stages: ['INITIATED', 'GATEWAY_PUSHED', 'CONFIRMED_SUCCESS'], slaHours: 1, requiredApprovers: ['ROLE_FT_CFO'], initialState: 'INITIATED' },
    { id: 'FT-WF-GL', productId: 'prod-fintech', moduleId: 'FT-MOD-GENERAL-LEDGER', code: 'FT-WF-GL', title: 'Financial Month-End Journal Closing Workflow', stages: ['JOURNALED', 'TRIAL_BALANCED', 'PERIOD_CLOSED'], slaHours: 24, requiredApprovers: ['ROLE_FT_CFO', 'ROLE_FT_CEO'], initialState: 'JOURNALED' },
    { id: 'FT-WF-UMRA', productId: 'prod-fintech', moduleId: 'FT-MOD-UMRA-COMPLIANCE', code: 'FT-WF-UMRA', title: 'UMRA Regulatory Prudential Return Filing Workflow', stages: ['COMPILED', 'BOARD_REVIEWED', 'UMRA_SUBMITTED'], slaHours: 168, requiredApprovers: ['ROLE_FT_CEO', 'ROLE_FT_CFO'], initialState: 'COMPILED' }
  ],
  databaseEntities: [
    { id: 'FT-DB-MEMBERS-CIF', productId: 'prod-fintech', moduleId: 'FT-MOD-MEMBER-KYC', tableName: 'ft_members_cif', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'member_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'full_name', type: 'VARCHAR(255)', required: true }, { name: 'phone', type: 'VARCHAR(20)', required: true }], auditLogged: true },
    { id: 'FT-DB-SAVINGS-ACCOUNTS', productId: 'prod-fintech', moduleId: 'FT-MOD-SAVINGS-ACCOUNTS', tableName: 'ft_savings_accounts', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'account_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'member_id', type: 'UUID', required: true, indexed: true }, { name: 'balance', type: 'DECIMAL(18,2)', required: true }, { name: 'currency', type: 'VARCHAR(3)', required: true }], auditLogged: true },
    { id: 'FT-DB-SHARES-LEDGER', productId: 'prod-fintech', moduleId: 'FT-MOD-SHARE-CAPITAL', tableName: 'ft_shares_ledger', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'member_id', type: 'UUID', required: true, indexed: true }, { name: 'shares_owned', type: 'INTEGER', required: true }, { name: 'par_value', type: 'DECIMAL(18,2)', required: true }, { name: 'total_value', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'FT-DB-VAULT-LEDGER', productId: 'prod-fintech', moduleId: 'FT-MOD-VAULT-CASH', tableName: 'ft_vault_ledger', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'vault_type', type: 'VARCHAR(50)', required: true }, { name: 'opening_balance', type: 'DECIMAL(18,2)', required: true }, { name: 'closing_balance', type: 'DECIMAL(18,2)', required: true }, { name: 'teller_id', type: 'UUID', required: false }], auditLogged: true },
    { id: 'FT-DB-LOANS-PORTFOLIO', productId: 'prod-fintech', moduleId: 'FT-MOD-LOAN-UNDERWRITING', tableName: 'ft_loans_portfolio', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'loan_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'principal', type: 'DECIMAL(18,2)', required: true }, { name: 'interest_rate', type: 'DECIMAL(5,2)', required: true }, { name: 'tenor_months', type: 'INTEGER', required: true }, { name: 'outstanding_balance', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'FT-DB-COLLATERAL-REGISTRY', productId: 'prod-fintech', moduleId: 'FT-MOD-CRB-COLLATERAL', tableName: 'ft_collateral_registry', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'loan_id', type: 'UUID', required: true, indexed: true }, { name: 'collateral_type', type: 'VARCHAR(50)', required: true }, { name: 'market_value', type: 'DECIMAL(18,2)', required: true }, { name: 'forced_sale_value', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'FT-DB-MOMO-TRANSACTIONS', productId: 'prod-fintech', moduleId: 'FT-MOD-DIGITAL-MOMO', tableName: 'ft_momo_transactions', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'tx_ref', type: 'VARCHAR(100)', required: true, indexed: true }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }, { name: 'phone_number', type: 'VARCHAR(20)', required: true }, { name: 'status', type: 'VARCHAR(30)', required: true }], auditLogged: true },
    { id: 'FT-DB-GENERAL-LEDGER', productId: 'prod-fintech', moduleId: 'FT-MOD-GENERAL-LEDGER', tableName: 'ft_general_ledger', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'journal_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'account_code', type: 'VARCHAR(20)', required: true, indexed: true }, { name: 'debit', type: 'DECIMAL(18,2)', required: true }, { name: 'credit', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'FT-DB-COMPLIANCE-REPORTS', productId: 'prod-fintech', moduleId: 'FT-MOD-UMRA-COMPLIANCE', tableName: 'ft_compliance_reports', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'quarter', type: 'VARCHAR(10)', required: true }, { name: 'year', type: 'INTEGER', required: true }, { name: 'liquidity_ratio', type: 'DECIMAL(5,2)', required: true }, { name: 'capital_adequacy', type: 'DECIMAL(5,2)', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'FT-API-KYC', productId: 'prod-fintech', moduleId: 'FT-MOD-MEMBER-KYC', code: 'API_FT_KYC', method: 'POST', endpoint: '/api/v1/fintech/members/onboard', requiredPermission: 'FT-PERM-CORE-BANKING', handlerName: 'onboardMemberHandler', summary: 'Onboard member and create CIF record.' },
    { id: 'FT-API-SAVINGS', productId: 'prod-fintech', moduleId: 'FT-MOD-SAVINGS-ACCOUNTS', code: 'API_FT_SAVINGS', method: 'POST', endpoint: '/api/v1/fintech/savings/deposit', requiredPermission: 'FT-PERM-CORE-BANKING', handlerName: 'postSavingsDepositHandler', summary: 'Post savings deposit transaction.' },
    { id: 'FT-API-SHARES', productId: 'prod-fintech', moduleId: 'FT-MOD-SHARE-CAPITAL', code: 'API_FT_SHARES', method: 'POST', endpoint: '/api/v1/fintech/shares/purchase', requiredPermission: 'FT-PERM-CORE-BANKING', handlerName: 'purchaseSharesHandler', summary: 'Purchase SACCO member share capital.' },
    { id: 'FT-API-VAULT', productId: 'prod-fintech', moduleId: 'FT-MOD-VAULT-CASH', code: 'API_FT_VAULT', method: 'POST', endpoint: '/api/v1/fintech/vault/till-transfer', requiredPermission: 'FT-PERM-CORE-BANKING', handlerName: 'vaultTransferHandler', summary: 'Execute strongroom vault to teller transfer.' },
    { id: 'FT-API-LOANS', productId: 'prod-fintech', moduleId: 'FT-MOD-LOAN-UNDERWRITING', code: 'API_FT_LOANS', method: 'POST', endpoint: '/api/v1/fintech/loans/appraise', requiredPermission: 'FT-PERM-CREDIT-RISK', handlerName: 'appraiseLoanHandler', summary: 'Appraise loan and calculate DSCR.' },
    { id: 'FT-API-CRB', productId: 'prod-fintech', moduleId: 'FT-MOD-CRB-COLLATERAL', code: 'API_FT_CRB', method: 'POST', endpoint: '/api/v1/fintech/crb/query', requiredPermission: 'FT-PERM-CREDIT-RISK', handlerName: 'queryCrbHandler', summary: 'Query real-time CRB credit reference.' },
    { id: 'FT-API-MOMO', productId: 'prod-fintech', moduleId: 'FT-MOD-DIGITAL-MOMO', code: 'API_FT_MOMO', method: 'POST', endpoint: '/api/v1/fintech/momo/disburse', requiredPermission: 'FT-PERM-DIGITAL-PAY', handlerName: 'disburseMomoLoanHandler', summary: 'Disburse B2C Mobile Money loan via Digital Pay.' },
    { id: 'FT-API-GL', productId: 'prod-fintech', moduleId: 'FT-MOD-GENERAL-LEDGER', code: 'API_FT_GL', method: 'POST', endpoint: '/api/v1/fintech/gl/journal', requiredPermission: 'FT-PERM-FINANCE-AUDIT', handlerName: 'postGlJournalHandler', summary: 'Post double-entry financial journal.' },
    { id: 'FT-API-UMRA', productId: 'prod-fintech', moduleId: 'FT-MOD-UMRA-COMPLIANCE', code: 'API_FT_UMRA', method: 'POST', endpoint: '/api/v1/fintech/compliance/umra-returns', requiredPermission: 'FT-PERM-FINANCE-AUDIT', handlerName: 'exportUmraReturnHandler', summary: 'Export UMRA statutory return.' }
  ],
  runtimeComponents: [
    { id: 'FT-RTC-KYC', productId: 'prod-fintech', moduleId: 'FT-MOD-MEMBER-KYC', componentKey: 'FintechKycEngine', name: 'Member CIF & Biometric KYC Engine', description: 'Real-time biometric KYC and NIRA National ID verification terminal.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MEMBERSHIP_CIF' },
    { id: 'FT-RTC-SAVINGS', productId: 'prod-fintech', moduleId: 'FT-MOD-SAVINGS-ACCOUNTS', componentKey: 'FintechSavingsEngine', name: 'Savings Accounts & Fixed Deposits Engine', description: 'Core deposit account manager, interest accrual engine, and term deposits.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'DEPOSITS_CORE' },
    { id: 'FT-RTC-SHARES', productId: 'prod-fintech', moduleId: 'FT-MOD-SHARE-CAPITAL', componentKey: 'FintechSharesEngine', name: 'Share Capital & Dividend Ledger Engine', description: 'Institutional share registry and annual cooperative dividend distribution.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EQUITY_SHARES' },
    { id: 'FT-RTC-VAULT', productId: 'prod-fintech', moduleId: 'FT-MOD-VAULT-CASH', componentKey: 'FintechVaultEngine', name: 'Cash Vault & Dual-Custody Strongroom Engine', description: 'Dual-custody strongroom vault balancing, denomination counts, and till audits.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CASH_OPERATIONS' },
    { id: 'FT-RTC-LOANS', productId: 'prod-fintech', moduleId: 'FT-MOD-LOAN-UNDERWRITING', componentKey: 'FintechLoansEngine', name: 'Loan Underwriting, Amortization & PAR Engine', description: 'Credit scoring engine, amortization scheduler, and PAR delinquency tracker.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CREDIT_LENDING' },
    { id: 'FT-RTC-COLLATERAL', productId: 'prod-fintech', moduleId: 'FT-MOD-CRB-COLLATERAL', componentKey: 'FintechCollateralEngine', name: 'CRB Credit Reference & Collateral Lien Engine', description: 'Automated Metropol/Compuscan CRB scoring and chattel lien registration.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CREDIT_LENDING' },
    { id: 'FT-RTC-MOMO', productId: 'prod-fintech', moduleId: 'FT-MOD-DIGITAL-MOMO', componentKey: 'FintechMomoEngine', name: 'Mobile Money Gateway Switch & B2C/C2B Engine', description: 'Direct telecom integration for instant mobile loan disbursement and collections.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'PAYMENTS_SWITCH' },
    { id: 'FT-RTC-GL', productId: 'prod-fintech', moduleId: 'FT-MOD-GENERAL-LEDGER', componentKey: 'FintechGlEngine', name: 'Double-Entry General Ledger & Balance Sheet Engine', description: 'Automated FAAP journal posting, trial balance, and financial statement generator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ACCOUNTING_GL' },
    { id: 'FT-RTC-UMRA', productId: 'prod-fintech', moduleId: 'FT-MOD-UMRA-COMPLIANCE', componentKey: 'FintechUmraEngine', name: 'UMRA Prudential Compliance & AML/CFT Engine', description: 'Tier-4 microfinance statutory returns, capital adequacy, and CTR filing.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'REGULATORY_COMPLIANCE' }
  ],
  permissions: [
    { id: 'FT-PERM-CORE-BANKING', productId: 'prod-fintech', code: 'PERM_FT_CORE_BANKING', name: 'Core Banking Operations & Tellers', description: 'Perform teller deposits, withdrawals, and customer CIF management.' },
    { id: 'FT-PERM-CREDIT-RISK', productId: 'prod-fintech', code: 'PERM_FT_CREDIT_UNDERWRITING', name: 'Credit Risk & Loan Underwriting', description: 'Appraise loans, query CRB, and approve credit facilities.' },
    { id: 'FT-PERM-DIGITAL-PAY', productId: 'prod-fintech', code: 'PERM_FT_DIGITAL_CHANNELS', name: 'Mobile Money Gateway & Switching', description: 'Manage digital payment switches, bulk disbursements, and telecom floats.' },
    { id: 'FT-PERM-FINANCE-AUDIT', productId: 'prod-fintech', code: 'PERM_FT_GL_COMPLIANCE', name: 'General Ledger & UMRA Audit', description: 'Post financial journals, trial balance, and export statutory regulatory returns.' }
  ],
  roles: [
    { id: 'FT-ROLE-CEO', productId: 'prod-fintech', code: 'ROLE_FT_CEO', name: 'Chief Executive Officer / SACCO GM', tier: 'GOVERNANCE', permissionIds: ['FT-PERM-CORE-BANKING', 'FT-PERM-CREDIT-RISK', 'FT-PERM-DIGITAL-PAY', 'FT-PERM-FINANCE-AUDIT'] },
    { id: 'FT-ROLE-CREDIT-OFFICER', productId: 'prod-fintech', code: 'ROLE_FT_CREDIT_OFFICER', name: 'Credit Risk Officer', tier: 'OPERATIONAL', permissionIds: ['FT-PERM-CREDIT-RISK'] },
    { id: 'FT-ROLE-TELLER', productId: 'prod-fintech', code: 'ROLE_FT_TELLER', name: 'Cashier / Teller', tier: 'OPERATIONAL', permissionIds: ['FT-PERM-CORE-BANKING'] },
    { id: 'FT-ROLE-CFO', productId: 'prod-fintech', code: 'ROLE_FT_CFO', name: 'Chief Financial Officer', tier: 'EXECUTIVE', permissionIds: ['FT-PERM-FINANCE-AUDIT', 'FT-PERM-CORE-BANKING'] }
  ]
};
