import { CanonicalProductHierarchy } from './types';

export const NATIONAL_HEALTH_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-national-health',
    code: 'HEALTH',
    name: 'National Health Platform',
    category: 'SOVEREIGN_PLATFORM',
    description: 'National electronic medical record (EMR), hospital clinical workflows, DHIS2 disease surveillance, centralized pharmaceutical supply chain, laboratory diagnostics, and universal health insurance coverage.',
    version: '2026.4.0',
    iconName: 'HeartPulse',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Director General of Sovereign Health Services',
    governingLegislation: 'Public Health Act & Sovereign Clinical Information Standards 2026',
    directorateIds: ['HLT-DIR-001', 'HLT-DIR-002', 'HLT-DIR-003', 'HLT-DIR-004']
  },
  directorates: [
    {
      id: 'HLT-DIR-001',
      productId: 'prod-national-health',
      code: 'HLT-DIR-CLINICAL',
      name: 'Directorate of Clinical Services & Hospital Operations',
      description: 'Patient admissions, outpatient departments (OPD), inpatient care (IPD), surgical theater scheduling, and emergency triage.',
      leadRole: 'DIRECTOR_CLINICAL_SERVICES',
      departmentIds: ['HLT-DEPT-001', 'HLT-DEPT-002', 'HLT-DEPT-003']
    },
    {
      id: 'HLT-DIR-002',
      productId: 'prod-national-health',
      code: 'HLT-DIR-DIAGNOSTIC',
      name: 'Directorate of Diagnostic Pathology & Laboratory Network',
      description: 'National public health laboratories, blood transfusion services, molecular diagnostics, and imaging radiology.',
      leadRole: 'DIRECTOR_DIAGNOSTICS',
      departmentIds: ['HLT-DEPT-004', 'HLT-DEPT-005']
    },
    {
      id: 'HLT-DIR-003',
      productId: 'prod-national-health',
      code: 'HLT-DIR-EPIDEMIOLOGY',
      name: 'Directorate of Public Health & Epidemic Surveillance',
      description: 'Real-time outbreak detection, DHIS2 reporting, EPI immunization tracking, and maternal & child health (MCH).',
      leadRole: 'CHIEF_EPIDEMIOLOGIST',
      departmentIds: ['HLT-DEPT-006', 'HLT-DEPT-007']
    },
    {
      id: 'HLT-DIR-004',
      productId: 'prod-national-health',
      code: 'HLT-DIR-SUPPLY-FINANCE',
      name: 'Directorate of Pharmaceutical Supply & Health Insurance',
      description: 'National medical stores logistics, cold-chain monitoring, drug dispensing, and SHIF/NHIF claims adjudication.',
      leadRole: 'DIRECTOR_PHARMA_FINANCE',
      departmentIds: ['HLT-DEPT-008', 'HLT-DEPT-009']
    }
  ],
  departments: [
    {
      id: 'HLT-DEPT-001',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      code: 'HLT-DEPT-TRIAGE',
      name: 'Department of Emergency Triage & Outpatient Intake',
      description: 'NIN-linked patient registration, vital signs logging, and Manchester triage sorting.',
      headRole: 'HEAD_TRIAGE_PHYSICIAN',
      officeIds: ['HLT-OFF-001', 'HLT-OFF-002']
    },
    {
      id: 'HLT-DEPT-002',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      code: 'HLT-DEPT-INPATIENT',
      name: 'Department of Inpatient Wards & Surgical Theater',
      description: 'Bed occupancy management, doctor ward rounds, medication charts, and post-op care.',
      headRole: 'HEAD_INPATIENT_SURGEON',
      officeIds: ['HLT-OFF-003']
    },
    {
      id: 'HLT-DEPT-003',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      code: 'HLT-DEPT-EMR',
      name: 'Department of Electronic Medical Records & Referrals',
      description: 'HL7/FHIR compliant health records, ICD-11 coding, and inter-hospital ambulance referrals.',
      headRole: 'HEAD_HEALTH_INFORMATICS',
      officeIds: ['HLT-OFF-004']
    },
    {
      id: 'HLT-DEPT-004',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-002',
      code: 'HLT-DEPT-LAB',
      name: 'Department of Clinical Laboratory & Pathology',
      description: 'Hematology, biochemistry, microbiology, viral load testing, and automated analyzer interfaces.',
      headRole: 'HEAD_PATHOLOGIST',
      officeIds: ['HLT-OFF-005']
    },
    {
      id: 'HLT-DEPT-005',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-002',
      code: 'HLT-DEPT-BLOOD',
      name: 'Department of National Blood Bank & Transfusion',
      description: 'Blood donor drives, serological screening, cold storage inventory, and cross-matching.',
      headRole: 'HEAD_BLOOD_BANK',
      officeIds: ['HLT-OFF-006']
    },
    {
      id: 'HLT-DEPT-006',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      code: 'HLT-DEPT-SURVEILLANCE',
      name: 'Department of Integrated Disease Surveillance & Response (IDSR)',
      description: 'Early warning alerts for cholera, Ebola, malaria, and COVID-19 with GPS clustering.',
      headRole: 'HEAD_IDSR_RESPONSE',
      officeIds: ['HLT-OFF-007']
    },
    {
      id: 'HLT-DEPT-007',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      code: 'HLT-DEPT-EPI-MCH',
      name: 'Department of Expanded Immunization & Maternal Care',
      description: 'National child vaccine schedule, antenatal care (ANC) visits, and maternal mortality audits.',
      headRole: 'HEAD_MCH_PROGRAMS',
      officeIds: ['HLT-OFF-008']
    },
    {
      id: 'HLT-DEPT-008',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      code: 'HLT-DEPT-PHARMACY',
      name: 'Department of Central Medical Stores & Pharmacy Dispensing',
      description: 'FEFO stock management, e-Prescriptions, batch recall, and dangerous drugs register.',
      headRole: 'CHIEF_PHARMACIST',
      officeIds: ['HLT-OFF-009', 'HLT-OFF-010']
    },
    {
      id: 'HLT-DEPT-009',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      code: 'HLT-DEPT-INSURANCE',
      name: 'Department of Universal Health Insurance Claims',
      description: 'Capitation tariffs, fee-for-service pre-authorization, diagnostic fraud checks, and billing.',
      headRole: 'HEAD_INSURANCE_CLAIMS',
      officeIds: ['HLT-OFF-011']
    }
  ],
  offices: [
    {
      id: 'HLT-OFF-001',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-001',
      code: 'HLT-OFF-OPD-RECEPTION',
      name: 'OPD Reception & Biometric Patient Vetting Desk',
      description: 'NIN lookup, biometric card tap, and medical record retrieval.',
      officerRole: 'OPD_REGISTRATION_CLERK',
      portalIds: ['HLT-PORTAL-001', 'HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-001']
    },
    {
      id: 'HLT-OFF-002',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-001',
      code: 'HLT-OFF-TRIAGE-NURSE',
      name: 'Clinical Triage & Vital Signs Station',
      description: 'Blood pressure, SpO2, blood glucose, temperature, and triage code assignment.',
      officerRole: 'TRIAGE_NURSE',
      portalIds: ['HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-001']
    },
    {
      id: 'HLT-OFF-003',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-002',
      code: 'HLT-OFF-SURGERY-WARD',
      name: 'Theater Scheduling & Ward Bed Management Office',
      description: 'Pre-op clearance, surgical checklist enforcement, and bed turnover.',
      officerRole: 'THEATER_SUPERVISOR',
      portalIds: ['HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-002']
    },
    {
      id: 'HLT-OFF-004',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-003',
      code: 'HLT-OFF-REFERRAL-DESK',
      name: 'National Patient Referral & Tele-Medicine Office',
      description: 'Dispatching ambulance transfers between Health Center IV and National Referral Hospital.',
      officerRole: 'REFERRAL_COORDINATOR',
      portalIds: ['HLT-PORTAL-001', 'HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-003']
    },
    {
      id: 'HLT-OFF-005',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-002',
      departmentId: 'HLT-DEPT-004',
      code: 'HLT-OFF-LAB-DISPATCH',
      name: 'Laboratory LIMS & Specimen Processing Desk',
      description: 'Barcode specimen labeling, analyzer result validation, and doctor alerts.',
      officerRole: 'LAB_SCIENTIST',
      portalIds: ['HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-004']
    },
    {
      id: 'HLT-OFF-006',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-002',
      departmentId: 'HLT-DEPT-005',
      code: 'HLT-OFF-BLOOD-CUSTODY',
      name: 'Blood Bank Cold Chain Custody Desk',
      description: 'Maintains refrigerated unit inventory and rapid emergency blood issue.',
      officerRole: 'BLOOD_BANK_OFFICER',
      portalIds: ['HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-005']
    },
    {
      id: 'HLT-OFF-007',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      departmentId: 'HLT-DEPT-006',
      code: 'HLT-OFF-EPIDEMIC-WAR-ROOM',
      name: 'Epidemic Situation Room & Outbreak Response Desk',
      description: '24/7 disease alert triaging, rapid response team dispatch, and WHO reporting.',
      officerRole: 'SURVEILLANCE_EPIDEMIOLOGIST',
      portalIds: ['HLT-PORTAL-001', 'HLT-PORTAL-003'],
      moduleIds: ['HLT-MOD-006']
    },
    {
      id: 'HLT-OFF-008',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      departmentId: 'HLT-DEPT-007',
      code: 'HLT-OFF-VACCINE-COLDCHAIN',
      name: 'National Immunization & Child Registry Desk',
      description: 'EPI vaccine batch tracking, SMS booster reminders to mothers, and digital certificates.',
      officerRole: 'IMMUNIZATION_OFFICER',
      portalIds: ['HLT-PORTAL-002', 'HLT-PORTAL-004'],
      moduleIds: ['HLT-MOD-007']
    },
    {
      id: 'HLT-OFF-009',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      departmentId: 'HLT-DEPT-008',
      code: 'HLT-OFF-PHARMA-DISPENSE',
      name: 'Hospital Pharmacy Dispensing Counter',
      description: 'e-Prescription fulfillment, drug interaction warning review, and patient dosage labeling.',
      officerRole: 'DISPENSING_PHARMACIST',
      portalIds: ['HLT-PORTAL-002'],
      moduleIds: ['HLT-MOD-008']
    },
    {
      id: 'HLT-OFF-010',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      departmentId: 'HLT-DEPT-008',
      code: 'HLT-OFF-DRUG-SUPPLY',
      name: 'Central Medical Stores & Logistics Office',
      description: 'Ordering essential medicines, tracking stock-outs, and batch expiry enforcement.',
      officerRole: 'MEDICAL_STORES_MANAGER',
      portalIds: ['HLT-PORTAL-001', 'HLT-PORTAL-003'],
      moduleIds: ['HLT-MOD-009']
    },
    {
      id: 'HLT-OFF-011',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      departmentId: 'HLT-DEPT-009',
      code: 'HLT-OFF-INSURANCE-CLAIMS',
      name: 'Health Insurance Pre-Authorization & Claims Desk',
      description: 'Tariff validation, biometric biometric attendance proof, and FAAP ledger reimbursement.',
      officerRole: 'HEALTH_CLAIMS_AUDITOR',
      portalIds: ['HLT-PORTAL-001', 'HLT-PORTAL-003'],
      moduleIds: ['HLT-MOD-010']
    }
  ],
  portals: [
    {
      id: 'HLT-PORTAL-001',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-001',
      officeId: 'HLT-OFF-001',
      code: 'HLT-PORTAL-EXECUTIVE',
      name: 'National Health Directorate & Hospital Executive Portal',
      description: 'Strategic hospital occupancy, national disease dashboard, budget execution, and policy control.',
      targetRole: 'MEDICAL_SUPERINTENDENT',
      authLevel: 'PKI_SOVEREIGN',
      route: '/health/executive',
      moduleIds: ['HLT-MOD-001', 'HLT-MOD-003', 'HLT-MOD-006', 'HLT-MOD-009', 'HLT-MOD-010']
    },
    {
      id: 'HLT-PORTAL-002',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-001',
      officeId: 'HLT-OFF-002',
      code: 'HLT-PORTAL-CLINICAL',
      name: 'Doctor, Nurse & Clinical Specialist Workspace',
      description: 'Doctor consultation room, prescription builder, lab orders, vital tracking, and surgical notes.',
      targetRole: 'CLINICAL_STAFF',
      authLevel: 'STAFF',
      route: '/health/clinical',
      moduleIds: ['HLT-MOD-001', 'HLT-MOD-002', 'HLT-MOD-004', 'HLT-MOD-005', 'HLT-MOD-007', 'HLT-MOD-008']
    },
    {
      id: 'HLT-PORTAL-003',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      departmentId: 'HLT-DEPT-006',
      officeId: 'HLT-OFF-007',
      code: 'HLT-PORTAL-SURVEILLANCE',
      name: 'Epidemiological Surveillance & Supply Chain Grid',
      description: 'District health intelligence, epidemic alert monitoring, and medical logistics tracking.',
      targetRole: 'EPIDEMIOLOGIST_OR_LOGISTICS',
      authLevel: 'OFFICER',
      route: '/health/surveillance',
      moduleIds: ['HLT-MOD-006', 'HLT-MOD-009', 'HLT-MOD-010']
    },
    {
      id: 'HLT-PORTAL-004',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      departmentId: 'HLT-DEPT-007',
      officeId: 'HLT-OFF-008',
      code: 'HLT-PORTAL-CITIZEN',
      name: 'Citizen Health Passport & Appointment Portal',
      description: 'Access personal immunization cards, lab results, upcoming doctor appointments, and insurance balance.',
      targetRole: 'PATIENT_CITIZEN',
      authLevel: 'PUBLIC',
      route: '/health/citizen-passport',
      moduleIds: ['HLT-MOD-003', 'HLT-MOD-007']
    }
  ],
  modules: [
    {
      id: 'HLT-MOD-001',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-001',
      officeId: 'HLT-OFF-001',
      portalId: 'HLT-PORTAL-002',
      code: 'HLT-MOD-OPD-TRIAGE',
      name: 'OPD Intake & Clinical Triage Engine',
      description: 'NIN-verified patient registration, electronic queueing, vital signs monitoring, and emergency priority scoring.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-001', 'HLT-CAP-002'],
      screenIds: ['HLT-SCR-001'],
      formIds: ['HLT-FORM-001'],
      dashboardIds: ['HLT-DASH-001'],
      reportIds: ['HLT-REP-001'],
      workflowIds: ['HLT-WF-001'],
      databaseEntityIds: ['HLT-DB-001'],
      apiIds: ['HLT-API-001'],
      runtimeComponentId: 'HLT-RTC-001',
      permissionIds: ['HLT-PERM-001']
    },
    {
      id: 'HLT-MOD-002',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-002',
      officeId: 'HLT-OFF-003',
      portalId: 'HLT-PORTAL-002',
      code: 'HLT-MOD-INPATIENT-THEATER',
      name: 'Inpatient Admission & Theater Scheduling',
      description: 'Ward bed allocation, doctor treatment orders, surgical theater bookings, and anesthesia checklists.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-003', 'HLT-CAP-004'],
      screenIds: ['HLT-SCR-002'],
      formIds: ['HLT-FORM-002'],
      dashboardIds: ['HLT-DASH-001'],
      reportIds: ['HLT-REP-002'],
      workflowIds: ['HLT-WF-002'],
      databaseEntityIds: ['HLT-DB-002'],
      apiIds: ['HLT-API-002'],
      runtimeComponentId: 'HLT-RTC-002',
      permissionIds: ['HLT-PERM-002']
    },
    {
      id: 'HLT-MOD-003',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-001',
      departmentId: 'HLT-DEPT-003',
      officeId: 'HLT-OFF-004',
      portalId: 'HLT-PORTAL-001',
      code: 'HLT-MOD-EMR-REFERRALS',
      name: 'FHIR Electronic Health Records & Referrals',
      description: 'Cross-facility patient longitudinal health summaries, allergy logs, ICD-11 diagnosis, and referral notes.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-005', 'HLT-CAP-006'],
      screenIds: ['HLT-SCR-003'],
      formIds: ['HLT-FORM-003'],
      dashboardIds: ['HLT-DASH-002'],
      reportIds: ['HLT-REP-003'],
      workflowIds: ['HLT-WF-003'],
      databaseEntityIds: ['HLT-DB-003'],
      apiIds: ['HLT-API-003'],
      runtimeComponentId: 'HLT-RTC-003',
      permissionIds: ['HLT-PERM-003']
    },
    {
      id: 'HLT-MOD-004',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-002',
      departmentId: 'HLT-DEPT-004',
      officeId: 'HLT-OFF-005',
      portalId: 'HLT-PORTAL-002',
      code: 'HLT-MOD-LIMS',
      name: 'Laboratory Information & Pathology LIMS',
      description: 'Lab test ordering, barcoded specimen tracking, automated analyzer telemetry, and digital doctor sign-off.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-007', 'HLT-CAP-008'],
      screenIds: ['HLT-SCR-004'],
      formIds: ['HLT-FORM-004'],
      dashboardIds: ['HLT-DASH-002'],
      reportIds: ['HLT-REP-004'],
      workflowIds: ['HLT-WF-004'],
      databaseEntityIds: ['HLT-DB-004'],
      apiIds: ['HLT-API-004'],
      runtimeComponentId: 'HLT-RTC-004',
      permissionIds: ['HLT-PERM-004']
    },
    {
      id: 'HLT-MOD-005',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-002',
      departmentId: 'HLT-DEPT-005',
      officeId: 'HLT-OFF-006',
      portalId: 'HLT-PORTAL-002',
      code: 'HLT-MOD-BLOOD-BANK',
      name: 'National Blood Bank & Transfusion Logistics',
      description: 'Blood unit serology screening, ABO/Rh typing, cold-chain temperature telemetry, and cross-match release.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-009', 'HLT-CAP-010'],
      screenIds: ['HLT-SCR-005'],
      formIds: ['HLT-FORM-005'],
      dashboardIds: [],
      reportIds: ['HLT-REP-005'],
      workflowIds: ['HLT-WF-005'],
      databaseEntityIds: ['HLT-DB-005'],
      apiIds: ['HLT-API-005'],
      runtimeComponentId: 'HLT-RTC-005',
      permissionIds: ['HLT-PERM-005']
    },
    {
      id: 'HLT-MOD-006',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      departmentId: 'HLT-DEPT-006',
      officeId: 'HLT-OFF-007',
      portalId: 'HLT-PORTAL-003',
      code: 'HLT-MOD-SURVEILLANCE-DHIS2',
      name: 'IDSR Outbreak Detection & DHIS2 Bridge',
      description: 'Real-time syndromic surveillance, geographic hotspot mapping, epidemic thresholds, and statutory alert dispatch.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-011', 'HLT-CAP-012'],
      screenIds: ['HLT-SCR-006'],
      formIds: [],
      dashboardIds: ['HLT-DASH-003'],
      reportIds: ['HLT-REP-006'],
      workflowIds: ['HLT-WF-006'],
      databaseEntityIds: ['HLT-DB-006'],
      apiIds: ['HLT-API-006'],
      runtimeComponentId: 'HLT-RTC-006',
      permissionIds: ['HLT-PERM-006']
    },
    {
      id: 'HLT-MOD-007',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-003',
      departmentId: 'HLT-DEPT-007',
      officeId: 'HLT-OFF-008',
      portalId: 'HLT-PORTAL-002',
      code: 'HLT-MOD-IMMUNIZATION-MCH',
      name: 'National Immunization & Maternal Care Engine',
      description: 'Child growth milestone charting, routine EPI immunization schedule, and antenatal care risk stratification.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-013', 'HLT-CAP-014'],
      screenIds: ['HLT-SCR-007'],
      formIds: ['HLT-FORM-006'],
      dashboardIds: ['HLT-DASH-003'],
      reportIds: ['HLT-REP-007'],
      workflowIds: ['HLT-WF-007'],
      databaseEntityIds: ['HLT-DB-007'],
      apiIds: ['HLT-API-007'],
      runtimeComponentId: 'HLT-RTC-007',
      permissionIds: ['HLT-PERM-007']
    },
    {
      id: 'HLT-MOD-008',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      departmentId: 'HLT-DEPT-008',
      officeId: 'HLT-OFF-009',
      portalId: 'HLT-PORTAL-002',
      code: 'HLT-MOD-EPRESCRIPTION',
      name: 'Clinical e-Prescription & Pharmacy Dispense',
      description: 'Digital doctor prescriptions, contraindication checks, dangerous drugs ledger, and patient counseling notes.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-015', 'HLT-CAP-016'],
      screenIds: ['HLT-SCR-008'],
      formIds: ['HLT-FORM-007'],
      dashboardIds: ['HLT-DASH-004'],
      reportIds: ['HLT-REP-008'],
      workflowIds: ['HLT-WF-008'],
      databaseEntityIds: ['HLT-DB-008'],
      apiIds: ['HLT-API-008'],
      runtimeComponentId: 'HLT-RTC-008',
      permissionIds: ['HLT-PERM-008']
    },
    {
      id: 'HLT-MOD-009',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      departmentId: 'HLT-DEPT-008',
      officeId: 'HLT-OFF-010',
      portalId: 'HLT-PORTAL-003',
      code: 'HLT-MOD-SUPPLY-CHAIN',
      name: 'Central Medical Stores & Cold-Chain Logistics',
      description: 'Essential medicines re-order points, warehouse inventory, vaccine cold-chain IoT, and stock-out alerts.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-017', 'HLT-CAP-018'],
      screenIds: ['HLT-SCR-009'],
      formIds: [],
      dashboardIds: ['HLT-DASH-004'],
      reportIds: ['HLT-REP-009'],
      workflowIds: ['HLT-WF-009'],
      databaseEntityIds: ['HLT-DB-009'],
      apiIds: ['HLT-API-009'],
      runtimeComponentId: 'HLT-RTC-009',
      permissionIds: ['HLT-PERM-009']
    },
    {
      id: 'HLT-MOD-010',
      productId: 'prod-national-health',
      directorateId: 'HLT-DIR-004',
      departmentId: 'HLT-DEPT-009',
      officeId: 'HLT-OFF-011',
      portalId: 'HLT-PORTAL-001',
      code: 'HLT-MOD-HEALTH-INSURANCE',
      name: 'Universal Health Insurance Claims Adjudication',
      description: 'National insurance pre-authorization, diagnostic DRG grouping, tariff validation, and FAAP payment settlement.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['HLT-CAP-019', 'HLT-CAP-020'],
      screenIds: ['HLT-SCR-010'],
      formIds: ['HLT-FORM-008'],
      dashboardIds: ['HLT-DASH-004'],
      reportIds: ['HLT-REP-010'],
      workflowIds: ['HLT-WF-010'],
      databaseEntityIds: ['HLT-DB-010'],
      apiIds: ['HLT-API-010'],
      runtimeComponentId: 'HLT-RTC-010',
      permissionIds: ['HLT-PERM-010']
    }
  ],
  capabilities: [
    { id: 'HLT-CAP-001', productId: 'prod-national-health', directorateId: 'HLT-DIR-001', departmentId: 'HLT-DEPT-001', officeId: 'HLT-OFF-001', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-001', code: 'HLT_CAP_REGISTER_PATIENT', name: 'NIN-Linked Patient Registration', description: 'Retrieves citizen biographic data from National Identity platform to create permanent medical dossier.', serviceAction: 'health.opd.registerPatient', requiredPermission: 'HLT-PERM-001', runtimeComponentId: 'HLT-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-002', productId: 'prod-national-health', directorateId: 'HLT-DIR-001', departmentId: 'HLT-DEPT-001', officeId: 'HLT-OFF-002', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-001', code: 'HLT_CAP_LOG_TRIAGE_VITALS', name: 'Capture Vital Signs & Triage Priority', description: 'Records pulse, blood pressure, oxygen saturation, and sets Emergency/Urgent/Routine priority code.', serviceAction: 'health.triage.logVitals', requiredPermission: 'HLT-PERM-001', runtimeComponentId: 'HLT-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-003', productId: 'prod-national-health', directorateId: 'HLT-DIR-001', departmentId: 'HLT-DEPT-002', officeId: 'HLT-OFF-003', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-002', code: 'HLT_CAP_ALLOCATE_BED', name: 'Assign Ward Bed & Medical Team', description: 'Reserves bed in general, ICU, or isolation ward with attending specialist assignment.', serviceAction: 'health.inpatient.allocateBed', requiredPermission: 'HLT-PERM-002', runtimeComponentId: 'HLT-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-004', productId: 'prod-national-health', directorateId: 'HLT-DIR-001', departmentId: 'HLT-DEPT-002', officeId: 'HLT-OFF-003', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-002', code: 'HLT_CAP_BOOK_SURGERY_THEATER', name: 'Schedule Surgical Theater Session', description: 'Books operating theater, surgeon, anesthetist, blood cross-match, and WHO surgical safety checklist.', serviceAction: 'health.theater.scheduleSurgery', requiredPermission: 'HLT-PERM-002', runtimeComponentId: 'HLT-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-005', productId: 'prod-national-health', directorateId: 'HLT-DIR-001', departmentId: 'HLT-DEPT-003', officeId: 'HLT-OFF-004', portalId: 'HLT-PORTAL-001', moduleId: 'HLT-MOD-003', code: 'HLT_CAP_FETCH_FHIR_RECORDS', name: 'Query National Longitudinal Health Summary', description: 'Fetches FHIR JSON bundle containing past surgeries, allergies, chronic conditions, and medications.', serviceAction: 'health.emr.fetchFhirSummary', requiredPermission: 'HLT-PERM-003', runtimeComponentId: 'HLT-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-006', productId: 'prod-national-health', directorateId: 'HLT-DIR-001', departmentId: 'HLT-DEPT-003', officeId: 'HLT-OFF-004', portalId: 'HLT-PORTAL-001', moduleId: 'HLT-MOD-003', code: 'HLT_CAP_INITIATE_REFERRAL', name: 'Issue Inter-Hospital Patient Referral', description: 'Generates secure transfer summary with ambulance telemetry and receiving doctor notification.', serviceAction: 'health.emr.issueReferral', requiredPermission: 'HLT-PERM-003', runtimeComponentId: 'HLT-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-007', productId: 'prod-national-health', directorateId: 'HLT-DIR-002', departmentId: 'HLT-DEPT-004', officeId: 'HLT-OFF-005', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-004', code: 'HLT_CAP_ORDER_LAB_TEST', name: 'Order Diagnostic Laboratory Panel', description: 'Submits electronic test request for CBC, malaria RDT, liver panel, or PCR with barcode label generation.', serviceAction: 'health.lims.orderTest', requiredPermission: 'HLT-PERM-004', runtimeComponentId: 'HLT-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-008', productId: 'prod-national-health', directorateId: 'HLT-DIR-002', departmentId: 'HLT-DEPT-004', officeId: 'HLT-OFF-005', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-004', code: 'HLT_CAP_VALIDATE_LAB_RESULTS', name: 'Authorize & Publish Laboratory Report', description: 'Validates quantitative analyzer readings against biological reference intervals and signs report.', serviceAction: 'health.lims.publishResults', requiredPermission: 'HLT-PERM-004', runtimeComponentId: 'HLT-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-009', productId: 'prod-national-health', directorateId: 'HLT-DIR-002', departmentId: 'HLT-DEPT-005', officeId: 'HLT-OFF-006', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-005', code: 'HLT_CAP_SCREEN_DONOR_BLOOD', name: 'Screen Donor Blood for Transfusion Safety', description: 'Validates negative ELISA/NAT testing for HIV, Hepatitis B/C, and Syphilis before releasing unit.', serviceAction: 'health.blood.screenUnit', requiredPermission: 'HLT-PERM-005', runtimeComponentId: 'HLT-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-010', productId: 'prod-national-health', directorateId: 'HLT-DIR-002', departmentId: 'HLT-DEPT-005', officeId: 'HLT-OFF-006', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-005', code: 'HLT_CAP_CROSSMATCH_AND_ISSUE', name: 'Perform Blood Cross-Match & Emergency Issue', description: 'Confirms recipient serum compatibility and issues unit with cold-chain transport tag.', serviceAction: 'health.blood.crossmatchIssue', requiredPermission: 'HLT-PERM-005', runtimeComponentId: 'HLT-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-011', productId: 'prod-national-health', directorateId: 'HLT-DIR-003', departmentId: 'HLT-DEPT-006', officeId: 'HLT-OFF-007', portalId: 'HLT-PORTAL-003', moduleId: 'HLT-MOD-006', code: 'HLT_CAP_INGEST_IDSR_NOTIFIABLE', name: 'Ingest Notifiable Disease Notification', description: 'Captures statutory alert for epidemic-prone disease within 2 hours of clinical suspicion.', serviceAction: 'health.surveillance.ingestAlert', requiredPermission: 'HLT-PERM-006', runtimeComponentId: 'HLT-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-012', productId: 'prod-national-health', directorateId: 'HLT-DIR-003', departmentId: 'HLT-DEPT-006', officeId: 'HLT-OFF-007', portalId: 'HLT-PORTAL-003', moduleId: 'HLT-MOD-006', code: 'HLT_CAP_EXPORT_DHIS2_AGGREGATES', name: 'Generate DHIS2 Monthly Epidemiological Return', description: 'Aggregates OPD/IPD disease tallies into national DHIS2 XML/JSON payload.', serviceAction: 'health.surveillance.exportDhis2', requiredPermission: 'HLT-PERM-006', runtimeComponentId: 'HLT-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-013', productId: 'prod-national-health', directorateId: 'HLT-DIR-003', departmentId: 'HLT-DEPT-007', officeId: 'HLT-OFF-008', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-007', code: 'HLT_CAP_RECORD_VACCINE_DOSE', name: 'Record Child Immunization Dose', description: 'Logs BCG, Polio, Pentavalent, Rotavirus, Measles with manufacturer batch and vial expiry.', serviceAction: 'health.immunization.recordDose', requiredPermission: 'HLT-PERM-007', runtimeComponentId: 'HLT-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-014', productId: 'prod-national-health', directorateId: 'HLT-DIR-003', departmentId: 'HLT-DEPT-007', officeId: 'HLT-OFF-008', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-007', code: 'HLT_CAP_AUDIT_MATERNAL_CARE', name: 'Antenatal Care Risk Assessment', description: 'Flags high-risk pregnancies (pre-eclampsia, gestational diabetes) for specialized delivery center referral.', serviceAction: 'health.mch.riskAssess', requiredPermission: 'HLT-PERM-007', runtimeComponentId: 'HLT-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-015', productId: 'prod-national-health', directorateId: 'HLT-DIR-004', departmentId: 'HLT-DEPT-008', officeId: 'HLT-OFF-009', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-008', code: 'HLT_CAP_AUTHORIZE_PRESCRIPTION', name: 'Issue Doctor e-Prescription', description: 'Prescribes medication with automated drug-drug interaction, allergy, and dosage checking.', serviceAction: 'health.pharma.prescribe', requiredPermission: 'HLT-PERM-008', runtimeComponentId: 'HLT-RTC-008', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-016', productId: 'prod-national-health', directorateId: 'HLT-DIR-004', departmentId: 'HLT-DEPT-008', officeId: 'HLT-OFF-009', portalId: 'HLT-PORTAL-002', moduleId: 'HLT-MOD-008', code: 'HLT_CAP_DISPENSE_MEDICATION', name: 'Dispense Medicine & Update Inventory', description: 'Decrements pharmacy stock, prints dosing label, and logs patient counseling confirmation.', serviceAction: 'health.pharma.dispense', requiredPermission: 'HLT-PERM-008', runtimeComponentId: 'HLT-RTC-008', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-017', productId: 'prod-national-health', directorateId: 'HLT-DIR-004', departmentId: 'HLT-DEPT-008', officeId: 'HLT-OFF-010', portalId: 'HLT-PORTAL-003', moduleId: 'HLT-MOD-009', code: 'HLT_CAP_MONITOR_COLDCHAIN_IOT', name: 'Monitor Vaccine Cold-Chain Telemetry', description: 'Ingests IoT temperature sensor logs (+2°C to +8°C) and raises excursion alerts.', serviceAction: 'health.stores.monitorColdChain', requiredPermission: 'HLT-PERM-009', runtimeComponentId: 'HLT-RTC-009', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-018', productId: 'prod-national-health', directorateId: 'HLT-DIR-004', departmentId: 'HLT-DEPT-008', officeId: 'HLT-OFF-010', portalId: 'HLT-PORTAL-003', moduleId: 'HLT-MOD-009', code: 'HLT_CAP_CALCULATE_REORDER_LEVELS', name: 'Predict Essential Drug Stock-Outs', description: 'Calculates consumption velocity and triggers automated purchase requisitions.', serviceAction: 'health.stores.calculateReorder', requiredPermission: 'HLT-PERM-009', runtimeComponentId: 'HLT-RTC-009', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-019', productId: 'prod-national-health', directorateId: 'HLT-DIR-004', departmentId: 'HLT-DEPT-009', officeId: 'HLT-OFF-011', portalId: 'HLT-PORTAL-001', moduleId: 'HLT-MOD-010', code: 'HLT_CAP_PREAUTH_INSURANCE_CLAIM', name: 'Pre-Authorize Medical Procedure Claim', description: 'Verifies citizen insurance policy coverage, annual limit, and approves admission capitation.', serviceAction: 'health.insurance.preAuthorize', requiredPermission: 'HLT-PERM-010', runtimeComponentId: 'HLT-RTC-010', status: 'ACTIVE_CORE' },
    { id: 'HLT-CAP-020', productId: 'prod-national-health', directorateId: 'HLT-DIR-004', departmentId: 'HLT-DEPT-009', officeId: 'HLT-OFF-011', portalId: 'HLT-PORTAL-001', moduleId: 'HLT-MOD-010', code: 'HLT_CAP_ADJUDICATE_HOSPITAL_BILL', name: 'Adjudicate Hospital Bill & Settle to FAAP', description: 'Audits diagnostic ICD-11 codes against treatment items and settles approved sum to hospital ledger.', serviceAction: 'health.insurance.settleClaim', requiredPermission: 'HLT-PERM-010', runtimeComponentId: 'HLT-RTC-010', status: 'ACTIVE_CORE' }
  ],
  screens: [
    { id: 'HLT-SCR-001', productId: 'prod-national-health', moduleId: 'HLT-MOD-001', code: 'HLT-SCR-TRIAGE', title: 'OPD Patient Queue & Clinical Triage', description: 'Live patient queue sorted by urgency.', viewType: 'TABLE', route: '/health/triage' },
    { id: 'HLT-SCR-002', productId: 'prod-national-health', moduleId: 'HLT-MOD-002', code: 'HLT-SCR-INPATIENT', title: 'Ward Occupancy & Theater Schedule', description: 'Bed occupancy grid and operating theater roster.', viewType: 'DASHBOARD', route: '/health/inpatient' },
    { id: 'HLT-SCR-003', productId: 'prod-national-health', moduleId: 'HLT-MOD-003', code: 'HLT-SCR-EMR', title: 'Patient Longitudinal EMR Summary', description: 'FHIR health record with allergies and history.', viewType: 'DETAIL', route: '/health/emr' },
    { id: 'HLT-SCR-004', productId: 'prod-national-health', moduleId: 'HLT-MOD-004', code: 'HLT-SCR-LAB', title: 'Laboratory Diagnostics & Specimen Workbench', description: 'Specimen orders, analyzer values, and approvals.', viewType: 'TABLE', route: '/health/lab' },
    { id: 'HLT-SCR-005', productId: 'prod-national-health', moduleId: 'HLT-MOD-005', code: 'HLT-SCR-BLOOD', title: 'Blood Bank Inventory & Cold Custody', description: 'Blood groups, expiration, and cross-matches.', viewType: 'TABLE', route: '/health/blood' },
    { id: 'HLT-SCR-006', productId: 'prod-national-health', moduleId: 'HLT-MOD-006', code: 'HLT-SCR-SURVEILLANCE', title: 'National Epidemic Surveillance GIS Map', description: 'Disease alerts and cluster hotspots.', viewType: 'DASHBOARD', route: '/health/epidemic-map' },
    { id: 'HLT-SCR-007', productId: 'prod-national-health', moduleId: 'HLT-MOD-007', code: 'HLT-SCR-IMMUNIZATION', title: 'Child Vaccine Registry & MCH Tracker', description: 'EPI vaccine milestones and antenatal schedule.', viewType: 'TABLE', route: '/health/immunization' },
    { id: 'HLT-SCR-008', productId: 'prod-national-health', moduleId: 'HLT-MOD-008', code: 'HLT-SCR-PHARMACY', title: 'Pharmacy e-Prescription & Dispensing Grid', description: 'Pending doctor orders and dispensing ledger.', viewType: 'TABLE', route: '/health/pharmacy' },
    { id: 'HLT-SCR-009', productId: 'prod-national-health', moduleId: 'HLT-MOD-009', code: 'HLT-SCR-STORES', title: 'Medical Stores Supply Chain & IoT Cold Chain', description: 'Stock levels and vaccine temperature monitors.', viewType: 'DASHBOARD', route: '/health/stores' },
    { id: 'HLT-SCR-010', productId: 'prod-national-health', moduleId: 'HLT-MOD-010', code: 'HLT-SCR-INSURANCE', title: 'Universal Health Insurance Claims Adjudication', description: 'Hospital claims, pre-authorizations, and settlements.', viewType: 'TABLE', route: '/health/claims' }
  ],
  forms: [
    {
      id: 'HLT-FORM-001',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-001',
      code: 'HLT-FORM-TRIAGE',
      title: 'Emergency Triage & Vital Signs Entry',
      submitAction: 'health.triage.logVitals',
      fieldCount: 5,
      fields: [
        { name: 'patientNIN', label: 'Patient National ID (NIN)', type: 'text', required: true },
        { name: 'systolicBP', label: 'Blood Pressure (mmHg)', type: 'number', required: true },
        { name: 'pulseRate', label: 'Pulse Rate (BPM)', type: 'number', required: true },
        { name: 'spo2Percent', label: 'Oxygen Saturation (SpO2 %)', type: 'number', required: true },
        { name: 'triageCategory', label: 'Triage Category', type: 'select', required: true }
      ],
      validationRules: ['NIN_EXISTS', 'VITALS_NUMERIC_RANGE']
    },
    {
      id: 'HLT-FORM-002',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-002',
      code: 'HLT-FORM-ADMISSION',
      title: 'Inpatient Admission & Ward Assignment',
      submitAction: 'health.inpatient.allocateBed',
      fieldCount: 4,
      fields: [
        { name: 'patientNIN', label: 'Patient NIN', type: 'text', required: true },
        { name: 'wardId', label: 'Assigned Ward', type: 'select', required: true },
        { name: 'admittingDiagnosis', label: 'Primary Admitting Diagnosis', type: 'text', required: true },
        { name: 'attendingDoctorId', label: 'Attending Physician Staff ID', type: 'text', required: true }
      ],
      validationRules: ['BED_AVAILABLE_CHECK']
    },
    {
      id: 'HLT-FORM-003',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-003',
      code: 'HLT-FORM-REFERRAL',
      title: 'Inter-Facility Medical Referral Dispatch',
      submitAction: 'health.emr.issueReferral',
      fieldCount: 4,
      fields: [
        { name: 'patientNIN', label: 'Patient NIN', type: 'text', required: true },
        { name: 'destinationHospital', label: 'Receiving Hospital Code', type: 'text', required: true },
        { name: 'clinicalJustification', label: 'Clinical Reason for Referral', type: 'textarea', required: true },
        { name: 'transportMode', label: 'Transport Mode', type: 'select', required: true }
      ],
      validationRules: ['RECEIVING_HOSPITAL_VALID']
    },
    {
      id: 'HLT-FORM-004',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-004',
      code: 'HLT-FORM-LAB-ORDER',
      title: 'Laboratory Diagnostic Test Requisition',
      submitAction: 'health.lims.orderTest',
      fieldCount: 4,
      fields: [
        { name: 'patientNIN', label: 'Patient NIN', type: 'text', required: true },
        { name: 'testCode', label: 'Lab Test Code (LOINC)', type: 'select', required: true },
        { name: 'specimenType', label: 'Specimen Type', type: 'select', required: true },
        { name: 'orderingDoctorId', label: 'Doctor Staff ID', type: 'text', required: true }
      ],
      validationRules: ['LOINC_CODE_VALID']
    },
    {
      id: 'HLT-FORM-005',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-005',
      code: 'HLT-FORM-BLOOD-CROSSMATCH',
      title: 'Emergency Blood Cross-Match Order',
      submitAction: 'health.blood.crossmatchIssue',
      fieldCount: 4,
      fields: [
        { name: 'patientNIN', label: 'Patient NIN', type: 'text', required: true },
        { name: 'bloodGroupRequired', label: 'Blood Group / Rh Factor', type: 'select', required: true },
        { name: 'unitsRequested', label: 'Units Requested', type: 'number', required: true },
        { name: 'urgency', label: 'Urgency Level', type: 'select', required: true }
      ],
      validationRules: ['BLOOD_GROUP_SPECIFIED']
    },
    {
      id: 'HLT-FORM-006',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-007',
      code: 'HLT-FORM-VACCINE-DOSE',
      title: 'Child Immunization Dose Administration',
      submitAction: 'health.immunization.recordDose',
      fieldCount: 4,
      fields: [
        { name: 'childNIN', label: 'Child NIN / Birth Cert ID', type: 'text', required: true },
        { name: 'vaccineCode', label: 'Vaccine Code (e.g. PENTA-1)', type: 'select', required: true },
        { name: 'batchNumber', label: 'Vial Batch Number', type: 'text', required: true },
        { name: 'administeringNurseId', label: 'Nurse Staff ID', type: 'text', required: true }
      ],
      validationRules: ['VACCINE_AGE_COMPLIANT']
    },
    {
      id: 'HLT-FORM-007',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-008',
      code: 'HLT-FORM-PRESCRIPTION',
      title: 'Electronic Medical Prescription Form',
      submitAction: 'health.pharma.prescribe',
      fieldCount: 5,
      fields: [
        { name: 'patientNIN', label: 'Patient NIN', type: 'text', required: true },
        { name: 'drugCode', label: 'Drug Code (INN/Brand)', type: 'select', required: true },
        { name: 'dosageMg', label: 'Dosage (e.g. 500mg)', type: 'text', required: true },
        { name: 'frequency', label: 'Frequency (e.g. 8-hourly for 5 days)', type: 'text', required: true },
        { name: 'prescribingDoctorId', label: 'Doctor Staff ID', type: 'text', required: true }
      ],
      validationRules: ['ALLERGY_INTERACTION_CHECK']
    },
    {
      id: 'HLT-FORM-008',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-010',
      code: 'HLT-FORM-CLAIM',
      title: 'Health Insurance Claim Submission',
      submitAction: 'health.insurance.settleClaim',
      fieldCount: 4,
      fields: [
        { name: 'patientNIN', label: 'Patient NIN', type: 'text', required: true },
        { name: 'serviceCode', label: 'Tariff Service Code', type: 'select', required: true },
        { name: 'claimedAmountUgx', label: 'Claimed Amount (UGX)', type: 'number', required: true },
        { name: 'hospitalId', label: 'Hospital Facility Code', type: 'text', required: true }
      ],
      validationRules: ['CAPITATION_LIMIT_CHECK']
    }
  ],
  dashboards: [
    {
      id: 'HLT-DASH-001',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-001',
      code: 'HLT-DASH-CLINICAL',
      title: 'National Hospital Operations & Bed Occupancy',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'National Bed Occupancy', value: '87.4%', trend: 'up', change: 'Optimal Range' },
        { label: 'Daily OPD Encounters', value: '142,500 Patients', trend: 'up', change: '+3.4% YoY' },
        { label: 'Average Triage Wait Time', value: '18 Minutes', trend: 'down', change: '-6 min' },
        { label: 'Emergency Theater Utilization', value: '74.2%', trend: 'neutral', change: 'Normal' }
      ]
    },
    {
      id: 'HLT-DASH-002',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-003',
      code: 'HLT-DASH-LIMS',
      title: 'Laboratory Diagnostic & Pathology Throughput',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Daily Lab Tests Completed', value: '38,900 Tests', trend: 'up', change: '99.4% Automated' },
        { label: 'Average Lab Turnaround', value: '42 Minutes', trend: 'down', change: '-12 min' },
        { label: 'Blood Units in Sovereign Reserve', value: '18,400 Units', trend: 'up', change: 'Safe Buffer' },
        { label: 'Specimen Rejection Rate', value: '0.12%', trend: 'down', change: 'ISO 15189' }
      ]
    },
    {
      id: 'HLT-DASH-003',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-006',
      code: 'HLT-DASH-SURVEILLANCE',
      title: 'National Epidemic Surveillance & Vaccine Coverage',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'National Immunization Coverage', value: '94.8%', trend: 'up', change: 'EPI Target Met' },
        { label: 'Active Epidemic Alerts', value: '2 Under Investigation', trend: 'down', change: 'Contained' },
        { label: 'Malaria Incidence Index', value: '12.4 / 1000', trend: 'down', change: '-18% MoM' },
        { label: 'DHIS2 Reporting Timeliness', value: '99.1%', trend: 'up', change: '135 Districts' }
      ]
    },
    {
      id: 'HLT-DASH-004',
      productId: 'prod-national-health',
      moduleId: 'HLT-MOD-009',
      code: 'HLT-DASH-SUPPLY',
      title: 'National Pharmaceutical Stock & Insurance Claims',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Essential Medicines Availability', value: '96.2%', trend: 'up', change: 'Zero Stockouts' },
        { label: 'Cold-Chain IoT Health', value: '100% In Range', trend: 'up', change: '+2°C to +8°C' },
        { label: 'Monthly Claims Settled', value: 'UGX 24.8 Billion', trend: 'up', change: 'Sub-48h Settle' },
        { label: 'Automated Fraud Rejection Rate', value: '2.1%', trend: 'down', change: 'UGX 520M Saved' }
      ]
    }
  ],
  reports: [
    { id: 'HLT-REP-001', productId: 'prod-national-health', moduleId: 'HLT-MOD-001', code: 'HLT-REP-OPD-MONTHLY', title: 'Monthly OPD Morbidity & Mortality Summary', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'HLT-REP-002', productId: 'prod-national-health', moduleId: 'HLT-MOD-002', code: 'HLT-REP-SURGERY-AUDIT', title: 'Hospital Surgical Outcomes & Infection Audit', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'HLT-REP-003', productId: 'prod-national-health', moduleId: 'HLT-MOD-003', code: 'HLT-REP-REFERRAL-LOG', title: 'National Inter-Hospital Ambulance Transfer Ledger', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'HLT-REP-004', productId: 'prod-national-health', moduleId: 'HLT-MOD-004', code: 'HLT-REP-LAB-QUALITY', title: 'LIMS Quality Control & Analyzer Calibration Report', format: 'SUMMARY', exportTypes: ['PDF', 'XLSX'] },
    { id: 'HLT-REP-005', productId: 'prod-national-health', moduleId: 'HLT-MOD-005', code: 'HLT-REP-BLOOD-CENSUS', title: 'National Blood Bank Transfusion Audit Report', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'HLT-REP-006', productId: 'prod-national-health', moduleId: 'HLT-MOD-006', code: 'HLT-REP-DHIS2-EPIDEMIC', title: 'Weekly Epidemiological Epidemic Surveillance Bulletin', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'JSON'] },
    { id: 'HLT-REP-007', productId: 'prod-national-health', moduleId: 'HLT-MOD-007', code: 'HLT-REP-IMMUNIZATION-SURVEY', title: 'District Vaccine Cold-Chain & EPI Coverage Survey', format: 'SUMMARY', exportTypes: ['PDF', 'XLSX'] },
    { id: 'HLT-REP-008', productId: 'prod-national-health', moduleId: 'HLT-MOD-008', code: 'HLT-REP-PHARMA-DISPENSE', title: 'Controlled Dangerous Drugs Prescription Audit', format: 'FORENSIC_TRAIL', exportTypes: ['PDF', 'CSV'] },
    { id: 'HLT-REP-009', productId: 'prod-national-health', moduleId: 'HLT-MOD-009', code: 'HLT-REP-STOCKOUT-PREDICTION', title: 'Central Medical Stores Inventory & Reorder Forecast', format: 'TABULAR', exportTypes: ['PDF', 'XLSX'] },
    { id: 'HLT-REP-010', productId: 'prod-national-health', moduleId: 'HLT-MOD-010', code: 'HLT-REP-INSURANCE-SETTLEMENT', title: 'Universal Health Insurance Capitation Settlement Return', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] }
  ],
  workflows: [
    { id: 'HLT-WF-001', productId: 'prod-national-health', moduleId: 'HLT-MOD-001', code: 'HLT-WF-OPD', title: 'OPD Clinical Consultation & Triage Flow', stages: ['Patient Vetting', 'Triage Vitals', 'Doctor Consultation', 'Prescription / Lab'], slaHours: 2, requiredApprovers: ['TRIAGE_NURSE', 'MEDICAL_OFFICER'], initialState: 'Patient Vetting' },
    { id: 'HLT-WF-002', productId: 'prod-national-health', moduleId: 'HLT-MOD-002', code: 'HLT-WF-INPATIENT', title: 'Inpatient Hospitalization & Surgery Lifecycle', stages: ['Ward Admission', 'Daily Ward Round', 'Pre-Op Checklist', 'Surgery Execution', 'Discharge Summary'], slaHours: 72, requiredApprovers: ['ATTENDING_PHYSICIAN'], initialState: 'Ward Admission' },
    { id: 'HLT-WF-003', productId: 'prod-national-health', moduleId: 'HLT-MOD-003', code: 'HLT-WF-REFERRAL', title: 'Emergency Hospital Transfer Flow', stages: ['Referral Order', 'Receiving Bed Lock', 'Ambulance Dispatch', 'Handover at Referral Center'], slaHours: 4, requiredApprovers: ['REFERRAL_COORDINATOR'], initialState: 'Referral Order' },
    { id: 'HLT-WF-004', productId: 'prod-national-health', moduleId: 'HLT-MOD-004', code: 'HLT-WF-LIMS', title: 'Laboratory Specimen Diagnostic Flow', stages: ['Specimen Order', 'Phlebotomy Barcode', 'Analyzer Processing', 'Pathologist Verification'], slaHours: 1, requiredApprovers: ['LAB_SCIENTIST'], initialState: 'Specimen Order' },
    { id: 'HLT-WF-005', productId: 'prod-national-health', moduleId: 'HLT-MOD-005', code: 'HLT-WF-BLOOD', title: 'Blood Donation & Transfusion Safety Flow', stages: ['Donor Bleed', 'Viral Screening', 'Cold Storage', 'Cross-Match Release'], slaHours: 24, requiredApprovers: ['BLOOD_BANK_OFFICER'], initialState: 'Donor Bleed' },
    { id: 'HLT-WF-006', productId: 'prod-national-health', moduleId: 'HLT-MOD-006', code: 'HLT-WF-IDSR', title: 'Epidemic Outbreak Rapid Response Flow', stages: ['Syndromic Alert', 'Field Verification', 'Lab Confirmation', 'Emergency Response Activation'], slaHours: 6, requiredApprovers: ['CHIEF_EPIDEMIOLOGIST'], initialState: 'Syndromic Alert' },
    { id: 'HLT-WF-007', productId: 'prod-national-health', moduleId: 'HLT-MOD-007', code: 'HLT-WF-IMMUNIZATION', title: 'National Child Immunization Pathway', stages: ['Birth Enrollment', 'EPI Dose Schedule', 'Administration Log', 'Certificate Issuance'], slaHours: 12, requiredApprovers: ['IMMUNIZATION_OFFICER'], initialState: 'Birth Enrollment' },
    { id: 'HLT-WF-008', productId: 'prod-national-health', moduleId: 'HLT-MOD-008', code: 'HLT-WF-EPRESCRIBE', title: 'e-Prescription Dispensing & Counseling Flow', stages: ['Doctor Prescription', 'Interaction Screen', 'Dispense Verification', 'Patient Counseling'], slaHours: 1, requiredApprovers: ['DISPENSING_PHARMACIST'], initialState: 'Doctor Prescription' },
    { id: 'HLT-WF-009', productId: 'prod-national-health', moduleId: 'HLT-MOD-009', code: 'HLT-WF-DRUG-ORDER', title: 'Central Medical Stores Procurement Flow', stages: ['Stock Velocity Reorder', 'Purchase Order', 'Cold Chain Delivery', 'Warehouse Receipt'], slaHours: 48, requiredApprovers: ['MEDICAL_STORES_MANAGER'], initialState: 'Stock Velocity Reorder' },
    { id: 'HLT-WF-010', productId: 'prod-national-health', moduleId: 'HLT-MOD-010', code: 'HLT-WF-INSURANCE-CLAIM', title: 'Insurance Claim Adjudication & FAAP Settlement Flow', stages: ['Claim Ingestion', 'DRG Code Audit', 'Pre-Auth Match', 'FAAP Payment Disbursement'], slaHours: 24, requiredApprovers: ['HEALTH_CLAIMS_AUDITOR'], initialState: 'Claim Ingestion' }
  ],
  databaseEntities: [
    { id: 'HLT-DB-001', productId: 'prod-national-health', moduleId: 'HLT-MOD-001', tableName: 'hlt_triage_encounters', primaryKey: 'encounter_id', fields: [{ name: 'encounter_id', type: 'VARCHAR(64)', required: true }, { name: 'patient_nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'triage_code', type: 'VARCHAR(16)', required: true }], auditLogged: true },
    { id: 'HLT-DB-002', productId: 'prod-national-health', moduleId: 'HLT-MOD-002', tableName: 'hlt_inpatient_admissions', primaryKey: 'admission_id', fields: [{ name: 'admission_id', type: 'VARCHAR(64)', required: true }, { name: 'bed_number', type: 'VARCHAR(32)', required: true }, { name: 'ward_code', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'HLT-DB-003', productId: 'prod-national-health', moduleId: 'HLT-MOD-003', tableName: 'hlt_fhir_records', primaryKey: 'fhir_id', fields: [{ name: 'fhir_id', type: 'VARCHAR(64)', required: true }, { name: 'patient_nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'bundle_json', type: 'JSONB', required: true }], auditLogged: true },
    { id: 'HLT-DB-004', productId: 'prod-national-health', moduleId: 'HLT-MOD-004', tableName: 'hlt_lab_orders', primaryKey: 'order_id', fields: [{ name: 'order_id', type: 'VARCHAR(64)', required: true }, { name: 'loinc_code', type: 'VARCHAR(32)', required: true }, { name: 'result_value', type: 'VARCHAR(128)', required: true }], auditLogged: true },
    { id: 'HLT-DB-005', productId: 'prod-national-health', moduleId: 'HLT-MOD-005', tableName: 'hlt_blood_inventory', primaryKey: 'unit_id', fields: [{ name: 'unit_id', type: 'VARCHAR(64)', required: true }, { name: 'abo_rh', type: 'VARCHAR(8)', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'HLT-DB-006', productId: 'prod-national-health', moduleId: 'HLT-MOD-006', tableName: 'hlt_idsr_alerts', primaryKey: 'alert_id', fields: [{ name: 'alert_id', type: 'VARCHAR(64)', required: true }, { name: 'disease_code', type: 'VARCHAR(32)', required: true }, { name: 'district_code', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'HLT-DB-007', productId: 'prod-national-health', moduleId: 'HLT-MOD-007', tableName: 'hlt_immunization_ledger', primaryKey: 'dose_id', fields: [{ name: 'dose_id', type: 'VARCHAR(64)', required: true }, { name: 'child_nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'vaccine_code', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'HLT-DB-008', productId: 'prod-national-health', moduleId: 'HLT-MOD-008', tableName: 'hlt_prescriptions', primaryKey: 'rx_id', fields: [{ name: 'rx_id', type: 'VARCHAR(64)', required: true }, { name: 'drug_code', type: 'VARCHAR(32)', required: true }, { name: 'dispensed_flag', type: 'BOOLEAN', required: true }], auditLogged: true },
    { id: 'HLT-DB-009', productId: 'prod-national-health', moduleId: 'HLT-MOD-009', tableName: 'hlt_medical_stores_stock', primaryKey: 'stock_id', fields: [{ name: 'stock_id', type: 'VARCHAR(64)', required: true }, { name: 'item_code', type: 'VARCHAR(32)', required: true }, { name: 'quantity_on_hand', type: 'INT', required: true }], auditLogged: true },
    { id: 'HLT-DB-010', productId: 'prod-national-health', moduleId: 'HLT-MOD-010', tableName: 'hlt_insurance_claims', primaryKey: 'claim_id', fields: [{ name: 'claim_id', type: 'VARCHAR(64)', required: true }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'HLT-API-001', productId: 'prod-national-health', moduleId: 'HLT-MOD-001', code: 'HLT_API_TRIAGE', method: 'POST', endpoint: '/api/v1/health/triage/register', requiredPermission: 'HLT-PERM-001', handlerName: 'registerTriageHandler', summary: 'Log OPD patient intake and vital signs' },
    { id: 'HLT-API-002', productId: 'prod-national-health', moduleId: 'HLT-MOD-002', code: 'HLT_API_INPATIENT', method: 'POST', endpoint: '/api/v1/health/inpatient/admit', requiredPermission: 'HLT-PERM-002', handlerName: 'admitInpatientHandler', summary: 'Admit patient to ward and bed' },
    { id: 'HLT-API-003', productId: 'prod-national-health', moduleId: 'HLT-MOD-003', code: 'HLT_API_FHIR', method: 'GET', endpoint: '/api/v1/health/emr/fhir/:nin', requiredPermission: 'HLT-PERM-003', handlerName: 'getFhirRecordHandler', summary: 'Get FHIR medical bundle' },
    { id: 'HLT-API-004', productId: 'prod-national-health', moduleId: 'HLT-MOD-004', code: 'HLT_API_LAB', method: 'POST', endpoint: '/api/v1/health/lab/orders', requiredPermission: 'HLT-PERM-004', handlerName: 'createLabOrderHandler', summary: 'Create LIMS laboratory order' },
    { id: 'HLT-API-005', productId: 'prod-national-health', moduleId: 'HLT-MOD-005', code: 'HLT_API_BLOOD', method: 'GET', endpoint: '/api/v1/health/blood/reserve', requiredPermission: 'HLT-PERM-005', handlerName: 'getBloodReserveHandler', summary: 'Check blood bank reserves' },
    { id: 'HLT-API-006', productId: 'prod-national-health', moduleId: 'HLT-MOD-006', code: 'HLT_API_IDSR', method: 'POST', endpoint: '/api/v1/health/surveillance/alert', requiredPermission: 'HLT-PERM-006', handlerName: 'postEpidemicAlertHandler', summary: 'Report notifiable disease outbreak' },
    { id: 'HLT-API-007', productId: 'prod-national-health', moduleId: 'HLT-MOD-007', code: 'HLT_API_IMMUNIZATION', method: 'POST', endpoint: '/api/v1/health/immunization/record', requiredPermission: 'HLT-PERM-007', handlerName: 'recordVaccineHandler', summary: 'Record vaccine administration' },
    { id: 'HLT-API-008', productId: 'prod-national-health', moduleId: 'HLT-MOD-008', code: 'HLT_API_PHARMA', method: 'POST', endpoint: '/api/v1/health/pharma/dispense', requiredPermission: 'HLT-PERM-008', handlerName: 'dispenseRxHandler', summary: 'Dispense prescription medicine' },
    { id: 'HLT-API-009', productId: 'prod-national-health', moduleId: 'HLT-MOD-009', code: 'HLT_API_STORES', method: 'GET', endpoint: '/api/v1/health/stores/stock', requiredPermission: 'HLT-PERM-009', handlerName: 'getStoresStockHandler', summary: 'Fetch warehouse inventory levels' },
    { id: 'HLT-API-010', productId: 'prod-national-health', moduleId: 'HLT-MOD-010', code: 'HLT_API_CLAIMS', method: 'POST', endpoint: '/api/v1/health/insurance/adjudicate', requiredPermission: 'HLT-PERM-010', handlerName: 'adjudicateClaimHandler', summary: 'Adjudicate insurance claim' }
  ],
  runtimeComponents: [
    { id: 'HLT-RTC-001', productId: 'prod-national-health', moduleId: 'HLT-MOD-001', componentKey: 'NationalHealthTriageEngine', name: 'Clinical Triage & OPD Queue Engine', description: 'Patient queueing and vitals monitoring workspace.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CLINICAL_UI' },
    { id: 'HLT-RTC-002', productId: 'prod-national-health', moduleId: 'HLT-MOD-002', componentKey: 'NationalHealthInpatientTheaterEngine', name: 'Inpatient Bed & Surgical Theater Engine', description: 'Ward beds and theater scheduling matrix.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CLINICAL_UI' },
    { id: 'HLT-RTC-003', productId: 'prod-national-health', moduleId: 'HLT-MOD-003', componentKey: 'NationalHealthEmrReferralEngine', name: 'FHIR Longitudinal Medical Records Engine', description: 'Interactive medical timeline and transfer orders.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'HEALTH_INFORMATICS' },
    { id: 'HLT-RTC-004', productId: 'prod-national-health', moduleId: 'HLT-MOD-004', componentKey: 'NationalHealthLimsEngine', name: 'Laboratory Diagnostics LIMS Engine', description: 'Analyzer values, LOINC codes, and pathology workbench.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'DIAGNOSTIC_LAB' },
    { id: 'HLT-RTC-005', productId: 'prod-national-health', moduleId: 'HLT-MOD-005', componentKey: 'NationalHealthBloodBankEngine', name: 'National Blood Bank Transfusion Engine', description: 'Serology testing and blood units cold chain inventory.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'BLOOD_BANK' },
    { id: 'HLT-RTC-006', productId: 'prod-national-health', moduleId: 'HLT-MOD-006', componentKey: 'NationalHealthSurveillanceEngine', name: 'IDSR Outbreak & DHIS2 Surveillance Engine', description: 'Epidemic map and disease cluster alerting.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'SURVEILLANCE' },
    { id: 'HLT-RTC-007', productId: 'prod-national-health', moduleId: 'HLT-MOD-007', componentKey: 'NationalHealthImmunizationEngine', name: 'Child Vaccine & Maternal Care Engine', description: 'EPI vaccine scheduler and antenatal tracking.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MCH_ENGINE' },
    { id: 'HLT-RTC-008', productId: 'prod-national-health', moduleId: 'HLT-MOD-008', componentKey: 'NationalHealthPharmacyEngine', name: 'Hospital e-Prescription & Pharmacy Engine', description: 'Prescription dispensing and drug interaction monitor.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'PHARMACY' },
    { id: 'HLT-RTC-009', productId: 'prod-national-health', moduleId: 'HLT-MOD-009', componentKey: 'NationalHealthSupplyChainEngine', name: 'Central Medical Stores & Cold-Chain IoT Engine', description: 'Warehouse logistics and temperature sensor grid.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LOGISTICS' },
    { id: 'HLT-RTC-010', productId: 'prod-national-health', moduleId: 'HLT-MOD-010', componentKey: 'NationalHealthInsuranceEngine', name: 'Universal Health Insurance Claims Engine', description: 'DRG claims adjudicator and automated FAAP payout bridge.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FINANCIAL_ENGINE' }
  ],
  permissions: [
    { id: 'HLT-PERM-001', productId: 'prod-national-health', code: 'health:opd:triage', name: 'OPD Intake & Triage Access', description: 'Authority to register patients and record triage vitals' },
    { id: 'HLT-PERM-002', productId: 'prod-national-health', code: 'health:inpatient:beds', name: 'Inpatient & Theater Scheduling Access', description: 'Authority to allocate beds and schedule surgeries' },
    { id: 'HLT-PERM-003', productId: 'prod-national-health', code: 'health:emr:fhir', name: 'FHIR Health Records Access', description: 'Authority to view and edit longitudinal patient records' },
    { id: 'HLT-PERM-004', productId: 'prod-national-health', code: 'health:lims:lab', name: 'Laboratory Diagnostics Access', description: 'Authority to process lab tests and validate results' },
    { id: 'HLT-PERM-005', productId: 'prod-national-health', code: 'health:blood:transfusion', name: 'Blood Bank Transfusion Access', description: 'Authority to manage blood inventory and cross-match' },
    { id: 'HLT-PERM-006', productId: 'prod-national-health', code: 'health:surveillance:idsr', name: 'Epidemic Disease Surveillance Access', description: 'Authority to ingest outbreak alerts and publish DHIS2 reports' },
    { id: 'HLT-PERM-007', productId: 'prod-national-health', code: 'health:mch:immunization', name: 'Immunization & MCH Access', description: 'Authority to administer vaccines and track maternal health' },
    { id: 'HLT-PERM-008', productId: 'prod-national-health', code: 'health:pharma:dispense', name: 'Pharmacy & Dispensing Access', description: 'Authority to dispense drugs and manage dangerous substances' },
    { id: 'HLT-PERM-009', productId: 'prod-national-health', code: 'health:stores:supply', name: 'Medical Stores & Cold-Chain Access', description: 'Authority to manage medical supplies and IoT cold-chain' },
    { id: 'HLT-PERM-010', productId: 'prod-national-health', code: 'health:insurance:claims', name: 'Health Insurance Claims Access', description: 'Authority to adjudicate claims and authorize reimbursement' }
  ],
  roles: [
    { id: 'HLT-ROLE-001', productId: 'prod-national-health', code: 'DIRECTOR_GENERAL_HEALTH', name: 'Director General of Health Services', tier: 'GOVERNANCE', permissionIds: ['HLT-PERM-001', 'HLT-PERM-002', 'HLT-PERM-003', 'HLT-PERM-006', 'HLT-PERM-010'] },
    { id: 'HLT-ROLE-002', productId: 'prod-national-health', code: 'MEDICAL_SUPERINTENDENT', name: 'Hospital Medical Superintendent', tier: 'EXECUTIVE', permissionIds: ['HLT-PERM-001', 'HLT-PERM-002', 'HLT-PERM-003', 'HLT-PERM-004', 'HLT-PERM-008'] },
    { id: 'HLT-ROLE-003', productId: 'prod-national-health', code: 'CONSULTANT_PHYSICIAN', name: 'Consultant Physician / Surgeon', tier: 'OPERATIONAL', permissionIds: ['HLT-PERM-001', 'HLT-PERM-002', 'HLT-PERM-003', 'HLT-PERM-004', 'HLT-PERM-008'] },
    { id: 'HLT-ROLE-004', productId: 'prod-national-health', code: 'CHIEF_EPIDEMIOLOGIST', name: 'National Epidemiologist', tier: 'OPERATIONAL', permissionIds: ['HLT-PERM-006', 'HLT-PERM-007'] },
    { id: 'HLT-ROLE-005', productId: 'prod-national-health', code: 'PATIENT_PUBLIC', name: 'Citizen Patient User', tier: 'PUBLIC', permissionIds: [] }
  ]
};
