import { CanonicalProductHierarchy } from './types';

export const NATIONAL_IDENTITY_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-national-identity',
    code: 'NID',
    name: 'National Identity Platform',
    category: 'SOVEREIGN_PLATFORM',
    description: 'Sovereign biometric enrollment, civil registration, National Identification Number (NIN) issuance, cryptographic KYC verification, and population census registry.',
    version: '2026.4.0',
    iconName: 'Fingerprint',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Registrar General of Citizen Data',
    governingLegislation: 'Registration of Persons Act & Sovereign Data Protection Standards 2026',
    directorateIds: ['NID-DIR-001', 'NID-DIR-002', 'NID-DIR-003', 'NID-DIR-004']
  },
  directorates: [
    {
      id: 'NID-DIR-001',
      productId: 'prod-national-identity',
      code: 'NID-DIR-CIVIL',
      name: 'Directorate of Civil Registration & Vital Statistics',
      description: 'Registration of births, deaths, adoptions, marriages, and legal changes of name.',
      leadRole: 'DIRECTOR_CIVIL_REGISTRATION',
      departmentIds: ['NID-DEPT-001', 'NID-DEPT-002', 'NID-DEPT-003']
    },
    {
      id: 'NID-DIR-002',
      productId: 'prod-national-identity',
      code: 'NID-DIR-BIOMETRIC',
      name: 'Directorate of Biometric Enrollment & Forensic Matching',
      description: 'Ten-fingerprint capture, iris scanning, facial recognition, and Automated Biometric Identification System (ABIS).',
      leadRole: 'DIRECTOR_BIOMETRICS',
      departmentIds: ['NID-DEPT-004', 'NID-DEPT-005', 'NID-DEPT-006']
    },
    {
      id: 'NID-DIR-003',
      productId: 'prod-national-identity',
      code: 'NID-DIR-CREDENTIAL',
      name: 'Directorate of Sovereign Credentials & NIN Issuance',
      description: 'Generation of unique National Identification Numbers, smart identity cards, electronic passports, and digital wallets.',
      leadRole: 'DIRECTOR_CREDENTIALS',
      departmentIds: ['NID-DEPT-007', 'NID-DEPT-008']
    },
    {
      id: 'NID-DIR-004',
      productId: 'prod-national-identity',
      code: 'NID-DIR-VERIFICATION',
      name: 'Directorate of National Verification & Institutional Integration',
      description: 'Real-time e-KYC APIs for banks, telecoms, immigration, revenue authorities, and courts with cryptographic audit trails.',
      leadRole: 'DIRECTOR_VERIFICATION',
      departmentIds: ['NID-DEPT-009', 'NID-DEPT-010']
    }
  ],
  departments: [
    {
      id: 'NID-DEPT-001',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      code: 'NID-DEPT-BIRTHS',
      name: 'Department of Birth Registration & Infant Biometrics',
      description: 'Hospital birth notifications, community registration, and unique infant identifier generation.',
      headRole: 'HEAD_BIRTH_REGISTRAR',
      officeIds: ['NID-OFF-001', 'NID-OFF-002']
    },
    {
      id: 'NID-DEPT-002',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      code: 'NID-DEPT-DEATHS',
      name: 'Department of Death Certification & Estate Notification',
      description: 'Civil death registers, coroner certifications, and instant deactivation of active civic credentials.',
      headRole: 'HEAD_DEATH_REGISTRAR',
      officeIds: ['NID-OFF-003']
    },
    {
      id: 'NID-DEPT-003',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      code: 'NID-DEPT-MARRIAGE',
      name: 'Department of Marital Status & Legal Gazette Records',
      description: 'Civil and religious marriage registers, divorce decrees, and legal deed poll name changes.',
      headRole: 'HEAD_MARITAL_REGISTRAR',
      officeIds: ['NID-OFF-004']
    },
    {
      id: 'NID-DEPT-004',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      code: 'NID-DEPT-FIELD-ENROLL',
      name: 'Department of Field Enrollment & Mobile Kits Management',
      description: 'Deployment of rugged biometric enrollment kits to sub-counties, embassies, and mobile outreach centers.',
      headRole: 'HEAD_FIELD_ENROLLMENT',
      officeIds: ['NID-OFF-005', 'NID-OFF-006']
    },
    {
      id: 'NID-DEPT-005',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      code: 'NID-DEPT-ABIS',
      name: 'Department of ABIS Multi-Modal Deduplication',
      description: 'High-throughput algorithmic matching to prevent duplicate registrations and fraudulent ghost identities.',
      headRole: 'HEAD_ABIS_OPERATIONS',
      officeIds: ['NID-OFF-007']
    },
    {
      id: 'NID-DEPT-006',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      code: 'NID-DEPT-FORENSIC',
      name: 'Department of Identity Forensics & Exception Resolution',
      description: 'Manual fingerprint verification for damaged prints, amputees, facial anomalies, and contested claims.',
      headRole: 'CHIEF_FORENSIC_EXAMINER',
      officeIds: ['NID-OFF-008']
    },
    {
      id: 'NID-DEPT-007',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      code: 'NID-DEPT-NIN-GEN',
      name: 'Department of NIN Generation & Cryptographic Vault',
      description: 'Secure generation and HSM storage of immutable 14-digit National Identification Numbers.',
      headRole: 'HEAD_NIN_OPERATIONS',
      officeIds: ['NID-OFF-009']
    },
    {
      id: 'NID-DEPT-008',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      code: 'NID-DEPT-CARD-PROD',
      name: 'Department of Smart Card Personalization & Laser Engraving',
      description: 'Sovereign chip personalization, laser engraving, cryptographic certificates, and batch dispatch.',
      headRole: 'HEAD_CARD_PRODUCTION',
      officeIds: ['NID-OFF-010', 'NID-OFF-011']
    },
    {
      id: 'NID-DEPT-009',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      code: 'NID-DEPT-EKYC',
      name: 'Department of Real-Time e-KYC & Telemetry Gateway',
      description: 'Zero-trust API gateways serving financial institutions, telecom SIM registrations, and public health.',
      headRole: 'HEAD_EKYC_GATEWAY',
      officeIds: ['NID-OFF-012']
    },
    {
      id: 'NID-DEPT-010',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      code: 'NID-DEPT-COMPLIANCE',
      name: 'Department of Data Protection & Sovereign Privacy Audit',
      description: 'Audit logs of every query, citizen consent management, and data protection commissioner reporting.',
      headRole: 'DATA_PROTECTION_OFFICER',
      officeIds: ['NID-OFF-013']
    }
  ],
  offices: [
    {
      id: 'NID-OFF-001',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      code: 'NID-OFF-HOSPITAL-INTAKE',
      name: 'Hospital Birth Notification Desk',
      description: 'Direct ingestion of birth records from maternity wards and public health centers.',
      officerRole: 'HOSPITAL_BIRTH_OFFICER',
      portalIds: ['NID-PORTAL-001', 'NID-PORTAL-002'],
      moduleIds: ['NID-MOD-001']
    },
    {
      id: 'NID-OFF-002',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      code: 'NID-OFF-LATE-BIRTH',
      name: 'Late Birth Registration & Age Verification Desk',
      description: 'Review of delayed birth applications with elder affidavits and village LC1 verification.',
      officerRole: 'SENIOR_CIVIL_OFFICER',
      portalIds: ['NID-PORTAL-001'],
      moduleIds: ['NID-MOD-001']
    },
    {
      id: 'NID-OFF-003',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-002',
      code: 'NID-OFF-DEATH-REG',
      name: 'Mortuary & Civil Death Registry Office',
      description: 'Validation of cause of death medical certificates and civic registry cancellation.',
      officerRole: 'DEATH_RECORDS_OFFICER',
      portalIds: ['NID-PORTAL-001'],
      moduleIds: ['NID-MOD-002']
    },
    {
      id: 'NID-OFF-004',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-003',
      code: 'NID-OFF-NAME-CHANGE',
      name: 'Legal Name Change & Deed Poll Desk',
      description: 'Gazette tracking and biographic updates with court order verification.',
      officerRole: 'LEGAL_RECORDS_OFFICER',
      portalIds: ['NID-PORTAL-001'],
      moduleIds: ['NID-MOD-003']
    },
    {
      id: 'NID-OFF-005',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      code: 'NID-OFF-KIT-PROVISION',
      name: 'Biometric Enrollment Kit Staging Desk',
      description: 'Cryptographic provisioning, firmware lockdown, and GPS geofencing of field kits.',
      officerRole: 'KIT_SECURITY_ENGINEER',
      portalIds: ['NID-PORTAL-003'],
      moduleIds: ['NID-MOD-004']
    },
    {
      id: 'NID-OFF-006',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      code: 'NID-OFF-CITIZEN-CAPTURE',
      name: 'Citizen Live Capture Operations Desk',
      description: 'Front-counter 10-finger biometric capture, ISO portrait photo, and iris capture.',
      officerRole: 'ENROLLMENT_OPERATOR',
      portalIds: ['NID-PORTAL-002', 'NID-PORTAL-003'],
      moduleIds: ['NID-MOD-004']
    },
    {
      id: 'NID-OFF-007',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-005',
      code: 'NID-OFF-ABIS-GRID',
      name: 'ABIS Engine Cluster Operations Office',
      description: 'Monitoring parallel 1-to-N matching clusters and 1-to-1 verification latency.',
      officerRole: 'ABIS_CLUSTER_ADMIN',
      portalIds: ['NID-PORTAL-003'],
      moduleIds: ['NID-MOD-005']
    },
    {
      id: 'NID-OFF-008',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-006',
      code: 'NID-OFF-FORENSIC-ADJUDICATION',
      name: 'Forensic Biometric Adjudication Desk',
      description: 'Manual inspection of split minutiae and biometric mismatch disputes.',
      officerRole: 'FORENSIC_ADJUDICATOR',
      portalIds: ['NID-PORTAL-001', 'NID-PORTAL-003'],
      moduleIds: ['NID-MOD-006']
    },
    {
      id: 'NID-OFF-009',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-007',
      code: 'NID-OFF-NIN-ALLOCATOR',
      name: 'NIN Allocation & HSM Vault Office',
      description: 'Cryptographic signing of NIN certificates with Hardware Security Module (HSM).',
      officerRole: 'HSM_SECURITY_OFFICER',
      portalIds: ['NID-PORTAL-003'],
      moduleIds: ['NID-MOD-007']
    },
    {
      id: 'NID-OFF-010',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      code: 'NID-OFF-CHIP-PERSO',
      name: 'Smart Card Chip Personalization Desk',
      description: 'Flashing ICAO 9303 applets, national PKI digital certificates, and contactless antenna.',
      officerRole: 'CHIP_PERSO_ENGINEER',
      portalIds: ['NID-PORTAL-003'],
      moduleIds: ['NID-MOD-008']
    },
    {
      id: 'NID-OFF-011',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      code: 'NID-OFF-DISPATCH',
      name: 'Secure Card Logistics & Collection Center',
      description: 'Tracking card shipments to district centers, SMS citizen notifications, and biometric handover.',
      officerRole: 'LOGISTICS_OFFICER',
      portalIds: ['NID-PORTAL-002', 'NID-PORTAL-004'],
      moduleIds: ['NID-MOD-009']
    },
    {
      id: 'NID-OFF-012',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-009',
      code: 'NID-OFF-API-SWITCH',
      name: 'Institutional KYC Switchboard Desk',
      description: 'Management of client API keys, rate limits, mutual TLS certificates, and KYC billing.',
      officerRole: 'INTEGRATION_ENGINEER',
      portalIds: ['NID-PORTAL-003', 'NID-PORTAL-004'],
      moduleIds: ['NID-MOD-010']
    },
    {
      id: 'NID-OFF-013',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-010',
      code: 'NID-OFF-AUDIT-VAULT',
      name: 'Sovereign Access Audit & Data Privacy Desk',
      description: 'Immutable ledger recording all agency queries against citizen biometric data.',
      officerRole: 'PRIVACY_COMPLIANCE_AUDITOR',
      portalIds: ['NID-PORTAL-001', 'NID-PORTAL-003'],
      moduleIds: ['NID-MOD-011']
    }
  ],
  portals: [
    {
      id: 'NID-PORTAL-001',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      officeId: 'NID-OFF-001',
      code: 'NID-PORTAL-REGISTRAR',
      name: 'National Civil Registrar Cockpit Portal',
      description: 'High-clearance operational portal for registrars, adjudicators, and civil directors.',
      targetRole: 'CIVIL_REGISTRAR',
      authLevel: 'PKI_SOVEREIGN',
      route: '/nid/registrar',
      moduleIds: ['NID-MOD-001', 'NID-MOD-002', 'NID-MOD-003', 'NID-MOD-006', 'NID-MOD-011']
    },
    {
      id: 'NID-PORTAL-002',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      officeId: 'NID-OFF-006',
      code: 'NID-PORTAL-FIELD-AGENT',
      name: 'Field Enrollment & Kit Operator Portal',
      description: 'Fast-flow biometric capture, fingerprint validation, and local offline kit sync.',
      targetRole: 'ENROLLMENT_OPERATOR',
      authLevel: 'STAFF',
      route: '/nid/field-operator',
      moduleIds: ['NID-MOD-001', 'NID-MOD-004', 'NID-MOD-009']
    },
    {
      id: 'NID-PORTAL-003',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-007',
      officeId: 'NID-OFF-009',
      code: 'NID-PORTAL-SOVEREIGN-ADMIN',
      name: 'National Identity Security & Infrastructure Portal',
      description: 'HSM key management, ABIS cluster health, API gateway telemetry, and security oversight.',
      targetRole: 'SOVEREIGN_ADMIN',
      authLevel: 'PKI_SOVEREIGN',
      route: '/nid/admin',
      moduleIds: ['NID-MOD-005', 'NID-MOD-007', 'NID-MOD-008', 'NID-MOD-010', 'NID-MOD-011']
    },
    {
      id: 'NID-PORTAL-004',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-009',
      officeId: 'NID-OFF-012',
      code: 'NID-PORTAL-PUBLIC-VERIFY',
      name: 'Citizen Self-Service & Institutional KYC Portal',
      description: 'Citizen status tracking, appointment booking, digital ID card viewing, and verified bank e-KYC query.',
      targetRole: 'CITIZEN_OR_CONSUMER_ENTITY',
      authLevel: 'PUBLIC',
      route: '/nid/public-verify',
      moduleIds: ['NID-MOD-009', 'NID-MOD-010']
    }
  ],
  modules: [
    {
      id: 'NID-MOD-001',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      officeId: 'NID-OFF-001',
      portalId: 'NID-PORTAL-001',
      code: 'NID-MOD-CIVIL-REG',
      name: 'Civil Vital Registration Engine',
      description: 'End-to-end processing of birth records, infant IDs, parent linkage, and civil status registers.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-001', 'NID-CAP-002', 'NID-CAP-003'],
      screenIds: ['NID-SCR-001'],
      formIds: ['NID-FORM-001'],
      dashboardIds: ['NID-DASH-001'],
      reportIds: ['NID-REP-001'],
      workflowIds: ['NID-WF-001'],
      databaseEntityIds: ['NID-DB-001'],
      apiIds: ['NID-API-001'],
      runtimeComponentId: 'NID-RTC-001',
      permissionIds: ['NID-PERM-001']
    },
    {
      id: 'NID-MOD-002',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-002',
      officeId: 'NID-OFF-003',
      portalId: 'NID-PORTAL-001',
      code: 'NID-MOD-DEATH-REG',
      name: 'Civil Death & Estate Deregistration',
      description: 'Formal death certification, estate notifier, voter roll de-listing, and passport invalidation.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-004', 'NID-CAP-005'],
      screenIds: ['NID-SCR-002'],
      formIds: ['NID-FORM-002'],
      dashboardIds: ['NID-DASH-001'],
      reportIds: ['NID-REP-002'],
      workflowIds: ['NID-WF-002'],
      databaseEntityIds: ['NID-DB-002'],
      apiIds: ['NID-API-002'],
      runtimeComponentId: 'NID-RTC-002',
      permissionIds: ['NID-PERM-002']
    },
    {
      id: 'NID-MOD-003',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-003',
      officeId: 'NID-OFF-004',
      portalId: 'NID-PORTAL-001',
      code: 'NID-MOD-NAME-CORRECT',
      name: 'Identity Correction & Deed Poll Management',
      description: 'Legal name changes, date-of-birth corrections with medical board findings, and gazette publication.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-006', 'NID-CAP-007'],
      screenIds: ['NID-SCR-003'],
      formIds: ['NID-FORM-003'],
      dashboardIds: [],
      reportIds: ['NID-REP-003'],
      workflowIds: ['NID-WF-003'],
      databaseEntityIds: ['NID-DB-003'],
      apiIds: ['NID-API-003'],
      runtimeComponentId: 'NID-RTC-003',
      permissionIds: ['NID-PERM-003']
    },
    {
      id: 'NID-MOD-004',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      officeId: 'NID-OFF-006',
      portalId: 'NID-PORTAL-002',
      code: 'NID-MOD-BIOMETRIC-ENROLL',
      name: 'Multi-Modal Biometric Live Capture Engine',
      description: 'Hardware integration with optical scanners, ICAO portrait capture, iris sensors, and quality scoring.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-008', 'NID-CAP-009', 'NID-CAP-010'],
      screenIds: ['NID-SCR-004'],
      formIds: ['NID-FORM-004'],
      dashboardIds: ['NID-DASH-002'],
      reportIds: ['NID-REP-004'],
      workflowIds: ['NID-WF-004'],
      databaseEntityIds: ['NID-DB-004'],
      apiIds: ['NID-API-004'],
      runtimeComponentId: 'NID-RTC-004',
      permissionIds: ['NID-PERM-004']
    },
    {
      id: 'NID-MOD-005',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-005',
      officeId: 'NID-OFF-007',
      portalId: 'NID-PORTAL-003',
      code: 'NID-MOD-ABIS-MATCH',
      name: 'Automated Biometric Identification System (ABIS)',
      description: 'Distributed 1:N fingerprint and facial matching engine with sub-second duplicate detection.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-011', 'NID-CAP-012'],
      screenIds: ['NID-SCR-005'],
      formIds: [],
      dashboardIds: ['NID-DASH-002'],
      reportIds: ['NID-REP-005'],
      workflowIds: ['NID-WF-005'],
      databaseEntityIds: ['NID-DB-005'],
      apiIds: ['NID-API-005'],
      runtimeComponentId: 'NID-RTC-005',
      permissionIds: ['NID-PERM-005']
    },
    {
      id: 'NID-MOD-006',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-006',
      officeId: 'NID-OFF-008',
      portalId: 'NID-PORTAL-001',
      code: 'NID-MOD-FORENSIC-ADJUDICATE',
      name: 'Forensic Exception & Minutiae Adjudication',
      description: 'Side-by-side comparison of fingerprint minutiae points, scar adjudication, and duplicate confirmation.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-013', 'NID-CAP-014'],
      screenIds: ['NID-SCR-006'],
      formIds: ['NID-FORM-005'],
      dashboardIds: [],
      reportIds: ['NID-REP-006'],
      workflowIds: ['NID-WF-006'],
      databaseEntityIds: ['NID-DB-006'],
      apiIds: ['NID-API-006'],
      runtimeComponentId: 'NID-RTC-006',
      permissionIds: ['NID-PERM-006']
    },
    {
      id: 'NID-MOD-007',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-007',
      officeId: 'NID-OFF-009',
      portalId: 'NID-PORTAL-003',
      code: 'NID-MOD-NIN-ISSUANCE',
      name: 'NIN Generation & HSM Signature Engine',
      description: 'Luhn-verified 14-digit NIN assignment, ISO digital signing, and population ledger committing.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-015', 'NID-CAP-016'],
      screenIds: ['NID-SCR-007'],
      formIds: ['NID-FORM-006'],
      dashboardIds: ['NID-DASH-003'],
      reportIds: ['NID-REP-007'],
      workflowIds: ['NID-WF-007'],
      databaseEntityIds: ['NID-DB-007'],
      apiIds: ['NID-API-007'],
      runtimeComponentId: 'NID-RTC-007',
      permissionIds: ['NID-PERM-007']
    },
    {
      id: 'NID-MOD-008',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      officeId: 'NID-OFF-010',
      portalId: 'NID-PORTAL-003',
      code: 'NID-MOD-SMARTCARD-PERSO',
      name: 'National Smart Card & Laser Engraving Manager',
      description: 'Control of industrial laser personalization machines, applet loading, and holographic security seals.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-017', 'NID-CAP-018'],
      screenIds: ['NID-SCR-008'],
      formIds: [],
      dashboardIds: ['NID-DASH-003'],
      reportIds: ['NID-REP-008'],
      workflowIds: ['NID-WF-008'],
      databaseEntityIds: ['NID-DB-008'],
      apiIds: ['NID-API-008'],
      runtimeComponentId: 'NID-RTC-008',
      permissionIds: ['NID-PERM-008']
    },
    {
      id: 'NID-MOD-009',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      officeId: 'NID-OFF-011',
      portalId: 'NID-PORTAL-002',
      code: 'NID-MOD-CARD-LOGISTICS',
      name: 'District Delivery & Biometric Handover Desk',
      description: 'Barcode-scanned secure crate distribution, district reception, and 1:1 match upon physical collection.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-019', 'NID-CAP-020'],
      screenIds: ['NID-SCR-009'],
      formIds: ['NID-FORM-007'],
      dashboardIds: [],
      reportIds: ['NID-REP-009'],
      workflowIds: ['NID-WF-009'],
      databaseEntityIds: ['NID-DB-009'],
      apiIds: ['NID-API-009'],
      runtimeComponentId: 'NID-RTC-009',
      permissionIds: ['NID-PERM-009']
    },
    {
      id: 'NID-MOD-010',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-009',
      officeId: 'NID-OFF-012',
      portalId: 'NID-PORTAL-004',
      code: 'NID-MOD-EKYC-GATEWAY',
      name: 'Real-Time Sovereign e-KYC Verification Gateway',
      description: 'Sub-100ms API for banks, telcos, and courts with biometrics, face liveness, and tokenized credentials.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-021', 'NID-CAP-022', 'NID-CAP-023'],
      screenIds: ['NID-SCR-010'],
      formIds: ['NID-FORM-008'],
      dashboardIds: ['NID-DASH-004'],
      reportIds: ['NID-REP-010'],
      workflowIds: ['NID-WF-010'],
      databaseEntityIds: ['NID-DB-010'],
      apiIds: ['NID-API-010'],
      runtimeComponentId: 'NID-RTC-010',
      permissionIds: ['NID-PERM-010']
    },
    {
      id: 'NID-MOD-011',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-010',
      officeId: 'NID-OFF-013',
      portalId: 'NID-PORTAL-001',
      code: 'NID-MOD-AUDIT-VAULT',
      name: 'Forensic Access Trail & Citizen Privacy Vault',
      description: 'Cryptographically sealed audit logs of every institutional access to citizen records with anomaly detection.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NID-CAP-024', 'NID-CAP-025'],
      screenIds: ['NID-SCR-011'],
      formIds: [],
      dashboardIds: ['NID-DASH-004'],
      reportIds: ['NID-REP-011'],
      workflowIds: ['NID-WF-011'],
      databaseEntityIds: ['NID-DB-011'],
      apiIds: ['NID-API-011'],
      runtimeComponentId: 'NID-RTC-011',
      permissionIds: ['NID-PERM-011']
    }
  ],
  capabilities: [
    {
      id: 'NID-CAP-001',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      officeId: 'NID-OFF-001',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-001',
      code: 'NID_CAP_RECORD_BIRTH',
      name: 'Record Hospital Birth Notification',
      description: 'Ingests newborn notification with mother and father NIN validation, doctor license check, and hospital seal.',
      serviceAction: 'nid.civil.recordBirthNotification',
      requiredPermission: 'NID-PERM-001',
      runtimeComponentId: 'NID-RTC-001',
      status: 'ACTIVE_CORE',
      inputs: [
        { name: 'childName', type: 'string', description: 'Full legal name of newborn', required: true },
        { name: 'dateOfBirth', type: 'date', description: 'Date and time of delivery', required: true },
        { name: 'motherNIN', type: 'string', description: 'Valid 14-digit National Identification Number of mother', required: true },
        { name: 'hospitalId', type: 'string', description: 'Licensed medical facility code', required: true }
      ],
      outputType: 'BirthNotificationRecord'
    },
    {
      id: 'NID-CAP-002',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      officeId: 'NID-OFF-001',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-001',
      code: 'NID_CAP_ISSUE_BIRTH_CERT',
      name: 'Generate Sovereign Birth Certificate',
      description: 'Issues cryptographic PDF and QR-coded certified birth registration with permanent registration number.',
      serviceAction: 'nid.civil.issueBirthCertificate',
      requiredPermission: 'NID-PERM-001',
      runtimeComponentId: 'NID-RTC-001',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-003',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-001',
      officeId: 'NID-OFF-002',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-001',
      code: 'NID_CAP_LATE_BIRTH_ADJUDICATE',
      name: 'Late Birth Registration Adjudication',
      description: 'Cross-verifies village administrative letters, baptism certificates, and clan testimony for non-hospital births.',
      serviceAction: 'nid.civil.adjudicateLateBirth',
      requiredPermission: 'NID-PERM-001',
      runtimeComponentId: 'NID-RTC-001',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-004',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-002',
      officeId: 'NID-OFF-003',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-002',
      code: 'NID_CAP_REGISTER_DEATH',
      name: 'Register Certified Death Event',
      description: 'Registers cause of death, locks the deceased person NIN against any new credit or voter registration.',
      serviceAction: 'nid.civil.registerDeath',
      requiredPermission: 'NID-PERM-002',
      runtimeComponentId: 'NID-RTC-002',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-005',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-002',
      officeId: 'NID-OFF-003',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-002',
      code: 'NID_CAP_ESTATE_NOTIFICATION',
      name: 'Broadcast Estate Probate Notification',
      description: 'Notifies the Administrator General, Judiciary Court Probate Registry, and Central Bank upon civil death confirmation.',
      serviceAction: 'nid.civil.broadcastEstateNotification',
      requiredPermission: 'NID-PERM-002',
      runtimeComponentId: 'NID-RTC-002',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-006',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-003',
      officeId: 'NID-OFF-004',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-003',
      code: 'NID_CAP_DEED_POLL_VERIFY',
      name: 'Verify High Court Deed Poll & Gazette Publication',
      description: 'Validates deed poll registration with the Uganda Gazette and updates historical alias index.',
      serviceAction: 'nid.civil.verifyDeedPoll',
      requiredPermission: 'NID-PERM-003',
      runtimeComponentId: 'NID-RTC-003',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-007',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-001',
      departmentId: 'NID-DEPT-003',
      officeId: 'NID-OFF-004',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-003',
      code: 'NID_CAP_UPDATE_BIODATA',
      name: 'Update Citizen Biographic Record',
      description: 'Applies authorized changes to marital status, residential address, or academic qualifications with audit logs.',
      serviceAction: 'nid.civil.updateBiodata',
      requiredPermission: 'NID-PERM-003',
      runtimeComponentId: 'NID-RTC-003',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-008',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      officeId: 'NID-OFF-006',
      portalId: 'NID-PORTAL-002',
      moduleId: 'NID-MOD-004',
      code: 'NID_CAP_CAPTURE_FINGERPRINTS',
      name: 'Capture 10-Print Biometrics (NFIQ2 Scored)',
      description: 'Acquires 4-4-2 slap fingerprints, calculates NIST NFIQ2 quality scores, and enforces re-capture on smudges.',
      serviceAction: 'nid.biometric.captureTenPrints',
      requiredPermission: 'NID-PERM-004',
      runtimeComponentId: 'NID-RTC-004',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-009',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      officeId: 'NID-OFF-006',
      portalId: 'NID-PORTAL-002',
      moduleId: 'NID-MOD-004',
      code: 'NID_CAP_CAPTURE_ICAO_PHOTO',
      name: 'Capture ICAO 9303 Compliant Facial Portrait',
      description: 'Enforces neutral expression, eye line symmetry, glare removal, and ISO/IEC 19794-5 image compliance.',
      serviceAction: 'nid.biometric.captureIcaoPortrait',
      requiredPermission: 'NID-PERM-004',
      runtimeComponentId: 'NID-RTC-004',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-010',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-004',
      officeId: 'NID-OFF-006',
      portalId: 'NID-PORTAL-002',
      moduleId: 'NID-MOD-004',
      code: 'NID_CAP_CAPTURE_IRIS',
      name: 'Dual Iris Infrared Sensor Capture',
      description: 'Captures left and right iris patterns with pupil dilation boundary detection for high-entropy biometric assurance.',
      serviceAction: 'nid.biometric.captureIris',
      requiredPermission: 'NID-PERM-004',
      runtimeComponentId: 'NID-RTC-004',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-011',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-005',
      officeId: 'NID-OFF-007',
      portalId: 'NID-PORTAL-003',
      moduleId: 'NID-MOD-005',
      code: 'NID_CAP_EXECUTE_ABIS_1TO_N',
      name: 'Execute 1-to-N National ABIS Deduplication',
      description: 'Searches multi-million biometric vector gallery to guarantee zero existing registrations for the enrollee.',
      serviceAction: 'nid.abis.execute1toNMatching',
      requiredPermission: 'NID-PERM-005',
      runtimeComponentId: 'NID-RTC-005',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-012',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-005',
      officeId: 'NID-OFF-007',
      portalId: 'NID-PORTAL-003',
      moduleId: 'NID-MOD-005',
      code: 'NID_CAP_CALCULATE_MATCH_SCORE',
      name: 'Calculate Multi-Biometric Fusion Score',
      description: 'Fuses fingerprint minutiae matching, facial embedding distance, and iris Hamming distance into a definitive score.',
      serviceAction: 'nid.abis.calculateFusionScore',
      requiredPermission: 'NID-PERM-005',
      runtimeComponentId: 'NID-RTC-005',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-013',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-006',
      officeId: 'NID-OFF-008',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-006',
      code: 'NID_CAP_FORENSIC_INSPECT_MINUTIAE',
      name: 'Inspect Visual Ridge Minutiae Points',
      description: 'Provides forensic magnification tools to confirm bifurcations, ridge endings, and scar patterns in contested matches.',
      serviceAction: 'nid.forensic.inspectMinutiae',
      requiredPermission: 'NID-PERM-006',
      runtimeComponentId: 'NID-RTC-006',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-014',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-002',
      departmentId: 'NID-DEPT-006',
      officeId: 'NID-OFF-008',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-006',
      code: 'NID_CAP_CONFIRM_OR_DISMISS_DUPLICATE',
      name: 'Issue Forensic Duplicate Verdict',
      description: 'Formal confirmation of fraud or dismissal of false-positive match, unlocking application for NIN assignment.',
      serviceAction: 'nid.forensic.issueAdjudicationVerdict',
      requiredPermission: 'NID-PERM-006',
      runtimeComponentId: 'NID-RTC-006',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-015',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-007',
      officeId: 'NID-OFF-009',
      portalId: 'NID-PORTAL-003',
      moduleId: 'NID-MOD-007',
      code: 'NID_CAP_GENERATE_NIN',
      name: 'Generate Luhn-Checked Immutable NIN',
      description: 'Generates 14-character alphanumeric National Identification Number conforming to ISO/IEC 7812 check algorithms.',
      serviceAction: 'nid.nin.generateIdentifier',
      requiredPermission: 'NID-PERM-007',
      runtimeComponentId: 'NID-RTC-007',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-016',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-007',
      officeId: 'NID-OFF-009',
      portalId: 'NID-PORTAL-003',
      moduleId: 'NID-MOD-007',
      code: 'NID_CAP_HSM_SIGN_IDENTITY',
      name: 'Cryptographic HSM Signing of Identity Token',
      description: 'Signs citizen identity payload with Sovereign Root Certificate via FIPS 140-2 Level 3 Hardware Security Module.',
      serviceAction: 'nid.nin.signWithHsm',
      requiredPermission: 'NID-PERM-007',
      runtimeComponentId: 'NID-RTC-007',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-017',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      officeId: 'NID-OFF-010',
      portalId: 'NID-PORTAL-003',
      moduleId: 'NID-MOD-008',
      code: 'NID_CAP_LOAD_CHIP_APPLETS',
      name: 'Provision ICAO e-ID Card Applets',
      description: 'Loads Match-On-Card biometric applet, e-Signature PKI private key container, and BAC/SAC access control.',
      serviceAction: 'nid.perso.loadCardApplets',
      requiredPermission: 'NID-PERM-008',
      runtimeComponentId: 'NID-RTC-008',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-018',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      officeId: 'NID-OFF-010',
      portalId: 'NID-PORTAL-003',
      moduleId: 'NID-MOD-008',
      code: 'NID_CAP_LASER_ENGRAVE_CARD',
      name: 'Execute Polycarbonate Laser Engraving',
      description: 'Engraves tactile ghost portrait, MLI/CLI optical variable device, and MRZ machine-readable zone.',
      serviceAction: 'nid.perso.executeLaserEngraving',
      requiredPermission: 'NID-PERM-008',
      runtimeComponentId: 'NID-RTC-008',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-019',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      officeId: 'NID-OFF-011',
      portalId: 'NID-PORTAL-002',
      moduleId: 'NID-MOD-009',
      code: 'NID_CAP_DISPATCH_CARD_BATCH',
      name: 'Dispatch Secure District Delivery Crate',
      description: 'Generates manifest of personalized cards with tamper-evident digital seals for armed courier transport.',
      serviceAction: 'nid.logistics.dispatchBatch',
      requiredPermission: 'NID-PERM-009',
      runtimeComponentId: 'NID-RTC-009',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-020',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-003',
      departmentId: 'NID-DEPT-008',
      officeId: 'NID-OFF-011',
      portalId: 'NID-PORTAL-002',
      moduleId: 'NID-MOD-009',
      code: 'NID_CAP_BIOMETRIC_CARD_HANDOVER',
      name: 'Verify Biometric Handover & Activate Card',
      description: 'Performs live 1:1 fingerprint match with citizen before handing over card and activating contactless chip.',
      serviceAction: 'nid.logistics.activateCardOnHandover',
      requiredPermission: 'NID-PERM-009',
      runtimeComponentId: 'NID-RTC-009',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-021',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-009',
      officeId: 'NID-OFF-012',
      portalId: 'NID-PORTAL-004',
      moduleId: 'NID-MOD-010',
      code: 'NID_CAP_INSTANT_EKYC_QUERY',
      name: 'Execute Real-Time Bank e-KYC Verification',
      description: 'Validates citizen NIN, surname, date of birth, and returns verified status with tamper-proof signature.',
      serviceAction: 'nid.ekyc.verifyCitizenQuery',
      requiredPermission: 'NID-PERM-010',
      runtimeComponentId: 'NID-RTC-010',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-022',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-009',
      officeId: 'NID-OFF-012',
      portalId: 'NID-PORTAL-004',
      moduleId: 'NID-MOD-010',
      code: 'NID_CAP_BIOMETRIC_MATCH_ON_API',
      name: 'Biometric 1:1 Match-on-API for Telco SIM Swap',
      description: 'Compares live biometric template from telecom shop against national vault to authorize high-risk SIM replacement.',
      serviceAction: 'nid.ekyc.matchBiometricApi',
      requiredPermission: 'NID-PERM-010',
      runtimeComponentId: 'NID-RTC-010',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-023',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-009',
      officeId: 'NID-OFF-012',
      portalId: 'NID-PORTAL-004',
      moduleId: 'NID-MOD-010',
      code: 'NID_CAP_MANAGE_API_QUOTA',
      name: 'Manage Institutional API Quota & Billing Switch',
      description: 'Tracks per-call e-KYC query charges, enforces SLA rate-limiting, and generates Treasury billing files.',
      serviceAction: 'nid.ekyc.manageInstitutionalQuota',
      requiredPermission: 'NID-PERM-010',
      runtimeComponentId: 'NID-RTC-010',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-024',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-010',
      officeId: 'NID-OFF-013',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-011',
      code: 'NID_CAP_FORENSIC_ACCESS_LOGGING',
      name: 'Record Cryptographic Access Ledger Block',
      description: 'Writes SHA-256 chained audit records for every viewing, verification, or export of citizen identity records.',
      serviceAction: 'nid.audit.appendForensicBlock',
      requiredPermission: 'NID-PERM-011',
      runtimeComponentId: 'NID-RTC-011',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NID-CAP-025',
      productId: 'prod-national-identity',
      directorateId: 'NID-DIR-004',
      departmentId: 'NID-DEPT-010',
      officeId: 'NID-OFF-013',
      portalId: 'NID-PORTAL-001',
      moduleId: 'NID-MOD-011',
      code: 'NID_CAP_GENERATE_PRIVACY_REPORT',
      name: 'Generate Citizen Data Privacy Audit Return',
      description: 'Compiles statutory reports for the Data Protection Commissioner documenting agency query volumes and consent verifications.',
      serviceAction: 'nid.audit.generatePrivacyReturn',
      requiredPermission: 'NID-PERM-011',
      runtimeComponentId: 'NID-RTC-011',
      status: 'ACTIVE_CORE'
    }
  ],
  screens: [
    { id: 'NID-SCR-001', productId: 'prod-national-identity', moduleId: 'NID-MOD-001', code: 'NID-SCR-BIRTHS', title: 'Civil Vital Registration Ledger', description: 'Real-time feed of birth and infant notifications.', viewType: 'TABLE', route: '/nid/births' },
    { id: 'NID-SCR-002', productId: 'prod-national-identity', moduleId: 'NID-MOD-002', code: 'NID-SCR-DEATHS', title: 'Civil Death & Estate Deactivation Registry', description: 'Deceased citizen records and estate notifications.', viewType: 'TABLE', route: '/nid/deaths' },
    { id: 'NID-SCR-003', productId: 'prod-national-identity', moduleId: 'NID-MOD-003', code: 'NID-SCR-DEEDPOLL', title: 'Deed Poll & Name Change Gazette Registry', description: 'Legal name changes and court order documents.', viewType: 'DETAIL', route: '/nid/corrections' },
    { id: 'NID-SCR-004', productId: 'prod-national-identity', moduleId: 'NID-MOD-004', code: 'NID-SCR-CAPTURE', title: 'Biometric Live Capture Terminal', description: 'Sensor integration for 10-prints, iris, and portrait.', viewType: 'FORM', route: '/nid/capture' },
    { id: 'NID-SCR-005', productId: 'prod-national-identity', moduleId: 'NID-MOD-005', code: 'NID-SCR-ABIS', title: 'ABIS Cluster Deduplication Grid', description: 'Parallel biometric search cluster load and score telemetry.', viewType: 'DASHBOARD', route: '/nid/abis' },
    { id: 'NID-SCR-006', productId: 'prod-national-identity', moduleId: 'NID-MOD-006', code: 'NID-SCR-FORENSIC', title: 'Forensic Minutiae Adjudication Console', description: 'Split ridge inspection and false match adjudication.', viewType: 'DETAIL', route: '/nid/adjudicate' },
    { id: 'NID-SCR-007', productId: 'prod-national-identity', moduleId: 'NID-MOD-007', code: 'NID-SCR-NIN', title: 'NIN Generation & HSM Signature Desk', description: 'Approved identity issuance and cryptographic committing.', viewType: 'TABLE', route: '/nid/issuance' },
    { id: 'NID-SCR-008', productId: 'prod-national-identity', moduleId: 'NID-MOD-008', code: 'NID-SCR-PERSO', title: 'Smart Card Laser Personalization Cockpit', description: 'Production lines, smart card laser engraving, and QC.', viewType: 'DASHBOARD', route: '/nid/personalization' },
    { id: 'NID-SCR-009', productId: 'prod-national-identity', moduleId: 'NID-MOD-009', code: 'NID-SCR-LOGISTICS', title: 'District Delivery & Card Handover Desk', description: 'Track card crates and verify 1:1 biometrics upon pickup.', viewType: 'TABLE', route: '/nid/logistics' },
    { id: 'NID-SCR-010', productId: 'prod-national-identity', moduleId: 'NID-MOD-010', code: 'NID-SCR-EKYC', title: 'Sovereign e-KYC Institutional Switchboard', description: 'Commercial query logs, latency telemetry, and billing.', viewType: 'DASHBOARD', route: '/nid/ekyc' },
    { id: 'NID-SCR-011', productId: 'prod-national-identity', moduleId: 'NID-MOD-011', code: 'NID-SCR-AUDIT', title: 'Sovereign Forensic Data Access Vault', description: 'Immutable hash chain of citizen record queries.', viewType: 'DOCUMENT', route: '/nid/audit' }
  ],
  forms: [
    {
      id: 'NID-FORM-001',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-001',
      code: 'NID-FORM-BIRTH',
      title: 'Newborn Civil Birth Registration Form',
      submitAction: 'nid.civil.recordBirthNotification',
      fieldCount: 6,
      fields: [
        { name: 'childName', label: 'Child Full Name', type: 'text', required: true, placeholder: 'e.g. Mukasa Jonathan' },
        { name: 'gender', label: 'Gender', type: 'select', required: true },
        { name: 'dateOfBirth', label: 'Date of Birth', type: 'date', required: true },
        { name: 'motherNIN', label: 'Mother NIN', type: 'text', required: true, placeholder: 'CM980000000000' },
        { name: 'fatherNIN', label: 'Father NIN', type: 'text', required: false, placeholder: 'CM970000000000' },
        { name: 'hospitalCode', label: 'Hospital Registration Code', type: 'text', required: true, placeholder: 'MULAGO-MAT-01' }
      ],
      validationRules: ['NIN_FORMAT_CHECK', 'DOCTOR_SEAL_REQUIRED']
    },
    {
      id: 'NID-FORM-002',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-002',
      code: 'NID-FORM-DEATH',
      title: 'Civil Death Certification Form',
      submitAction: 'nid.civil.registerDeath',
      fieldCount: 5,
      fields: [
        { name: 'deceasedNIN', label: 'Deceased NIN', type: 'text', required: true },
        { name: 'dateOfDeath', label: 'Date of Death', type: 'date', required: true },
        { name: 'causeOfDeath', label: 'Certified Medical Cause', type: 'text', required: true },
        { name: 'certifyingDoctorNIN', label: 'Certifying Doctor NIN', type: 'text', required: true },
        { name: 'burialPermitNumber', label: 'Burial Permit Number', type: 'text', required: true }
      ],
      validationRules: ['DECEASED_NIN_EXISTS', 'CORONER_VERIFIED']
    },
    {
      id: 'NID-FORM-003',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-003',
      code: 'NID-FORM-DEEDPOLL',
      title: 'Legal Name Change & Deed Poll Application',
      submitAction: 'nid.civil.verifyDeedPoll',
      fieldCount: 5,
      fields: [
        { name: 'currentNIN', label: 'Citizen NIN', type: 'text', required: true },
        { name: 'requestedNewName', label: 'Requested Legal Name', type: 'text', required: true },
        { name: 'highCourtOrderRef', label: 'High Court Order Reference', type: 'text', required: true },
        { name: 'gazetteNoticeNumber', label: 'Uganda Gazette Vol/Page', type: 'text', required: true },
        { name: 'reasonCode', label: 'Reason for Modification', type: 'select', required: true }
      ],
      validationRules: ['COURT_ORDER_ATTACHED', 'GAZETTE_VERIFIED']
    },
    {
      id: 'NID-FORM-004',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-004',
      code: 'NID-FORM-BIOMETRIC-INTAKE',
      title: 'Biometric Live Capture Dossier',
      submitAction: 'nid.biometric.captureTenPrints',
      fieldCount: 6,
      fields: [
        { name: 'enrollmentRef', label: 'Enrollment Dossier Reference', type: 'text', required: true },
        { name: 'scannerSerial', label: 'Optical Scanner Serial', type: 'text', required: true },
        { name: 'fingerprintQualityThreshold', label: 'Min NFIQ2 Score (1-100)', type: 'number', required: true },
        { name: 'facialPortraitStatus', label: 'Portrait ICAO Quality', type: 'text', required: true },
        { name: 'irisCaptureLeft', label: 'Left Iris Hash', type: 'text', required: true },
        { name: 'irisCaptureRight', label: 'Right Iris Hash', type: 'text', required: true }
      ],
      validationRules: ['NFIQ2_MIN_60', 'ICAO_POSE_SYMMETRY']
    },
    {
      id: 'NID-FORM-005',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-006',
      code: 'NID-FORM-ADJUDICATION-VERDICT',
      title: 'Forensic Adjudication Ruling Form',
      submitAction: 'nid.forensic.issueAdjudicationVerdict',
      fieldCount: 4,
      fields: [
        { name: 'dossierId', label: 'Contested Dossier ID', type: 'text', required: true },
        { name: 'examinerId', label: 'Examiner Clearance ID', type: 'text', required: true },
        { name: 'verdict', label: 'Forensic Finding', type: 'select', required: true },
        { name: 'justificationNotes', label: 'Technical Minutiae Analysis Justification', type: 'textarea', required: true }
      ],
      validationRules: ['SENIOR_FORENSIC_SIGNATURE']
    },
    {
      id: 'NID-FORM-006',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-007',
      code: 'NID-FORM-NIN-COMMITTING',
      title: 'NIN Generation & Ledger Commit Authorization',
      submitAction: 'nid.nin.generateIdentifier',
      fieldCount: 4,
      fields: [
        { name: 'dossierId', label: 'Approved Dossier ID', type: 'text', required: true },
        { name: 'districtCode', label: 'Origin District Code', type: 'text', required: true },
        { name: 'hsmSlotId', label: 'HSM Signature Slot', type: 'text', required: true },
        { name: 'rootKeyVersion', label: 'Sovereign Root Key Version', type: 'text', required: true }
      ],
      validationRules: ['HSM_DUAL_OPERATOR_SIGN']
    },
    {
      id: 'NID-FORM-007',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-009',
      code: 'NID-FORM-HANDOVER',
      title: 'Biometric Handover & Activation Verification',
      submitAction: 'nid.logistics.activateCardOnHandover',
      fieldCount: 4,
      fields: [
        { name: 'cardBarcode', label: 'Card Serial Barcode', type: 'text', required: true },
        { name: 'presenterNIN', label: 'Citizen NIN', type: 'text', required: true },
        { name: 'liveMatchScore', label: 'Match-On-Card Score (1-100)', type: 'number', required: true },
        { name: 'issuingOfficerId', label: 'Handover Officer Staff ID', type: 'text', required: true }
      ],
      validationRules: ['MATCH_ON_CARD_PASS']
    },
    {
      id: 'NID-FORM-008',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-010',
      code: 'NID-FORM-EKYC-PROVISION',
      name: 'Institutional e-KYC Access Provisioning',
      title: 'Institutional e-KYC Partner Onboarding',
      submitAction: 'nid.ekyc.manageInstitutionalQuota',
      fieldCount: 5,
      fields: [
        { name: 'institutionName', label: 'Financial / Telco Entity Name', type: 'text', required: true },
        { name: 'licenseNumber', label: 'Central Bank / Regulatory License', type: 'text', required: true },
        { name: 'allocatedMonthlyQuota', label: 'Monthly e-KYC Quota', type: 'number', required: true },
        { name: 'ipWhitelist', label: 'Whitelisted IPv4/IPv6 Subnets', type: 'text', required: true },
        { name: 'mTLSCertificatePem', label: 'Public mTLS Certificate (PEM)', type: 'textarea', required: true }
      ],
      validationRules: ['REGULATORY_LICENSE_ACTIVE']
    }
  ],
  dashboards: [
    {
      id: 'NID-DASH-001',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-001',
      code: 'NID-DASH-CIVIL',
      title: 'National Civil Vital Statistics Cockpit',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Registered Citizens', value: '45,820,419', trend: 'up', change: '+1.8% QoQ' },
        { label: 'Annual Live Births Ingested', value: '1,420,890', trend: 'up', change: '98.4% Hospitalized' },
        { label: 'Civil Deaths Commited', value: '284,500', trend: 'neutral', change: '100% De-listed' },
        { label: 'Late Birth Backlog', value: '14,210', trend: 'down', change: '-34% Resolved' }
      ]
    },
    {
      id: 'NID-DASH-002',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-005',
      code: 'NID-DASH-ABIS',
      title: 'ABIS Engine Cluster Performance & Deduplication Rate',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'ABIS Deduplication Accuracy', value: '99.9998%', trend: 'up', change: 'Zero False Accepts' },
        { label: 'Average 1:N Search Latency', value: '380 ms', trend: 'down', change: '-45ms Optimized' },
        { label: 'Active Field Kits Online', value: '3,850', trend: 'up', change: '99.1% Connected' },
        { label: 'Duplicate Fraud Interceptions', value: '18,450', trend: 'up', change: 'Handed to Police' }
      ]
    },
    {
      id: 'NID-DASH-003',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-007',
      code: 'NID-DASH-PRODUCTION',
      title: 'Smart Card Factory Production & Laser Throughput',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Daily Card Personalization Capacity', value: '65,000 Cards', trend: 'up', change: 'Full Capacity' },
        { label: 'Total Smart Cards Issued', value: '28,940,120', trend: 'up', change: '63.1% National' },
        { label: 'District Pickup Rate', value: '94.2%', trend: 'up', change: '+2.1% MoM' },
        { label: 'Laser Quality Rejection Rate', value: '0.04%', trend: 'down', change: 'Industrial Grade' }
      ]
    },
    {
      id: 'NID-DASH-004',
      productId: 'prod-national-identity',
      moduleId: 'NID-MOD-010',
      code: 'NID-DASH-EKYC',
      title: 'Institutional Sovereign e-KYC Traffic & Security Grid',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Real-Time e-KYC Queries / Sec', value: '4,280 TPS', trend: 'up', change: 'Peak Traffic' },
        { label: 'Integrated Banking Institutions', value: '34 Commercial Banks', trend: 'neutral', change: '100% Coverage' },
        { label: 'Telecom SIM Vetting Ingestions', value: '820,000 / Day', trend: 'up', change: 'Sub-150ms P99' },
        { label: 'Forensic Audit Integrity', value: '100% Hash Chained', trend: 'up', change: 'Zero Tampering' }
      ]
    }
  ],
  reports: [
    { id: 'NID-REP-001', productId: 'prod-national-identity', moduleId: 'NID-MOD-001', code: 'NID-REP-BIRTHS-MONTHLY', title: 'Monthly District Live Birth Registration Return', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'NID-REP-002', productId: 'prod-national-identity', moduleId: 'NID-MOD-002', code: 'NID-REP-DEATHS-PROBATE', title: 'Deceased Citizens Gazette & Court Notification Roster', format: 'FORENSIC_TRAIL', exportTypes: ['PDF', 'JSON'] },
    { id: 'NID-REP-003', productId: 'prod-national-identity', moduleId: 'NID-MOD-003', code: 'NID-REP-NAME-CHANGES', title: 'Quarterly Legal Name Modification Gazette Index', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'NID-REP-004', productId: 'prod-national-identity', moduleId: 'NID-MOD-004', code: 'NID-REP-FIELD-KITS', title: 'Field Enrollment Kit Daily Census & GPS Log', format: 'TABULAR', exportTypes: ['CSV', 'JSON'] },
    { id: 'NID-REP-005', productId: 'prod-national-identity', moduleId: 'NID-MOD-005', code: 'NID-REP-ABIS-DEDUP', title: 'ABIS Duplicate Identity Interception Forensic Ledger', format: 'FORENSIC_TRAIL', exportTypes: ['PDF', 'JSON'] },
    { id: 'NID-REP-006', productId: 'prod-national-identity', moduleId: 'NID-MOD-006', code: 'NID-REP-ADJUDICATION-LOG', title: 'Adjudication Officer Exception Ruling Summary', format: 'SUMMARY', exportTypes: ['PDF', 'XLSX'] },
    { id: 'NID-REP-007', productId: 'prod-national-identity', moduleId: 'NID-MOD-007', code: 'NID-REP-NIN-ISSUANCE', title: 'National NIN Generation & Population Ledger Certificate', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF'] },
    { id: 'NID-REP-008', productId: 'prod-national-identity', moduleId: 'NID-MOD-008', code: 'NID-REP-FACTORY-QC', title: 'Laser Engraving Batch Production Quality Report', format: 'SUMMARY', exportTypes: ['PDF', 'CSV'] },
    { id: 'NID-REP-009', productId: 'prod-national-identity', moduleId: 'NID-MOD-009', code: 'NID-REP-DISTRICT-CARDS', title: 'District Card Custody & Collection Reconciled Balance', format: 'TABULAR', exportTypes: ['PDF', 'XLSX'] },
    { id: 'NID-REP-010', productId: 'prod-national-identity', moduleId: 'NID-MOD-010', code: 'NID-REP-EKYC-BILLING', title: 'Institutional e-KYC Transaction Fee Treasury Statement', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'NID-REP-011', productId: 'prod-national-identity', moduleId: 'NID-MOD-011', code: 'NID-REP-DATA-PROTECTION', title: 'Annual Data Protection Commissioner Audit Compliance Return', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] }
  ],
  workflows: [
    { id: 'NID-WF-001', productId: 'prod-national-identity', moduleId: 'NID-MOD-001', code: 'NID-WF-BIRTH', title: 'Civil Birth Registration Lifecycle', stages: ['Hospital Notification', 'Parent NIN Vetting', 'Registrar Seal', 'NIN Issuance'], slaHours: 24, requiredApprovers: ['CIVIL_REGISTRAR'], initialState: 'Hospital Notification' },
    { id: 'NID-WF-002', productId: 'prod-national-identity', moduleId: 'NID-MOD-002', code: 'NID-WF-DEATH', title: 'Civil Death & Estate Deregistration Workflow', stages: ['Medical Cause Verification', 'Court Coroner Confirmation', 'Ledger Lock', 'Inter-Agency Broadcast'], slaHours: 12, requiredApprovers: ['CORONER_OFFICER', 'CHIEF_REGISTRAR'], initialState: 'Medical Cause Verification' },
    { id: 'NID-WF-003', productId: 'prod-national-identity', moduleId: 'NID-MOD-003', code: 'NID-WF-DEEDPOLL', title: 'Legal Name Change Verification', stages: ['Deed Poll Ingestion', 'Gazette Verification', 'Senior Legal Review', 'Registry Update'], slaHours: 48, requiredApprovers: ['LEGAL_RECORDS_OFFICER'], initialState: 'Deed Poll Ingestion' },
    { id: 'NID-WF-004', productId: 'prod-national-identity', moduleId: 'NID-MOD-004', code: 'NID-WF-ENROLL', title: 'Citizen Biometric Enrollment Workflow', stages: ['Dossier Creation', 'Biometric Capture', 'Quality Scored', 'ABIS Ingestion'], slaHours: 2, requiredApprovers: ['ENROLLMENT_OPERATOR'], initialState: 'Dossier Creation' },
    { id: 'NID-WF-005', productId: 'prod-national-identity', moduleId: 'NID-MOD-005', code: 'NID-WF-ABIS', title: 'ABIS 1:N Deduplication Verification', stages: ['Minutiae Extraction', '1:N Cluster Search', 'Score Fusion', 'Pass or Escalate'], slaHours: 1, requiredApprovers: ['ABIS_CLUSTER_ADMIN'], initialState: 'Minutiae Extraction' },
    { id: 'NID-WF-006', productId: 'prod-national-identity', moduleId: 'NID-MOD-006', code: 'NID-WF-ADJUDICATE', title: 'Forensic Duplicate Exception Adjudication', stages: ['Flagged Discrepancy', 'Ridge Minutiae Magnification', 'Dual Examiner Review', 'Final Ruling'], slaHours: 72, requiredApprovers: ['FORENSIC_ADJUDICATOR', 'CHIEF_FORENSIC_EXAMINER'], initialState: 'Flagged Discrepancy' },
    { id: 'NID-WF-007', productId: 'prod-national-identity', moduleId: 'NID-MOD-007', code: 'NID-WF-NIN', title: 'NIN Generation & Cryptographic Committing', stages: ['Luhn Number Generation', 'HSM Digital Sign', 'Population Ledger Commit', 'Ready for Perso'], slaHours: 4, requiredApprovers: ['HSM_SECURITY_OFFICER'], initialState: 'Luhn Number Generation' },
    { id: 'NID-WF-008', productId: 'prod-national-identity', moduleId: 'NID-MOD-008', code: 'NID-WF-PERSO', title: 'Smart Card Laser Personalization Workflow', stages: ['Card Body Staging', 'Laser Engraving', 'Chip Flashing', 'Optical QC Check'], slaHours: 6, requiredApprovers: ['CHIP_PERSO_ENGINEER'], initialState: 'Card Body Staging' },
    { id: 'NID-WF-009', productId: 'prod-national-identity', moduleId: 'NID-MOD-009', code: 'NID-WF-DELIVERY', title: 'District Card Custody & Biometric Collection', stages: ['Armed Transit', 'District Vault Receipt', 'SMS Citizen Alert', 'Biometric Handover'], slaHours: 96, requiredApprovers: ['LOGISTICS_OFFICER'], initialState: 'Armed Transit' },
    { id: 'NID-WF-010', productId: 'prod-national-identity', moduleId: 'NID-MOD-010', code: 'NID-WF-EKYC', title: 'Institutional e-KYC Query Execution', stages: ['mTLS Handshake', 'Consent Token Verification', 'Ledger Lookup', 'Signed Response'], slaHours: 1, requiredApprovers: ['INTEGRATION_ENGINEER'], initialState: 'mTLS Handshake' },
    { id: 'NID-WF-011', productId: 'prod-national-identity', moduleId: 'NID-MOD-011', code: 'NID-WF-PRIVACY-AUDIT', title: 'Data Privacy Violation Investigation', stages: ['Anomaly Alarm', 'Forensic Ledger Trace', 'Internal Affairs Report', 'Sanction Filing'], slaHours: 24, requiredApprovers: ['DATA_PROTECTION_OFFICER'], initialState: 'Anomaly Alarm' }
  ],
  databaseEntities: [
    { id: 'NID-DB-001', productId: 'prod-national-identity', moduleId: 'NID-MOD-001', tableName: 'nid_birth_records', primaryKey: 'birth_id', fields: [{ name: 'birth_id', type: 'VARCHAR(64)', required: true }, { name: 'child_name', type: 'VARCHAR(128)', required: true }, { name: 'mother_nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'dob', type: 'DATE', required: true }], auditLogged: true },
    { id: 'NID-DB-002', productId: 'prod-national-identity', moduleId: 'NID-MOD-002', tableName: 'nid_death_records', primaryKey: 'death_id', fields: [{ name: 'death_id', type: 'VARCHAR(64)', required: true }, { name: 'nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'date_of_death', type: 'DATE', required: true }], auditLogged: true },
    { id: 'NID-DB-003', productId: 'prod-national-identity', moduleId: 'NID-MOD-003', tableName: 'nid_deed_polls', primaryKey: 'deed_poll_id', fields: [{ name: 'deed_poll_id', type: 'VARCHAR(64)', required: true }, { name: 'nin', type: 'VARCHAR(14)', required: true }, { name: 'gazette_ref', type: 'VARCHAR(64)', required: true }], auditLogged: true },
    { id: 'NID-DB-004', productId: 'prod-national-identity', moduleId: 'NID-MOD-004', tableName: 'nid_biometric_templates', primaryKey: 'template_id', fields: [{ name: 'template_id', type: 'VARCHAR(64)', required: true }, { name: 'nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'nfiq2_score', type: 'INT', required: true }, { name: 'wsq_data', type: 'BYTEA', required: true }], auditLogged: true },
    { id: 'NID-DB-005', productId: 'prod-national-identity', moduleId: 'NID-MOD-005', tableName: 'nid_abis_match_jobs', primaryKey: 'job_id', fields: [{ name: 'job_id', type: 'VARCHAR(64)', required: true }, { name: 'match_score', type: 'FLOAT', required: true }, { name: 'verdict', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'NID-DB-006', productId: 'prod-national-identity', moduleId: 'NID-MOD-006', tableName: 'nid_adjudication_rulings', primaryKey: 'ruling_id', fields: [{ name: 'ruling_id', type: 'VARCHAR(64)', required: true }, { name: 'examiner_id', type: 'VARCHAR(64)', required: true }, { name: 'ruling', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'NID-DB-007', productId: 'prod-national-identity', moduleId: 'NID-MOD-007', tableName: 'nid_citizen_master_ledger', primaryKey: 'nin', fields: [{ name: 'nin', type: 'VARCHAR(14)', required: true, indexed: true }, { name: 'full_name', type: 'VARCHAR(256)', required: true }, { name: 'hsm_signature', type: 'TEXT', required: true }, { name: 'status', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'NID-DB-008', productId: 'prod-national-identity', moduleId: 'NID-MOD-008', tableName: 'nid_card_personalization_batches', primaryKey: 'batch_id', fields: [{ name: 'batch_id', type: 'VARCHAR(64)', required: true }, { name: 'total_cards', type: 'INT', required: true }, { name: 'laser_status', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'NID-DB-009', productId: 'prod-national-identity', moduleId: 'NID-MOD-009', tableName: 'nid_card_custody_handover', primaryKey: 'handover_id', fields: [{ name: 'handover_id', type: 'VARCHAR(64)', required: true }, { name: 'nin', type: 'VARCHAR(14)', required: true }, { name: 'match_score', type: 'INT', required: true }], auditLogged: true },
    { id: 'NID-DB-010', productId: 'prod-national-identity', moduleId: 'NID-MOD-010', tableName: 'nid_ekyc_partner_accounts', primaryKey: 'partner_id', fields: [{ name: 'partner_id', type: 'VARCHAR(64)', required: true }, { name: 'name', type: 'VARCHAR(128)', required: true }, { name: 'quota_remaining', type: 'INT', required: true }], auditLogged: true },
    { id: 'NID-DB-011', productId: 'prod-national-identity', moduleId: 'NID-MOD-011', tableName: 'nid_forensic_access_blocks', primaryKey: 'block_id', fields: [{ name: 'block_id', type: 'VARCHAR(64)', required: true }, { name: 'prev_hash', type: 'VARCHAR(64)', required: true }, { name: 'block_hash', type: 'VARCHAR(64)', required: true }, { name: 'payload', type: 'JSONB', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'NID-API-001', productId: 'prod-national-identity', moduleId: 'NID-MOD-001', code: 'NID_API_BIRTHS', method: 'POST', endpoint: '/api/v1/nid/births/register', requiredPermission: 'NID-PERM-001', handlerName: 'registerBirthHandler', summary: 'Ingest certified hospital birth record' },
    { id: 'NID-API-002', productId: 'prod-national-identity', moduleId: 'NID-MOD-002', code: 'NID_API_DEATHS', method: 'POST', endpoint: '/api/v1/nid/deaths/record', requiredPermission: 'NID-PERM-002', handlerName: 'recordDeathHandler', summary: 'Record civil death certificate and lock NIN' },
    { id: 'NID-API-003', productId: 'prod-national-identity', moduleId: 'NID-MOD-003', code: 'NID_API_DEEDPOLL', method: 'POST', endpoint: '/api/v1/nid/corrections/deed-poll', requiredPermission: 'NID-PERM-003', handlerName: 'verifyDeedPollHandler', summary: 'Submit verified deed poll name correction' },
    { id: 'NID-API-004', productId: 'prod-national-identity', moduleId: 'NID-MOD-004', code: 'NID_API_CAPTURE', method: 'POST', endpoint: '/api/v1/nid/biometrics/capture', requiredPermission: 'NID-PERM-004', handlerName: 'ingestBiometricsHandler', summary: 'Ingest 10-fingerprint and portrait package' },
    { id: 'NID-API-005', productId: 'prod-national-identity', moduleId: 'NID-MOD-005', code: 'NID_API_ABIS', method: 'POST', endpoint: '/api/v1/nid/abis/search-1toN', requiredPermission: 'NID-PERM-005', handlerName: 'searchAbisHandler', summary: 'Execute 1:N biometric gallery search' },
    { id: 'NID-API-006', productId: 'prod-national-identity', moduleId: 'NID-MOD-006', code: 'NID_API_ADJUDICATE', method: 'POST', endpoint: '/api/v1/nid/forensics/ruling', requiredPermission: 'NID-PERM-006', handlerName: 'submitAdjudicationRulingHandler', summary: 'Post forensic duplicate ruling verdict' },
    { id: 'NID-API-007', productId: 'prod-national-identity', moduleId: 'NID-MOD-007', code: 'NID_API_NIN_GEN', method: 'POST', endpoint: '/api/v1/nid/nin/generate', requiredPermission: 'NID-PERM-007', handlerName: 'generateNinHandler', summary: 'Commit new citizen and sign with HSM' },
    { id: 'NID-API-008', productId: 'prod-national-identity', moduleId: 'NID-MOD-008', code: 'NID_API_PERSO', method: 'POST', endpoint: '/api/v1/nid/cards/laser-job', requiredPermission: 'NID-PERM-008', handlerName: 'queueLaserJobHandler', summary: 'Send card job to smart card laser engine' },
    { id: 'NID-API-009', productId: 'prod-national-identity', moduleId: 'NID-MOD-009', code: 'NID_API_HANDOVER', method: 'POST', endpoint: '/api/v1/nid/cards/activate', requiredPermission: 'NID-PERM-009', handlerName: 'activateCardHandler', summary: 'Hand over card following 1:1 match' },
    { id: 'NID-API-010', productId: 'prod-national-identity', moduleId: 'NID-MOD-010', code: 'NID_API_EKYC', method: 'POST', endpoint: '/api/v1/nid/ekyc/verify', requiredPermission: 'NID-PERM-010', handlerName: 'verifyEkycHandler', summary: 'Real-time financial/telecom e-KYC check' },
    { id: 'NID-API-011', productId: 'prod-national-identity', moduleId: 'NID-MOD-011', code: 'NID_API_AUDIT', method: 'GET', endpoint: '/api/v1/nid/audit/chain-blocks', requiredPermission: 'NID-PERM-011', handlerName: 'getAuditBlocksHandler', summary: 'Fetch forensic SHA-256 audit ledger' }
  ],
  runtimeComponents: [
    { id: 'NID-RTC-001', productId: 'prod-national-identity', moduleId: 'NID-MOD-001', componentKey: 'NationalIdentityCivilRegEngine', name: 'Civil Vital Registration Runtime Engine', description: 'Interactive ledger and birth certificate issuing workspace.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CIVIL_ENGINE' },
    { id: 'NID-RTC-002', productId: 'prod-national-identity', moduleId: 'NID-MOD-002', componentKey: 'NationalIdentityDeathRegEngine', name: 'Death Deregistration & Estate Probate Runtime', description: 'Deceased citizen de-listing console.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CIVIL_ENGINE' },
    { id: 'NID-RTC-003', productId: 'prod-national-identity', moduleId: 'NID-MOD-003', componentKey: 'NationalIdentityDeedPollEngine', name: 'Deed Poll & Legal Alias Runtime', description: 'Court order review and legal gazette updates.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LEGAL_ENGINE' },
    { id: 'NID-RTC-004', productId: 'prod-national-identity', moduleId: 'NID-MOD-004', componentKey: 'NationalIdentityBiometricCaptureEngine', name: 'Biometric Capture & Quality Scoring Runtime', description: 'Hardware scanner capture and live ISO quality evaluation.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'BIOMETRIC_HARDWARE' },
    { id: 'NID-RTC-005', productId: 'prod-national-identity', moduleId: 'NID-MOD-005', componentKey: 'NationalIdentityAbisEngine', name: 'ABIS Deduplication & Matching Runtime', description: 'Parallel cluster search visualizer and fusion scorer.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MATCHING_CLUSTER' },
    { id: 'NID-RTC-006', productId: 'prod-national-identity', moduleId: 'NID-MOD-006', componentKey: 'NationalIdentityForensicAdjudicator', name: 'Forensic Minutiae Adjudication Console', description: 'Side-by-side fingerprint ridge analyzer.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FORENSIC_LAB' },
    { id: 'NID-RTC-007', productId: 'prod-national-identity', moduleId: 'NID-MOD-007', componentKey: 'NationalIdentityNinIssuanceEngine', name: 'NIN Generation & HSM Signature Runtime', description: 'National Identification Number commit and HSM signing console.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'CRYPTO_SECURITY' },
    { id: 'NID-RTC-008', productId: 'prod-national-identity', moduleId: 'NID-MOD-008', componentKey: 'NationalIdentityLaserPersoEngine', name: 'Smart Card Laser Personalization Console', description: 'Industrial card printer and laser telemetry interface.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'MANUFACTURING_PERSO' },
    { id: 'NID-RTC-009', productId: 'prod-national-identity', moduleId: 'NID-MOD-009', componentKey: 'NationalIdentityCardLogisticsEngine', name: 'District Delivery & Handover Runtime', description: '1:1 match verification and card activation desk.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LOGISTICS' },
    { id: 'NID-RTC-010', productId: 'prod-national-identity', moduleId: 'NID-MOD-010', componentKey: 'NationalIdentityEkycSwitchboard', name: 'Sovereign e-KYC Switchboard & Telemetry', description: 'Real-time bank query monitor and tokenized KYC responder.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'INTER_AGENCY_GATEWAY' },
    { id: 'NID-RTC-011', productId: 'prod-national-identity', moduleId: 'NID-MOD-011', componentKey: 'NationalIdentityAuditVaultRuntime', name: 'Forensic Access Ledger & Privacy Vault', description: 'Tamper-proof hash chain explorer.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'DATA_PRIVACY_VAULT' }
  ],
  permissions: [
    { id: 'NID-PERM-001', productId: 'prod-national-identity', code: 'nid:civil:births', name: 'Civil Birth Registration Access', description: 'Authority to register hospital births and issue certificates' },
    { id: 'NID-PERM-002', productId: 'prod-national-identity', code: 'nid:civil:deaths', name: 'Civil Death & Estate Access', description: 'Authority to certify deaths and notify courts' },
    { id: 'NID-PERM-003', productId: 'prod-national-identity', code: 'nid:civil:deedpoll', name: 'Deed Poll Modification Access', description: 'Authority to apply gazetted legal name corrections' },
    { id: 'NID-PERM-004', productId: 'prod-national-identity', code: 'nid:biometrics:capture', name: 'Biometric Enrollment Access', description: 'Authority to operate live optical scanners and photo booths' },
    { id: 'NID-PERM-005', productId: 'prod-national-identity', code: 'nid:abis:search', name: 'ABIS Search & Cluster Management', description: 'Authority to monitor 1:N matching clusters' },
    { id: 'NID-PERM-006', productId: 'prod-national-identity', code: 'nid:forensics:adjudicate', name: 'Forensic Adjudication Authority', description: 'Authority to issue binding rulings on disputed duplicates' },
    { id: 'NID-PERM-007', productId: 'prod-national-identity', code: 'nid:nin:issue', name: 'NIN Issuance & HSM Signing', description: 'High-clearance authority to commit citizen records to master ledger' },
    { id: 'NID-PERM-008', productId: 'prod-national-identity', code: 'nid:perso:laser', name: 'Smart Card Personalization Management', description: 'Authority to command industrial laser engraving lines' },
    { id: 'NID-PERM-009', productId: 'prod-national-identity', code: 'nid:logistics:handover', name: 'District Card Handover & Activation', description: 'Authority to conduct 1:1 match and activate smart card' },
    { id: 'NID-PERM-010', productId: 'prod-national-identity', code: 'nid:ekyc:manage', name: 'e-KYC Gateway Administration', description: 'Authority to provision bank quotas and query telemetry' },
    { id: 'NID-PERM-011', productId: 'prod-national-identity', code: 'nid:audit:inspect', name: 'Sovereign Audit & Privacy Inspection', description: 'Authority to review forensic query chains and file privacy returns' }
  ],
  roles: [
    { id: 'NID-ROLE-001', productId: 'prod-national-identity', code: 'REGISTRAR_GENERAL', name: 'Registrar General of Citizen Data', tier: 'GOVERNANCE', permissionIds: ['NID-PERM-001', 'NID-PERM-002', 'NID-PERM-003', 'NID-PERM-006', 'NID-PERM-007', 'NID-PERM-011'] },
    { id: 'NID-ROLE-002', productId: 'prod-national-identity', code: 'CHIEF_FORENSIC_EXAMINER', name: 'Chief Biometric Forensic Examiner', tier: 'EXECUTIVE', permissionIds: ['NID-PERM-004', 'NID-PERM-005', 'NID-PERM-006'] },
    { id: 'NID-ROLE-003', productId: 'prod-national-identity', code: 'ENROLLMENT_OPERATOR', name: 'Field Biometric Enrollment Officer', tier: 'OPERATIONAL', permissionIds: ['NID-PERM-004', 'NID-PERM-009'] },
    { id: 'NID-ROLE-004', productId: 'prod-national-identity', code: 'EKYC_INTEGRATION_OFFICER', name: 'Institutional e-KYC Controller', tier: 'OPERATIONAL', permissionIds: ['NID-PERM-010', 'NID-PERM-011'] },
    { id: 'NID-ROLE-005', productId: 'prod-national-identity', code: 'CITIZEN_PUBLIC_USER', name: 'Verified Citizen / Self-Service User', tier: 'PUBLIC', permissionIds: [] }
  ]
};
