import { CanonicalProductHierarchy } from './types';

export const NURSERY_PRIMARY_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-nursery-primary',
    code: 'NPERP',
    name: 'Nursery & Primary School Enterprise ERP',
    category: 'INSTITUTIONAL_ERP',
    description: 'Complete early childhood and primary school operating system: Baby/Middle/Top ECD thematic curriculum, P1–P7 competence assessment, continuous assessment tests (CAT), UNEB PLE mock & indexing series, automated report cards, school fees cashbook & paycodes, child nutrition & food rations, and parent SMS gateway.',
    version: '2026.4.0',
    iconName: 'School',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Headteacher / Director of Nursery & Primary Academy',
    governingLegislation: 'NCDC Primary Curriculum & National ECD Policy 2026',
    directorateIds: [
      'NP-DIR-ECD-ACADEMICS',
      'NP-DIR-PRIMARY-CURRICULUM',
      'NP-DIR-BURSARY-STORES',
      'NP-DIR-CHILD-WELFARE-HEALTH',
      'NP-DIR-PARENT-PTA'
    ]
  },
  directorates: [
    {
      id: 'NP-DIR-ECD-ACADEMICS',
      productId: 'prod-nursery-primary',
      code: 'NP-DIR-ECD',
      name: 'Directorate of Early Childhood Development (ECD) & Nursery',
      description: 'Nursery Baby, Middle, and Top class developmental milestones, Montessori sensory learning, phonics, and primary school transition readiness.',
      leadRole: 'DIRECTOR_ECD_STUDIES',
      departmentIds: ['NP-DEPT-BABY-MIDDLE', 'NP-DEPT-TOP-TRANSITION']
    },
    {
      id: 'NP-DIR-PRIMARY-CURRICULUM',
      productId: 'prod-nursery-primary',
      code: 'NP-DIR-PRIMARY',
      name: 'Directorate of Primary Academics & National Assessment (P1–P7)',
      description: 'Lower Primary (P1–P3) thematic curriculum, Upper Primary (P4–P6) subject grading, and P7 UNEB Primary Leaving Examination (PLE) candidate preparation.',
      leadRole: 'DIRECTOR_OF_STUDIES_PRIMARY',
      departmentIds: ['NP-DEPT-LOWER-PRIMARY', 'NP-DEPT-UPPER-PRIMARY', 'NP-DEPT-PLE-CANDIDATE']
    },
    {
      id: 'NP-DIR-BURSARY-STORES',
      productId: 'prod-nursery-primary',
      code: 'NP-DIR-FINANCE',
      name: 'Directorate of School Bursary, Fees & Food Stores',
      description: 'Termly school fee billing, mobile money paycode reconciliations, bursary allocations, food rations (posho/beans) and scholastic inventory.',
      leadRole: 'HEAD_BURSAR',
      departmentIds: ['NP-DEPT-FEES-COLLECTION', 'NP-DEPT-KITCHEN-STORES']
    },
    {
      id: 'NP-DIR-CHILD-WELFARE-HEALTH',
      productId: 'prod-nursery-primary',
      code: 'NP-DIR-WELFARE',
      name: 'Directorate of Child Protection, Health & Boarding Welfare',
      description: 'Pediatric sickbay clinic, childhood deworming and immunization tracking, junior dormitory care, and morning school bus logistics.',
      leadRole: 'DEPUTY_HEAD_WELFARE',
      departmentIds: ['NP-DEPT-SICKBAY-CLINIC', 'NP-DEPT-PRIMARY-BOARDING', 'NP-DEPT-TRANSPORT-BUS']
    },
    {
      id: 'NP-DIR-PARENT-PTA',
      productId: 'prod-nursery-primary',
      code: 'NP-DIR-PTA',
      name: 'Directorate of Parent Engagement & PTA Governance',
      description: 'Automated SMS broadcast engine, termly academic circulars, digital report card dispatch, and PTA executive resolutions.',
      leadRole: 'PTA_LIAISON_LEAD',
      departmentIds: ['NP-DEPT-PARENT-COMMUNICATION']
    }
  ],
  departments: [
    {
      id: 'NP-DEPT-BABY-MIDDLE',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      code: 'NP-DEPT-ECD-INFANT',
      name: 'Department of Infant Daycare & Baby/Middle Phonics',
      description: 'Montessori sensory activities, gross/fine motor skills, social habits, rhymes, and foundational letter sounds.',
      headRole: 'HEAD_ECD_NURSERY',
      officeIds: ['NP-OFF-ECD-COORDINATOR']
    },
    {
      id: 'NP-DEPT-TOP-TRANSITION',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      code: 'NP-DEPT-TOP-CLASS',
      name: 'Department of Top Class & Primary Transition',
      description: 'Early reading comprehension, number concept mastery, handwriting, and P1 entrance assessment.',
      headRole: 'HEAD_TOP_CLASS',
      officeIds: ['NP-OFF-TOP-READINESS']
    },
    {
      id: 'NP-DEPT-LOWER-PRIMARY',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      code: 'NP-DEPT-THEMATIC-P1-P3',
      name: 'Department of Lower Primary Thematic Curriculum (P1–P3)',
      description: 'NCDC thematic learning in mother tongue and English, numeracy foundations, and continuous competence grading.',
      headRole: 'HEAD_LOWER_PRIMARY',
      officeIds: ['NP-OFF-THEMATIC-DESK']
    },
    {
      id: 'NP-DEPT-UPPER-PRIMARY',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      code: 'NP-DEPT-UPPER-P4-P6',
      name: 'Department of Upper Primary Subject Specialists (P4–P6)',
      description: 'Specialist teaching in Mathematics, Integrated Science, English Language, and Social Studies (SST) with CAT testing.',
      headRole: 'HEAD_UPPER_PRIMARY',
      officeIds: ['NP-OFF-UPPER-PRIMARY-DESK']
    },
    {
      id: 'NP-DEPT-PLE-CANDIDATE',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      code: 'NP-DEPT-PLE-P7',
      name: 'Department of P.7 UNEB PLE Candidate Preparation',
      description: 'Mock exam administration, candidate indexing, PLE registration e-portal verification, and academic performance clinics.',
      headRole: 'HEAD_PLE_CENTER',
      officeIds: ['NP-OFF-PLE-DESK']
    },
    {
      id: 'NP-DEPT-FEES-COLLECTION',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      code: 'NP-DEPT-FEES',
      name: 'Department of Primary Fees Invoicing & PayCode Cashbook',
      description: 'Termly student fee billing, Pegasus/SchoolPay mobile money matching, bursary discounts, and cashier posting.',
      headRole: 'CHIEF_PRIMARY_BURSAR',
      officeIds: ['NP-OFF-BURSAR-CASHIER']
    },
    {
      id: 'NP-DEPT-KITCHEN-STORES',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      code: 'NP-DEPT-STORES',
      name: 'Department of School Food Rations, Nutrition & Stores',
      description: 'Posho, beans, and sugar bulk warehouse ledger, kitchen ration requisitions, and scholastic supplies inventory.',
      headRole: 'HEAD_STOREKEEPER',
      officeIds: ['NP-OFF-STORES-DESK']
    },
    {
      id: 'NP-DEPT-SICKBAY-CLINIC',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      code: 'NP-DEPT-SICKBAY',
      name: 'Department of School Sickbay & Pediatric First Aid',
      description: 'Pediatric triage, immunization logs, malaria treatment protocols, deworming terms, and emergency parent referrals.',
      headRole: 'RESIDENT_CLINICAL_NURSE',
      officeIds: ['NP-OFF-SICKBAY-NURSE']
    },
    {
      id: 'NP-DEPT-PRIMARY-BOARDING',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      code: 'NP-DEPT-DORMS',
      name: 'Department of Junior Boarding Hostels & Dormitory Care',
      description: 'Cubicle bed space allocation, bedtime roll-call, laundry management, and matron pastoral supervision.',
      headRole: 'SENIOR_HOSTEL_MATRON',
      officeIds: ['NP-OFF-HOSTEL-MATRON']
    },
    {
      id: 'NP-DEPT-TRANSPORT-BUS',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      code: 'NP-DEPT-TRANSPORT',
      name: 'Department of School Van Fleet & Morning Logistics',
      description: 'Route mapping, morning pickup/evening drop-off rolls, vehicle safety checklists, and driver logs.',
      headRole: 'TRANSPORT_SUPERVISOR',
      officeIds: ['NP-OFF-TRANSPORT-DESK']
    },
    {
      id: 'NP-DEPT-PARENT-COMMUNICATION',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PARENT-PTA',
      code: 'NP-DEPT-SMS',
      name: 'Department of Parent SMS Gateway & Pastoral Circulars',
      description: 'Automated fee balance SMS broadcasts, instant absent pupil alerts, and digital report card PDF links.',
      headRole: 'COMMUNICATIONS_OFFICER',
      officeIds: ['NP-OFF-SMS-GATEWAY']
    }
  ],
  offices: [
    {
      id: 'NP-OFF-ECD-COORDINATOR',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-BABY-MIDDLE',
      code: 'NP-OFF-ECD-DESK',
      name: 'Early Childhood Coordination & Sensory Learning Desk',
      description: 'Daycare enrollment, motor development observations, and nursery activity plans.',
      officerRole: 'ECD_COORDINATOR',
      portalIds: ['NP-PORTAL-HEADTEACHER', 'NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-ECD-TRACKER', 'NP-MOD-PUPIL-REGISTRY']
    },
    {
      id: 'NP-OFF-TOP-READINESS',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-TOP-TRANSITION',
      code: 'NP-OFF-TOP-DESK',
      name: 'Top Class Reading & Primary Entry Readiness Desk',
      description: 'Phonics reading assessments and P1 admissions screening.',
      officerRole: 'TOP_CLASS_LEAD_TEACHER',
      portalIds: ['NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-ECD-TRACKER']
    },
    {
      id: 'NP-OFF-THEMATIC-DESK',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-LOWER-PRIMARY',
      code: 'NP-OFF-THEMATIC',
      name: 'Lower Primary Thematic Assessment Desk',
      description: 'Continuous assessment score entry for P1–P3 thematic learning strands.',
      officerRole: 'LOWER_PRIMARY_DOS',
      portalIds: ['NP-PORTAL-HEADTEACHER', 'NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-THEMATIC-CURRICULUM']
    },
    {
      id: 'NP-OFF-UPPER-PRIMARY-DESK',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-UPPER-PRIMARY',
      code: 'NP-OFF-UPPER-DESK',
      name: 'Upper Primary Subject Grading & Continuous Assessment Desk',
      description: 'Marking sheets, subject aggregate auto-calculation, and termly report cards compilation.',
      officerRole: 'DIRECTOR_OF_STUDIES',
      portalIds: ['NP-PORTAL-HEADTEACHER', 'NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-PRIMARY-EXAMS']
    },
    {
      id: 'NP-OFF-PLE-DESK',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-PLE-CANDIDATE',
      code: 'NP-OFF-PLE',
      name: 'UNEB PLE Examination Center Desk',
      description: 'P7 candidate index verification, Mock exam analysis, and UNEB PLE registration.',
      officerRole: 'PLE_CENTER_SUPERVISOR',
      portalIds: ['NP-PORTAL-HEADTEACHER', 'NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-PLE-CENTER']
    },
    {
      id: 'NP-OFF-BURSAR-CASHIER',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-FEES-COLLECTION',
      code: 'NP-OFF-BURSAR',
      name: 'Primary Bursar Cashier Desk',
      description: 'Issuing official fee receipts, bank slip clearances, and PayCode reconciliation.',
      officerRole: 'ASSISTANT_BURSAR',
      portalIds: ['NP-PORTAL-HEADTEACHER', 'NP-PORTAL-BURSAR'],
      moduleIds: ['NP-MOD-FEES-CASHBOOK']
    },
    {
      id: 'NP-OFF-STORES-DESK',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-KITCHEN-STORES',
      code: 'NP-OFF-STORES',
      name: 'Food Rations & Scholastic Storekeeper Desk',
      description: 'Dispatching kitchen food rations, uniforms, textbooks, and exercise books.',
      officerRole: 'STORE_DISPATCH_OFFICER',
      portalIds: ['NP-PORTAL-TEACHER', 'NP-PORTAL-BURSAR'],
      moduleIds: ['NP-MOD-KITCHEN-STORES']
    },
    {
      id: 'NP-OFF-SICKBAY-NURSE',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-SICKBAY-CLINIC',
      code: 'NP-OFF-SICKBAY',
      name: 'Resident Clinical Nurse Desk',
      description: 'Child triage, temperature logging, deworming administration, and medical logs.',
      officerRole: 'CLINICAL_NURSE',
      portalIds: ['NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-SICKBAY-PEDIATRIC']
    },
    {
      id: 'NP-OFF-HOSTEL-MATRON',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-PRIMARY-BOARDING',
      code: 'NP-OFF-DORMS',
      name: 'Junior Dormitory Matron Desk',
      description: 'Bed space assignment, evening biometric roll-call, and pastoral care.',
      officerRole: 'SENIOR_MATRON',
      portalIds: ['NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-BOARDING-DORMS']
    },
    {
      id: 'NP-OFF-TRANSPORT-DESK',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-TRANSPORT-BUS',
      code: 'NP-OFF-TRANSPORT',
      name: 'School Van Dispatch & Route Desk',
      description: 'Morning pickup route monitoring, van driver logbooks, and passenger rolls.',
      officerRole: 'FLEET_OFFICER',
      portalIds: ['NP-PORTAL-TEACHER'],
      moduleIds: ['NP-MOD-PUPIL-REGISTRY']
    },
    {
      id: 'NP-OFF-SMS-GATEWAY',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PARENT-PTA',
      departmentId: 'NP-DEPT-PARENT-COMMUNICATION',
      code: 'NP-OFF-SMS',
      name: 'Parent Telephony & SMS Dispatch Desk',
      description: 'Bulk SMS campaigns, automated fee payment alerts, and urgent notices.',
      officerRole: 'COMMUNICATIONS_LEAD',
      portalIds: ['NP-PORTAL-HEADTEACHER', 'NP-PORTAL-PARENT'],
      moduleIds: ['NP-MOD-PARENT-GATEWAY']
    }
  ],
  portals: [
    {
      id: 'NP-PORTAL-HEADTEACHER',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-UPPER-PRIMARY',
      officeId: 'NP-OFF-UPPER-PRIMARY-DESK',
      code: 'NP-PORTAL-HEADTEACHER',
      name: 'Headteacher & Management Board Cockpit',
      description: 'School enrollment statistics, total fee collections, PLE pass rate projections, and staff oversight.',
      targetRole: 'HEADTEACHER',
      authLevel: 'PKI_SOVEREIGN',
      route: '/nursery-primary/headteacher',
      moduleIds: ['NP-MOD-PUPIL-REGISTRY', 'NP-MOD-PRIMARY-EXAMS', 'NP-MOD-PLE-CENTER', 'NP-MOD-FEES-CASHBOOK', 'NP-MOD-PARENT-GATEWAY']
    },
    {
      id: 'NP-PORTAL-TEACHER',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-UPPER-PRIMARY',
      officeId: 'NP-OFF-UPPER-PRIMARY-DESK',
      code: 'NP-PORTAL-TEACHER',
      name: 'Primary Teacher & ECD Educator Workspace',
      description: 'Mark continuous assessment tests, enter attendance, submit kitchen requisitions, and record sickbay visits.',
      targetRole: 'PRIMARY_TEACHER',
      authLevel: 'STAFF',
      route: '/nursery-primary/staff',
      moduleIds: ['NP-MOD-ECD-TRACKER', 'NP-MOD-THEMATIC-CURRICULUM', 'NP-MOD-PRIMARY-EXAMS', 'NP-MOD-KITCHEN-STORES', 'NP-MOD-SICKBAY-PEDIATRIC', 'NP-MOD-BOARDING-DORMS']
    },
    {
      id: 'NP-PORTAL-BURSAR',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-FEES-COLLECTION',
      officeId: 'NP-OFF-BURSAR-CASHIER',
      code: 'NP-PORTAL-BURSAR',
      name: 'School Bursar & Cashbook Terminal',
      description: 'Fee collection posting, PayCode mobile money matching, store inventory requisitions, and bursary ledger.',
      targetRole: 'SCHOOL_BURSAR',
      authLevel: 'STAFF',
      route: '/nursery-primary/bursar',
      moduleIds: ['NP-MOD-FEES-CASHBOOK', 'NP-MOD-KITCHEN-STORES']
    },
    {
      id: 'NP-PORTAL-PARENT',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PARENT-PTA',
      departmentId: 'NP-DEPT-PARENT-COMMUNICATION',
      officeId: 'NP-OFF-SMS-GATEWAY',
      code: 'NP-PORTAL-PARENT',
      name: 'Parent Mobile E-Portal & Fee Payment App',
      description: 'View pupil report cards, pay school fees via Mobile Money, and track school van pickup location.',
      targetRole: 'PARENT_GUARDIAN',
      authLevel: 'PUBLIC',
      route: '/nursery-primary/parent',
      moduleIds: ['NP-MOD-PRIMARY-EXAMS', 'NP-MOD-FEES-CASHBOOK', 'NP-MOD-PARENT-GATEWAY']
    }
  ],
  modules: [
    {
      id: 'NP-MOD-ECD-TRACKER',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-BABY-MIDDLE',
      officeId: 'NP-OFF-ECD-COORDINATOR',
      portalId: 'NP-PORTAL-TEACHER',
      code: 'NP-MOD-ECD-TRACKER',
      name: 'Early Childhood Milestone & Phonics Ledger',
      description: 'Baby, Middle, and Top class developmental milestone assessments, sensory motor records, and phonics readiness tracking.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-ECD-001', 'NP-CAP-ECD-002'],
      screenIds: ['NP-SCR-ECD'],
      formIds: ['NP-FORM-ECD-EVAL'],
      dashboardIds: ['NP-DASH-ECD'],
      reportIds: ['NP-REP-ECD'],
      workflowIds: ['NP-WF-ECD'],
      databaseEntityIds: ['NP-DB-ECD-RECORDS'],
      apiIds: ['NP-API-ECD'],
      runtimeComponentId: 'NP-RTC-ECD',
      permissionIds: ['NP-PERM-ECD']
    },
    {
      id: 'NP-MOD-THEMATIC-CURRICULUM',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-LOWER-PRIMARY',
      officeId: 'NP-OFF-THEMATIC-DESK',
      portalId: 'NP-PORTAL-TEACHER',
      code: 'NP-MOD-THEMATIC-CURRICULUM',
      name: 'P1–P3 Thematic Learning & Competence Assessor',
      description: 'NCDC thematic curriculum grading: learning strands, mother tongue & English literacy, and social habits competence evaluation.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-THEM-001', 'NP-CAP-THEM-002'],
      screenIds: ['NP-SCR-THEMATIC'],
      formIds: ['NP-FORM-THEM-SCORE'],
      dashboardIds: ['NP-DASH-ACADEMICS'],
      reportIds: ['NP-REP-THEM'],
      workflowIds: ['NP-WF-THEMATIC'],
      databaseEntityIds: ['NP-DB-THEMATIC'],
      apiIds: ['NP-API-THEMATIC'],
      runtimeComponentId: 'NP-RTC-THEMATIC',
      permissionIds: ['NP-PERM-ACADEMICS']
    },
    {
      id: 'NP-MOD-PRIMARY-EXAMS',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-UPPER-PRIMARY',
      officeId: 'NP-OFF-UPPER-PRIMARY-DESK',
      portalId: 'NP-PORTAL-TEACHER',
      code: 'NP-MOD-PRIMARY-EXAMS',
      name: 'P4–P6 Subject Grading & Continuous Assessment (CAT)',
      description: 'Continuous assessment test scores (30%) + End of term exams (70%), automated grading aggregates, and PDF report cards.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-EXAM-001', 'NP-CAP-EXAM-002'],
      screenIds: ['NP-SCR-EXAMS'],
      formIds: ['NP-FORM-MARKS-ENTRY'],
      dashboardIds: ['NP-DASH-ACADEMICS'],
      reportIds: ['NP-REP-REPORTCARD'],
      workflowIds: ['NP-WF-REPORTCARD'],
      databaseEntityIds: ['NP-DB-MARKS'],
      apiIds: ['NP-API-MARKS'],
      runtimeComponentId: 'NP-RTC-EXAMS',
      permissionIds: ['NP-PERM-ACADEMICS']
    },
    {
      id: 'NP-MOD-PLE-CENTER',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-PLE-CANDIDATE',
      officeId: 'NP-OFF-PLE-DESK',
      portalId: 'NP-PORTAL-HEADTEACHER',
      code: 'NP-MOD-PLE-CENTER',
      name: 'P7 UNEB PLE Candidate Mock & Indexing System',
      description: 'UNEB PLE candidate registration, national indexing verification, mock examination series, and performance forecasting.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-PLE-001', 'NP-CAP-PLE-002'],
      screenIds: ['NP-SCR-PLE'],
      formIds: ['NP-FORM-PLE-CANDIDATE'],
      dashboardIds: ['NP-DASH-ACADEMICS'],
      reportIds: ['NP-REP-PLE'],
      workflowIds: ['NP-WF-PLE'],
      databaseEntityIds: ['NP-DB-PLE-CANDIDATES'],
      apiIds: ['NP-API-PLE'],
      runtimeComponentId: 'NP-RTC-PLE',
      permissionIds: ['NP-PERM-HEADTEACHER']
    },
    {
      id: 'NP-MOD-PUPIL-REGISTRY',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-BABY-MIDDLE',
      officeId: 'NP-OFF-ECD-COORDINATOR',
      portalId: 'NP-PORTAL-HEADTEACHER',
      code: 'NP-MOD-PUPIL-REGISTRY',
      name: 'Pupil Enrollment, Biometrics & LIN Registry',
      description: 'Pupil biographical census, learner identification numbers (LIN), class registers, and daily morning biometric rolls.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-SIS-001', 'NP-CAP-SIS-002'],
      screenIds: ['NP-SCR-PUPILS'],
      formIds: ['NP-FORM-PUPIL-REG'],
      dashboardIds: ['NP-DASH-ENROLLMENT'],
      reportIds: ['NP-REP-ENROLLMENT'],
      workflowIds: ['NP-WF-ADMISSION'],
      databaseEntityIds: ['NP-DB-PUPILS'],
      apiIds: ['NP-API-PUPILS'],
      runtimeComponentId: 'NP-RTC-SIS',
      permissionIds: ['NP-PERM-SIS']
    },
    {
      id: 'NP-MOD-FEES-CASHBOOK',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-FEES-COLLECTION',
      officeId: 'NP-OFF-BURSAR-CASHIER',
      portalId: 'NP-PORTAL-BURSAR',
      code: 'NP-MOD-FEES-CASHBOOK',
      name: 'Primary School Fees Billing, Bursary & PayCode Ledger',
      description: 'Termly fee invoices, SchoolPay/Pegasus PayCode ingestion, cashier cashbook postings, and fee clearance receipts.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-FEE-001', 'NP-CAP-FEE-002'],
      screenIds: ['NP-SCR-FEES'],
      formIds: ['NP-FORM-FEE-POST'],
      dashboardIds: ['NP-DASH-FINANCE'],
      reportIds: ['NP-REP-FEES'],
      workflowIds: ['NP-WF-FEES'],
      databaseEntityIds: ['NP-DB-FEES-LEDGER'],
      apiIds: ['NP-API-FEES'],
      runtimeComponentId: 'NP-RTC-FEES',
      permissionIds: ['NP-PERM-BURSAR']
    },
    {
      id: 'NP-MOD-KITCHEN-STORES',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-KITCHEN-STORES',
      officeId: 'NP-OFF-STORES-DESK',
      portalId: 'NP-PORTAL-BURSAR',
      code: 'NP-MOD-KITCHEN-STORES',
      name: 'Food Rations, Nutrition & Uniform Inventory',
      description: 'Bulk store posho/beans stock balances, daily kitchen ration issues, pupil uniform issuance, and scholastic supplies.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-STORE-001', 'NP-CAP-STORE-002'],
      screenIds: ['NP-SCR-STORES'],
      formIds: ['NP-FORM-RATIONS-DISPATCH'],
      dashboardIds: ['NP-DASH-FINANCE'],
      reportIds: ['NP-REP-STORES'],
      workflowIds: ['NP-WF-STORES'],
      databaseEntityIds: ['NP-DB-STORES'],
      apiIds: ['NP-API-STORES'],
      runtimeComponentId: 'NP-RTC-STORES',
      permissionIds: ['NP-PERM-STORES']
    },
    {
      id: 'NP-MOD-SICKBAY-PEDIATRIC',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-SICKBAY-CLINIC',
      officeId: 'NP-OFF-SICKBAY-NURSE',
      portalId: 'NP-PORTAL-TEACHER',
      code: 'NP-MOD-SICKBAY-PEDIATRIC',
      name: 'Primary Sickbay Encounter & Deworming Clinic',
      description: 'Pediatric encounter records, temperature triage, routine deworming logs, prescription records, and hospital transfers.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-HEALTH-001', 'NP-CAP-HEALTH-002'],
      screenIds: ['NP-SCR-SICKBAY'],
      formIds: ['NP-FORM-SICKBAY-LOG'],
      dashboardIds: ['NP-DASH-WELFARE'],
      reportIds: ['NP-REP-HEALTH'],
      workflowIds: ['NP-WF-HEALTH'],
      databaseEntityIds: ['NP-DB-SICKBAY'],
      apiIds: ['NP-API-HEALTH'],
      runtimeComponentId: 'NP-RTC-HEALTH',
      permissionIds: ['NP-PERM-HEALTH']
    },
    {
      id: 'NP-MOD-BOARDING-DORMS',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-PRIMARY-BOARDING',
      officeId: 'NP-OFF-HOSTEL-MATRON',
      portalId: 'NP-PORTAL-TEACHER',
      code: 'NP-MOD-BOARDING-DORMS',
      name: 'Junior Boarding Hostels & Evening Biometric Roll-Call',
      description: 'Junior dormitory bed allocation, evening headcount verification, weekend leave permits, and matron pastoral reports.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-DORM-001', 'NP-CAP-DORM-002'],
      screenIds: ['NP-SCR-BOARDING'],
      formIds: ['NP-FORM-DORM-BED'],
      dashboardIds: ['NP-DASH-WELFARE'],
      reportIds: ['NP-REP-BOARDING'],
      workflowIds: ['NP-WF-BOARDING'],
      databaseEntityIds: ['NP-DB-BOARDING'],
      apiIds: ['NP-API-BOARDING'],
      runtimeComponentId: 'NP-RTC-BOARDING',
      permissionIds: ['NP-PERM-BOARDING']
    },
    {
      id: 'NP-MOD-PARENT-GATEWAY',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PARENT-PTA',
      departmentId: 'NP-DEPT-PARENT-COMMUNICATION',
      officeId: 'NP-OFF-SMS-GATEWAY',
      portalId: 'NP-PORTAL-HEADTEACHER',
      code: 'NP-MOD-PARENT-GATEWAY',
      name: 'Parent SMS Broadcasts & Digital Report Card Dispatch',
      description: 'Automated SMS broadcast engine for fee balance notifications, unexcused absence alerts, and end-of-term circulars.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['NP-CAP-SMS-001', 'NP-CAP-SMS-002'],
      screenIds: ['NP-SCR-SMS'],
      formIds: ['NP-FORM-SMS-CAMPAIGN'],
      dashboardIds: ['NP-DASH-ENROLLMENT'],
      reportIds: ['NP-REP-SMS'],
      workflowIds: ['NP-WF-SMS'],
      databaseEntityIds: ['NP-DB-SMS-LOGS'],
      apiIds: ['NP-API-SMS'],
      runtimeComponentId: 'NP-RTC-SMS',
      permissionIds: ['NP-PERM-COMMUNICATIONS']
    }
  ],
  capabilities: [
    {
      id: 'NP-CAP-ECD-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-BABY-MIDDLE',
      officeId: 'NP-OFF-ECD-COORDINATOR',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-ECD-TRACKER',
      code: 'NP_CAP_ECD_EVALUATE_MILESTONES',
      name: 'Evaluate Nursery Child Developmental Milestones',
      description: 'Records gross/fine motor skills, speech development, social interaction, and color recognition for baby and middle classes.',
      serviceAction: 'primary.ecd.evaluateMilestones',
      requiredPermission: 'NP-PERM-ECD',
      runtimeComponentId: 'NP-RTC-ECD',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-ECD-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-TOP-TRANSITION',
      officeId: 'NP-OFF-TOP-READINESS',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-ECD-TRACKER',
      code: 'NP_CAP_ECD_TOP_READINESS_CERT',
      name: 'Assess Top Class Primary Transition Readiness',
      description: 'Certifies child phonics fluency, number counting, pencil grip, and certifies eligibility for P.1 enrollment.',
      serviceAction: 'primary.ecd.certifyReadiness',
      requiredPermission: 'NP-PERM-ECD',
      runtimeComponentId: 'NP-RTC-ECD',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-THEM-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-LOWER-PRIMARY',
      officeId: 'NP-OFF-THEMATIC-DESK',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-THEMATIC-CURRICULUM',
      code: 'NP_CAP_THEM_RECORD_STRAND_SCORE',
      name: 'Record Thematic Competence Strand Score (P1–P3)',
      description: 'Enters competence ratings (Level 1–3) for NCDC thematic learning strands including Our Environment, Health, and Community.',
      serviceAction: 'primary.thematic.recordStrandScore',
      requiredPermission: 'NP-PERM-ACADEMICS',
      runtimeComponentId: 'NP-RTC-THEMATIC',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-THEM-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-LOWER-PRIMARY',
      officeId: 'NP-OFF-THEMATIC-DESK',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-THEMATIC-CURRICULUM',
      code: 'NP_CAP_THEM_GENERATE_THEMATIC_REPORT',
      name: 'Generate Lower Primary Thematic Progress Report',
      description: 'Compiles pictorial and descriptive thematic progress card with class teacher and headteacher remarks.',
      serviceAction: 'primary.thematic.generateReport',
      requiredPermission: 'NP-PERM-ACADEMICS',
      runtimeComponentId: 'NP-RTC-THEMATIC',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-EXAM-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-UPPER-PRIMARY',
      officeId: 'NP-OFF-UPPER-PRIMARY-DESK',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-PRIMARY-EXAMS',
      code: 'NP_CAP_EXAM_ENTER_MARKS',
      name: 'Enter Subject Assessment Marks (CAT & End of Term)',
      description: 'Enters scores for English, Math, Science, and SST with automated weighting: 30% Continuous Assessment + 70% Terminal Exam.',
      serviceAction: 'primary.academics.enterMarks',
      requiredPermission: 'NP-PERM-ACADEMICS',
      runtimeComponentId: 'NP-RTC-EXAMS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-EXAM-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-UPPER-PRIMARY',
      officeId: 'NP-OFF-UPPER-PRIMARY-DESK',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-PRIMARY-EXAMS',
      code: 'NP_CAP_EXAM_GENERATE_REPORT_CARDS',
      name: 'Generate Automated Termly Report Cards with Aggregates',
      description: 'Auto-computes subject grades (D1–F9), aggregate out of 36, class division (Division 1–4), and generates signed PDF report cards.',
      serviceAction: 'primary.academics.generateReportCards',
      requiredPermission: 'NP-PERM-ACADEMICS',
      runtimeComponentId: 'NP-RTC-EXAMS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-PLE-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-PLE-CANDIDATE',
      officeId: 'NP-OFF-PLE-DESK',
      portalId: 'NP-PORTAL-HEADTEACHER',
      moduleId: 'NP-MOD-PLE-CENTER',
      code: 'NP_CAP_PLE_REGISTER_CANDIDATE',
      name: 'Register & Verify UNEB PLE Candidate Index',
      description: 'Validates birth certificates, LIN registration, passport photograph, and generates official UNEB candidate verification slip.',
      serviceAction: 'primary.ple.registerCandidate',
      requiredPermission: 'NP-PERM-HEADTEACHER',
      runtimeComponentId: 'NP-RTC-PLE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-PLE-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PRIMARY-CURRICULUM',
      departmentId: 'NP-DEPT-PLE-CANDIDATE',
      officeId: 'NP-OFF-PLE-DESK',
      portalId: 'NP-PORTAL-HEADTEACHER',
      moduleId: 'NP-MOD-PLE-CENTER',
      code: 'NP_CAP_PLE_MOCK_SERIES_ANALYTICS',
      name: 'Analyze Inter-School PLE Mock Examination Series',
      description: 'Aggregates Mock 1, Mock 2, and Joint Diocesan Mock exam trends to forecast Division 1 candidate distributions.',
      serviceAction: 'primary.ple.analyzeMockSeries',
      requiredPermission: 'NP-PERM-HEADTEACHER',
      runtimeComponentId: 'NP-RTC-PLE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-SIS-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-BABY-MIDDLE',
      officeId: 'NP-OFF-ECD-COORDINATOR',
      portalId: 'NP-PORTAL-HEADTEACHER',
      moduleId: 'NP-MOD-PUPIL-REGISTRY',
      code: 'NP_CAP_SIS_ENROLL_PUPIL',
      name: 'Enroll Primary / Nursery Pupil with LIN',
      description: 'Registers child legal names, date of birth, emergency parent phone numbers, medical allergies, and issues Learner ID.',
      serviceAction: 'primary.pupil.enrollStudent',
      requiredPermission: 'NP-PERM-SIS',
      runtimeComponentId: 'NP-RTC-SIS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-SIS-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-ECD-ACADEMICS',
      departmentId: 'NP-DEPT-BABY-MIDDLE',
      officeId: 'NP-OFF-ECD-COORDINATOR',
      portalId: 'NP-PORTAL-HEADTEACHER',
      moduleId: 'NP-MOD-PUPIL-REGISTRY',
      code: 'NP_CAP_SIS_RECORD_DAILY_ATTENDANCE',
      name: 'Record Daily Class Register & Morning Attendance',
      description: 'Logs morning presence/absence and triggers automated SMS alerts to parents of unexcused absent pupils.',
      serviceAction: 'primary.pupil.recordAttendance',
      requiredPermission: 'NP-PERM-SIS',
      runtimeComponentId: 'NP-RTC-SIS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-FEE-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-FEES-COLLECTION',
      officeId: 'NP-OFF-BURSAR-CASHIER',
      portalId: 'NP-PORTAL-BURSAR',
      moduleId: 'NP-MOD-FEES-CASHBOOK',
      code: 'NP_CAP_FEE_POST_PAYMENT',
      name: 'Post School Fee Receipt & Clear Balance',
      description: 'Reconciles cash, bank deposit slip, or Mobile Money transaction against pupil fee account and prints receipt.',
      serviceAction: 'primary.finance.postFeePayment',
      requiredPermission: 'NP-PERM-BURSAR',
      runtimeComponentId: 'NP-RTC-FEES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-FEE-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-FEES-COLLECTION',
      officeId: 'NP-OFF-BURSAR-CASHIER',
      portalId: 'NP-PORTAL-BURSAR',
      moduleId: 'NP-MOD-FEES-CASHBOOK',
      code: 'NP_CAP_FEE_GENERATE_TERMLY_INVOICES',
      name: 'Generate Termly School Fee Invoices & PayCodes',
      description: 'Generates tuition, boarding, development fund, and uniform charges with unique SchoolPay / Pegasus PayCodes.',
      serviceAction: 'primary.finance.generateInvoices',
      requiredPermission: 'NP-PERM-BURSAR',
      runtimeComponentId: 'NP-RTC-FEES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-STORE-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-KITCHEN-STORES',
      officeId: 'NP-OFF-STORES-DESK',
      portalId: 'NP-PORTAL-BURSAR',
      moduleId: 'NP-MOD-KITCHEN-STORES',
      code: 'NP_CAP_STORE_DISPATCH_RATIONS',
      name: 'Dispatch Food Rations to School Kitchen',
      description: 'Authorizes posho, beans, rice, and cooking oil release with head cook electronic signature verification.',
      serviceAction: 'primary.store.dispatchRations',
      requiredPermission: 'NP-PERM-STORES',
      runtimeComponentId: 'NP-RTC-STORES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-STORE-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-BURSARY-STORES',
      departmentId: 'NP-DEPT-KITCHEN-STORES',
      officeId: 'NP-OFF-STORES-DESK',
      portalId: 'NP-PORTAL-BURSAR',
      moduleId: 'NP-MOD-KITCHEN-STORES',
      code: 'NP_CAP_STORE_AUDIT_STOCK',
      name: 'Audit Store Inventory & Food Ration Balances',
      description: 'Performs physical inventory count of scholastic materials, uniforms, and food rations against store ledger.',
      serviceAction: 'primary.store.auditStock',
      requiredPermission: 'NP-PERM-STORES',
      runtimeComponentId: 'NP-RTC-STORES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-HEALTH-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-SICKBAY-CLINIC',
      officeId: 'NP-OFF-SICKBAY-NURSE',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-SICKBAY-PEDIATRIC',
      code: 'NP_CAP_HEALTH_LOG_SICKBAY_VISIT',
      name: 'Record Pupil Sickbay Clinical Encounter',
      description: 'Logs vital signs, body temperature, diagnosed illness (e.g. Malaria, Flu), administered medicine, and bed rest.',
      serviceAction: 'primary.health.logSickbayVisit',
      requiredPermission: 'NP-PERM-HEALTH',
      runtimeComponentId: 'NP-RTC-HEALTH',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-HEALTH-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-SICKBAY-CLINIC',
      officeId: 'NP-OFF-SICKBAY-NURSE',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-SICKBAY-PEDIATRIC',
      code: 'NP_CAP_HEALTH_ISSUE_HOSPITAL_REFERRAL',
      name: 'Authorize Urgent Hospital Transfer & Alert Parent',
      description: 'Issues clinical referral document for acute conditions and triggers automated emergency telephone dispatch.',
      serviceAction: 'primary.health.issueHospitalReferral',
      requiredPermission: 'NP-PERM-HEALTH',
      runtimeComponentId: 'NP-RTC-HEALTH',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-DORM-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-PRIMARY-BOARDING',
      officeId: 'NP-OFF-HOSTEL-MATRON',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-BOARDING-DORMS',
      code: 'NP_CAP_DORM_ALLOCATE_BED',
      name: 'Allocate Boarding Hostel Bed Space',
      description: 'Assigns pupil to dormitory, cubicle, and bed number with matron supervision checklist.',
      serviceAction: 'primary.boarding.allocateDormBed',
      requiredPermission: 'NP-PERM-BOARDING',
      runtimeComponentId: 'NP-RTC-BOARDING',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-DORM-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-CHILD-WELFARE-HEALTH',
      departmentId: 'NP-DEPT-PRIMARY-BOARDING',
      officeId: 'NP-OFF-HOSTEL-MATRON',
      portalId: 'NP-PORTAL-TEACHER',
      moduleId: 'NP-MOD-BOARDING-DORMS',
      code: 'NP_CAP_DORM_SUBMIT_ROLLCALL',
      name: 'Submit Bedtime Dormitory Roll-Call',
      description: 'Nightly headcount verifying all boarding pupils are accounted for in hostel cubicles.',
      serviceAction: 'primary.boarding.submitRollCall',
      requiredPermission: 'NP-PERM-BOARDING',
      runtimeComponentId: 'NP-RTC-BOARDING',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-SMS-001',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PARENT-PTA',
      departmentId: 'NP-DEPT-PARENT-COMMUNICATION',
      officeId: 'NP-OFF-SMS-GATEWAY',
      portalId: 'NP-PORTAL-HEADTEACHER',
      moduleId: 'NP-MOD-PARENT-GATEWAY',
      code: 'NP_CAP_SMS_BROADCAST_PARENTS',
      name: 'Send Bulk SMS Broadcast to Parents',
      description: 'Sends targeted text messages by class or school-wide for urgent announcements and school opening notices.',
      serviceAction: 'primary.sms.broadcastParentSms',
      requiredPermission: 'NP-PERM-COMMUNICATIONS',
      runtimeComponentId: 'NP-RTC-SMS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'NP-CAP-SMS-002',
      productId: 'prod-nursery-primary',
      directorateId: 'NP-DIR-PARENT-PTA',
      departmentId: 'NP-DEPT-PARENT-COMMUNICATION',
      officeId: 'NP-OFF-SMS-GATEWAY',
      portalId: 'NP-PORTAL-HEADTEACHER',
      moduleId: 'NP-MOD-PARENT-GATEWAY',
      code: 'NP_CAP_SMS_SEND_FEE_REMINDERS',
      name: 'Trigger Automated Fee Balance Reminder SMS',
      description: 'Pushes personalized SMS with pupil name, outstanding fee balance, and unique Pegasus PayCode.',
      serviceAction: 'primary.sms.sendFeeReminders',
      requiredPermission: 'NP-PERM-COMMUNICATIONS',
      runtimeComponentId: 'NP-RTC-SMS',
      status: 'ACTIVE_CORE'
    }
  ],
  screens: [
    { id: 'NP-SCR-ECD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-ECD-TRACKER', code: 'NP-SCR-ECD', title: 'Early Childhood Milestones & Phonics Dashboard', description: 'Nursery class milestone progress and phonics tracker.', viewType: 'TABLE', route: '/nursery-primary/ecd' },
    { id: 'NP-SCR-THEMATIC', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-THEMATIC-CURRICULUM', code: 'NP-SCR-THEMATIC', title: 'Lower Primary Thematic Curriculum (P1–P3)', description: 'Thematic strand assessment and progress ratings.', viewType: 'TABLE', route: '/nursery-primary/thematic' },
    { id: 'NP-SCR-EXAMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PRIMARY-EXAMS', code: 'NP-SCR-EXAMS', title: 'P4–P6 Subject Grading & Terminal Report Cards', description: 'Continuous assessment marks, exam scoring, and report cards.', viewType: 'TABLE', route: '/nursery-primary/exams' },
    { id: 'NP-SCR-PLE', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PLE-CENTER', code: 'NP-SCR-PLE', title: 'P7 UNEB PLE Candidate Preparation Center', description: 'Candidate indexing, Mock examination series, and performance trends.', viewType: 'TABLE', route: '/nursery-primary/ple' },
    { id: 'NP-SCR-PUPILS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PUPIL-REGISTRY', code: 'NP-SCR-PUPILS', title: 'Pupil Enrollment, Bio Records & LIN Directory', description: 'Active enrolled pupils, class streams, and biometric registers.', viewType: 'TABLE', route: '/nursery-primary/pupils' },
    { id: 'NP-SCR-FEES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-FEES-CASHBOOK', code: 'NP-SCR-FEES', title: 'School Fees Cashbook, PayCodes & Bursary Ledger', description: 'Fee billing, collection receipts, and defaulters follow-up.', viewType: 'TABLE', route: '/nursery-primary/bursary' },
    { id: 'NP-SCR-STORES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-KITCHEN-STORES', code: 'NP-SCR-STORES', title: 'School Food Stores, Nutrition & Rations Vault', description: 'Warehouse stock of posho/beans, kitchen releases, and uniforms.', viewType: 'TABLE', route: '/nursery-primary/stores' },
    { id: 'NP-SCR-SICKBAY', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-SICKBAY-PEDIATRIC', code: 'NP-SCR-SICKBAY', title: 'School Sickbay & Child Health Clinic', description: 'Clinical encounter logs, immunization, and medical notes.', viewType: 'TABLE', route: '/nursery-primary/sickbay' },
    { id: 'NP-SCR-BOARDING', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-BOARDING-DORMS', code: 'NP-SCR-BOARDING', title: 'Junior Boarding Hostels & Dormitory Roll-Call', description: 'Dormitory rooming, bedtime attendance, and pastoral notes.', viewType: 'TABLE', route: '/nursery-primary/boarding' },
    { id: 'NP-SCR-SMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PARENT-GATEWAY', code: 'NP-SCR-SMS', title: 'Parent SMS Center & Notification Gateway', description: 'Bulk SMS campaigns, automated fee alerts, and notices.', viewType: 'DASHBOARD', route: '/nursery-primary/sms' }
  ],
  forms: [
    {
      id: 'NP-FORM-ECD-EVAL',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-ECD-TRACKER',
      code: 'NP-FORM-ECD-EVAL',
      title: 'Nursery Child Milestone Evaluation Form',
      submitAction: 'primary.ecd.evaluateMilestones',
      fieldCount: 5,
      fields: [
        { name: 'pupilId', label: 'Pupil Registration / LIN', type: 'text', required: true },
        { name: 'nurseryClass', label: 'Class (Baby / Middle / Top)', type: 'select', required: true },
        { name: 'motorSkillsRating', label: 'Fine & Gross Motor Skills (1-5)', type: 'number', required: true },
        { name: 'phonicsReadiness', label: 'Letter Sound / Phonics Level', type: 'select', required: true },
        { name: 'teacherRemarks', label: 'Developmental Remarks', type: 'textarea', required: false }
      ],
      validationRules: ['RATING_1_TO_5']
    },
    {
      id: 'NP-FORM-THEM-SCORE',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-THEMATIC-CURRICULUM',
      code: 'NP-FORM-THEM-SCORE',
      title: 'Lower Primary Thematic Competence Entry',
      submitAction: 'primary.thematic.recordStrandScore',
      fieldCount: 5,
      fields: [
        { name: 'pupilId', label: 'Pupil Registration ID', type: 'text', required: true },
        { name: 'thematicStrand', label: 'Thematic Strand (Environment / Health / Home)', type: 'select', required: true },
        { name: 'competenceLevel', label: 'Competence Rating (Level 1/2/3)', type: 'select', required: true },
        { name: 'motherTongueSkill', label: 'Mother Tongue Literacy Rating', type: 'select', required: true },
        { name: 'englishLiteracySkill', label: 'English Literacy Rating', type: 'select', required: true }
      ],
      validationRules: ['COMPETENCE_VALID']
    },
    {
      id: 'NP-FORM-MARKS-ENTRY',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-PRIMARY-EXAMS',
      code: 'NP-FORM-MARKS-ENTRY',
      title: 'Upper Primary Marks Score Sheet',
      submitAction: 'primary.academics.enterMarks',
      fieldCount: 5,
      fields: [
        { name: 'pupilId', label: 'Pupil Registration Number', type: 'text', required: true },
        { name: 'subjectName', label: 'Subject Name (Math / English / SST / Science)', type: 'select', required: true },
        { name: 'catScore', label: 'Continuous Assessment (0–30)', type: 'number', required: true },
        { name: 'examScore', label: 'End of Term Exam Score (0–70)', type: 'number', required: true },
        { name: 'teacherRemarks', label: 'Class Teacher Remarks', type: 'text', required: false }
      ],
      validationRules: ['MARKS_RANGE_VALID']
    },
    {
      id: 'NP-FORM-PLE-CANDIDATE',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-PLE-CENTER',
      code: 'NP-FORM-PLE-CANDIDATE',
      title: 'P.7 UNEB PLE Candidate Registration',
      submitAction: 'primary.ple.registerCandidate',
      fieldCount: 5,
      fields: [
        { name: 'pupilId', label: 'Pupil School Registration ID', type: 'text', required: true },
        { name: 'linNumber', label: 'National Learner ID (LIN)', type: 'text', required: true },
        { name: 'candidateIndexNumber', label: 'Assigned UNEB Index Number', type: 'text', required: true },
        { name: 'dateOfBirth', label: 'Verified Date of Birth', type: 'date', required: true },
        { name: 'specialNeedsProvision', label: 'Special Examination Needs (None/Braille/Large Print)', type: 'select', required: true }
      ],
      validationRules: ['INDEX_VALID']
    },
    {
      id: 'NP-FORM-PUPIL-REG',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-PUPIL-REGISTRY',
      code: 'NP-FORM-PUPIL-REG',
      title: 'Primary / Nursery Pupil Admission Entry',
      submitAction: 'primary.pupil.enrollStudent',
      fieldCount: 5,
      fields: [
        { name: 'pupilFullName', label: 'Pupil Legal Name', type: 'text', required: true },
        { name: 'dob', label: 'Date of Birth', type: 'date', required: true },
        { name: 'entryClass', label: 'Admitted Class (Baby, Middle, Top, P.1–P.7)', type: 'select', required: true },
        { name: 'parentName', label: 'Parent / Guardian Full Name', type: 'text', required: true },
        { name: 'parentPhone', label: 'Parent Mobile Money Phone Number', type: 'text', required: true }
      ],
      validationRules: ['PHONE_VALID']
    },
    {
      id: 'NP-FORM-FEE-POST',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-FEES-CASHBOOK',
      code: 'NP-FORM-FEE-POST',
      title: 'School Fee Payment Cashier Posting',
      submitAction: 'primary.finance.postFeePayment',
      fieldCount: 4,
      fields: [
        { name: 'pupilId', label: 'Pupil Registration ID', type: 'text', required: true },
        { name: 'amountPaidUgx', label: 'Payment Amount (UGX)', type: 'number', required: true },
        { name: 'paymentChannel', label: 'Channel (CASH / BANK_SLIP / MOMO)', type: 'select', required: true },
        { name: 'bankSlipRef', label: 'Bank Slip / PayCode Reference', type: 'text', required: true }
      ],
      validationRules: ['AMOUNT_POSITIVE']
    },
    {
      id: 'NP-FORM-RATIONS-DISPATCH',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-KITCHEN-STORES',
      code: 'NP-FORM-RATIONS-DISPATCH',
      title: 'School Kitchen Food Rations Requisition',
      submitAction: 'primary.store.dispatchRations',
      fieldCount: 4,
      fields: [
        { name: 'itemCode', label: 'Store Item (Maize Posho / Sugar / Beans)', type: 'select', required: true },
        { name: 'quantityKg', label: 'Dispatched Quantity (KG / Bags)', type: 'number', required: true },
        { name: 'headCookStaffId', label: 'Receiving Head Cook Staff ID', type: 'text', required: true },
        { name: 'mealPurpose', label: 'Meal Purpose (Pupil Lunch / Supper)', type: 'text', required: true }
      ],
      validationRules: ['STOCK_AVAILABLE']
    },
    {
      id: 'NP-FORM-SICKBAY-LOG',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-SICKBAY-PEDIATRIC',
      code: 'NP-FORM-SICKBAY-LOG',
      title: 'Pupil Sickbay Clinical Encounter Log',
      submitAction: 'primary.health.logSickbayVisit',
      fieldCount: 5,
      fields: [
        { name: 'pupilId', label: 'Pupil Registration ID', type: 'text', required: true },
        { name: 'temperatureCelsius', label: 'Body Temperature (°C)', type: 'number', required: true },
        { name: 'symptoms', label: 'Clinical Symptoms Observed', type: 'text', required: true },
        { name: 'administeredDrug', label: 'Medication Given (Dose & Time)', type: 'text', required: true },
        { name: 'bedRestPrescribed', label: 'Bed Rest Required in Sickbay?', type: 'checkbox', required: false }
      ],
      validationRules: ['TEMP_REALISTIC']
    },
    {
      id: 'NP-FORM-DORM-BED',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-BOARDING-DORMS',
      code: 'NP-FORM-DORM-BED',
      title: 'Boarding House Bed Space Assignment',
      submitAction: 'primary.boarding.allocateDormBed',
      fieldCount: 4,
      fields: [
        { name: 'pupilId', label: 'Pupil Registration ID', type: 'text', required: true },
        { name: 'dormitoryName', label: 'Hostel / Dormitory Wing', type: 'select', required: true },
        { name: 'cubicleNo', label: 'Cubicle / Room Number', type: 'text', required: true },
        { name: 'bedNumber', label: 'Assigned Bed Number', type: 'text', required: true }
      ],
      validationRules: ['BED_UNOCCUPIED']
    },
    {
      id: 'NP-FORM-SMS-CAMPAIGN',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-PARENT-GATEWAY',
      code: 'NP-FORM-SMS-CAMPAIGN',
      title: 'Parent SMS Broadcast Campaign Form',
      submitAction: 'primary.sms.broadcastParentSms',
      fieldCount: 4,
      fields: [
        { name: 'targetGroup', label: 'Target Audience (ALL / BY_CLASS / DEFAULTERS)', type: 'select', required: true },
        { name: 'senderId', label: 'Registered SMS Sender ID', type: 'text', required: true },
        { name: 'messageText', label: 'SMS Content (Max 160 chars)', type: 'textarea', required: true },
        { name: 'includePaycode', label: 'Append Individual Student PayCode?', type: 'checkbox', required: false }
      ],
      validationRules: ['MESSAGE_NOT_EMPTY']
    }
  ],
  dashboards: [
    {
      id: 'NP-DASH-ECD',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-ECD-TRACKER',
      code: 'NP-DASH-ECD',
      title: 'Early Childhood Development & Nursery Health',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Enrolled Nursery Toddlers', value: '380 Toddlers', trend: 'up', change: 'Baby, Middle & Top' },
        { label: 'Phonics Fluency Milestone', value: '92.4%', trend: 'up', change: 'Montessori Assessment' },
        { label: 'Daily Nutrition Intake Rate', value: '98.5%', trend: 'up', change: 'Morning Porridge / Fruit' },
        { label: 'Top Class Transition Index', value: '100%', trend: 'up', change: 'Ready for P.1' }
      ]
    },
    {
      id: 'NP-DASH-ACADEMICS',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-PRIMARY-EXAMS',
      code: 'NP-DASH-ACADEMICS',
      title: 'Primary Academic Performance & PLE Projections',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Enrolled Primary Pupils', value: '1,040 Pupils', trend: 'up', change: 'P.1 to P.7 Full Roll' },
        { label: 'Termly Exam Pass Rate', value: '95.6%', trend: 'up', change: 'Continuous Assessment' },
        { label: 'Candidate PLE Target', value: '100% Div 1 & 2', trend: 'up', change: '86 Candidates' },
        { label: 'Daily Class Attendance', value: '97.2%', trend: 'up', change: 'Morning Biometric' }
      ]
    },
    {
      id: 'NP-DASH-FINANCE',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-FEES-CASHBOOK',
      code: 'NP-DASH-FINANCE',
      title: 'School Fees Bursary & Store Stock Cashflow',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Term Fee Collection Rate', value: '89.6%', trend: 'up', change: 'UGX 890M Ingested' },
        { label: 'Mobile Money PayCode Share', value: '78.4%', trend: 'up', change: 'Pegasus / SchoolPay' },
        { label: 'Posho/Beans Store Cover', value: '45 Days Food', trend: 'up', change: 'Sufficient Buffer' },
        { label: 'Fee Clearance Issued', value: '1,280 Pupils', trend: 'up', change: 'Exam Permits' }
      ]
    },
    {
      id: 'NP-DASH-WELFARE',
      productId: 'prod-nursery-primary',
      moduleId: 'NP-MOD-SICKBAY-PEDIATRIC',
      code: 'NP-DASH-WELFARE',
      title: 'Child Welfare, Sickbay Clinic & Boarding',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Boarding Hostel Headcount', value: '520 Boarders', trend: 'up', change: '100% Roll Checked' },
        { label: 'Sickbay Triage Encounters', value: '18 Visits/Wk', trend: 'down', change: 'Mild Malaria & Flu' },
        { label: 'Routine Deworming Coverage', value: '100%', trend: 'up', change: 'Term 1 Campaign Complete' },
        { label: 'Active School Van Routes', value: '8 Vans Active', trend: 'neutral', change: 'GPS Tracked' }
      ]
    }
  ],
  reports: [
    { id: 'NP-REP-ECD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-ECD-TRACKER', code: 'NP-REP-ECD', title: 'Early Childhood Milestone & Growth Ledger', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'NP-REP-THEM', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-THEMATIC-CURRICULUM', code: 'NP-REP-THEM', title: 'Lower Primary Thematic Progress Transcript', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'NP-REP-REPORTCARD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PRIMARY-EXAMS', code: 'NP-REP-REPORTCARD', title: 'Official Termly Continuous Assessment Report Card', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'NP-REP-PLE', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PLE-CENTER', code: 'NP-REP-PLE', title: 'P.7 UNEB Candidate Registration & Mock Performance Ledger', format: 'REGULATORY_RETURN', exportTypes: ['PDF', 'XLSX'] },
    { id: 'NP-REP-ENROLLMENT', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PUPIL-REGISTRY', code: 'NP-REP-ENROLLMENT', title: 'Headteacher Termly Census & Enrollment Register', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'NP-REP-FEES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-FEES-CASHBOOK', code: 'NP-REP-FEES', title: 'School Fees Collection & Defaulters Cashbook', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX', 'CSV'] },
    { id: 'NP-REP-STORES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-KITCHEN-STORES', code: 'NP-REP-STORES', title: 'Food Rations & Scholastic Materials Consumption Audit', format: 'FORENSIC_TRAIL', exportTypes: ['PDF', 'CSV'] },
    { id: 'NP-REP-HEALTH', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-SICKBAY-PEDIATRIC', code: 'NP-REP-HEALTH', title: 'Pediatric Sickbay Encounter & Deworming Register', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'NP-REP-BOARDING', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-BOARDING-DORMS', code: 'NP-REP-BOARDING', title: 'Hostel Bed Space & Biometric Headcount Report', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'NP-REP-SMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PARENT-GATEWAY', code: 'NP-REP-SMS', title: 'Parent SMS Delivery & Telephony Log', format: 'FORENSIC_TRAIL', exportTypes: ['PDF', 'XLSX'] }
  ],
  workflows: [
    { id: 'NP-WF-ECD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-ECD-TRACKER', code: 'NP-WF-ECD', title: 'Nursery Child Milestone Observation Workflow', stages: ['OBSERVED', 'EVALUATED', 'PARENT_NOTIFIED'], slaHours: 24, requiredApprovers: ['ROLE_NP_TEACHER'], initialState: 'OBSERVED' },
    { id: 'NP-WF-THEMATIC', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-THEMATIC-CURRICULUM', code: 'NP-WF-THEMATIC', title: 'Thematic Strand Competence Moderation Workflow', stages: ['ENTERED', 'MODERATED', 'PUBLISHED'], slaHours: 48, requiredApprovers: ['ROLE_NP_TEACHER', 'ROLE_NP_HEADTEACHER'], initialState: 'ENTERED' },
    { id: 'NP-WF-REPORTCARD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PRIMARY-EXAMS', code: 'NP-WF-REPORTCARD', title: 'Report Card Compilation & Seal Workflow', stages: ['MARKS_DRAFT', 'DOS_REVIEWED', 'HEADTEACHER_SEALED'], slaHours: 72, requiredApprovers: ['ROLE_NP_HEADTEACHER'], initialState: 'MARKS_DRAFT' },
    { id: 'NP-WF-PLE', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PLE-CENTER', code: 'NP-WF-PLE', title: 'UNEB PLE Candidate Verification Workflow', stages: ['LIN_VERIFIED', 'PHOTO_VALIDATED', 'INDEXED_SUBMITTED'], slaHours: 168, requiredApprovers: ['ROLE_NP_HEADTEACHER'], initialState: 'LIN_VERIFIED' },
    { id: 'NP-WF-ADMISSION', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PUPIL-REGISTRY', code: 'NP-WF-ADMISSION', title: 'New Pupil Admission & Class Allocation Workflow', stages: ['APPLIED', 'INTERVIEWED', 'ADMITTED_ENROLLED'], slaHours: 24, requiredApprovers: ['ROLE_NP_HEADTEACHER'], initialState: 'APPLIED' },
    { id: 'NP-WF-FEES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-FEES-CASHBOOK', code: 'NP-WF-FEES', title: 'School Fees Receipt & Clearance Workflow', stages: ['INVOICED', 'PAYMENT_RECEIVED', 'RECEIPT_CLEARANCE_ISSUED'], slaHours: 12, requiredApprovers: ['ROLE_NP_BURSAR'], initialState: 'INVOICED' },
    { id: 'NP-WF-STORES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-KITCHEN-STORES', code: 'NP-WF-STORES', title: 'Kitchen Food Ration Requisition & Release Workflow', stages: ['REQUISITIONED', 'BURSAR_APPROVED', 'STORE_DISPATCHED'], slaHours: 6, requiredApprovers: ['ROLE_NP_BURSAR'], initialState: 'REQUISITIONED' },
    { id: 'NP-WF-HEALTH', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-SICKBAY-PEDIATRIC', code: 'NP-WF-HEALTH', title: 'Sickbay Clinical Encounter & Triage Workflow', stages: ['TRIAGED', 'MEDICATED', 'RECOVERED_DISCHARGED'], slaHours: 4, requiredApprovers: ['ROLE_NP_NURSE'], initialState: 'TRIAGED' },
    { id: 'NP-WF-BOARDING', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-BOARDING-DORMS', code: 'NP-WF-BOARDING', title: 'Hostel Bed Allocation & Roll-Call Workflow', stages: ['BED_ASSIGNED', 'NIGHTLY_CHECKED', 'TERM_CLEARED'], slaHours: 8, requiredApprovers: ['ROLE_NP_MATRON'], initialState: 'BED_ASSIGNED' },
    { id: 'NP-WF-SMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PARENT-GATEWAY', code: 'NP-WF-SMS', title: 'Parent SMS Campaign Dispatch Workflow', stages: ['COMPOSED', 'DISPATCHED', 'DELIVERED'], slaHours: 1, requiredApprovers: ['ROLE_NP_HEADTEACHER'], initialState: 'COMPOSED' }
  ],
  databaseEntities: [
    { id: 'NP-DB-ECD-RECORDS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-ECD-TRACKER', tableName: 'np_ecd_milestones', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'pupil_id', type: 'UUID', required: true, indexed: true }, { name: 'phonics_score', type: 'INTEGER', required: true }, { name: 'motor_skills', type: 'VARCHAR(50)', required: true }, { name: 'assessed_at', type: 'TIMESTAMP', required: true }], auditLogged: true },
    { id: 'NP-DB-THEMATIC', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-THEMATIC-CURRICULUM', tableName: 'np_thematic_assessments', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'pupil_id', type: 'UUID', required: true, indexed: true }, { name: 'strand_name', type: 'VARCHAR(100)', required: true }, { name: 'competence_level', type: 'VARCHAR(20)', required: true }, { name: 'term', type: 'VARCHAR(20)', required: true }], auditLogged: true },
    { id: 'NP-DB-MARKS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PRIMARY-EXAMS', tableName: 'np_student_marks', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'pupil_id', type: 'UUID', required: true, indexed: true }, { name: 'subject_code', type: 'VARCHAR(20)', required: true }, { name: 'score', type: 'DECIMAL(5,2)', required: true }, { name: 'aggregate', type: 'INTEGER', required: true }], auditLogged: true },
    { id: 'NP-DB-PLE-CANDIDATES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PLE-CENTER', tableName: 'np_ple_candidates', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'lin_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'pupil_name', type: 'VARCHAR(255)', required: true }, { name: 'index_no', type: 'VARCHAR(30)', required: true, indexed: true }, { name: 'mock_aggregate', type: 'INTEGER', required: true }], auditLogged: true },
    { id: 'NP-DB-PUPILS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PUPIL-REGISTRY', tableName: 'np_pupils_registry', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'reg_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'full_name', type: 'VARCHAR(255)', required: true }, { name: 'class_stream', type: 'VARCHAR(50)', required: true }, { name: 'parent_phone', type: 'VARCHAR(20)', required: true }], auditLogged: true },
    { id: 'NP-DB-FEES-LEDGER', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-FEES-CASHBOOK', tableName: 'np_fees_cashbook', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'receipt_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'pupil_id', type: 'UUID', required: true, indexed: true }, { name: 'amount_paid', type: 'DECIMAL(18,2)', required: true }, { name: 'paycode', type: 'VARCHAR(50)', required: true }], auditLogged: true },
    { id: 'NP-DB-STORES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-KITCHEN-STORES', tableName: 'np_stores_inventory', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'item_name', type: 'VARCHAR(100)', required: true }, { name: 'quantity_kg', type: 'DECIMAL(10,2)', required: true }, { name: 'store_location', type: 'VARCHAR(50)', required: true }, { name: 'reorder_level', type: 'DECIMAL(10,2)', required: true }], auditLogged: true },
    { id: 'NP-DB-SICKBAY', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-SICKBAY-PEDIATRIC', tableName: 'np_sickbay_encounters', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'pupil_id', type: 'UUID', required: true, indexed: true }, { name: 'symptoms', type: 'TEXT', required: true }, { name: 'administered_drug', type: 'VARCHAR(255)', required: true }, { name: 'temperature_celsius', type: 'DECIMAL(4,1)', required: true }], auditLogged: true },
    { id: 'NP-DB-BOARDING', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-BOARDING-DORMS', tableName: 'np_hostel_allocations', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'pupil_id', type: 'UUID', required: true, indexed: true }, { name: 'dormitory_name', type: 'VARCHAR(100)', required: true }, { name: 'bed_number', type: 'VARCHAR(20)', required: true }, { name: 'term', type: 'VARCHAR(20)', required: true }], auditLogged: true },
    { id: 'NP-DB-SMS-LOGS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PARENT-GATEWAY', tableName: 'np_sms_broadcast_logs', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'recipient_phone', type: 'VARCHAR(20)', required: true }, { name: 'message_body', type: 'TEXT', required: true }, { name: 'delivery_status', type: 'VARCHAR(20)', required: true }, { name: 'sent_at', type: 'TIMESTAMP', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'NP-API-ECD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-ECD-TRACKER', code: 'API_NP_ECD', method: 'POST', endpoint: '/api/v1/primary/ecd/milestones', requiredPermission: 'NP-PERM-ECD', handlerName: 'submitEcdMilestonesHandler', summary: 'Submit nursery child milestone record.' },
    { id: 'NP-API-THEMATIC', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-THEMATIC-CURRICULUM', code: 'API_NP_THEMATIC', method: 'POST', endpoint: '/api/v1/primary/thematic/scores', requiredPermission: 'NP-PERM-ACADEMICS', handlerName: 'submitThematicScoresHandler', summary: 'Submit lower primary thematic scores.' },
    { id: 'NP-API-MARKS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PRIMARY-EXAMS', code: 'API_NP_MARKS', method: 'POST', endpoint: '/api/v1/primary/academics/marks', requiredPermission: 'NP-PERM-ACADEMICS', handlerName: 'submitMarksHandler', summary: 'Submit marks and generate report cards.' },
    { id: 'NP-API-PLE', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PLE-CENTER', code: 'API_NP_PLE', method: 'POST', endpoint: '/api/v1/primary/ple/candidates', requiredPermission: 'NP-PERM-HEADTEACHER', handlerName: 'registerPleCandidateHandler', summary: 'Register PLE candidate and submit mock results.' },
    { id: 'NP-API-PUPILS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PUPIL-REGISTRY', code: 'API_NP_PUPILS', method: 'POST', endpoint: '/api/v1/primary/pupils/enroll', requiredPermission: 'NP-PERM-SIS', handlerName: 'enrollPupilHandler', summary: 'Enroll primary student and allocate class.' },
    { id: 'NP-API-FEES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-FEES-CASHBOOK', code: 'API_NP_FEES', method: 'POST', endpoint: '/api/v1/primary/finance/payments', requiredPermission: 'NP-PERM-BURSAR', handlerName: 'postFeePaymentHandler', summary: 'Post fee payment receipt and update ledger.' },
    { id: 'NP-API-STORES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-KITCHEN-STORES', code: 'API_NP_STORES', method: 'POST', endpoint: '/api/v1/primary/stores/dispatch', requiredPermission: 'NP-PERM-STORES', handlerName: 'dispatchStoreRationsHandler', summary: 'Dispatch food rations to school kitchen.' },
    { id: 'NP-API-HEALTH', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-SICKBAY-PEDIATRIC', code: 'API_NP_HEALTH', method: 'POST', endpoint: '/api/v1/primary/health/encounters', requiredPermission: 'NP-PERM-HEALTH', handlerName: 'logSickbayEncounterHandler', summary: 'Log pupil clinical visit at sickbay.' },
    { id: 'NP-API-BOARDING', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-BOARDING-DORMS', code: 'API_NP_BOARDING', method: 'POST', endpoint: '/api/v1/primary/boarding/rollcall', requiredPermission: 'NP-PERM-BOARDING', handlerName: 'submitBoardingRollCallHandler', summary: 'Submit nightly hostel roll-call headcount.' },
    { id: 'NP-API-SMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PARENT-GATEWAY', code: 'API_NP_SMS', method: 'POST', endpoint: '/api/v1/primary/sms/broadcast', requiredPermission: 'NP-PERM-COMMUNICATIONS', handlerName: 'sendParentSmsHandler', summary: 'Trigger bulk SMS gateway dispatch to parents.' }
  ],
  runtimeComponents: [
    { id: 'NP-RTC-ECD', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-ECD-TRACKER', componentKey: 'NurseryEcdEngine', name: 'Nursery & Early Childhood Development Engine', description: 'Montessori early learning milestones, phonics fluency tracker, and daily feeding chart.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EARLY_LEARNING' },
    { id: 'NP-RTC-THEMATIC', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-THEMATIC-CURRICULUM', componentKey: 'PrimaryThematicEngine', name: 'Lower Primary Thematic Curriculum Engine', description: 'NCDC P.1-P.3 thematic curriculum continuous competency and literacy tracker.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LOWER_PRIMARY' },
    { id: 'NP-RTC-EXAMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PRIMARY-EXAMS', componentKey: 'PrimaryMarksEngine', name: 'Primary Assessment & Report Card Generator', description: 'BOT, MOT, EOT continuous assessment grading, term aggregate calculation, and printable report cards.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ACADEMICS' },
    { id: 'NP-RTC-PLE', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PLE-CENTER', componentKey: 'PrimaryPleEngine', name: 'UNEB PLE Candidate & Mock Series Engine', description: 'P.7 candidate LIN validation, Mock exam grading, aggregate prediction, and UNEB center returns.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EXAMINATION_CENTER' },
    { id: 'NP-RTC-SIS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PUPIL-REGISTRY', componentKey: 'PrimarySisEngine', name: 'Primary Pupil SIS & Biometric Attendance Engine', description: 'Pupil enrollment master directory, daily attendance roll, and parent contact ledger.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'STUDENT_INFO' },
    { id: 'NP-RTC-FEES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-FEES-CASHBOOK', componentKey: 'PrimaryFeesEngine', name: 'School Fees Cashbook & PayCode Engine', description: 'Pegasus/SchoolPay 10-digit PayCode fee collections, term invoicing, and examination clearance permits.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FEES_FINANCE' },
    { id: 'NP-RTC-STORES', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-KITCHEN-STORES', componentKey: 'PrimaryStoresEngine', name: 'School Food Rations & Inventory Store Engine', description: 'Posho/Beans stock bin cards, kitchen ration requisitions, and scholastic supplies tracking.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LOGISTICS_STORES' },
    { id: 'NP-RTC-HEALTH', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-SICKBAY-PEDIATRIC', componentKey: 'PrimarySickbayEngine', name: 'Primary Sickbay & Child Health Clinic Engine', description: 'Pupil clinical encounters, pediatric vitals, deworming register, and malaria treatment log.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'HEALTH_SICKBAY' },
    { id: 'NP-RTC-BOARDING', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-BOARDING-DORMS', componentKey: 'PrimaryBoardingEngine', name: 'Junior Boarding Hostels & Roll-Call Engine', description: 'Hostel bed assignments, nightly roll-call verification, and pupil boarding welfare logs.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'BOARDING_DORMS' },
    { id: 'NP-RTC-SMS', productId: 'prod-nursery-primary', moduleId: 'NP-MOD-PARENT-GATEWAY', componentKey: 'PrimarySmsEngine', name: 'Parent SMS Gateway & Telephony Broadcast Engine', description: 'Bulk automated SMS alerts for fee arrears, report card release, and urgent school notices.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'PARENT_COMMS' }
  ],
  permissions: [
    { id: 'NP-PERM-ECD', productId: 'prod-nursery-primary', code: 'PERM_NP_ECD_OPERATE', name: 'Nursery & ECD Assessment Permission', description: 'Assess early childhood milestones and Montessori portfolios.' },
    { id: 'NP-PERM-ACADEMICS', productId: 'prod-nursery-primary', code: 'PERM_NP_ACADEMICS_OPERATE', name: 'Primary Academics & Grading Permission', description: 'Enter subject marks, compile report cards, and submit mock series.' },
    { id: 'NP-PERM-HEADTEACHER', productId: 'prod-nursery-primary', code: 'PERM_NP_HEADTEACHER_EXECUTIVE', name: 'Headteacher Executive Governance Permission', description: 'Approve report cards, PLE submissions, and institutional settings.' },
    { id: 'NP-PERM-SIS', productId: 'prod-nursery-primary', code: 'PERM_NP_SIS_OPERATE', name: 'Pupil Enrollment & Attendance Permission', description: 'Manage student biographical profiles and take daily class roll-calls.' },
    { id: 'NP-PERM-BURSAR', productId: 'prod-nursery-primary', code: 'PERM_NP_BURSAR_FINANCE', name: 'School Fees & Bursary Cashbook Permission', description: 'Manage school fee collections, PayCodes, and financial journals.' },
    { id: 'NP-PERM-STORES', productId: 'prod-nursery-primary', code: 'PERM_NP_STORES_DISPATCH', name: 'Food Rations & Stores Dispatch Permission', description: 'Manage posho/beans food stock, inventory, and kitchen dispatches.' },
    { id: 'NP-PERM-HEALTH', productId: 'prod-nursery-primary', code: 'PERM_NP_SICKBAY_HEALTH', name: 'Sickbay Clinical Encounter Permission', description: 'Log sickbay clinical encounters, medications, and health registers.' },
    { id: 'NP-PERM-BOARDING', productId: 'prod-nursery-primary', code: 'PERM_NP_BOARDING_DORMS', name: 'Junior Dormitory Care Permission', description: 'Manage dorm allocations, bed numbers, and nightly roll-call.' },
    { id: 'NP-PERM-COMMUNICATIONS', productId: 'prod-nursery-primary', code: 'PERM_NP_PARENT_SMS', name: 'Parent SMS Dispatch Permission', description: 'Compose and dispatch SMS broadcasts to parent phone numbers.' }
  ],
  roles: [
    { id: 'NP-ROLE-HEADTEACHER', productId: 'prod-nursery-primary', code: 'ROLE_NP_HEADTEACHER', name: 'Headteacher / Principal Director', tier: 'GOVERNANCE', permissionIds: ['NP-PERM-HEADTEACHER', 'NP-PERM-ACADEMICS', 'NP-PERM-SIS', 'NP-PERM-BURSAR', 'NP-PERM-COMMUNICATIONS'] },
    { id: 'NP-ROLE-TEACHER', productId: 'prod-nursery-primary', code: 'ROLE_NP_TEACHER', name: 'Primary Class Teacher & Subject Specialist', tier: 'OPERATIONAL', permissionIds: ['NP-PERM-ACADEMICS', 'NP-PERM-SIS', 'NP-PERM-ECD'] },
    { id: 'NP-ROLE-BURSAR', productId: 'prod-nursery-primary', code: 'ROLE_NP_BURSAR', name: 'School Bursar & Cashier', tier: 'OPERATIONAL', permissionIds: ['NP-PERM-BURSAR', 'NP-PERM-STORES'] },
    { id: 'NP-ROLE-NURSE', productId: 'prod-nursery-primary', code: 'ROLE_NP_NURSE', name: 'Resident Clinical Sickbay Nurse', tier: 'OPERATIONAL', permissionIds: ['NP-PERM-HEALTH'] },
    { id: 'NP-ROLE-MATRON', productId: 'prod-nursery-primary', code: 'ROLE_NP_MATRON', name: 'Junior Boarding Hostel Matron / Warden', tier: 'OPERATIONAL', permissionIds: ['NP-PERM-BOARDING'] }
  ]
};
