import { CanonicalProductHierarchy } from './types';

export const SECONDARY_SCHOOL_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-secondary-school',
    code: 'SECERP',
    name: 'Secondary School Enterprise ERP',
    category: 'INSTITUTIONAL_ERP',
    description: 'Sovereign secondary and high school operating system: S1–S4 NCDC competence curriculum, S5–S6 O & A Level subject combination matrices, UNEB UCE/UACE national center registration, science laboratory apparatus inventory, e-library Dewey decimal catalog, secondary bursar cashbook, student boarding hostels, disciplinary tribunal, and direct integration with JUMO ALUMNI for graduating cohorts.',
    version: '2026.4.0',
    iconName: 'GraduationCap',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Principal / Headmaster of Secondary Institution',
    governingLegislation: 'National Curriculum Development Centre (NCDC) & UNEB Act 2026',
    directorateIds: [
      'SEC-DIR-ACADEMICS',
      'SEC-DIR-SCIENCE-LIBRARY',
      'SEC-DIR-FINANCE-PAYROLL',
      'SEC-DIR-BOARDING-DISCIPLINE',
      'SEC-DIR-ADVANCEMENT-ALUMNI'
    ]
  },
  directorates: [
    {
      id: 'SEC-DIR-ACADEMICS',
      productId: 'prod-secondary-school',
      code: 'SEC-DIR-ACADEMICS',
      name: 'Directorate of Secondary Academics & Curriculum Innovation',
      description: 'Lower Secondary (S1–S4) competence projects, Advanced Level (S5–S6) subject combinations, and UNEB national center examination administration.',
      leadRole: 'DEPUTY_HEAD_ACADEMICS',
      departmentIds: ['SEC-DEPT-LOWER-SECONDARY', 'SEC-DEPT-UPPER-SECONDARY', 'SEC-DEPT-UNEB-EXAMS']
    },
    {
      id: 'SEC-DIR-SCIENCE-LIBRARY',
      productId: 'prod-secondary-school',
      code: 'SEC-DIR-RESOURCES',
      name: 'Directorate of Science Laboratories & E-Library Resources',
      description: 'Physics, Chemistry, Biology laboratories, dangerous chemical reagents vault, digital e-library, and past examination papers archive.',
      leadRole: 'HEAD_SCIENTIFIC_RESOURCES',
      departmentIds: ['SEC-DEPT-SCIENCE-LABS', 'SEC-DEPT-LIBRARY-MEDIA', 'SEC-DEPT-ICT-INNOVATION']
    },
    {
      id: 'SEC-DIR-FINANCE-PAYROLL',
      productId: 'prod-secondary-school',
      code: 'SEC-DIR-FINANCE',
      name: 'Directorate of Bursary, School Fees & Staff Remuneration',
      description: 'Termly student fee invoices, SchoolPay bank reconciliation, teaching staff payroll, extra-lesson allowances, and fee clearance cards.',
      leadRole: 'FINANCIAL_CONTROLLER_BURSAR',
      departmentIds: ['SEC-DEPT-FEES-CASHBOOK', 'SEC-DEPT-STAFF-PAYROLL']
    },
    {
      id: 'SEC-DIR-BOARDING-DISCIPLINE',
      productId: 'prod-secondary-school',
      code: 'SEC-DIR-WELFARE',
      name: 'Directorate of Boarding Hostels, Prefects & Student Welfare',
      description: 'Senior boarding houses, housemaster roll-calls, exeat pass permits, prefect guild governance, and student disciplinary tribunal hearings.',
      leadRole: 'DEPUTY_HEAD_DISCIPLINE',
      departmentIds: ['SEC-DEPT-HOSTEL-HOUSES', 'SEC-DEPT-DISCIPLINE-GUILD']
    },
    {
      id: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      productId: 'prod-secondary-school',
      code: 'SEC-DIR-ALUMNI',
      name: 'Directorate of Institutional Advancement & Alumni Relations',
      description: 'Senior six graduate exit census, transition to JUMO ALUMNI platform, alumni mentorship matching, and endowment fund contributions.',
      leadRole: 'DIRECTOR_ALUMNI_ADVANCEMENT',
      departmentIds: ['SEC-DEPT-ALUMNI-TRANSITION']
    }
  ],
  departments: [
    {
      id: 'SEC-DEPT-LOWER-SECONDARY',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      code: 'SEC-DEPT-NCDC-S1-S4',
      name: 'Department of Lower Secondary NCDC Curriculum (S1–S4)',
      description: 'Competence assessment projects (20%), continuous assessment descriptors, formative evaluation, and learner activities of integration.',
      headRole: 'DOS_LOWER_SECONDARY',
      officeIds: ['SEC-OFF-DOS-LOWER']
    },
    {
      id: 'SEC-DEPT-UPPER-SECONDARY',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      code: 'SEC-DEPT-A-LEVEL-S5-S6',
      name: 'Department of Advanced Level Combinations & Academics (S5–S6)',
      description: 'A-Level combination vetting (PCM, PCB, BCM, PEM, HEG, MEK), subsidiary ICT/Maths, principal GPA scoring, and mock exams.',
      headRole: 'DOS_UPPER_SECONDARY',
      officeIds: ['SEC-OFF-DOS-UPPER']
    },
    {
      id: 'SEC-DEPT-UNEB-EXAMS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      code: 'SEC-DEPT-UNEB-CENTER',
      name: 'Department of National Examination Center & UNEB Registration',
      description: 'UCE & UACE national candidate registration, index assignment, e-registration data validation, and UNEB center invigilation.',
      headRole: 'CHIEF_EXAMINATION_SECRETARY',
      officeIds: ['SEC-OFF-UNEB-CENTER']
    },
    {
      id: 'SEC-DEPT-SCIENCE-LABS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      code: 'SEC-DEPT-LABS',
      name: 'Department of Physics, Chemistry & Biology Science Laboratories',
      description: 'Dangerous chemical reagent vault, glass apparatus inventory, specimen preservation, and practical exam bench bookings.',
      headRole: 'CHIEF_SCIENCE_TECHNOLOGIST',
      officeIds: ['SEC-OFF-LAB-TECHNOLOGIST']
    },
    {
      id: 'SEC-DEPT-LIBRARY-MEDIA',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      code: 'SEC-DEPT-LIBRARY',
      name: 'Department of School E-Library & Past Papers Repository',
      description: 'Dewey decimal physical book catalog, student RFID loans, digital past exam papers archive, and reading cubicles.',
      headRole: 'CHIEF_LIBRARIAN',
      officeIds: ['SEC-OFF-LIBRARIAN']
    },
    {
      id: 'SEC-DEPT-ICT-INNOVATION',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      code: 'SEC-DEPT-ICT',
      name: 'Department of Computer Labs & Digital Skills',
      description: 'Computer laboratory terminals, robotics innovation club, network accounts, and digital coding projects.',
      headRole: 'ICT_LAB_SUPERVISOR',
      officeIds: ['SEC-OFF-ICT-LAB']
    },
    {
      id: 'SEC-DEPT-FEES-CASHBOOK',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      code: 'SEC-DEPT-FEES',
      name: 'Department of Secondary Fees Billing & SchoolPay Reconciliations',
      description: 'Termly student fee invoicing, boarding surcharges, SchoolPay/Pegasus bank slip postings, and exam clearance permits.',
      headRole: 'SENIOR_BURSAR',
      officeIds: ['SEC-OFF-BURSAR-COUNTER']
    },
    {
      id: 'SEC-DEPT-STAFF-PAYROLL',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      code: 'SEC-DEPT-PAYROLL',
      name: 'Department of Teaching Staff Payroll & Extra-Lesson Allowances',
      description: 'Monthly salary disbursements, PTA science teacher allowances, remedial evening lesson tokens, and statutory NSSF/PAYE deductions.',
      headRole: 'PAYROLL_OFFICER',
      officeIds: ['SEC-OFF-PAYROLL-DESK']
    },
    {
      id: 'SEC-DEPT-HOSTEL-HOUSES',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      code: 'SEC-DEPT-HOSTELS',
      name: 'Department of Boarding Houses & Residential Life',
      description: 'Senior boarding houses, housemaster allocations, inter-house sports competitions, and weekend exeat gate passes.',
      headRole: 'CHIEF_HOUSEMASTER',
      officeIds: ['SEC-OFF-SENIOR-HOUSEMASTER']
    },
    {
      id: 'SEC-DEPT-DISCIPLINE-GUILD',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      code: 'SEC-DEPT-GUILD',
      name: 'Department of Prefect Guild Governance & Disciplinary Tribunal',
      description: 'Student guild cabinet elections, disciplinary offense logs, tribunal hearings, behavioral contracts, and suspensions.',
      headRole: 'DISCIPLINARY_MASTER',
      officeIds: ['SEC-OFF-DISCIPLINE-MASTER']
    },
    {
      id: 'SEC-DEPT-ALUMNI-TRANSITION',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      code: 'SEC-DEPT-ALUMNI',
      name: 'Department of Graduate Transition & Old Boys/Girls Association',
      description: 'Graduating S6 class transition bridge to JUMO ALUMNI platform, alumni career mentorship, and endowment fundraisers.',
      headRole: 'ADVANCEMENT_OFFICER',
      officeIds: ['SEC-OFF-ALUMNI-LIAISON']
    }
  ],
  offices: [
    {
      id: 'SEC-OFF-DOS-LOWER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      code: 'SEC-OFF-DOS-LOWER',
      name: 'Director of Studies (DOS) Lower Secondary Office',
      description: 'Lower secondary learner project ratings and NCDC continuous assessment logs.',
      officerRole: 'DOS_LOWER_SEC',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-DOS-ACADEMICS'],
      moduleIds: ['SEC-MOD-LOWER-NCDC', 'SEC-MOD-STUDENT-SIS']
    },
    {
      id: 'SEC-OFF-DOS-UPPER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UPPER-SECONDARY',
      code: 'SEC-OFF-DOS-UPPER',
      name: 'Director of Studies (DOS) A-Level Office',
      description: 'A-Level combination approvals, principal subject grading, and transcript issuance.',
      officerRole: 'DOS_A_LEVEL',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-DOS-ACADEMICS'],
      moduleIds: ['SEC-MOD-UPPER-COMBOS', 'SEC-MOD-STUDENT-SIS']
    },
    {
      id: 'SEC-OFF-UNEB-CENTER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UNEB-EXAMS',
      code: 'SEC-OFF-UNEB',
      name: 'UNEB Examination Center Supervisor Office',
      description: 'UCE and UACE candidate registration index generation and UNEB mock examination results.',
      officerRole: 'UNEB_CENTER_OFFICER',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-DOS-ACADEMICS'],
      moduleIds: ['SEC-MOD-UNEB-EXAMS']
    },
    {
      id: 'SEC-OFF-LAB-TECHNOLOGIST',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-SCIENCE-LABS',
      code: 'SEC-OFF-LABS',
      name: 'Chief Science Laboratory Technologist Office',
      description: 'Chemical reagent vault logbooks, apparatus custody, and practical exam workstations.',
      officerRole: 'SENIOR_LAB_TECHNICIAN',
      portalIds: ['SEC-PORTAL-TEACHER'],
      moduleIds: ['SEC-MOD-SCIENCE-LABS']
    },
    {
      id: 'SEC-OFF-LIBRARIAN',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-LIBRARY-MEDIA',
      code: 'SEC-OFF-LIBRARY',
      name: 'Chief Librarian Desk',
      description: 'Textbook lending, digital library archive, and past paper catalog.',
      officerRole: 'LIBRARIAN',
      portalIds: ['SEC-PORTAL-TEACHER', 'SEC-PORTAL-STUDENT-PARENT'],
      moduleIds: ['SEC-MOD-LIBRARY-SYSTEM']
    },
    {
      id: 'SEC-OFF-ICT-LAB',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-ICT-INNOVATION',
      code: 'SEC-OFF-ICT',
      name: 'Computer Laboratory Supervisor Desk',
      description: 'ICT practical stations, student login credentials, and coding lab sessions.',
      officerRole: 'ICT_COORDINATOR',
      portalIds: ['SEC-PORTAL-TEACHER'],
      moduleIds: ['SEC-MOD-LIBRARY-SYSTEM']
    },
    {
      id: 'SEC-OFF-BURSAR-COUNTER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-FEES-CASHBOOK',
      code: 'SEC-OFF-BURSAR',
      name: 'Senior Bursar Cashier Counter',
      description: 'Fee collection posting, SchoolPay bank integration, and exam clearance permits.',
      officerRole: 'SENIOR_BURSAR',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-BURSAR'],
      moduleIds: ['SEC-MOD-FEES-BURSARY']
    },
    {
      id: 'SEC-OFF-PAYROLL-DESK',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-STAFF-PAYROLL',
      code: 'SEC-OFF-PAYROLL',
      name: 'Staff Payroll & Remuneration Desk',
      description: 'Monthly teacher salary computation, extra-lesson tokens, and PAYE tax schedules.',
      officerRole: 'PAYROLL_ACCOUNTANT',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-BURSAR'],
      moduleIds: ['SEC-MOD-TEACHER-PAYROLL']
    },
    {
      id: 'SEC-OFF-SENIOR-HOUSEMASTER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-HOSTEL-HOUSES',
      code: 'SEC-OFF-HOSTELS',
      name: 'Senior Housemaster Command Desk',
      description: 'Hostel dormitory allocations, exeat leave slips, and evening roll-calls.',
      officerRole: 'SENIOR_HOUSEMASTER',
      portalIds: ['SEC-PORTAL-TEACHER'],
      moduleIds: ['SEC-MOD-BOARDING-HOUSES']
    },
    {
      id: 'SEC-OFF-DISCIPLINE-MASTER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-DISCIPLINE-GUILD',
      code: 'SEC-OFF-DISCIPLINE',
      name: 'Disciplinary Tribunal & Prefect Desk',
      description: 'Prefect guild monitoring, student offense hearings, and behavioral records.',
      officerRole: 'DISCIPLINARY_MASTER',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-TEACHER'],
      moduleIds: ['SEC-MOD-DISCIPLINE-GUILD']
    },
    {
      id: 'SEC-OFF-ALUMNI-LIAISON',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      departmentId: 'SEC-DEPT-ALUMNI-TRANSITION',
      code: 'SEC-OFF-ALUMNI',
      name: 'Alumni Association & Career Guidance Desk',
      description: 'S6 graduate census, career mentorship matching, and JUMO ALUMNI integration bridge.',
      officerRole: 'ALUMNI_LIAISON_LEAD',
      portalIds: ['SEC-PORTAL-PRINCIPAL', 'SEC-PORTAL-STUDENT-PARENT'],
      moduleIds: ['SEC-MOD-ALUMNI-INTEGRATION']
    }
  ],
  portals: [
    {
      id: 'SEC-PORTAL-PRINCIPAL',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UNEB-EXAMS',
      officeId: 'SEC-OFF-UNEB-CENTER',
      code: 'SEC-PORTAL-PRINCIPAL',
      name: 'Principal & Board of Governors Sovereign Portal',
      description: 'Institutional metrics: UNEB pass projections, tuition collection cashbook, staff payroll, and hostel capacity.',
      targetRole: 'PRINCIPAL',
      authLevel: 'PKI_SOVEREIGN',
      route: '/secondary/principal',
      moduleIds: ['SEC-MOD-STUDENT-SIS', 'SEC-MOD-UNEB-EXAMS', 'SEC-MOD-FEES-BURSARY', 'SEC-MOD-TEACHER-PAYROLL', 'SEC-MOD-ALUMNI-INTEGRATION']
    },
    {
      id: 'SEC-PORTAL-DOS-ACADEMICS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UPPER-SECONDARY',
      officeId: 'SEC-OFF-DOS-UPPER',
      code: 'SEC-PORTAL-DOS',
      name: 'Director of Studies (DOS) Examination & Combinations Portal',
      description: 'S1–S4 NCDC competence marks, S5–S6 combinations, master timetable scheduler, and UNEB candidate registrations.',
      targetRole: 'DOS',
      authLevel: 'STAFF',
      route: '/secondary/academics',
      moduleIds: ['SEC-MOD-LOWER-NCDC', 'SEC-MOD-UPPER-COMBOS', 'SEC-MOD-UNEB-EXAMS', 'SEC-MOD-STUDENT-SIS']
    },
    {
      id: 'SEC-PORTAL-TEACHER',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-SCIENCE-LABS',
      officeId: 'SEC-OFF-LAB-TECHNOLOGIST',
      code: 'SEC-PORTAL-TEACHER',
      name: 'Secondary Subject Teacher & Form Tutor Workspace',
      description: 'Enter class marks, submit practical laboratory requisitions, issue student library cards, and record exeat passes.',
      targetRole: 'SECONDARY_TEACHER',
      authLevel: 'STAFF',
      route: '/secondary/teacher',
      moduleIds: ['SEC-MOD-LOWER-NCDC', 'SEC-MOD-UPPER-COMBOS', 'SEC-MOD-SCIENCE-LABS', 'SEC-MOD-LIBRARY-SYSTEM', 'SEC-MOD-BOARDING-HOUSES', 'SEC-MOD-DISCIPLINE-GUILD']
    },
    {
      id: 'SEC-PORTAL-BURSAR',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-FEES-CASHBOOK',
      officeId: 'SEC-OFF-BURSAR-COUNTER',
      code: 'SEC-PORTAL-BURSAR',
      name: 'Senior Bursar & Cashbook Terminal',
      description: 'Termly fee billing, SchoolPay bank statement reconciliation, teacher payroll vouchers, and fee clearance receipts.',
      targetRole: 'SECONDARY_BURSAR',
      authLevel: 'STAFF',
      route: '/secondary/bursar',
      moduleIds: ['SEC-MOD-FEES-BURSARY', 'SEC-MOD-TEACHER-PAYROLL']
    },
    {
      id: 'SEC-PORTAL-STUDENT-PARENT',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      departmentId: 'SEC-DEPT-ALUMNI-TRANSITION',
      officeId: 'SEC-OFF-ALUMNI-LIAISON',
      code: 'SEC-PORTAL-STUDENT',
      name: 'Student & Parent Academic Tracking Portal',
      description: 'Check termly report cards, download e-library past papers, check fee balance, and connect to JUMO ALUMNI network.',
      targetRole: 'STUDENT_PARENT',
      authLevel: 'PUBLIC',
      route: '/secondary/portal',
      moduleIds: ['SEC-MOD-LOWER-NCDC', 'SEC-MOD-UPPER-COMBOS', 'SEC-MOD-LIBRARY-SYSTEM', 'SEC-MOD-FEES-BURSARY', 'SEC-MOD-ALUMNI-INTEGRATION']
    }
  ],
  modules: [
    {
      id: 'SEC-MOD-LOWER-NCDC',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      officeId: 'SEC-OFF-DOS-LOWER',
      portalId: 'SEC-PORTAL-DOS-ACADEMICS',
      code: 'SEC-MOD-LOWER-NCDC',
      name: 'Lower Secondary Competence-Based Assessment Engine',
      description: 'NCDC S1–S4 curriculum: 20% continuous project assessment, competence scores, activities of integration, and descriptors.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-NCDC-001', 'SEC-CAP-NCDC-002'],
      screenIds: ['SEC-SCR-NCDC'],
      formIds: ['SEC-FORM-NCDC-PROJECT'],
      dashboardIds: ['SEC-DASH-ACADEMICS'],
      reportIds: ['SEC-REP-NCDC'],
      workflowIds: ['SEC-WF-NCDC'],
      databaseEntityIds: ['SEC-DB-NCDC-PROJECTS'],
      apiIds: ['SEC-API-NCDC'],
      runtimeComponentId: 'SEC-RTC-NCDC',
      permissionIds: ['SEC-PERM-ACADEMICS']
    },
    {
      id: 'SEC-MOD-UPPER-COMBOS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UPPER-SECONDARY',
      officeId: 'SEC-OFF-DOS-UPPER',
      portalId: 'SEC-PORTAL-DOS-ACADEMICS',
      code: 'SEC-MOD-UPPER-COMBOS',
      name: 'A-Level Subject Combinations & GPA Points Calculator',
      description: 'S5–S6 subject combination vetting (Sciences/Arts), principal subject grading (A=6 pts to F=0), subsidiary scores, and transcripts.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-COMBO-001', 'SEC-CAP-COMBO-002'],
      screenIds: ['SEC-SCR-COMBOS'],
      formIds: ['SEC-FORM-COMBO-SELECT'],
      dashboardIds: ['SEC-DASH-ACADEMICS'],
      reportIds: ['SEC-REP-ALEVEL'],
      workflowIds: ['SEC-WF-COMBOS'],
      databaseEntityIds: ['SEC-DB-ALEVEL-COMBOS'],
      apiIds: ['SEC-API-COMBOS'],
      runtimeComponentId: 'SEC-RTC-COMBOS',
      permissionIds: ['SEC-PERM-ACADEMICS']
    },
    {
      id: 'SEC-MOD-UNEB-EXAMS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UNEB-EXAMS',
      officeId: 'SEC-OFF-UNEB-CENTER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      code: 'SEC-MOD-UNEB-EXAMS',
      name: 'UNEB UCE/UACE National Examination Center',
      description: 'UNEB center management, candidate e-registration, national index allocation, and Mock examination series compilation.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-UNEB-001', 'SEC-CAP-UNEB-002'],
      screenIds: ['SEC-SCR-UNEB'],
      formIds: ['SEC-FORM-UNEB-REG'],
      dashboardIds: ['SEC-DASH-ACADEMICS'],
      reportIds: ['SEC-REP-UNEB'],
      workflowIds: ['SEC-WF-UNEB'],
      databaseEntityIds: ['SEC-DB-UNEB-CANDIDATES'],
      apiIds: ['SEC-API-UNEB'],
      runtimeComponentId: 'SEC-RTC-UNEB',
      permissionIds: ['SEC-PERM-PRINCIPAL']
    },
    {
      id: 'SEC-MOD-STUDENT-SIS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      officeId: 'SEC-OFF-DOS-LOWER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      code: 'SEC-MOD-STUDENT-SIS',
      name: 'Secondary Student Information System & Class Registers',
      description: 'Secondary student biographical registry, admission numbers, class stream allocation (S1A to S6Sci), and daily attendance.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-SIS-001', 'SEC-CAP-SIS-002'],
      screenIds: ['SEC-SCR-SIS'],
      formIds: ['SEC-FORM-STUDENT-ENROLL'],
      dashboardIds: ['SEC-DASH-ENROLLMENT'],
      reportIds: ['SEC-REP-SIS'],
      workflowIds: ['SEC-WF-ADMISSIONS'],
      databaseEntityIds: ['SEC-DB-STUDENTS'],
      apiIds: ['SEC-API-STUDENTS'],
      runtimeComponentId: 'SEC-RTC-SIS',
      permissionIds: ['SEC-PERM-SIS']
    },
    {
      id: 'SEC-MOD-SCIENCE-LABS',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-SCIENCE-LABS',
      officeId: 'SEC-OFF-LAB-TECHNOLOGIST',
      portalId: 'SEC-PORTAL-TEACHER',
      code: 'SEC-MOD-SCIENCE-LABS',
      name: 'Physics, Chemistry & Biology Laboratory Vault',
      description: 'Chemical reagents inventory, hazardous storage protocols, physics apparatus tracking, and UNEB practical bench allocations.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-LAB-001', 'SEC-CAP-LAB-002'],
      screenIds: ['SEC-SCR-LABS'],
      formIds: ['SEC-FORM-LAB-REQUISITION'],
      dashboardIds: ['SEC-DASH-RESOURCES'],
      reportIds: ['SEC-REP-LABS'],
      workflowIds: ['SEC-WF-LABS'],
      databaseEntityIds: ['SEC-DB-LAB-INVENTORY'],
      apiIds: ['SEC-API-LABS'],
      runtimeComponentId: 'SEC-RTC-LABS',
      permissionIds: ['SEC-PERM-LABS']
    },
    {
      id: 'SEC-MOD-LIBRARY-SYSTEM',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-LIBRARY-MEDIA',
      officeId: 'SEC-OFF-LIBRARIAN',
      portalId: 'SEC-PORTAL-TEACHER',
      code: 'SEC-MOD-LIBRARY-SYSTEM',
      name: 'Digital E-Library & Past Examination Paper Repository',
      description: 'Dewey decimal catalog, RFID book loans, return overdue penalties, and digital past papers PDF repository.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-LIB-001', 'SEC-CAP-LIB-002'],
      screenIds: ['SEC-SCR-LIBRARY'],
      formIds: ['SEC-FORM-BOOK-LOAN'],
      dashboardIds: ['SEC-DASH-RESOURCES'],
      reportIds: ['SEC-REP-LIBRARY'],
      workflowIds: ['SEC-WF-LIBRARY'],
      databaseEntityIds: ['SEC-DB-BOOKS'],
      apiIds: ['SEC-API-LIBRARY'],
      runtimeComponentId: 'SEC-RTC-LIBRARY',
      permissionIds: ['SEC-PERM-LIBRARY']
    },
    {
      id: 'SEC-MOD-FEES-BURSARY',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-FEES-CASHBOOK',
      officeId: 'SEC-OFF-BURSAR-COUNTER',
      portalId: 'SEC-PORTAL-BURSAR',
      code: 'SEC-MOD-FEES-BURSARY',
      name: 'Secondary Fees Billing, PayCodes & Clearance Cards',
      description: 'Tuition and boarding fee structure, SchoolPay bank code generation, cashbook posting, and digital examination clearance cards.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-FEE-001', 'SEC-CAP-FEE-002'],
      screenIds: ['SEC-SCR-FEES'],
      formIds: ['SEC-FORM-FEE-RECEIPT'],
      dashboardIds: ['SEC-DASH-FINANCE'],
      reportIds: ['SEC-REP-FEES'],
      workflowIds: ['SEC-WF-FEES'],
      databaseEntityIds: ['SEC-DB-FEES-CASHBOOK'],
      apiIds: ['SEC-API-FEES'],
      runtimeComponentId: 'SEC-RTC-FEES',
      permissionIds: ['SEC-PERM-BURSAR']
    },
    {
      id: 'SEC-MOD-TEACHER-PAYROLL',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-STAFF-PAYROLL',
      officeId: 'SEC-OFF-PAYROLL-DESK',
      portalId: 'SEC-PORTAL-BURSAR',
      code: 'SEC-MOD-TEACHER-PAYROLL',
      name: 'Teaching Staff Payroll & Extra-Lesson Allowances',
      description: 'Monthly faculty salary processing, science allowance additions, remedial lesson stipends, and statutory tax deductions.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-PAY-001', 'SEC-CAP-PAY-002'],
      screenIds: ['SEC-SCR-PAYROLL'],
      formIds: ['SEC-FORM-PAYROLL-VOUCHER'],
      dashboardIds: ['SEC-DASH-FINANCE'],
      reportIds: ['SEC-REP-PAYROLL'],
      workflowIds: ['SEC-WF-PAYROLL'],
      databaseEntityIds: ['SEC-DB-STAFF-PAYROLL'],
      apiIds: ['SEC-API-PAYROLL'],
      runtimeComponentId: 'SEC-RTC-PAYROLL',
      permissionIds: ['SEC-PERM-BURSAR']
    },
    {
      id: 'SEC-MOD-BOARDING-HOUSES',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-HOSTEL-HOUSES',
      officeId: 'SEC-OFF-SENIOR-HOUSEMASTER',
      portalId: 'SEC-PORTAL-TEACHER',
      code: 'SEC-MOD-BOARDING-HOUSES',
      name: 'Boarding Hostels, House Points & Exeat Leave Engine',
      description: 'Senior hostel bed space allocations, evening housemaster roll-call, weekend exeat gate passes, and inter-house competitions.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-HOUSE-001', 'SEC-CAP-HOUSE-002'],
      screenIds: ['SEC-SCR-BOARDING'],
      formIds: ['SEC-FORM-EXEAT-PASS'],
      dashboardIds: ['SEC-DASH-WELFARE'],
      reportIds: ['SEC-REP-BOARDING'],
      workflowIds: ['SEC-WF-BOARDING'],
      databaseEntityIds: ['SEC-DB-HOSTELS'],
      apiIds: ['SEC-API-BOARDING'],
      runtimeComponentId: 'SEC-RTC-BOARDING',
      permissionIds: ['SEC-PERM-HOSTELS']
    },
    {
      id: 'SEC-MOD-DISCIPLINE-GUILD',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-DISCIPLINE-GUILD',
      officeId: 'SEC-OFF-DISCIPLINE-MASTER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      code: 'SEC-MOD-DISCIPLINE-GUILD',
      name: 'Disciplinary Tribunal & Prefect Guild Governance',
      description: 'Prefect cabinet appointments, disciplinary offense docket, tribunal summons, suspension orders, and character ratings.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-DISC-001', 'SEC-CAP-DISC-002'],
      screenIds: ['SEC-SCR-DISCIPLINE'],
      formIds: ['SEC-FORM-DISCIPLINE-CASE'],
      dashboardIds: ['SEC-DASH-WELFARE'],
      reportIds: ['SEC-REP-DISCIPLINE'],
      workflowIds: ['SEC-WF-DISCIPLINE'],
      databaseEntityIds: ['SEC-DB-DISCIPLINE-CASES'],
      apiIds: ['SEC-API-DISCIPLINE'],
      runtimeComponentId: 'SEC-RTC-DISCIPLINE',
      permissionIds: ['SEC-PERM-DISCIPLINE']
    },
    {
      id: 'SEC-MOD-ALUMNI-INTEGRATION',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      departmentId: 'SEC-DEPT-ALUMNI-TRANSITION',
      officeId: 'SEC-OFF-ALUMNI-LIAISON',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      code: 'SEC-MOD-ALUMNI-INTEGRATION',
      name: 'Alumni Network Bridge & Endowment Campaign Tracker',
      description: 'Direct integration contract with JUMO ALUMNI platform: seamless graduation cohort export, alumni mentorship linkage, and capital endowment tracking.',
      status: 'ACTIVE_CORE',
      capabilityIds: ['SEC-CAP-ALUM-001', 'SEC-CAP-ALUM-002'],
      screenIds: ['SEC-SCR-ALUMNI'],
      formIds: ['SEC-FORM-ALUMNI-EXPORT'],
      dashboardIds: ['SEC-DASH-ENROLLMENT'],
      reportIds: ['SEC-REP-ALUMNI'],
      workflowIds: ['SEC-WF-ALUMNI'],
      databaseEntityIds: ['SEC-DB-ALUMNI-BRIDGE'],
      apiIds: ['SEC-API-ALUMNI'],
      runtimeComponentId: 'SEC-RTC-ALUMNI',
      permissionIds: ['SEC-PERM-PRINCIPAL']
    }
  ],
  capabilities: [
    {
      id: 'SEC-CAP-NCDC-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      officeId: 'SEC-OFF-DOS-LOWER',
      portalId: 'SEC-PORTAL-DOS-ACADEMICS',
      moduleId: 'SEC-MOD-LOWER-NCDC',
      code: 'SEC_CAP_NCDC_SCORE_PROJECT',
      name: 'Score Lower Secondary NCDC Learner Competence Project',
      description: 'Enters scores (out of 20%) for activities of integration and hands-on competence projects under the NCDC revised curriculum.',
      serviceAction: 'secondary.ncdc.scoreProject',
      requiredPermission: 'SEC-PERM-ACADEMICS',
      runtimeComponentId: 'SEC-RTC-NCDC',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-NCDC-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      officeId: 'SEC-OFF-DOS-LOWER',
      portalId: 'SEC-PORTAL-DOS-ACADEMICS',
      moduleId: 'SEC-MOD-LOWER-NCDC',
      code: 'SEC_CAP_NCDC_GENERATE_ASSESSMENT',
      name: 'Generate S1–S4 NCDC Continuous Competence Transcript',
      description: 'Compiles formative descriptor ratings and exports verified continuous assessment scores for UNEB transmission.',
      serviceAction: 'secondary.ncdc.generateAssessment',
      requiredPermission: 'SEC-PERM-ACADEMICS',
      runtimeComponentId: 'SEC-RTC-NCDC',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-COMBO-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UPPER-SECONDARY',
      officeId: 'SEC-OFF-DOS-UPPER',
      portalId: 'SEC-PORTAL-DOS-ACADEMICS',
      moduleId: 'SEC-MOD-UPPER-COMBOS',
      code: 'SEC_CAP_COMBO_VALIDATE_CHOICE',
      name: 'Validate S5 Subject Combination Eligibility',
      description: 'Checks UCE pass grades against combinations (e.g. PCM requires Distinction in Physics/Maths) and assigns official combo code.',
      serviceAction: 'secondary.combos.validateChoice',
      requiredPermission: 'SEC-PERM-ACADEMICS',
      runtimeComponentId: 'SEC-RTC-COMBOS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-COMBO-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UPPER-SECONDARY',
      officeId: 'SEC-OFF-DOS-UPPER',
      portalId: 'SEC-PORTAL-DOS-ACADEMICS',
      moduleId: 'SEC-MOD-UPPER-COMBOS',
      code: 'SEC_CAP_COMBO_CALCULATE_POINTS',
      name: 'Calculate A-Level Principal Points & Class Division',
      description: 'Calculates principal grade points (A=6, B=5, C=4, D=3, E=2, O=1, F=0) + Subsidiaries to yield maximum 20-point score.',
      serviceAction: 'secondary.combos.calculatePoints',
      requiredPermission: 'SEC-PERM-ACADEMICS',
      runtimeComponentId: 'SEC-RTC-COMBOS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-UNEB-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UNEB-EXAMS',
      officeId: 'SEC-OFF-UNEB-CENTER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-UNEB-EXAMS',
      code: 'SEC_CAP_UNEB_REGISTER_CENTER_CANDIDATE',
      name: 'Register UNEB UCE/UACE Center Candidate',
      description: 'Enters candidate biographical data, passport photo, LIN, subject papers, and validates against official UNEB e-registration portal.',
      serviceAction: 'secondary.uneb.registerCandidate',
      requiredPermission: 'SEC-PERM-PRINCIPAL',
      runtimeComponentId: 'SEC-RTC-UNEB',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-UNEB-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-UNEB-EXAMS',
      officeId: 'SEC-OFF-UNEB-CENTER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-UNEB-EXAMS',
      code: 'SEC_CAP_UNEB_PROCESS_MOCK_RESULTS',
      name: 'Compile Regional Mock Examination League Table',
      description: 'Aggregates school mock examination results across science and arts departments to pinpoint low-scoring papers for revision.',
      serviceAction: 'secondary.uneb.processMockResults',
      requiredPermission: 'SEC-PERM-PRINCIPAL',
      runtimeComponentId: 'SEC-RTC-UNEB',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-SIS-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      officeId: 'SEC-OFF-DOS-LOWER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-STUDENT-SIS',
      code: 'SEC_CAP_SIS_ADMIT_STUDENT',
      name: 'Admit Secondary Student & Assign House/Stream',
      description: 'Generates student admission number, allocates class stream, boarding house, and issues student identity card barcode.',
      serviceAction: 'secondary.sis.admitStudent',
      requiredPermission: 'SEC-PERM-SIS',
      runtimeComponentId: 'SEC-RTC-SIS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-SIS-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ACADEMICS',
      departmentId: 'SEC-DEPT-LOWER-SECONDARY',
      officeId: 'SEC-OFF-DOS-LOWER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-STUDENT-SIS',
      code: 'SEC_CAP_SIS_TAKE_DAILY_ROLLCALL',
      name: 'Take Form Tutor Period Attendance',
      description: 'Records classroom presence and notifies housemasters and parents of unexcused absences via automated notification rail.',
      serviceAction: 'secondary.sis.takeAttendance',
      requiredPermission: 'SEC-PERM-SIS',
      runtimeComponentId: 'SEC-RTC-SIS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-LAB-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-SCIENCE-LABS',
      officeId: 'SEC-OFF-LAB-TECHNOLOGIST',
      portalId: 'SEC-PORTAL-TEACHER',
      moduleId: 'SEC-MOD-SCIENCE-LABS',
      code: 'SEC_CAP_LAB_BOOK_PRACTICAL_SESSION',
      name: 'Book Science Practical Workstation & Reagents',
      description: 'Schedules biology dissection, chemistry titration, or physics mechanics apparatus for specific class streams.',
      serviceAction: 'secondary.labs.bookPracticalSession',
      requiredPermission: 'SEC-PERM-LABS',
      runtimeComponentId: 'SEC-RTC-LABS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-LAB-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-SCIENCE-LABS',
      officeId: 'SEC-OFF-LAB-TECHNOLOGIST',
      portalId: 'SEC-PORTAL-TEACHER',
      moduleId: 'SEC-MOD-SCIENCE-LABS',
      code: 'SEC_CAP_LAB_AUDIT_HAZARD_REAGENTS',
      name: 'Audit Laboratory Hazardous Chemicals Vault',
      description: 'Audits concentrated acids, flammable reagents, and biological specimens to ensure national laboratory safety compliance.',
      serviceAction: 'secondary.labs.auditHazardReagents',
      requiredPermission: 'SEC-PERM-LABS',
      runtimeComponentId: 'SEC-RTC-LABS',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-LIB-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-LIBRARY-MEDIA',
      officeId: 'SEC-OFF-LIBRARIAN',
      portalId: 'SEC-PORTAL-TEACHER',
      moduleId: 'SEC-MOD-LIBRARY-SYSTEM',
      code: 'SEC_CAP_LIB_ISSUE_BOOK_LOAN',
      name: 'Issue Library Book Loan & Scan RFID',
      description: 'Scans student ID barcode and book RFID tag to log a 14-day borrowing loan with automated overdue SMS warnings.',
      serviceAction: 'secondary.library.issueBookLoan',
      requiredPermission: 'SEC-PERM-LIBRARY',
      runtimeComponentId: 'SEC-RTC-LIBRARY',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-LIB-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-SCIENCE-LIBRARY',
      departmentId: 'SEC-DEPT-LIBRARY-MEDIA',
      officeId: 'SEC-OFF-LIBRARIAN',
      portalId: 'SEC-PORTAL-TEACHER',
      moduleId: 'SEC-MOD-LIBRARY-SYSTEM',
      code: 'SEC_CAP_LIB_INDEX_PAST_PAPERS',
      name: 'Upload & Index UNEB Past Examination Papers',
      description: 'Indexes past examination questions by subject, year, and topic in the student digital learning portal.',
      serviceAction: 'secondary.library.indexPastPapers',
      requiredPermission: 'SEC-PERM-LIBRARY',
      runtimeComponentId: 'SEC-RTC-LIBRARY',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-FEE-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-FEES-CASHBOOK',
      officeId: 'SEC-OFF-BURSAR-COUNTER',
      portalId: 'SEC-PORTAL-BURSAR',
      moduleId: 'SEC-MOD-FEES-BURSARY',
      code: 'SEC_CAP_FEE_POST_BANK_PAYMENT',
      name: 'Post SchoolPay / Bank Fee Payment',
      description: 'Matches bank transaction reference against student account, updates bursary cashbook, and generates clearance token.',
      serviceAction: 'secondary.finance.postPayment',
      requiredPermission: 'SEC-PERM-BURSAR',
      runtimeComponentId: 'SEC-RTC-FEES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-FEE-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-FEES-CASHBOOK',
      officeId: 'SEC-OFF-BURSAR-COUNTER',
      portalId: 'SEC-PORTAL-BURSAR',
      moduleId: 'SEC-MOD-FEES-BURSARY',
      code: 'SEC_CAP_FEE_ISSUE_EXAM_PERMIT',
      name: 'Generate Exam Clearance Permit Card',
      description: 'Verifies 100% fee payment and prints official encrypted barcode examination clearance permit for UNEB and terminal exams.',
      serviceAction: 'secondary.finance.issueExamPermit',
      requiredPermission: 'SEC-PERM-BURSAR',
      runtimeComponentId: 'SEC-RTC-FEES',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-PAY-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-STAFF-PAYROLL',
      officeId: 'SEC-OFF-PAYROLL-DESK',
      portalId: 'SEC-PORTAL-BURSAR',
      moduleId: 'SEC-MOD-TEACHER-PAYROLL',
      code: 'SEC_CAP_PAY_RUN_MONTHLY_PAYROLL',
      name: 'Execute Monthly Faculty Salary Payroll Run',
      description: 'Computes basic salary, science teacher allowances, housing stipends, NSSF 10%, and PAYE withholding schedules.',
      serviceAction: 'secondary.payroll.runMonthlyPayroll',
      requiredPermission: 'SEC-PERM-BURSAR',
      runtimeComponentId: 'SEC-RTC-PAYROLL',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-PAY-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-FINANCE-PAYROLL',
      departmentId: 'SEC-DEPT-STAFF-PAYROLL',
      officeId: 'SEC-OFF-PAYROLL-DESK',
      portalId: 'SEC-PORTAL-BURSAR',
      moduleId: 'SEC-MOD-TEACHER-PAYROLL',
      code: 'SEC_CAP_PAY_DISBURSE_LESSON_ALLOWANCE',
      name: 'Disburse Weekend Remedial Lesson Tokens',
      description: 'Calculates verified extra-teaching sessions and disburses instant Mobile Money lesson allowance via JUMO DIGITAL PAY.',
      serviceAction: 'secondary.payroll.disburseLessonAllowance',
      requiredPermission: 'SEC-PERM-BURSAR',
      runtimeComponentId: 'SEC-RTC-PAYROLL',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-HOUSE-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-HOSTEL-HOUSES',
      officeId: 'SEC-OFF-SENIOR-HOUSEMASTER',
      portalId: 'SEC-PORTAL-TEACHER',
      moduleId: 'SEC-MOD-BOARDING-HOUSES',
      code: 'SEC_CAP_HOUSE_ISSUE_EXEAT_PASS',
      name: 'Approve & Issue Student Exeat Leave Permit',
      description: 'Validates parent leave request, medical appointment letter, and issues QR-coded gate exeat pass verified by security.',
      serviceAction: 'secondary.hostels.issueExeatPass',
      requiredPermission: 'SEC-PERM-HOSTELS',
      runtimeComponentId: 'SEC-RTC-BOARDING',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-HOUSE-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-HOSTEL-HOUSES',
      officeId: 'SEC-OFF-SENIOR-HOUSEMASTER',
      portalId: 'SEC-PORTAL-TEACHER',
      moduleId: 'SEC-MOD-BOARDING-HOUSES',
      code: 'SEC_CAP_HOUSE_TAKE_NIGHT_ROLLCALL',
      name: 'Record Hostel Dormitory Night Headcount',
      description: 'Housemaster nightly verification ensuring all enrolled resident boarders are safely locked in dormitories by 10:00 PM.',
      serviceAction: 'secondary.hostels.takeNightRollCall',
      requiredPermission: 'SEC-PERM-HOSTELS',
      runtimeComponentId: 'SEC-RTC-BOARDING',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-DISC-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-DISCIPLINE-GUILD',
      officeId: 'SEC-OFF-DISCIPLINE-MASTER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-DISCIPLINE-GUILD',
      code: 'SEC_CAP_DISC_FILE_OFFENSE_CHARGE',
      name: 'File Disciplinary Offense & Tribunal Hearing',
      description: 'Logs student breach of school rules (e.g. bullying, sneaking out) and schedules hearing before the Disciplinary Committee.',
      serviceAction: 'secondary.discipline.fileOffense',
      requiredPermission: 'SEC-PERM-DISCIPLINE',
      runtimeComponentId: 'SEC-RTC-DISCIPLINE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-DISC-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-BOARDING-DISCIPLINE',
      departmentId: 'SEC-DEPT-DISCIPLINE-GUILD',
      officeId: 'SEC-OFF-DISCIPLINE-MASTER',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-DISCIPLINE-GUILD',
      code: 'SEC_CAP_DISC_ELECT_PREFECT_CABINET',
      name: 'Administer Student Prefect Guild Elections',
      description: 'Conducts digital ballot voting for Head Boy, Head Girl, Dining Prefects, and validates vote tally in real time.',
      serviceAction: 'secondary.discipline.electPrefects',
      requiredPermission: 'SEC-PERM-DISCIPLINE',
      runtimeComponentId: 'SEC-RTC-DISCIPLINE',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-ALUM-001',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      departmentId: 'SEC-DEPT-ALUMNI-TRANSITION',
      officeId: 'SEC-OFF-ALUMNI-LIAISON',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-ALUMNI-INTEGRATION',
      code: 'SEC_CAP_ALUM_EXPORT_GRADUATE_COHORT',
      name: 'Export Graduating S6 Class to JUMO ALUMNI Platform',
      description: 'Executes integration contract with JUMO ALUMNI: migrates candidate biographical data, email, and phone to the Alumni Sovereign registry.',
      serviceAction: 'secondary.alumni.exportGraduates',
      requiredPermission: 'SEC-PERM-PRINCIPAL',
      runtimeComponentId: 'SEC-RTC-ALUMNI',
      status: 'ACTIVE_CORE'
    },
    {
      id: 'SEC-CAP-ALUM-002',
      productId: 'prod-secondary-school',
      directorateId: 'SEC-DIR-ADVANCEMENT-ALUMNI',
      departmentId: 'SEC-DEPT-ALUMNI-TRANSITION',
      officeId: 'SEC-OFF-ALUMNI-LIAISON',
      portalId: 'SEC-PORTAL-PRINCIPAL',
      moduleId: 'SEC-MOD-ALUMNI-INTEGRATION',
      code: 'SEC_CAP_ALUM_TRACK_ENDOWMENT_FUND',
      name: 'Track Alumni Capital Campaign & Mentorship Matches',
      description: 'Monitors Old Boys / Old Girls endowment donations for school infrastructure and pairs senior students with alumni mentors.',
      serviceAction: 'secondary.alumni.trackEndowments',
      requiredPermission: 'SEC-PERM-PRINCIPAL',
      runtimeComponentId: 'SEC-RTC-ALUMNI',
      status: 'ACTIVE_CORE'
    }
  ],
  screens: [
    { id: 'SEC-SCR-NCDC', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LOWER-NCDC', code: 'SEC-SCR-NCDC', title: 'Lower Secondary NCDC Project Assessment Dashboard', description: 'Continuous assessment marks, project portfolios, and descriptors.', viewType: 'TABLE', route: '/secondary/ncdc' },
    { id: 'SEC-SCR-COMBOS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UPPER-COMBOS', code: 'SEC-SCR-COMBOS', title: 'A-Level Subject Combinations & GPA Analyzer', description: 'PCM, PCB, HEG subject choices and points calculation.', viewType: 'TABLE', route: '/secondary/combos' },
    { id: 'SEC-SCR-UNEB', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UNEB-EXAMS', code: 'SEC-SCR-UNEB', title: 'UNEB Examination Center & Candidate Indexing', description: 'UCE/UACE national registration and mock performance analysis.', viewType: 'TABLE', route: '/secondary/uneb' },
    { id: 'SEC-SCR-SIS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-STUDENT-SIS', code: 'SEC-SCR-SIS', title: 'Secondary Student Biographical SIS & Roll-Call', description: 'Enrollment census, stream assignments, and daily attendance.', viewType: 'TABLE', route: '/secondary/sis' },
    { id: 'SEC-SCR-LABS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-SCIENCE-LABS', code: 'SEC-SCR-LABS', title: 'Science Laboratories, Reagents & Apparatus Vault', description: 'Physics, Chemistry, and Biology practical bookings and stocks.', viewType: 'TABLE', route: '/secondary/labs' },
    { id: 'SEC-SCR-LIBRARY', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LIBRARY-SYSTEM', code: 'SEC-SCR-LIBRARY', title: 'School E-Library & UNEB Past Papers Repository', description: 'Book loans, digital paper downloads, and reading logs.', viewType: 'TABLE', route: '/secondary/library' },
    { id: 'SEC-SCR-FEES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-FEES-BURSARY', code: 'SEC-SCR-FEES', title: 'Secondary School Fees Cashbook & SchoolPay Ledger', description: 'Tuition collections, fee clearance cards, and defaulters follow-up.', viewType: 'TABLE', route: '/secondary/fees' },
    { id: 'SEC-SCR-PAYROLL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-TEACHER-PAYROLL', code: 'SEC-SCR-PAYROLL', title: 'Teaching Staff Payroll & Extra-Lesson Allowances', description: 'Faculty remuneration, science allowances, and tax schedules.', viewType: 'TABLE', route: '/secondary/payroll' },
    { id: 'SEC-SCR-BOARDING', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-BOARDING-HOUSES', code: 'SEC-SCR-BOARDING', title: 'Senior Boarding Houses & Exeat Gate Passes', description: 'Hostel room allocations, weekend leave passes, and roll-calls.', viewType: 'TABLE', route: '/secondary/boarding' },
    { id: 'SEC-SCR-DISCIPLINE', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-DISCIPLINE-GUILD', code: 'SEC-SCR-DISCIPLINE', title: 'Disciplinary Tribunal & Prefect Guild Governance', description: 'Student offenses, committee verdicts, and prefect election results.', viewType: 'TABLE', route: '/secondary/discipline' },
    { id: 'SEC-SCR-ALUMNI', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-ALUMNI-INTEGRATION', code: 'SEC-SCR-ALUMNI', title: 'JUMO ALUMNI Integration & Endowment Bridge', description: 'Graduate export status, mentorship connections, and campaign contributions.', viewType: 'DASHBOARD', route: '/secondary/alumni' }
  ],
  forms: [
    {
      id: 'SEC-FORM-NCDC-PROJECT',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-LOWER-NCDC',
      code: 'SEC-FORM-NCDC-PROJECT',
      title: 'Lower Secondary NCDC Project Score Sheet',
      submitAction: 'secondary.ncdc.scoreProject',
      fieldCount: 5,
      fields: [
        { name: 'studentId', label: 'Student Admission Number', type: 'text', required: true },
        { name: 'subject', label: 'Subject (Physics / Maths / Geography / Biology)', type: 'select', required: true },
        { name: 'projectTitle', label: 'Hands-On Project Activity Title', type: 'text', required: true },
        { name: 'scoreOut20', label: 'Competence Project Score (0–20%)', type: 'number', required: true },
        { name: 'descriptorRating', label: 'NCDC Descriptor Rating (Basic / Moderate / Outstanding)', type: 'select', required: true }
      ],
      validationRules: ['SCORE_0_TO_20']
    },
    {
      id: 'SEC-FORM-COMBO-SELECT',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-UPPER-COMBOS',
      code: 'SEC-FORM-COMBO-SELECT',
      title: 'A-Level Subject Combination Enrollment Form',
      submitAction: 'secondary.combos.validateChoice',
      fieldCount: 5,
      fields: [
        { name: 'studentId', label: 'Student Admission Number', type: 'text', required: true },
        { name: 'combinationCode', label: 'Principal Combination (e.g. PCM, PCB, HEG, BCM)', type: 'select', required: true },
        { name: 'subsidiarySubject', label: 'Subsidiary (Subsidiary ICT / Subsidiary Maths)', type: 'select', required: true },
        { name: 'generalPaperEnrolled', label: 'General Paper (GP) Compulsory Enrollment', type: 'checkbox', required: true },
        { name: 'uceAggregateCheck', label: 'UCE Aggregate Division Verification', type: 'text', required: true }
      ],
      validationRules: ['COMBINATION_VALID']
    },
    {
      id: 'SEC-FORM-UNEB-REG',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-UNEB-EXAMS',
      code: 'SEC-FORM-UNEB-REG',
      title: 'UNEB UCE / UACE National Candidate Registration',
      submitAction: 'secondary.uneb.registerCandidate',
      fieldCount: 5,
      fields: [
        { name: 'studentId', label: 'Student School Registration ID', type: 'text', required: true },
        { name: 'nationalLin', label: 'Learner Identification Number (LIN)', type: 'text', required: true },
        { name: 'unebLevel', label: 'Examination Level (UCE / UACE)', type: 'select', required: true },
        { name: 'candidateIndex', label: 'UNEB Center Candidate Index (e.g. U0001/001)', type: 'text', required: true },
        { name: 'examCenterPasscode', label: 'Supervisor Authorization PIN', type: 'password', required: true }
      ],
      validationRules: ['INDEX_VALID']
    },
    {
      id: 'SEC-FORM-STUDENT-ENROLL',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-STUDENT-SIS',
      code: 'SEC-FORM-STUDENT-ENROLL',
      title: 'Secondary Student Admission & House Allocation',
      submitAction: 'secondary.sis.admitStudent',
      fieldCount: 5,
      fields: [
        { name: 'studentFullName', label: 'Student Full Legal Name', type: 'text', required: true },
        { name: 'admittedClass', label: 'Admitted Class (S.1, S.2, S.3, S.4, S.5, S.6)', type: 'select', required: true },
        { name: 'boardingHouse', label: 'Allocated Boarding House / Day Wing', type: 'select', required: true },
        { name: 'parentContact', label: 'Parent / Guardian Mobile Phone', type: 'text', required: true },
        { name: 'pleUcePasscode', label: 'Previous National Exam Result Slip Ref', type: 'text', required: true }
      ],
      validationRules: ['STUDENT_VALID']
    },
    {
      id: 'SEC-FORM-LAB-REQUISITION',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-SCIENCE-LABS',
      code: 'SEC-FORM-LAB-REQUISITION',
      title: 'Science Practical Requisition & Apparatus Booking',
      submitAction: 'secondary.labs.bookPracticalSession',
      fieldCount: 4,
      fields: [
        { name: 'labDepartment', label: 'Laboratory (Physics / Chemistry / Biology)', type: 'select', required: true },
        { name: 'targetClassStream', label: 'Class Stream (e.g. S.4 Science B)', type: 'text', required: true },
        { name: 'practicalTitle', label: 'Practical Title (e.g. Acid-Base Titration)', type: 'text', required: true },
        { name: 'reagentsRequired', label: 'Required Chemical Reagents & Glassware', type: 'textarea', required: true }
      ],
      validationRules: ['LAB_AVAILABLE']
    },
    {
      id: 'SEC-FORM-BOOK-LOAN',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-LIBRARY-SYSTEM',
      code: 'SEC-FORM-BOOK-LOAN',
      title: 'Library RFID Book Borrowing Checkout',
      submitAction: 'secondary.library.issueBookLoan',
      fieldCount: 4,
      fields: [
        { name: 'studentAdmissionNo', label: 'Student ID Barcode', type: 'text', required: true },
        { name: 'bookIsbnOrRfid', label: 'Book RFID / Accession Number', type: 'text', required: true },
        { name: 'borrowDurationDays', label: 'Borrow Duration (Default 14 Days)', type: 'number', required: true },
        { name: 'librarianStaffId', label: 'Authorizing Librarian Staff ID', type: 'text', required: true }
      ],
      validationRules: ['RFID_VALID']
    },
    {
      id: 'SEC-FORM-FEE-RECEIPT',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-FEES-BURSARY',
      code: 'SEC-FORM-FEE-RECEIPT',
      title: 'School Fees Cashier Payment Entry',
      submitAction: 'secondary.finance.postPayment',
      fieldCount: 4,
      fields: [
        { name: 'studentId', label: 'Student Admission Number', type: 'text', required: true },
        { name: 'amountUgx', label: 'Payment Amount (UGX)', type: 'number', required: true },
        { name: 'schoolPayRef', label: 'SchoolPay / Bank Deposit PRN Reference', type: 'text', required: true },
        { name: 'termSemester', label: 'Term / Academic Session', type: 'select', required: true }
      ],
      validationRules: ['PAYMENT_POSITIVE']
    },
    {
      id: 'SEC-FORM-PAYROLL-VOUCHER',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-TEACHER-PAYROLL',
      code: 'SEC-FORM-PAYROLL-VOUCHER',
      title: 'Faculty Extra-Lesson & Salary Allowance Voucher',
      submitAction: 'secondary.payroll.disburseLessonAllowance',
      fieldCount: 4,
      fields: [
        { name: 'teacherStaffId', label: 'Faculty Staff Member ID', type: 'text', required: true },
        { name: 'lessonCount', label: 'Verified Extra / Practical Lessons Taught', type: 'number', required: true },
        { name: 'ratePerLessonUgx', label: 'Agreed Hourly Allowance Rate (UGX)', type: 'number', required: true },
        { name: 'mobileMoneyPhone', label: 'Teacher Mobile Money Disbursal Line', type: 'text', required: true }
      ],
      validationRules: ['RATE_VALID']
    },
    {
      id: 'SEC-FORM-EXEAT-PASS',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-BOARDING-HOUSES',
      code: 'SEC-FORM-EXEAT-PASS',
      title: 'Boarding Student Exeat Leave Application',
      submitAction: 'secondary.hostels.issueExeatPass',
      fieldCount: 4,
      fields: [
        { name: 'studentId', label: 'Boarding Student ID', type: 'text', required: true },
        { name: 'leaveReason', label: 'Reason for Exeat (Medical / Family / Official)', type: 'select', required: true },
        { name: 'departureDateTime', label: 'Departure Date & Time', type: 'datetime-local', required: true },
        { name: 'expectedReturnTime', label: 'Expected Return Date & Time', type: 'datetime-local', required: true }
      ],
      validationRules: ['DATES_COHERENT']
    },
    {
      id: 'SEC-FORM-DISCIPLINE-CASE',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-DISCIPLINE-GUILD',
      code: 'SEC-FORM-DISCIPLINE-CASE',
      title: 'Disciplinary Offense Filing & Hearing Docket',
      submitAction: 'secondary.discipline.fileOffense',
      fieldCount: 4,
      fields: [
        { name: 'accusedStudentId', label: 'Accused Student Admission ID', type: 'text', required: true },
        { name: 'offenseCategory', label: 'Offense (Bullying / Substance / Insubordination)', type: 'select', required: true },
        { name: 'incidentDescription', label: 'Summary of Incident & Witnesses', type: 'textarea', required: true },
        { name: 'hearingDate', label: 'Scheduled Disciplinary Tribunal Date', type: 'date', required: true }
      ],
      validationRules: ['OFFENSE_VALID']
    },
    {
      id: 'SEC-FORM-ALUMNI-EXPORT',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-ALUMNI-INTEGRATION',
      code: 'SEC-FORM-ALUMNI-EXPORT',
      title: 'Graduating S.6 Class JUMO ALUMNI Bridge Export',
      submitAction: 'secondary.alumni.exportGraduates',
      fieldCount: 4,
      fields: [
        { name: 'graduatingYear', label: 'Graduation Academic Year (e.g. 2026)', type: 'number', required: true },
        { name: 'targetClassStream', label: 'Cohort (All S.6 Arts & Sciences)', type: 'select', required: true },
        { name: 'jumoAlumniEndpoint', label: 'JUMO ALUMNI Contract Sovereign RPC', type: 'text', required: true },
        { name: 'authorizeSignature', label: 'Principal Authorization Secret', type: 'password', required: true }
      ],
      validationRules: ['EXPORT_AUTHORIZED']
    }
  ],
  dashboards: [
    {
      id: 'SEC-DASH-ACADEMICS',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-UPPER-COMBOS',
      code: 'SEC-DASH-ACADEMICS',
      title: 'Academics, UNEB Center & Subject Combinations',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Enrolled Secondary Students', value: '1,420 Students', trend: 'up', change: 'S.1 to S.6' },
        { label: 'A-Level 20-Point Projection', value: '74 Candidates', trend: 'up', change: 'Science & Arts Combos' },
        { label: 'UCE Competence Compliance Rate', value: '98.2%', trend: 'up', change: 'NCDC 20% Projects' },
        { label: 'UNEB Center Registration Complete', value: '100% Locked', trend: 'up', change: 'Center # U0184' }
      ]
    },
    {
      id: 'SEC-DASH-FINANCE',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-FEES-BURSARY',
      code: 'SEC-DASH-FINANCE',
      title: 'Secondary Bursary Cashbook & Faculty Payroll',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'SchoolPay Collection Total', value: 'UGX 1.84 Billion', trend: 'up', change: 'Term 1 Collections' },
        { label: 'Exam Clearance Cards Issued', value: '1,385 Cleared', trend: 'up', change: '97.5% Permitted' },
        { label: 'Faculty Payroll Disbursed', value: 'UGX 145M / Mo', trend: 'neutral', change: '62 Teachers' },
        { label: 'Science Teacher Allowance Ratio', value: '100% Disbursed', trend: 'up', change: 'Paid via Mobile Money' }
      ]
    },
    {
      id: 'SEC-DASH-RESOURCES',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-SCIENCE-LABS',
      code: 'SEC-DASH-RESOURCES',
      title: 'Science Laboratories & E-Library Utilization',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Weekly Science Practical Sessions', value: '34 Labs Held', trend: 'up', change: 'Physics, Chem, Bio' },
        { label: 'Chemical Vault Stock Health', value: '94% Reagent Level', trend: 'up', change: 'Safety Inspected' },
        { label: 'Active Library Book Loans', value: '620 Books', trend: 'up', change: 'Dewey Catalog' },
        { label: 'UNEB Past Paper E-Downloads', value: '4,850 Downloads', trend: 'up', change: 'Digital Archive' }
      ]
    },
    {
      id: 'SEC-DASH-WELFARE',
      productId: 'prod-secondary-school',
      moduleId: 'SEC-MOD-BOARDING-HOUSES',
      code: 'SEC-DASH-WELFARE',
      title: 'Senior Boarding Houses & Student Governance',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Boarding Hostel Residents', value: '1,150 Boarders', trend: 'up', change: '6 Residential Houses' },
        { label: 'Nightly Roll-Call Compliance', value: '100% Present', trend: 'up', change: 'Housemaster Verified' },
        { label: 'Active Weekend Exeat Passes', value: '24 Passes', trend: 'down', change: 'Strict Gate Control' },
        { label: 'Disciplinary Tribunal Dockets', value: '2 Hearings Set', trend: 'down', change: 'Guild Moderated' }
      ]
    }
  ],
  reports: [
    { id: 'SEC-REP-NCDC', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LOWER-NCDC', code: 'SEC-REP-NCDC', title: 'Lower Secondary Continuous Competence Assessment Report', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'SEC-REP-ALEVEL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UPPER-COMBOS', code: 'SEC-REP-ALEVEL', title: 'Advanced Level Subject Combination & Principal Points Ledger', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'SEC-REP-UNEB', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UNEB-EXAMS', code: 'SEC-REP-UNEB', title: 'Official UNEB Center Candidate Verification & Mock Exam Analysis', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] },
    { id: 'SEC-REP-SIS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-STUDENT-SIS', code: 'SEC-REP-SIS', title: 'Principal Termly Student Census & Class Registers', format: 'TABULAR', exportTypes: ['PDF', 'CSV'] },
    { id: 'SEC-REP-LABS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-SCIENCE-LABS', code: 'SEC-REP-LABS', title: 'Science Laboratory Reagents Consumption & Apparatus Audit', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] },
    { id: 'SEC-REP-LIBRARY', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LIBRARY-SYSTEM', code: 'SEC-REP-LIBRARY', title: 'E-Library Cataloging, RFID Circulation & Overdue Ledger', format: 'TABULAR', exportTypes: ['PDF', 'XLSX'] },
    { id: 'SEC-REP-FEES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-FEES-BURSARY', code: 'SEC-REP-FEES', title: 'Secondary School Fees Collection & SchoolPay Reconciliation', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX', 'CSV'] },
    { id: 'SEC-REP-PAYROLL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-TEACHER-PAYROLL', code: 'SEC-REP-PAYROLL', title: 'Teaching Staff Payroll Summary & Statutory Deductions', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF'] },
    { id: 'SEC-REP-BOARDING', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-BOARDING-HOUSES', code: 'SEC-REP-BOARDING', title: 'Boarding House Bed Space & Night Headcount Logbook', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'SEC-REP-DISCIPLINE', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-DISCIPLINE-GUILD', code: 'SEC-REP-DISCIPLINE', title: 'Disciplinary Committee Hearings & Sanctions Registry', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] },
    { id: 'SEC-REP-ALUMNI', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-ALUMNI-INTEGRATION', code: 'SEC-REP-ALUMNI', title: 'Senior Six Graduate Transition & Alumni Endowment Audit', format: 'SUMMARY', exportTypes: ['PDF'] }
  ],
  workflows: [
    { id: 'SEC-WF-NCDC', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LOWER-NCDC', code: 'SEC-WF-NCDC', title: 'NCDC Project Evaluation & Moderation Workflow', stages: ['PROJECT_SUBMITTED', 'TEACHER_SCORED', 'DOS_MODERATED'], slaHours: 48, requiredApprovers: ['ROLE_SEC_TEACHER', 'ROLE_SEC_DOS'], initialState: 'PROJECT_SUBMITTED' },
    { id: 'SEC-WF-COMBOS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UPPER-COMBOS', code: 'SEC-WF-COMBOS', title: 'A-Level Subject Combination Vetting Workflow', stages: ['APPLIED', 'VETTED_ELIGIBLE', 'ENROLLED'], slaHours: 24, requiredApprovers: ['ROLE_SEC_DOS'], initialState: 'APPLIED' },
    { id: 'SEC-WF-UNEB', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UNEB-EXAMS', code: 'SEC-WF-UNEB', title: 'UNEB National Center Registration Workflow', stages: ['BIOMETRIC_CHECKED', 'INDEX_ASSIGNED', 'UNEB_SUBMITTED'], slaHours: 168, requiredApprovers: ['ROLE_SEC_PRINCIPAL'], initialState: 'BIOMETRIC_CHECKED' },
    { id: 'SEC-WF-ADMISSIONS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-STUDENT-SIS', code: 'SEC-WF-ADMISSIONS', title: 'Secondary Student Admission Workflow', stages: ['APPLIED', 'ADMITTED', 'HOUSE_ALLOCATED'], slaHours: 24, requiredApprovers: ['ROLE_SEC_PRINCIPAL'], initialState: 'APPLIED' },
    { id: 'SEC-WF-LABS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-SCIENCE-LABS', code: 'SEC-WF-LABS', title: 'Laboratory Practical Requisition Workflow', stages: ['REQUESTED', 'PREPARED', 'COMPLETED'], slaHours: 12, requiredApprovers: ['ROLE_SEC_DOS'], initialState: 'REQUESTED' },
    { id: 'SEC-WF-LIBRARY', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LIBRARY-SYSTEM', code: 'SEC-WF-LIBRARY', title: 'Book Borrowing & Return Clearance Workflow', stages: ['ISSUED', 'DUE_SOON', 'RETURNED_CLEARED'], slaHours: 72, requiredApprovers: ['ROLE_SEC_TEACHER'], initialState: 'ISSUED' },
    { id: 'SEC-WF-FEES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-FEES-BURSARY', code: 'SEC-WF-FEES', title: 'SchoolPay Payment Reconciliation Workflow', stages: ['INVOICED', 'BANK_CLEARED', 'PERMIT_ISSUED'], slaHours: 12, requiredApprovers: ['ROLE_SEC_BURSAR'], initialState: 'INVOICED' },
    { id: 'SEC-WF-PAYROLL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-TEACHER-PAYROLL', code: 'SEC-WF-PAYROLL', title: 'Faculty Salary Payroll Execution Workflow', stages: ['HOURS_VERIFIED', 'BURSAR_CALCULATED', 'DISBURSED'], slaHours: 24, requiredApprovers: ['ROLE_SEC_BURSAR', 'ROLE_SEC_PRINCIPAL'], initialState: 'HOURS_VERIFIED' },
    { id: 'SEC-WF-BOARDING', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-BOARDING-HOUSES', code: 'SEC-WF-BOARDING', title: 'Boarding Exeat Leave Authorization Workflow', stages: ['REQUESTED', 'PARENT_CONFIRMED', 'GATE_PASSED'], slaHours: 6, requiredApprovers: ['ROLE_SEC_HOUSEMASTER'], initialState: 'REQUESTED' },
    { id: 'SEC-WF-DISCIPLINE', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-DISCIPLINE-GUILD', code: 'SEC-WF-DISCIPLINE', title: 'Disciplinary Tribunal Hearing Workflow', stages: ['OFFENSE_CHARGED', 'TRIBUNAL_HEARD', 'VERDICT_ENFORCED'], slaHours: 48, requiredApprovers: ['ROLE_SEC_HOUSEMASTER', 'ROLE_SEC_PRINCIPAL'], initialState: 'OFFENSE_CHARGED' },
    { id: 'SEC-WF-ALUMNI', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-ALUMNI-INTEGRATION', code: 'SEC-WF-ALUMNI', title: 'Graduating Cohort Alumni Bridge Workflow', stages: ['CENSUS_RECORDED', 'ALUMNI_RPC_SYNCED', 'WELCOME_SENT'], slaHours: 72, requiredApprovers: ['ROLE_SEC_PRINCIPAL'], initialState: 'CENSUS_RECORDED' }
  ],
  databaseEntities: [
    { id: 'SEC-DB-NCDC-PROJECTS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LOWER-NCDC', tableName: 'sec_ncdc_projects', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'student_id', type: 'UUID', required: true, indexed: true }, { name: 'project_name', type: 'VARCHAR(255)', required: true }, { name: 'score_20', type: 'DECIMAL(4,2)', required: true }, { name: 'descriptor', type: 'VARCHAR(50)', required: true }], auditLogged: true },
    { id: 'SEC-DB-ALEVEL-COMBOS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UPPER-COMBOS', tableName: 'sec_alevel_combos', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'student_id', type: 'UUID', required: true, indexed: true }, { name: 'combo_code', type: 'VARCHAR(10)', required: true }, { name: 'principal_points', type: 'INTEGER', required: true }, { name: 'term', type: 'VARCHAR(20)', required: true }], auditLogged: true },
    { id: 'SEC-DB-UNEB-CANDIDATES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UNEB-EXAMS', tableName: 'sec_uneb_candidates', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'center_no', type: 'VARCHAR(20)', required: true, indexed: true }, { name: 'index_no', type: 'VARCHAR(30)', required: true, indexed: true }, { name: 'lin_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'exam_level', type: 'VARCHAR(10)', required: true }], auditLogged: true },
    { id: 'SEC-DB-STUDENTS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-STUDENT-SIS', tableName: 'sec_students_sis', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'admission_no', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'full_name', type: 'VARCHAR(255)', required: true }, { name: 'class_level', type: 'VARCHAR(10)', required: true }, { name: 'house_name', type: 'VARCHAR(50)', required: true }], auditLogged: true },
    { id: 'SEC-DB-LAB-INVENTORY', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-SCIENCE-LABS', tableName: 'sec_lab_inventory', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'reagent_name', type: 'VARCHAR(100)', required: true }, { name: 'lab_dept', type: 'VARCHAR(50)', required: true }, { name: 'current_volume', type: 'DECIMAL(10,2)', required: true }, { name: 'safety_level', type: 'VARCHAR(20)', required: true }], auditLogged: true },
    { id: 'SEC-DB-BOOKS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LIBRARY-SYSTEM', tableName: 'sec_library_books', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'dewey_code', type: 'VARCHAR(50)', required: true, indexed: true }, { name: 'title', type: 'VARCHAR(255)', required: true }, { name: 'author', type: 'VARCHAR(255)', required: true }, { name: 'available_copies', type: 'INTEGER', required: true }], auditLogged: true },
    { id: 'SEC-DB-FEES-CASHBOOK', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-FEES-BURSARY', tableName: 'sec_fees_cashbook', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'schoolpay_txn_id', type: 'VARCHAR(100)', required: true, indexed: true }, { name: 'student_id', type: 'UUID', required: true, indexed: true }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }, { name: 'clearance_issued', type: 'BOOLEAN', required: true }], auditLogged: true },
    { id: 'SEC-DB-STAFF-PAYROLL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-TEACHER-PAYROLL', tableName: 'sec_staff_payroll', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'staff_id', type: 'UUID', required: true, indexed: true }, { name: 'base_salary', type: 'DECIMAL(18,2)', required: true }, { name: 'science_allowance', type: 'DECIMAL(18,2)', required: true }, { name: 'net_disbursed', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'SEC-DB-HOSTELS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-BOARDING-HOUSES', tableName: 'sec_boarding_hostels', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'house_name', type: 'VARCHAR(50)', required: true }, { name: 'student_id', type: 'UUID', required: true, indexed: true }, { name: 'bed_id', type: 'VARCHAR(20)', required: true }, { name: 'nightly_present', type: 'BOOLEAN', required: true }], auditLogged: true },
    { id: 'SEC-DB-DISCIPLINE-CASES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-DISCIPLINE-GUILD', tableName: 'sec_discipline_cases', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'student_id', type: 'UUID', required: true, indexed: true }, { name: 'offense_category', type: 'VARCHAR(100)', required: true }, { name: 'sanction_verdict', type: 'VARCHAR(255)', required: true }, { name: 'verdict_enforced', type: 'BOOLEAN', required: true }], auditLogged: true },
    { id: 'SEC-DB-ALUMNI-BRIDGE', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-ALUMNI-INTEGRATION', tableName: 'sec_alumni_bridge', primaryKey: 'id', fields: [{ name: 'id', type: 'UUID', required: true, indexed: true }, { name: 'graduating_year', type: 'INTEGER', required: true, indexed: true }, { name: 'student_id', type: 'UUID', required: true, indexed: true }, { name: 'synced_to_alumni_at', type: 'TIMESTAMP', required: false }, { name: 'alumni_member_id', type: 'VARCHAR(50)', required: false }], auditLogged: true }
  ],
  apis: [
    { id: 'SEC-API-NCDC', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LOWER-NCDC', code: 'API_SEC_NCDC', method: 'POST', endpoint: '/api/v1/secondary/ncdc/scores', requiredPermission: 'SEC-PERM-ACADEMICS', handlerName: 'submitNcdcScoresHandler', summary: 'Submit lower secondary project scores.' },
    { id: 'SEC-API-COMBOS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UPPER-COMBOS', code: 'API_SEC_COMBOS', method: 'POST', endpoint: '/api/v1/secondary/combos/enroll', requiredPermission: 'SEC-PERM-ACADEMICS', handlerName: 'enrollComboHandler', summary: 'Enroll A-Level subject combination.' },
    { id: 'SEC-API-UNEB', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UNEB-EXAMS', code: 'API_SEC_UNEB', method: 'POST', endpoint: '/api/v1/secondary/uneb/register', requiredPermission: 'SEC-PERM-PRINCIPAL', handlerName: 'registerUnebCandidateHandler', summary: 'Register candidate for UNEB exams.' },
    { id: 'SEC-API-STUDENTS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-STUDENT-SIS', code: 'API_SEC_STUDENTS', method: 'POST', endpoint: '/api/v1/secondary/students/admit', requiredPermission: 'SEC-PERM-SIS', handlerName: 'admitStudentHandler', summary: 'Admit secondary student.' },
    { id: 'SEC-API-LABS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-SCIENCE-LABS', code: 'API_SEC_LABS', method: 'POST', endpoint: '/api/v1/secondary/labs/book', requiredPermission: 'SEC-PERM-LABS', handlerName: 'bookLabSessionHandler', summary: 'Book science laboratory session.' },
    { id: 'SEC-API-LIBRARY', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LIBRARY-SYSTEM', code: 'API_SEC_LIBRARY', method: 'POST', endpoint: '/api/v1/secondary/library/loan', requiredPermission: 'SEC-PERM-LIBRARY', handlerName: 'issueBookLoanHandler', summary: 'Issue RFID book loan.' },
    { id: 'SEC-API-FEES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-FEES-BURSARY', code: 'API_SEC_FEES', method: 'POST', endpoint: '/api/v1/secondary/fees/post', requiredPermission: 'SEC-PERM-BURSAR', handlerName: 'postSchoolPayFeeHandler', summary: 'Post SchoolPay fee payment.' },
    { id: 'SEC-API-PAYROLL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-TEACHER-PAYROLL', code: 'API_SEC_PAYROLL', method: 'POST', endpoint: '/api/v1/secondary/payroll/run', requiredPermission: 'SEC-PERM-BURSAR', handlerName: 'runPayrollHandler', summary: 'Execute faculty payroll run.' },
    { id: 'SEC-API-BOARDING', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-BOARDING-HOUSES', code: 'API_SEC_BOARDING', method: 'POST', endpoint: '/api/v1/secondary/boarding/exeat', requiredPermission: 'SEC-PERM-HOSTELS', handlerName: 'issueExeatPassHandler', summary: 'Issue exeat gate leave pass.' },
    { id: 'SEC-API-DISCIPLINE', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-DISCIPLINE-GUILD', code: 'API_SEC_DISCIPLINE', method: 'POST', endpoint: '/api/v1/secondary/discipline/charge', requiredPermission: 'SEC-PERM-DISCIPLINE', handlerName: 'fileDisciplineChargeHandler', summary: 'File disciplinary charge.' },
    { id: 'SEC-API-ALUMNI', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-ALUMNI-INTEGRATION', code: 'API_SEC_ALUMNI', method: 'POST', endpoint: '/api/v1/secondary/alumni/sync', requiredPermission: 'SEC-PERM-PRINCIPAL', handlerName: 'syncAlumniBridgeHandler', summary: 'Bridge graduating class to JUMO ALUMNI platform.' }
  ],
  runtimeComponents: [
    { id: 'SEC-RTC-NCDC', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LOWER-NCDC', componentKey: 'SecondaryNcdcEngine', name: 'Lower Secondary NCDC Competence Engine', description: 'NCDC competence curriculum 20% continuous assessment rubric and project score validator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LOWER_SECONDARY' },
    { id: 'SEC-RTC-COMBOS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UPPER-COMBOS', componentKey: 'SecondaryCombosEngine', name: 'A-Level Subject Combinations & GPA Engine', description: 'Subject combinations rules engine (PCM/BCM/HEG/etc.), subsidiary ICT/GP, and 20-point GPA calculation.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'UPPER_SECONDARY' },
    { id: 'SEC-RTC-UNEB', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-UNEB-EXAMS', componentKey: 'SecondaryUnebEngine', name: 'UNEB UCE/UACE National Examination Center Engine', description: 'National center examination registration, biometric candidate validation, and mock series analytics.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'EXAMINATION_CENTER' },
    { id: 'SEC-RTC-SIS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-STUDENT-SIS', componentKey: 'SecondarySisEngine', name: 'Secondary Student SIS & Biometric Attendance Engine', description: 'Complete S.1 to S.6 student directory, biometric gate attendance, and guardian records.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'STUDENT_INFO' },
    { id: 'SEC-RTC-LABS', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-SCIENCE-LABS', componentKey: 'SecondaryLabsEngine', name: 'Science Laboratories & Chemical Vault Engine', description: 'Physics/Chemistry/Biology laboratory timetable, chemical vault safety logs, and practical materials inventory.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LABORATORIES' },
    { id: 'SEC-RTC-LIBRARY', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-LIBRARY-SYSTEM', componentKey: 'SecondaryLibraryEngine', name: 'Digital E-Library & Past Papers Repository Engine', description: 'Dewey decimal system book circulation, RFID loans, and digital UNEB past papers archive.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'LIBRARY' },
    { id: 'SEC-RTC-FEES', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-FEES-BURSARY', componentKey: 'SecondaryFeesEngine', name: 'Secondary School Fees & SchoolPay Ledger Engine', description: 'Real-time SchoolPay fee reconciliation, bank payment slip clearing, and examination permit pass issuance.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FEES_FINANCE' },
    { id: 'SEC-RTC-PAYROLL', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-TEACHER-PAYROLL', componentKey: 'SecondaryPayrollEngine', name: 'Faculty Payroll & Remuneration Engine', description: 'Secondary teacher salary slips, science teacher allowances, PAYE/NSSF deductions, and payment execution.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FACULTY_PAYROLL' },
    { id: 'SEC-RTC-BOARDING', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-BOARDING-HOUSES', componentKey: 'SecondaryBoardingEngine', name: 'Senior Boarding Houses & Exeat Permit Engine', description: 'Residential house management, exeat gate pass workflow with SMS parent clearance, and night inspection rolls.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'BOARDING_HOUSES' },
    { id: 'SEC-RTC-DISCIPLINE', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-DISCIPLINE-GUILD', componentKey: 'SecondaryDisciplineEngine', name: 'Disciplinary Tribunal & Prefect Guild Engine', description: 'Student governance, prefect elections, offense dockets, and disciplinary committee tribunal hearings.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'STUDENT_GUILD' },
    { id: 'SEC-RTC-ALUMNI', productId: 'prod-secondary-school', moduleId: 'SEC-MOD-ALUMNI-INTEGRATION', componentKey: 'SecondaryAlumniBridge', name: 'JUMO ALUMNI Platform Integration Bridge', description: 'Direct contract bridge to export graduating S.6 cohorts directly into the JUMO ALUMNI network.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ALUMNI_BRIDGE' }
  ],
  permissions: [
    { id: 'SEC-PERM-ACADEMICS', productId: 'prod-secondary-school', code: 'PERM_SEC_ACADEMICS_OPERATE', name: 'Secondary Academics & Combinations Permission', description: 'Grade NCDC projects, enter subject marks, and manage combinations.' },
    { id: 'SEC-PERM-PRINCIPAL', productId: 'prod-secondary-school', code: 'PERM_SEC_PRINCIPAL_EXECUTIVE', name: 'Principal Executive Governance Permission', description: 'Approve UNEB candidate lists, alumni bridge exports, and institutional rules.' },
    { id: 'SEC-PERM-SIS', productId: 'prod-secondary-school', code: 'PERM_SEC_SIS_OPERATE', name: 'Secondary Student Enrollment Permission', description: 'Manage student records, admission letters, and class stream assignments.' },
    { id: 'SEC-PERM-LABS', productId: 'prod-secondary-school', code: 'PERM_SEC_LABS_OPERATE', name: 'Science Laboratory Vault Permission', description: 'Schedule lab practicals and manage chemical stock inventory.' },
    { id: 'SEC-PERM-LIBRARY', productId: 'prod-secondary-school', code: 'PERM_SEC_LIBRARY_OPERATE', name: 'E-Library & Past Papers Permission', description: 'Manage library cataloging, RFID book loans, and e-book downloads.' },
    { id: 'SEC-PERM-BURSAR', productId: 'prod-secondary-school', code: 'PERM_SEC_BURSAR_FINANCE', name: 'Secondary Fees & Payroll Cashbook Permission', description: 'Reconcile SchoolPay fees, manage student bursaries, and run faculty payroll.' },
    { id: 'SEC-PERM-HOSTELS', productId: 'prod-secondary-school', code: 'PERM_SEC_BOARDING_HOUSES', name: 'Boarding Houses & Exeat Permission', description: 'Issue exeat gate passes, manage hostel rooms, and verify night roll-call.' },
    { id: 'SEC-PERM-DISCIPLINE', productId: 'prod-secondary-school', code: 'PERM_SEC_DISCIPLINE_GUILD', name: 'Disciplinary Tribunal Permission', description: 'File discipline cases, schedule hearings, and supervise prefect body.' }
  ],
  roles: [
    { id: 'SEC-ROLE-PRINCIPAL', productId: 'prod-secondary-school', code: 'ROLE_SEC_PRINCIPAL', name: 'Principal / Headmaster', tier: 'GOVERNANCE', permissionIds: ['SEC-PERM-PRINCIPAL', 'SEC-PERM-ACADEMICS', 'SEC-PERM-SIS', 'SEC-PERM-BURSAR', 'SEC-PERM-DISCIPLINE'] },
    { id: 'SEC-ROLE-DOS', productId: 'prod-secondary-school', code: 'ROLE_SEC_DOS', name: 'Director of Studies (DOS)', tier: 'EXECUTIVE', permissionIds: ['SEC-PERM-ACADEMICS', 'SEC-PERM-SIS', 'SEC-PERM-LABS'] },
    { id: 'SEC-ROLE-TEACHER', productId: 'prod-secondary-school', code: 'ROLE_SEC_TEACHER', name: 'Secondary Subject Teacher', tier: 'OPERATIONAL', permissionIds: ['SEC-PERM-ACADEMICS', 'SEC-PERM-SIS', 'SEC-PERM-LIBRARY'] },
    { id: 'SEC-ROLE-BURSAR', productId: 'prod-secondary-school', code: 'ROLE_SEC_BURSAR', name: 'Senior Bursar & Finance Controller', tier: 'OPERATIONAL', permissionIds: ['SEC-PERM-BURSAR'] },
    { id: 'SEC-ROLE-HOUSEMASTER', productId: 'prod-secondary-school', code: 'ROLE_SEC_HOUSEMASTER', name: 'Senior Housemaster / Matron', tier: 'OPERATIONAL', permissionIds: ['SEC-PERM-HOSTELS', 'SEC-PERM-DISCIPLINE'] }
  ]
};
