import { CanonicalProductHierarchy } from './types';

export const UNIVERSITY_TERTIARY_HIERARCHY: CanonicalProductHierarchy = {
  product: {
    id: 'prod-university-tertiary',
    code: 'UNERP',
    name: 'University & Tertiary Institution Enterprise ERP',
    category: 'INSTITUTIONAL_ERP',
    description: 'Comprehensive collegiate ERP: Semester modular course unit registration, GPA/CGPA grading engine, NCHE academic accreditation, research grant accounting, hall of residence accommodation, e-transcripts, graduation clearance, and lecturer appraisals.',
    version: '2026.4.0',
    iconName: 'GraduationCap',
    status: 'ACTIVE_CORE',
    leadExecutiveRole: 'Vice-Chancellor / Academic Registrar',
    governingLegislation: 'Universities and Other Tertiary Institutions Act & NCHE Quality Standards 2026',
    directorateIds: ['UN-DIR-001', 'UN-DIR-002', 'UN-DIR-003', 'UN-DIR-004']
  },
  directorates: [
    { id: 'UN-DIR-001', productId: 'prod-university-tertiary', code: 'UN-DIR-ACADEMIC-REGISTRAR', name: 'Directorate of Academic Registrar & Senate Affairs', description: 'Undergraduate/postgraduate admissions, semester course units, GPA/CGPA computation, e-transcripts, and graduation clearance.', leadRole: 'ACADEMIC_REGISTRAR', departmentIds: ['UN-DEPT-001', 'UN-DEPT-002'] },
    { id: 'UN-DIR-002', productId: 'prod-university-tertiary', code: 'UN-DIR-FINANCE-GRANTS', name: 'Directorate of University Bursary & Research Grants', description: 'Tuition PRN billing, functional fees, research donor grant accounting, and staff academic payroll.', leadRole: 'UNIVERSITY_BURSAR', departmentIds: ['UN-DEPT-003', 'UN-DEPT-004'] },
    { id: 'UN-DIR-003', productId: 'prod-university-tertiary', code: 'UN-DIR-STUDENT-AFFAIRS', name: 'Directorate of Dean of Students & Guild Governance', description: 'Halls of residence room allocation, Guild Representative Council (GRC) budget, sports, and university clinic.', leadRole: 'DEAN_OF_STUDENTS', departmentIds: ['UN-DEPT-005', 'UN-DEPT-006'] },
    { id: 'UN-DIR-004', productId: 'prod-university-tertiary', code: 'UN-DIR-QUALITY-RESEARCH', name: 'Directorate of Quality Assurance, NCHE & Graduate School', description: 'NCHE program accreditation, PhD thesis repository, anti-plagiarism checks, and lecturer student appraisals.', leadRole: 'DIRECTOR_QUALITY_ASSURANCE', departmentIds: ['UN-DEPT-007', 'UN-DEPT-008'] }
  ],
  departments: [
    { id: 'UN-DEPT-001', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', code: 'UN-DEPT-ADMISSIONS-UNITS', name: 'Department of Admissions & Modular Course Registration', description: 'Direct entry, diploma scheme, mature age exams, and credit unit validation.', headRole: 'HEAD_ADMISSIONS', officeIds: ['UN-OFF-001'] },
    { id: 'UN-DEPT-002', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', code: 'UN-DEPT-EXAMS-TRANSCRIPTS', name: 'Department of Examinations, Senate & E-Transcripts', description: 'Semester exam card permits, CGPA calculation, retake tracking, and blockchain verifiable transcripts.', headRole: 'HEAD_EXAMINATIONS', officeIds: ['UN-OFF-002'] },
    { id: 'UN-DEPT-003', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', code: 'UN-DEPT-TUITION-BILLING', name: 'Department of Student Accounts & URA E-Payment PRN', description: 'Tuition, guild, registration, examination, and computer laboratory fee invoicing.', headRole: 'HEAD_STUDENT_ACCOUNTS', officeIds: ['UN-OFF-003'] },
    { id: 'UN-DEPT-004', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', code: 'UN-DEPT-RESEARCH-GRANTS', name: 'Department of Grants Management & Project Accounting', description: 'Donor funding, grant disbursements, procurement compliance, and international research audits.', headRole: 'HEAD_GRANTS_MANAGEMENT', officeIds: ['UN-OFF-004'] },
    { id: 'UN-DEPT-005', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', code: 'UN-DEPT-HALLS-RESIDENCE', name: 'Department of Halls of Residence & Non-Resident Affairs', description: 'University halls bed bidding, warden supervision, cafeteria meal plans, and private hostel accreditation.', headRole: 'HEAD_HALLS_RESIDENCE', officeIds: ['UN-OFF-005'] },
    { id: 'UN-DEPT-006', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', code: 'UN-DEPT-GUILD-SERVICES', name: 'Department of Guild Government & Career Placement', description: 'Guild election electronic voting, student societies registration, and graduate internship placement.', headRole: 'HEAD_STUDENT_WELFARE', officeIds: ['UN-OFF-006'] },
    { id: 'UN-DEPT-007', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', code: 'UN-DEPT-NCHE-ACCREDIT', name: 'Department of NCHE Accreditation & Curriculum Audit', description: 'Monitors NCHE 5-year curriculum review cycle and faculty staff-to-student ratios.', headRole: 'HEAD_ACCREDITATION', officeIds: ['UN-OFF-007'] },
    { id: 'UN-DEPT-008', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', code: 'UN-DEPT-GRADUATE-THESIS', name: 'Department of Graduate School & Anti-Plagiarism Repository', description: 'Masters/PhD viva voce defense scheduling, plagiarism similarity index, and publication repository.', headRole: 'DEAN_GRADUATE_SCHOOL', officeIds: ['UN-OFF-008'] }
  ],
  offices: [
    { id: 'UN-OFF-001', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-001', code: 'UN-OFF-ADMISSIONS-DESK', name: 'Academic Admissions & Course Enrollment Desk', description: 'Student admission letters, LIN verification, and course unit selection.', officerRole: 'SENIOR_ADMISSIONS_OFFICER', portalIds: ['UN-PORTAL-001', 'UN-PORTAL-002'], moduleIds: ['UN-MOD-001'] },
    { id: 'UN-OFF-002', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-002', code: 'UN-OFF-EXAMS-SENATE', name: 'Examinations & Transcripts Verification Office', description: 'Semester marks approval, Senate graduation list, and transcript security embossing.', officerRole: 'EXAMINATIONS_OFFICER', portalIds: ['UN-PORTAL-001', 'UN-PORTAL-002'], moduleIds: ['UN-MOD-002'] },
    { id: 'UN-OFF-003', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-003', code: 'UN-OFF-BURSARY-COUNTER', name: 'Student Billing & Tuition Clearance Counter', description: 'Tuition PRN generation, bank reconciliation, and automated exam clearance permits.', officerRole: 'ASSISTANT_BURSAR', portalIds: ['UN-PORTAL-001', 'UN-PORTAL-002'], moduleIds: ['UN-MOD-003'] },
    { id: 'UN-OFF-004', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-004', code: 'UN-OFF-GRANTS-OFFICE', name: 'Research Grants & Project Accounting Desk', description: 'Tracking multi-million donor grants, milestone disbursements, and audit logs.', officerRole: 'GRANTS_ACCOUNTANT', portalIds: ['UN-PORTAL-001'], moduleIds: ['UN-MOD-004'] },
    { id: 'UN-OFF-005', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-005', code: 'UN-OFF-HALL-WARDENS', name: 'Halls of Residence Wardens Command Office', description: 'Hostel room allocations, non-resident allowances, and cafeteria meal vouchers.', officerRole: 'SENIOR_WARDEN', portalIds: ['UN-PORTAL-002'], moduleIds: ['UN-MOD-005'] },
    { id: 'UN-OFF-006', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-006', code: 'UN-OFF-GUILD-DESK', name: 'Guild President & Electoral Commission Office', description: 'Student government elections, society budget allocations, and internship requests.', officerRole: 'GUILD_ADVISOR', portalIds: ['UN-PORTAL-002', 'UN-PORTAL-003'], moduleIds: ['UN-MOD-006'] },
    { id: 'UN-OFF-007', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-007', code: 'UN-OFF-QUALITY-DESK', name: 'NCHE Quality Assurance & Lecturer Appraisal Desk', description: 'Conducts student-lecturer teaching appraisals and monitors curriculum compliance.', officerRole: 'QUALITY_ASSURANCE_OFFICER', portalIds: ['UN-PORTAL-001', 'UN-PORTAL-002'], moduleIds: ['UN-MOD-007'] },
    { id: 'UN-OFF-008', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-008', code: 'UN-OFF-GRADUATE-DESK', name: 'Graduate School & Plagiarism Defense Office', description: 'Thesis plagiarism scanning, supervisor appointments, and doctoral viva voce panels.', officerRole: 'GRADUATE_COORDINATOR', portalIds: ['UN-PORTAL-001', 'UN-PORTAL-002'], moduleIds: ['UN-MOD-008'] }
  ],
  portals: [
    { id: 'UN-PORTAL-001', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-001', officeId: 'UN-OFF-001', code: 'UN-PORTAL-EXECUTIVE', name: 'Vice-Chancellor, Academic Registrar & Senate Cockpit', description: 'Institutional enrollment, Senate graduation lists, tuition cashflow, NCHE accreditation, and grant portfolios.', targetRole: 'VICE_CHANCELLOR', authLevel: 'PKI_SOVEREIGN', route: '/university/executive', moduleIds: ['UN-MOD-001', 'UN-MOD-002', 'UN-MOD-003', 'UN-MOD-004', 'UN-MOD-007', 'UN-MOD-008'] },
    { id: 'UN-PORTAL-002', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-001', officeId: 'UN-OFF-001', code: 'UN-PORTAL-FACULTY-STAFF', name: 'Faculty Deans, Lecturers & Staff Workspace', description: 'Upload continuous assessment scores, enter exam marks, review student thesis, and manage research grants.', targetRole: 'FACULTY_LECTURER', authLevel: 'STAFF', route: '/university/faculty', moduleIds: ['UN-MOD-001', 'UN-MOD-002', 'UN-MOD-005', 'UN-MOD-007', 'UN-MOD-008'] },
    { id: 'UN-PORTAL-003', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-006', officeId: 'UN-OFF-006', code: 'UN-PORTAL-STUDENT-ACADEMIC', name: 'Student Academic Portal & E-Learning Gateway', description: 'Register semester course units, view CGPA, generate tuition PRNs, apply for hostel rooms, and download e-transcripts.', targetRole: 'UNIVERSITY_STUDENT', authLevel: 'PUBLIC', route: '/university/student', moduleIds: ['UN-MOD-001', 'UN-MOD-002', 'UN-MOD-003', 'UN-MOD-005', 'UN-MOD-006'] }
  ],
  modules: [
    { id: 'UN-MOD-001', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-001', officeId: 'UN-OFF-001', portalId: 'UN-PORTAL-002', code: 'UN-MOD-COURSE-REG', name: 'Semester Modular Course Unit & Credit Registration', description: 'Prerequisite verification, minimum/maximum credit limits, and timetable clash detection.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-001', 'UN-CAP-002'], screenIds: ['UN-SCR-001'], formIds: ['UN-FORM-001'], dashboardIds: ['UN-DASH-001'], reportIds: ['UN-REP-001'], workflowIds: ['UN-WF-001'], databaseEntityIds: ['UN-DB-001'], apiIds: ['UN-API-001'], runtimeComponentId: 'UN-RTC-001', permissionIds: ['UN-PERM-001'] },
    { id: 'UN-MOD-002', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-002', officeId: 'UN-OFF-002', portalId: 'UN-PORTAL-002', code: 'UN-MOD-GPA-CGPA', name: 'GPA/CGPA Grading Engine & Verifiable E-Transcripts', description: 'Computes GPA (Grade Points x Credit Units / Total Credits) and issues blockchain verifiable transcripts.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-003', 'UN-CAP-004'], screenIds: ['UN-SCR-002'], formIds: ['UN-FORM-002'], dashboardIds: ['UN-DASH-001'], reportIds: ['UN-REP-002'], workflowIds: ['UN-WF-002'], databaseEntityIds: ['UN-DB-002'], apiIds: ['UN-API-002'], runtimeComponentId: 'UN-RTC-002', permissionIds: ['UN-PERM-002'] },
    { id: 'UN-MOD-003', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-003', officeId: 'UN-OFF-003', portalId: 'UN-PORTAL-001', code: 'UN-MOD-TUITION-BILLING', name: 'University Bursary, PRN Billing & Exam Clearance', description: 'Automates payment registration number (PRN) billing and generates digital exam permits.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-005', 'UN-CAP-006'], screenIds: ['UN-SCR-003'], formIds: ['UN-FORM-003'], dashboardIds: ['UN-DASH-002'], reportIds: ['UN-REP-003'], workflowIds: ['UN-WF-003'], databaseEntityIds: ['UN-DB-003'], apiIds: ['UN-API-003'], runtimeComponentId: 'UN-RTC-003', permissionIds: ['UN-PERM-003'] },
    { id: 'UN-MOD-004', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-004', officeId: 'UN-OFF-004', portalId: 'UN-PORTAL-001', code: 'UN-MOD-RESEARCH-GRANTS', name: 'Research Grants & Project Accounting Engine', description: 'Multi-currency donor grant budget tracking, milestone expenditure, and international compliance.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-007', 'UN-CAP-008'], screenIds: ['UN-SCR-004'], formIds: ['UN-FORM-004'], dashboardIds: ['UN-DASH-002'], reportIds: ['UN-REP-004'], workflowIds: ['UN-WF-004'], databaseEntityIds: ['UN-DB-004'], apiIds: ['UN-API-004'], runtimeComponentId: 'UN-RTC-004', permissionIds: ['UN-PERM-004'] },
    { id: 'UN-MOD-005', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-005', officeId: 'UN-OFF-005', portalId: 'UN-PORTAL-002', code: 'UN-MOD-HALLS-RESIDENCE', name: 'Halls of Residence & Campus Accommodation', description: 'Automated room bidding algorithm based on seniority/need and private hostel accreditation.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-009', 'UN-CAP-010'], screenIds: ['UN-SCR-005'], formIds: ['UN-FORM-005'], dashboardIds: ['UN-DASH-003'], reportIds: ['UN-REP-005'], workflowIds: ['UN-WF-005'], databaseEntityIds: ['UN-DB-005'], apiIds: ['UN-API-005'], runtimeComponentId: 'UN-RTC-005', permissionIds: ['UN-PERM-005'] },
    { id: 'UN-MOD-006', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-006', officeId: 'UN-OFF-006', portalId: 'UN-PORTAL-003', code: 'UN-MOD-GUILD-VOTING', name: 'Guild Government Electronic Voting & Student Societies', description: 'Cryptographic student council elections and student club charter management.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-011', 'UN-CAP-012'], screenIds: ['UN-SCR-006'], formIds: ['UN-FORM-006'], dashboardIds: ['UN-DASH-003'], reportIds: ['UN-REP-006'], workflowIds: ['UN-WF-006'], databaseEntityIds: ['UN-DB-006'], apiIds: ['UN-API-006'], runtimeComponentId: 'UN-RTC-006', permissionIds: ['UN-PERM-006'] },
    { id: 'UN-MOD-007', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-007', officeId: 'UN-OFF-007', portalId: 'UN-PORTAL-001', code: 'UN-MOD-QUALITY-NCHE', name: 'NCHE Quality Assurance & Lecturer Appraisal', description: 'Evaluates course curriculum compliance and runs student anonymous teaching evaluations.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-013', 'UN-CAP-014'], screenIds: ['UN-SCR-007'], formIds: ['UN-FORM-007'], dashboardIds: ['UN-DASH-004'], reportIds: ['UN-REP-007'], workflowIds: ['UN-WF-007'], databaseEntityIds: ['UN-DB-007'], apiIds: ['UN-API-007'], runtimeComponentId: 'UN-RTC-007', permissionIds: ['UN-PERM-007'] },
    { id: 'UN-MOD-008', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-008', officeId: 'UN-OFF-008', portalId: 'UN-PORTAL-001', code: 'UN-MOD-GRADUATE-THESIS', name: 'Graduate School Thesis & Anti-Plagiarism Repository', description: 'Automated plagiarism similarity scan, thesis supervisor assignment, and defense scheduling.', status: 'ACTIVE_CORE', capabilityIds: ['UN-CAP-015', 'UN-CAP-016'], screenIds: ['UN-SCR-008'], formIds: ['UN-FORM-008'], dashboardIds: ['UN-DASH-004'], reportIds: ['UN-REP-008'], workflowIds: ['UN-WF-008'], databaseEntityIds: ['UN-DB-008'], apiIds: ['UN-API-008'], runtimeComponentId: 'UN-RTC-008', permissionIds: ['UN-PERM-008'] }
  ],
  capabilities: [
    { id: 'UN-CAP-001', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-001', officeId: 'UN-OFF-001', portalId: 'UN-PORTAL-002', moduleId: 'UN-MOD-001', code: 'UN_CAP_REGISTER_COURSE_UNITS', name: 'Register Semester Modular Course Units', description: 'Validates prerequisites, credit load (min 15 / max 28 CUs), and confirms enrollment.', serviceAction: 'university.academics.registerCourseUnits', requiredPermission: 'UN-PERM-001', runtimeComponentId: 'UN-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-002', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-001', officeId: 'UN-OFF-001', portalId: 'UN-PORTAL-002', moduleId: 'UN-MOD-001', code: 'UN_CAP_APPROVE_RETAKE', name: 'Approve Course Retake / Special Examination', description: 'Schedules retake exam for scored unit < 50% (Grade Point 0.0) in subsequent semester.', serviceAction: 'university.academics.approveRetake', requiredPermission: 'UN-PERM-001', runtimeComponentId: 'UN-RTC-001', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-003', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-002', officeId: 'UN-OFF-002', portalId: 'UN-PORTAL-002', moduleId: 'UN-MOD-002', code: 'UN_CAP_COMPUTE_CGPA', name: 'Calculate Semester GPA & Cumulative CGPA', description: 'Computes GPV, GPA, and CGPA on 5.0 scale (Class: First Class >= 4.40, Second Upper >= 3.60).', serviceAction: 'university.academics.computeCgpa', requiredPermission: 'UN-PERM-002', runtimeComponentId: 'UN-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-004', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-001', departmentId: 'UN-DEPT-002', officeId: 'UN-OFF-002', portalId: 'UN-PORTAL-002', moduleId: 'UN-MOD-002', code: 'UN_CAP_ISSUE_VERIFIABLE_TRANSCRIPT', name: 'Issue Blockchain Verifiable E-Transcript', description: 'Signs e-transcript with Academic Registrar PKI key and attaches cryptographic QR code.', serviceAction: 'university.academics.issueVerifiableTranscript', requiredPermission: 'UN-PERM-002', runtimeComponentId: 'UN-RTC-002', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-005', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-003', officeId: 'UN-OFF-003', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-003', code: 'UN_CAP_GENERATE_URA_PRN', name: 'Generate URA Payment Registration Number (PRN)', description: 'Issues 14-digit PRN for commercial bank or mobile money tuition fee clearance.', serviceAction: 'university.finance.generatePrn', requiredPermission: 'UN-PERM-003', runtimeComponentId: 'UN-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-006', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-003', officeId: 'UN-OFF-003', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-003', code: 'UN_CAP_ISSUE_EXAM_PERMIT', name: 'Issue Biometric Examination Room Permit', description: 'Confirms 100% financial clearance and generates QR exam room admission card.', serviceAction: 'university.finance.issueExamPermit', requiredPermission: 'UN-PERM-003', runtimeComponentId: 'UN-RTC-003', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-007', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-004', officeId: 'UN-OFF-004', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-004', code: 'UN_CAP_CREATE_GRANT_ACCOUNT', name: 'Setup Research Donor Grant Account', description: 'Sets up multi-currency budget lines, PI overhead allocations, and milestone deliverables.', serviceAction: 'university.grants.createGrantAccount', requiredPermission: 'UN-PERM-004', runtimeComponentId: 'UN-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-008', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-002', departmentId: 'UN-DEPT-004', officeId: 'UN-OFF-004', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-004', code: 'UN_CAP_DISBURSE_GRANT_FUNDS', name: 'Authorize Research Fieldwork Disbursement', description: 'Releases project funds upon verification of previous tranche milestone retirement.', serviceAction: 'university.grants.disburseFunds', requiredPermission: 'UN-PERM-004', runtimeComponentId: 'UN-RTC-004', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-009', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-005', officeId: 'UN-OFF-005', portalId: 'UN-PORTAL-002', moduleId: 'UN-MOD-005', code: 'UN_CAP_BID_HOSTEL_ROOM', name: 'Execute Automated Hall Room Bidding', description: 'Allocates hall of residence rooms based on disability, academic excellence, and first-year status.', serviceAction: 'university.halls.bidHostelRoom', requiredPermission: 'UN-PERM-005', runtimeComponentId: 'UN-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-010', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-005', officeId: 'UN-OFF-005', portalId: 'UN-PORTAL-002', moduleId: 'UN-MOD-005', code: 'UN_CAP_ACCREDIT_PRIVATE_HOSTEL', name: 'Accredit Private Student Hostel', description: 'Audits student hostel perimeter security, hygiene, and fire safety for university certification.', serviceAction: 'university.halls.accreditHostel', requiredPermission: 'UN-PERM-005', runtimeComponentId: 'UN-RTC-005', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-011', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-006', officeId: 'UN-OFF-006', portalId: 'UN-PORTAL-003', moduleId: 'UN-MOD-006', code: 'UN_CAP_EXECUTE_GUILD_ELECTION', name: 'Run Cryptographic Student Guild Election', description: 'Zero-knowledge cryptographic ballot voting for Guild President and Faculty Representatives.', serviceAction: 'university.guild.executeElection', requiredPermission: 'UN-PERM-006', runtimeComponentId: 'UN-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-012', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-003', departmentId: 'UN-DEPT-006', officeId: 'UN-OFF-006', portalId: 'UN-PORTAL-003', moduleId: 'UN-MOD-006', code: 'UN_CAP_CHARTER_STUDENT_SOCIETY', name: 'Approve & Charter Student Society', description: 'Registers academic/cultural club and allocates annual student activity budget.', serviceAction: 'university.guild.charterSociety', requiredPermission: 'UN-PERM-006', runtimeComponentId: 'UN-RTC-006', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-013', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-007', officeId: 'UN-OFF-007', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-007', code: 'UN_CAP_AUDIT_NCHE_COMPLIANCE', name: 'Run NCHE Program Accreditation Audit', description: 'Validates curriculum credit weighting, lab infrastructure, and PhD staff ratios against NCHE standards.', serviceAction: 'university.quality.auditNcheCompliance', requiredPermission: 'UN-PERM-007', runtimeComponentId: 'UN-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-014', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-007', officeId: 'UN-OFF-007', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-007', code: 'UN_CAP_RUN_LECTURER_APPRAISAL', name: 'Publish Anonymous Lecturer Student Appraisal', description: 'Aggregates student ratings on course delivery, punctuality, and grading fairness.', serviceAction: 'university.quality.runLecturerAppraisal', requiredPermission: 'UN-PERM-007', runtimeComponentId: 'UN-RTC-007', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-015', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-008', officeId: 'UN-OFF-008', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-008', code: 'UN_CAP_SCAN_THESIS_PLAGIARISM', name: 'Scan Dissertation for Plagiarism & AI Generation', description: 'Computes similarity index score; enforces <= 15% threshold for Masters/PhD defense.', serviceAction: 'university.thesis.scanPlagiarism', requiredPermission: 'UN-PERM-008', runtimeComponentId: 'UN-RTC-008', status: 'ACTIVE_CORE' },
    { id: 'UN-CAP-016', productId: 'prod-university-tertiary', directorateId: 'UN-DIR-004', departmentId: 'UN-DEPT-008', officeId: 'UN-OFF-008', portalId: 'UN-PORTAL-001', moduleId: 'UN-MOD-008', code: 'UN_CAP_CONVENE_VIVA_VOCE', name: 'Convene Doctoral Viva Voce Defense Panel', description: 'Appoints external examiner, schedules public defense, and records final Senate recommendation.', serviceAction: 'university.thesis.conveneVivaVoce', requiredPermission: 'UN-PERM-008', runtimeComponentId: 'UN-RTC-008', status: 'ACTIVE_CORE' }
  ],
  screens: [
    { id: 'UN-SCR-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', code: 'UN-SCR-REGISTRATION', title: 'Modular Course Units & Timetable Planning', description: 'Semester course registrations and credit loads.', viewType: 'TABLE', route: '/university/registration' },
    { id: 'UN-SCR-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', code: 'UN-SCR-CGPA', title: 'Examinations, GPA/CGPA & Senate Transcripts', description: 'Semester marks scorecards, CGPA calculator, and transcripts.', viewType: 'TABLE', route: '/university/grades' },
    { id: 'UN-SCR-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', code: 'UN-SCR-BURSARY', title: 'University Bursary, PRN Billing & Exam Permits', description: 'Tuition ledger, URA PRN receipts, and exam clearance.', viewType: 'TABLE', route: '/university/bursary' },
    { id: 'UN-SCR-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', code: 'UN-SCR-GRANTS', title: 'Research Grants & International Donor Projects', description: 'Grant budgets, milestone disbursements, and audits.', viewType: 'TABLE', route: '/university/grants' },
    { id: 'UN-SCR-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', code: 'UN-SCR-HALLS', title: 'Halls of Residence & Campus Accommodation', description: 'Room allocations, bed bidding, and private hostel registry.', viewType: 'TABLE', route: '/university/halls' },
    { id: 'UN-SCR-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', code: 'UN-SCR-GUILD', title: 'Student Guild Council & E-Voting Console', description: 'Electoral results, guild budget, and societies.', viewType: 'DASHBOARD', route: '/university/guild' },
    { id: 'UN-SCR-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', code: 'UN-SCR-QUALITY', title: 'NCHE Quality Assurance & Lecturer Appraisals', description: 'Accreditation audits and teaching evaluation analytics.', viewType: 'DASHBOARD', route: '/university/quality' },
    { id: 'UN-SCR-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', code: 'UN-SCR-THESIS', title: 'Graduate School Dissertations & Viva Voce Panel', description: 'Thesis plagiarism index and defense panels.', viewType: 'TABLE', route: '/university/thesis' }
  ],
  forms: [
    { id: 'UN-FORM-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', code: 'UN-FORM-COURSE-ENROLL', title: 'Semester Course Unit Enrollment Form', submitAction: 'university.academics.registerCourseUnits', fieldCount: 5, fields: [{ name: 'studentRegNo', label: 'Student University Reg Number', type: 'text', required: true }, { name: 'academicYear', label: 'Academic Year (e.g. 2026/2027)', type: 'text', required: true }, { name: 'semester', label: 'Semester (Semester 1 / Semester 2)', type: 'select', required: true }, { name: 'courseUnitsJson', label: 'Selected Course Unit Codes (Comma Separated)', type: 'text', required: true }, { name: 'totalCredits', label: 'Total Enrolled Credit Units', type: 'number', required: true }], validationRules: ['CREDITS_BETWEEN_15_AND_28'] },
    { id: 'UN-FORM-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', code: 'UN-FORM-MARKS-SUBMIT', title: 'Faculty Course Unit Marks Submission', submitAction: 'university.academics.computeCgpa', fieldCount: 5, fields: [{ name: 'courseUnitCode', label: 'Course Unit Code (e.g. CSC 3101)', type: 'text', required: true }, { name: 'academicYear', label: 'Academic Year', type: 'text', required: true }, { name: 'lecturerStaffId', label: 'Lecturer Staff ID', type: 'text', required: true }, { name: 'deanApprovalPin', label: 'Faculty Dean Sign-Off PIN', type: 'password', required: true }, { name: 'examScoresBatch', label: 'Student Marks Roster Payload', type: 'textarea', required: true }], validationRules: ['SCORES_WITHIN_100'] },
    { id: 'UN-FORM-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', code: 'UN-FORM-PRN-GEN', title: 'Generate URA Tuition PRN Payment Slip', submitAction: 'university.finance.generatePrn', fieldCount: 4, fields: [{ name: 'studentRegNo', label: 'Student Registration Number', type: 'text', required: true }, { name: 'tuitionAmountUgx', label: 'Tuition Fee Amount (UGX)', type: 'number', required: true }, { name: 'functionalFeesUgx', label: 'Functional / Guild Fees (UGX)', type: 'number', required: true }, { name: 'paymentMode', label: 'Intended Payment Channel (EFT/Mobile Money/Bank)', type: 'select', required: true }], validationRules: ['FEES_POSITIVE'] },
    { id: 'UN-FORM-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', code: 'UN-FORM-GRANT-CREATE', title: 'New Research Grant Account Setup', submitAction: 'university.grants.createGrantAccount', fieldCount: 5, fields: [{ name: 'grantTitle', label: 'Research Project Title', type: 'text', required: true }, { name: 'donorAgency', label: 'Funding Donor Agency (e.g. NIH/EU/World Bank)', type: 'text', required: true }, { name: 'piStaffId', label: 'Principal Investigator Staff ID', type: 'text', required: true }, { name: 'grantCurrency', label: 'Funding Currency (USD/EUR/UGX)', type: 'select', required: true }, { name: 'totalGrantBudget', label: 'Total Awarded Budget', type: 'number', required: true }], validationRules: ['BUDGET_POSITIVE'] },
    { id: 'UN-FORM-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', code: 'UN-FORM-HALL-BID', title: 'Hall of Residence Accommodation Bidding', submitAction: 'university.halls.bidHostelRoom', fieldCount: 4, fields: [{ name: 'studentRegNo', label: 'Student Registration Number', type: 'text', required: true }, { name: 'preferredHall', label: 'First Choice Hall of Residence', type: 'select', required: true }, { name: 'specialNeedsCategory', label: 'Special Medical / Disability Need (if any)', type: 'text', required: false }, { name: 'academicYear', label: 'Academic Year', type: 'text', required: true }], validationRules: ['STUDENT_ELIGIBLE'] },
    { id: 'UN-FORM-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', code: 'UN-FORM-BALLOT-CAST', title: 'Guild Presidential Electronic Ballot', submitAction: 'university.guild.executeElection', fieldCount: 3, fields: [{ name: 'studentVoterCardNo', label: 'Biometric Voter Pass Token', type: 'text', required: true }, { name: 'candidateSelection', label: 'Candidate Selection (President)', type: 'select', required: true }, { name: 'zeroKnowledgeHash', label: 'Client-Side Cryptographic Hash', type: 'text', required: true }], validationRules: ['VOTE_NOT_DUPLICATED'] },
    { id: 'UN-FORM-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', code: 'UN-FORM-APPRAISAL-EVAL', title: 'Student Anonymous Course & Lecturer Evaluation', submitAction: 'university.quality.runLecturerAppraisal', fieldCount: 5, fields: [{ name: 'courseUnitCode', label: 'Course Unit Code', type: 'text', required: true }, { name: 'contentMasteryRating', label: 'Lecturer Content Mastery (1-5 Stars)', type: 'number', required: true }, { name: 'punctualityRating', label: 'Class Punctuality & Availability (1-5 Stars)', type: 'number', required: true }, { name: 'gradingFairnessRating', label: 'Coursework Feedback & Fairness (1-5 Stars)', type: 'number', required: true }, { name: 'qualitativeRemarks', label: 'Suggestions for Improvement', type: 'textarea', required: false }], validationRules: ['RATINGS_1_TO_5'] },
    { id: 'UN-FORM-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', code: 'UN-FORM-THESIS-SUBMIT', title: 'Postgraduate Thesis Plagiarism & Defense Submission', submitAction: 'university.thesis.scanPlagiarism', fieldCount: 5, fields: [{ name: 'candidateRegNo', label: 'Masters / PhD Candidate Reg Number', type: 'text', required: true }, { name: 'dissertationTitle', label: 'Dissertation / Thesis Title', type: 'text', required: true }, { name: 'principalSupervisor', label: 'Principal Supervisor Name & Faculty', type: 'text', required: true }, { name: 'manuscriptDocUrl', label: 'Complete Dissertation Manuscript (PDF/Word)', type: 'text', required: true }, { name: 'supervisorSignOffRef', label: 'Supervisor Defense Clearance Ref', type: 'text', required: true }], validationRules: ['SUPERVISOR_SIGNED'] }
  ],
  dashboards: [
    {
      id: 'UN-DASH-001',
      productId: 'prod-university-tertiary',
      moduleId: 'UN-MOD-001',
      code: 'UN-DASH-ENROLLMENT',
      title: 'University Enrollment & Senate Academic Standing',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Enrolled University Students', value: '34,800 Students', trend: 'up', change: '10 Colleges' },
        { label: 'Course Unit Registration Rate', value: '98.4%', trend: 'up', change: 'Prerequisites Verified' },
        { label: 'First Class Honors Candidates', value: '8.4%', trend: 'up', change: 'CGPA >= 4.40' },
        { label: 'Graduation Clearance Rate', value: '94.2%', trend: 'up', change: '8,400 Graduands' }
      ]
    },
    {
      id: 'UN-DASH-002',
      productId: 'prod-university-tertiary',
      moduleId: 'UN-MOD-003',
      code: 'UN-DASH-FINANCIALS',
      title: 'University Bursary Cashflow & Research Grants',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'Total Tuition Collections', value: 'UGX 54.8 Billion', trend: 'up', change: 'URA PRN Unified' },
        { label: 'Active International Grants', value: '142 Grants ($28M)', trend: 'up', change: 'NIH, EU, Gates Fdn' },
        { label: 'Research Overhead Yield', value: 'UGX 3.4 Billion', trend: 'up', change: 'Reinvested in Labs' },
        { label: 'Exam Financial Permits Issued', value: '32,600 Cards', trend: 'up', change: '100% Cleared' }
      ]
    },
    {
      id: 'UN-DASH-003',
      productId: 'prod-university-tertiary',
      moduleId: 'UN-MOD-005',
      code: 'UN-DASH-CAMPUS-LIFE',
      title: 'Halls of Residence & Guild Democratic Affairs',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'University Hall Bed Capacity', value: '6,200 Beds', trend: 'neutral', change: '100% Occupied' },
        { label: 'Accredited Private Hostels', value: '48 Hostels', trend: 'up', change: '24,000 Students' },
        { label: 'Guild Election Turnout', value: '78.6%', trend: 'up', change: 'Cryptographic Voting' },
        { label: 'Chartered Student Clubs', value: '86 Societies', trend: 'up', change: 'Active Charters' }
      ]
    },
    {
      id: 'UN-DASH-004',
      productId: 'prod-university-tertiary',
      moduleId: 'UN-MOD-007',
      code: 'UN-DASH-RESEARCH-QUALITY',
      title: 'NCHE Quality Assurance & Postgraduate Thesis Output',
      widgetCount: 4,
      kpiMetrics: [
        { label: 'NCHE Accredited Programs', value: '184 Programs', trend: 'up', change: '100% Compliant' },
        { label: 'Average Lecturer Evaluation', value: '4.4 / 5.0 Stars', trend: 'up', change: 'Student Appraisals' },
        { label: 'Doctoral (PhD) Defenses Run', value: '42 Dissertations', trend: 'up', change: 'Plagiarism < 10%' },
        { label: 'Indexed Research Publications', value: '620 Papers', trend: 'up', change: 'Scopus / Nature' }
      ]
    }
  ],
  reports: [
    { id: 'UN-REP-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', code: 'UN-REP-ENROLLMENT-CENSUS', title: 'Institutional Student Enrollment & Course Unit Matrix', format: 'TABULAR', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'UN-REP-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', code: 'UN-REP-TRANSCRIPT-SENATE', title: 'Official Senate Academic Transcript & Graduation Gazette', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] },
    { id: 'UN-REP-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', code: 'UN-REP-BURSARY-PRN', title: 'University Tuition Revenue & URA PRN Settlement Sheet', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'CSV', 'XLSX'] },
    { id: 'UN-REP-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', code: 'UN-REP-GRANT-AUDIT', title: 'Donor Research Grants Expenditure & Compliance Audit', format: 'FINANCIAL_STATEMENT', exportTypes: ['PDF', 'XLSX'] },
    { id: 'UN-REP-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', code: 'UN-REP-HALLS-OCCUPANCY', title: 'Halls of Residence Occupancy & Private Hostels Audit', format: 'TABULAR', exportTypes: ['PDF'] },
    { id: 'UN-REP-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', code: 'UN-REP-GUILD-ELECTIONS', title: 'Guild Electoral Commission Certified Results Gazette', format: 'SUMMARY', exportTypes: ['PDF'] },
    { id: 'UN-REP-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', code: 'UN-REP-NCHE-AUDIT', title: 'National Council for Higher Education (NCHE) Institutional Return', format: 'REGULATORY_RETURN', exportTypes: ['PDF'] },
    { id: 'UN-REP-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', code: 'UN-REP-THESIS-REPOSITORY', title: 'Postgraduate Thesis Plagiarism & Defense Verification Registry', format: 'FORENSIC_TRAIL', exportTypes: ['PDF'] }
  ],
  workflows: [
    { id: 'UN-WF-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', code: 'UN-WF-COURSE-REG', title: 'Semester Course Unit Registration Flow', stages: ['Course Selection', 'Prerequisite Check', 'Advisor Sign-Off', 'Timetable Lock'], slaHours: 48, requiredApprovers: ['SENIOR_ADMISSIONS_OFFICER'], initialState: 'Course Selection' },
    { id: 'UN-WF-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', code: 'UN-WF-CGPA-COMPUTE', title: 'Senate Marks Approval & Transcript Release Flow', stages: ['Department Marks Entry', 'Faculty Board Audit', 'Senate Confirmation', 'E-Transcript PKI Signing'], slaHours: 96, requiredApprovers: ['EXAMINATIONS_OFFICER', 'ACADEMIC_REGISTRAR'], initialState: 'Department Marks Entry' },
    { id: 'UN-WF-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', code: 'UN-WF-PRN-CLEARANCE', title: 'Tuition PRN Ingest & Exam Clearance Flow', stages: ['URA PRN Generation', 'Bank Settlement Ingest', 'Clearance Permit Issue', 'Barcode Gate Verification'], slaHours: 1, requiredApprovers: ['ASSISTANT_BURSAR'], initialState: 'URA PRN Generation' },
    { id: 'UN-WF-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', code: 'UN-WF-GRANT-DISBURSE', title: 'Research Grant Expenditure Milestone Flow', stages: ['PI Requisition', 'Milestone Audit', 'Bursary Approval', 'Wire Transfer'], slaHours: 24, requiredApprovers: ['GRANTS_ACCOUNTANT', 'UNIVERSITY_BURSAR'], initialState: 'PI Requisition' },
    { id: 'UN-WF-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', code: 'UN-WF-ROOM-BIDDING', title: 'Hall of Residence Room Allocation Flow', stages: ['Student Application', 'Algorithm Scoring', 'Warden Room Tag', 'Key Issuance'], slaHours: 24, requiredApprovers: ['SENIOR_WARDEN'], initialState: 'Student Application' },
    { id: 'UN-WF-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', code: 'UN-WF-GUILD-ELECTION', title: 'Guild Presidential Election Certification Flow', stages: ['Candidate Vetting', 'Campaign Window', 'Encrypted Balloting', 'Public Tally Declaration'], slaHours: 12, requiredApprovers: ['GUILD_ADVISOR', 'DEAN_OF_STUDENTS'], initialState: 'Candidate Vetting' },
    { id: 'UN-WF-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', code: 'UN-WF-NCHE-REVIEW', title: 'NCHE Curriculum 5-Year Review Cycle Flow', stages: ['Faculty Draft', 'External Peer Review', 'Senate Approval', 'NCHE Gazette Submission'], slaHours: 720, requiredApprovers: ['DIRECTOR_QUALITY_ASSURANCE', 'VICE_CHANCELLOR'], initialState: 'Faculty Draft' },
    { id: 'UN-WF-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', code: 'UN-WF-THESIS-DEFENSE', title: 'Doctoral Dissertation Viva Voce Defense Flow', stages: ['Plagiarism Scan', 'External Examiner Report', 'Public Viva Defense', 'Senate Degree Conferment'], slaHours: 360, requiredApprovers: ['DEAN_GRADUATE_SCHOOL', 'ACADEMIC_REGISTRAR'], initialState: 'Plagiarism Scan' }
  ],
  databaseEntities: [
    { id: 'UN-DB-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', tableName: 'un_course_registrations', primaryKey: 'registration_id', fields: [{ name: 'registration_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'student_reg_no', type: 'VARCHAR(32)', required: true }, { name: 'credit_units', type: 'INT', required: true }], auditLogged: true },
    { id: 'UN-DB-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', tableName: 'un_student_transcripts', primaryKey: 'transcript_id', fields: [{ name: 'transcript_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'student_reg_no', type: 'VARCHAR(32)', required: true }, { name: 'cgpa', type: 'DECIMAL(4,2)', required: true }], auditLogged: true },
    { id: 'UN-DB-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', tableName: 'un_prn_payments', primaryKey: 'prn', fields: [{ name: 'prn', type: 'VARCHAR(32)', required: true, indexed: true }, { name: 'student_reg_no', type: 'VARCHAR(32)', required: true }, { name: 'amount', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'UN-DB-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', tableName: 'un_research_grants', primaryKey: 'grant_id', fields: [{ name: 'grant_id', type: 'VARCHAR(64)', required: true, indexed: true }, { name: 'donor', type: 'VARCHAR(128)', required: true }, { name: 'budget_usd', type: 'DECIMAL(18,2)', required: true }], auditLogged: true },
    { id: 'UN-DB-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', tableName: 'un_hall_allocations', primaryKey: 'allocation_id', fields: [{ name: 'allocation_id', type: 'VARCHAR(64)', required: true }, { name: 'student_reg_no', type: 'VARCHAR(32)', required: true }, { name: 'hall_name', type: 'VARCHAR(64)', required: true }], auditLogged: true },
    { id: 'UN-DB-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', tableName: 'un_guild_votes', primaryKey: 'vote_hash', fields: [{ name: 'vote_hash', type: 'VARCHAR(128)', required: true }, { name: 'candidate_id', type: 'VARCHAR(32)', required: true }], auditLogged: true },
    { id: 'UN-DB-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', tableName: 'un_lecturer_evaluations', primaryKey: 'evaluation_id', fields: [{ name: 'evaluation_id', type: 'VARCHAR(64)', required: true }, { name: 'course_code', type: 'VARCHAR(32)', required: true }, { name: 'score', type: 'DECIMAL(3,2)', required: true }], auditLogged: true },
    { id: 'UN-DB-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', tableName: 'un_graduate_theses', primaryKey: 'thesis_id', fields: [{ name: 'thesis_id', type: 'VARCHAR(64)', required: true }, { name: 'student_reg_no', type: 'VARCHAR(32)', required: true }, { name: 'plagiarism_score', type: 'DECIMAL(4,2)', required: true }], auditLogged: true }
  ],
  apis: [
    { id: 'UN-API-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', code: 'UN_API_COURSES', method: 'POST', endpoint: '/api/v1/university/courses/register', requiredPermission: 'UN-PERM-001', handlerName: 'registerCourseUnitsHandler', summary: 'Register semester course units' },
    { id: 'UN-API-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', code: 'UN_API_GRADES', method: 'POST', endpoint: '/api/v1/university/grades/compute', requiredPermission: 'UN-PERM-002', handlerName: 'computeCgpaHandler', summary: 'Compute student CGPA' },
    { id: 'UN-API-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', code: 'UN_API_PRN', method: 'POST', endpoint: '/api/v1/university/finance/prn', requiredPermission: 'UN-PERM-003', handlerName: 'generatePrnHandler', summary: 'Generate URA payment PRN' },
    { id: 'UN-API-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', code: 'UN_API_GRANTS', method: 'POST', endpoint: '/api/v1/university/grants/create', requiredPermission: 'UN-PERM-004', handlerName: 'createGrantAccountHandler', summary: 'Create research grant account' },
    { id: 'UN-API-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', code: 'UN_API_HALLS', method: 'POST', endpoint: '/api/v1/university/halls/bid', requiredPermission: 'UN-PERM-005', handlerName: 'bidHallRoomHandler', summary: 'Bid for hall of residence' },
    { id: 'UN-API-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', code: 'UN_API_GUILD', method: 'POST', endpoint: '/api/v1/university/guild/vote', requiredPermission: 'UN-PERM-006', handlerName: 'castGuildVoteHandler', summary: 'Cast encrypted guild ballot' },
    { id: 'UN-API-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', code: 'UN_API_QUALITY', method: 'POST', endpoint: '/api/v1/university/quality/appraise', requiredPermission: 'UN-PERM-007', handlerName: 'submitLecturerAppraisalHandler', summary: 'Submit lecturer appraisal' },
    { id: 'UN-API-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', code: 'UN_API_THESIS', method: 'POST', endpoint: '/api/v1/university/thesis/scan', requiredPermission: 'UN-PERM-008', handlerName: 'scanThesisPlagiarismHandler', summary: 'Scan thesis for plagiarism' }
  ],
  runtimeComponents: [
    { id: 'UN-RTC-001', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-001', componentKey: 'UniversityCourseRegEngine', name: 'Semester Modular Course Unit & Credit Engine', description: 'Course enrollment validator and timetable conflict resolver.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ACADEMICS' },
    { id: 'UN-RTC-002', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-002', componentKey: 'UniversityGpaCgpaEngine', name: 'GPA/CGPA Grading Engine & Verifiable E-Transcripts', description: 'Cumulative grade points calculator and blockchain e-transcript generator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ACADEMICS' },
    { id: 'UN-RTC-003', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-003', componentKey: 'UniversityTuitionBillingEngine', name: 'University Bursary, PRN Billing & Exam Clearance', description: 'URA PRN slip creator and examination permit verification engine.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'FINANCE' },
    { id: 'UN-RTC-004', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-004', componentKey: 'UniversityResearchGrantsEngine', name: 'Research Grants & Project Accounting Engine', description: 'Multi-currency donor budget manager and milestone disbursements.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'RESEARCH' },
    { id: 'UN-RTC-005', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-005', componentKey: 'UniversityHallsResidenceEngine', name: 'Halls of Residence & Campus Accommodation Engine', description: 'Automated room bidding allocator and private hostel registry.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'ACCOMMODATION' },
    { id: 'UN-RTC-006', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-006', componentKey: 'UniversityGuildVotingEngine', name: 'Guild Government Electronic Voting & Societies Engine', description: 'Cryptographic e-voting ballot and student club chartering.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'GUILD' },
    { id: 'UN-RTC-007', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-007', componentKey: 'UniversityQualityNcheEngine', name: 'NCHE Quality Assurance & Lecturer Appraisal Engine', description: 'Accreditation checklist and anonymous student rating evaluator.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'QUALITY_ASSURANCE' },
    { id: 'UN-RTC-008', productId: 'prod-university-tertiary', moduleId: 'UN-MOD-008', componentKey: 'UniversityGraduateThesisEngine', name: 'Graduate School Thesis & Anti-Plagiarism Engine', description: 'Dissertation similarity index scanner and viva voce panel scheduler.', renderStrategy: 'BESPOKE_INTERACTIVE', category: 'GRADUATE_SCHOOL' }
  ],
  permissions: [
    { id: 'UN-PERM-001', productId: 'prod-university-tertiary', code: 'university:courses:register', name: 'Course Unit Registration Access', description: 'Authority to enroll students in semester course units' },
    { id: 'UN-PERM-002', productId: 'prod-university-tertiary', code: 'university:grades:cgpa', name: 'Examinations & CGPA Computation', description: 'Authority to compute grade points and issue transcripts' },
    { id: 'UN-PERM-003', productId: 'prod-university-tertiary', code: 'university:tuition:prn', name: 'University Bursary & PRN Billing', description: 'Authority to bill tuition and issue exam cards' },
    { id: 'UN-PERM-004', productId: 'prod-university-tertiary', code: 'university:grants:projects', name: 'Research Grants Accounting', description: 'Authority to manage donor funds and authorize project releases' },
    { id: 'UN-PERM-005', productId: 'prod-university-tertiary', code: 'university:halls:residence', name: 'Halls of Residence Management', description: 'Authority to allocate hostel rooms and certify private hostels' },
    { id: 'UN-PERM-006', productId: 'prod-university-tertiary', code: 'university:guild:elections', name: 'Guild Electoral Commission Access', description: 'Authority to manage student council elections' },
    { id: 'UN-PERM-007', productId: 'prod-university-tertiary', code: 'university:quality:nche', name: 'NCHE Quality Assurance Access', description: 'Authority to audit curricula and view lecturer appraisals' },
    { id: 'UN-PERM-008', productId: 'prod-university-tertiary', code: 'university:thesis:plagiarism', name: 'Graduate School Thesis Authority', description: 'Authority to scan plagiarism and convene viva voce panels' }
  ],
  roles: [
    { id: 'UN-ROLE-001', productId: 'prod-university-tertiary', code: 'VICE_CHANCELLOR_LEAD', name: 'Vice-Chancellor / Principal', tier: 'GOVERNANCE', permissionIds: ['UN-PERM-001', 'UN-PERM-002', 'UN-PERM-003', 'UN-PERM-004', 'UN-PERM-007', 'UN-PERM-008'] },
    { id: 'UN-ROLE-002', productId: 'prod-university-tertiary', code: 'ACADEMIC_REGISTRAR', name: 'Academic Registrar', tier: 'EXECUTIVE', permissionIds: ['UN-PERM-001', 'UN-PERM-002', 'UN-PERM-007'] },
    { id: 'UN-ROLE-003', productId: 'prod-university-tertiary', code: 'UNIVERSITY_BURSAR', name: 'University Bursar', tier: 'EXECUTIVE', permissionIds: ['UN-PERM-003', 'UN-PERM-004'] },
    { id: 'UN-ROLE-004', productId: 'prod-university-tertiary', code: 'FACULTY_LECTURER', name: 'Faculty Dean / Senior Lecturer', tier: 'OPERATIONAL', permissionIds: ['UN-PERM-001', 'UN-PERM-002', 'UN-PERM-008'] },
    { id: 'UN-ROLE-005', productId: 'prod-university-tertiary', code: 'UNIVERSITY_STUDENT', name: 'University Student / Researcher', tier: 'CLIENT', permissionIds: [] }
  ]
};
