# Schema for Views access plugin.
views.access.farm_entity_collection:
  type: mapping
  label: 'Entity collection access'
  mapping:
    entity_type:
      type: sequence
      label: 'Entity types'
      sequence:
        type: string
        label: 'Entity type'
