import { SECONDARY_SCHOOL_HIERARCHY } from '../canonical/secondarySchool';

export const SECERP_MODULES = SECONDARY_SCHOOL_HIERARCHY.modules;
export const SECERP_CAPABILITIES = SECONDARY_SCHOOL_HIERARCHY.capabilities;
export const SECERP_FORMS = SECONDARY_SCHOOL_HIERARCHY.forms;
export const SECERP_DASHBOARDS = SECONDARY_SCHOOL_HIERARCHY.dashboards;
export const SECERP_WORKFLOWS = SECONDARY_SCHOOL_HIERARCHY.workflows;
export const SECERP_DB_ENTITIES = SECONDARY_SCHOOL_HIERARCHY.databaseEntities;
