services:
  db:
    image: postgres:17
    volumes:
      - './db:/var/lib/postgresql/data'
    environment:
      # Set a strong password and optionally change the user/database name.
      POSTGRES_USER: farm
      POSTGRES_PASSWORD: farm
      POSTGRES_DB: farm
    restart: always

  www:
    depends_on:
      - db
    # Update this to the latest stable version before deploying.
    image: farmos/farmos:x.y.z
    volumes:
      - './sites:/opt/drupal/web/sites'
      - './keys:/opt/drupal/keys'
    ports:
      - '80:80'
    restart: always
