/**
 * JUMO UEOS — APPROVED SIX PRODUCT MANIFESTS INDEX
 */

export * from "./JUMO-FINTECH.manifest";
export * from "./JUMO-NURSERY-PRIMARY-ERP.manifest";
export * from "./JUMO-SECONDARY-ERP.manifest";
export * from "./JUMO-ALUMNI-ERP.manifest";
export * from "./JUMO-CHURCH-ERP.manifest";
export * from "./JUMO-OWNER-CONTROL-CENTER.manifest";

import JUMO_FINTECH_MANIFEST from "./JUMO-FINTECH.manifest";
import JUMO_NURSERY_PRIMARY_MANIFEST from "./JUMO-NURSERY-PRIMARY-ERP.manifest";
import JUMO_SECONDARY_MANIFEST from "./JUMO-SECONDARY-ERP.manifest";
import JUMO_ALUMNI_MANIFEST from "./JUMO-ALUMNI-ERP.manifest";
import JUMO_CHURCH_MANIFEST from "./JUMO-CHURCH-ERP.manifest";
import JUMO_OWNER_CONTROL_CENTER_MANIFEST from "./JUMO-OWNER-CONTROL-CENTER.manifest";

export const ALL_SIX_PRODUCT_MANIFESTS = [
  JUMO_FINTECH_MANIFEST,
  JUMO_NURSERY_PRIMARY_MANIFEST,
  JUMO_SECONDARY_MANIFEST,
  JUMO_ALUMNI_MANIFEST,
  JUMO_CHURCH_MANIFEST,
  JUMO_OWNER_CONTROL_CENTER_MANIFEST
] as const;

export default ALL_SIX_PRODUCT_MANIFESTS;
